const G10_MATH_COMPLETE = [
    // --- TOPIC 1: POINTS, LINES, ANGLES & PROOFS (25 Questions) ---
    { id: "G10-MA-01", grade: 10, subject: "Math", topic: "Basics", question: "Two lines that intersect at 90 degrees are called ___.", choices: ["Parallel", "Skew", "Perpendicular", "Bisecting"], answer: 2 },
    { id: "G10-MA-02", grade: 10, subject: "Math", topic: "Angles", question: "Angles that add up to 90 degrees are ___.", choices: ["Supplementary", "Complementary", "Congruent", "Adjacent"], answer: 1 },
    { id: "G10-MA-03", grade: 10, subject: "Math", topic: "Angles", question: "Angles that add up to 180 degrees are ___.", choices: ["Complementary", "Supplementary", "Vertical", "Right"], answer: 1 },
    { id: "G10-MA-04", grade: 10, subject: "Math", topic: "Basics", question: "A statement that is assumed to be true without proof is a(n) ___.", choices: ["Theorem", "Postulate/Axiom", "Corollary", "Hypothesis"], answer: 1 },
    { id: "G10-MA-05", grade: 10, subject: "Math", topic: "Basics", question: "A statement that has been proven true is a ___.", choices: ["Postulate", "Theorem", "Conjecture", "Definition"], answer: 1 },
    { id: "G10-MA-06", grade: 10, subject: "Math", topic: "Angles", question: "Opposite angles formed by intersecting lines are ___.", choices: ["Supplementary", "Vertical", "Adjacent", "Alternate"], answer: 1 },
    { id: "G10-MA-07", grade: 10, subject: "Math", topic: "Basics", question: "Two points determine exactly one ___.", choices: ["Plane", "Angle", "Line", "Ray"], answer: 2 },
    { id: "G10-MA-08", grade: 10, subject: "Math", topic: "Basics", question: "Three non-collinear points determine exactly one ___.", choices: ["Line", "Segment", "Plane", "Vertex"], answer: 2 },
    { id: "G10-MA-09", grade: 10, subject: "Math", topic: "Angles", question: "If a ray bisects an angle, it divides it into two ___ parts.", choices: ["Unequal", "Supplementary", "Congruent", "Vertical"], answer: 2 },
    { id: "G10-MA-10", grade: 10, subject: "Math", topic: "Lines", question: "When a transversal crosses two parallel lines, alternate interior angles are ___.", choices: ["Supplementary", "Congruent", "90 degrees", "Adjacent"], answer: 1 },
    { id: "G10-MA-11", grade: 10, subject: "Math", topic: "Lines", question: "When a transversal crosses parallel lines, corresponding angles are ___.", choices: ["Congruent", "Supplementary", "Linear", "Skew"], answer: 0 },
    { id: "G10-MA-12", grade: 10, subject: "Math", topic: "Lines", question: "Same-side interior angles are ___.", choices: ["Congruent", "Supplementary", "Right", "Vertical"], answer: 1 },
    { id: "G10-MA-13", grade: 10, subject: "Math", topic: "Logic", question: "An 'If-Then' statement is called a ___ statement.", choices: ["Converse", "Conditional", "Inverse", "Contrapositive"], answer: 1 },
    { id: "G10-MA-14", grade: 10, subject: "Math", topic: "Logic", question: "Switching the hypothesis and conclusion (If Q, then P) is the ___.", choices: ["Inverse", "Converse", "Contrapositive", "Negation"], answer: 1 },
    { id: "G10-MA-15", grade: 10, subject: "Math", topic: "Logic", question: "Negating both sides (If not P, then not Q) is the ___.", choices: ["Converse", "Inverse", "Contrapositive", "Proof"], answer: 1 },
    { id: "G10-MA-16", grade: 10, subject: "Math", topic: "Logic", question: "Switching and negating (If not Q, then not P) is the ___.", choices: ["Inverse", "Converse", "Contrapositive", "Biconditional"], answer: 2 },
    { id: "G10-MA-17", grade: 10, subject: "Math", topic: "Distance", question: "Distance Formula between (x1,y1) and (x2,y2)?", choices: ["sqrt((x2-x1)^2 + (y2-y1)^2)", "((x1+x2)/2, (y1+y2)/2)", "y=mx+b", "abs(x1-x2)"], answer: 0 },
    { id: "G10-MA-18", grade: 10, subject: "Math", topic: "Distance", question: "Midpoint Formula?", choices: ["sqrt((x2-x1)^2)", "((x1+x2)/2, (y1+y2)/2)", "x+y=z", "mx+b"], answer: 1 },
    { id: "G10-MA-19", grade: 10, subject: "Math", topic: "Lines", question: "Skew lines are lines that do not intersect and are NOT ___.", choices: ["Coplannar", "Parallel", "Perpendicular", "Both A and B"], answer: 3 },
    { id: "G10-MA-20", grade: 10, subject: "Math", topic: "Basics", question: "The intersection of two planes is a ___.", choices: ["Point", "Line", "Ray", "Plane"], answer: 1 },
    { id: "G10-MA-21", grade: 10, subject: "Math", topic: "Basics", question: "The intersection of two lines is a ___.", choices: ["Line", "Ray", "Point", "Angle"], answer: 2 },
    { id: "G10-MA-22", grade: 10, subject: "Math", topic: "Angles", question: "The measure of a linear pair of angles adds to ___.", choices: ["90", "180", "270", "360"], answer: 1 },
    { id: "G10-MA-23", grade: 10, subject: "Math", topic: "Basics", question: "A ray has one ___ and extends infinitely in one direction.", choices: ["Midpoint", "Endpoint", "Vertex", "Slope"], answer: 1 },
    { id: "G10-MA-24", grade: 10, subject: "Math", topic: "Angles", question: "An obtuse angle measures between ___.", choices: ["0 and 90", "90 and 180", "180 and 360", "Exactly 90"], answer: 1 },
    { id: "G10-MA-25", grade: 10, subject: "Math", topic: "Angles", question: "An acute angle measures less than ___.", choices: ["180", "90", "45", "0"], answer: 1 },

    // --- TOPIC 2: TRIANGLES & CONGRUENCE (25 Questions) ---
    { id: "G10-MA-26", grade: 10, subject: "Math", topic: "Triangles", question: "The interior angles of a triangle always sum to ___.", choices: ["90", "180", "270", "360"], answer: 1 },
    { id: "G10-MA-27", grade: 10, subject: "Math", topic: "Triangles", question: "An isosceles triangle has at least ___ congruent sides.", choices: ["0", "1", "2", "3"], answer: 2 },
    { id: "G10-MA-28", grade: 10, subject: "Math", topic: "Triangles", question: "An equilateral triangle has ___ congruent angles.", choices: ["1", "2", "3", "0"], answer: 2 },
    { id: "G10-MA-29", grade: 10, subject: "Math", topic: "Triangles", question: "Congruence shortcut: 3 sides of one equal to 3 sides of another.", choices: ["SAS", "SSS", "ASA", "AAS"], answer: 1 },
    { id: "G10-MA-30", grade: 10, subject: "Math", topic: "Triangles", question: "Congruence shortcut: 2 sides and the angle between them.", choices: ["SSS", "SAS", "ASA", "SSA"], answer: 1 },
    { id: "G10-MA-31", grade: 10, subject: "Math", topic: "Triangles", question: "Congruence shortcut: 2 angles and the side between them.", choices: ["AAA", "AAS", "ASA", "SSS"], answer: 2 },
    { id: "G10-MA-32", grade: 10, subject: "Math", topic: "Triangles", question: "CPCTC stands for: Corresponding Parts of Congruent Triangles are ___.", choices: ["Constant", "Congruent", "Calculated", "Circular"], answer: 1 },
    { id: "G10-MA-33", grade: 10, subject: "Math", topic: "Triangles", question: "Pythagorean Theorem applies only to ___ triangles.", choices: ["Obtuse", "Acute", "Right", "Equilateral"], answer: 2 },
    { id: "G10-MA-34", grade: 10, subject: "Math", topic: "Triangles", question: "In a right triangle, the side opposite the right angle is the ___.", choices: ["Leg", "Hypotenuse", "Base", "Altitude"], answer: 1 },
    { id: "G10-MA-35", grade: 10, subject: "Math", topic: "Triangles", question: "A 45-45-90 triangle is also called an isosceles ___ triangle.", choices: ["Obtuse", "Right", "Acute", "Scalene"], answer: 1 },
    { id: "G10-MA-36", grade: 10, subject: "Math", topic: "Triangles", question: "In a 30-60-90 triangle, the hypotenuse is ___ the shorter leg.", choices: ["Half", "Double", "Same as", "Triple"], answer: 1 },
    { id: "G10-MA-37", grade: 10, subject: "Math", topic: "Trig", question: "SOH CAH TOA: Sin(θ) = ___.", choices: ["Opp/Adj", "Adj/Hyp", "Opp/Hyp", "Adj/Opp"], answer: 2 },
    { id: "G10-MA-38", grade: 10, subject: "Math", topic: "Trig", question: "SOH CAH TOA: Cos(θ) = ___.", choices: ["Opp/Hyp", "Adj/Hyp", "Opp/Adj", "Hyp/Adj"], answer: 1 },
    { id: "G10-MA-39", grade: 10, subject: "Math", topic: "Trig", question: "SOH CAH TOA: Tan(θ) = ___.", choices: ["Opp/Adj", "Opp/Hyp", "Adj/Hyp", "Adj/Opp"], answer: 0 },
    { id: "G10-MA-40", grade: 10, subject: "Math", topic: "Triangles", question: "The sum of any two sides of a triangle must be ___ than the third side.", choices: ["Less", "Greater", "Equal", "Half"], answer: 1 },
    { id: "G10-MA-41", grade: 10, subject: "Math", topic: "Triangles", question: "The longest side of a triangle is opposite the ___ angle.", choices: ["Smallest", "Largest", "Right", "Exterior"], answer: 1 },
    { id: "G10-MA-42", grade: 10, subject: "Math", topic: "Triangles", question: "A segment connecting the midpoints of two sides is the ___.", choices: ["Median", "Altitude", "Midsegment", "Bisector"], answer: 2 },
    { id: "G10-MA-43", grade: 10, subject: "Math", topic: "Triangles", question: "A segment from a vertex to the midpoint of the opposite side is a ___.", choices: ["Altitude", "Median", "Angle Bisector", "Hypotenuse"], answer: 1 },
    { id: "G10-MA-44", grade: 10, subject: "Math", topic: "Triangles", question: "A segment from a vertex perpendicular to the opposite side is a(n) ___.", choices: ["Median", "Altitude", "Midsegment", "Diagonal"], answer: 1 },
    { id: "G10-MA-45", grade: 10, subject: "Math", topic: "Triangles", question: "H-L (Hypotenuse-Leg) proves congruence in which triangles?", choices: ["All", "Right", "Isosceles", "Equilateral"], answer: 1 },
    { id: "G10-MA-46", grade: 10, subject: "Math", topic: "Triangles", question: "Centroid is the intersection of the ___.", choices: ["Altitudes", "Medians", "Perpendicular Bisectors", "Angle Bisectors"], answer: 1 },
    { id: "G10-MA-47", grade: 10, subject: "Math", topic: "Triangles", question: "Incenter is the intersection of the ___.", choices: ["Angle Bisectors", "Medians", "Altitudes", "Sides"], answer: 0 },
    { id: "G10-MA-48", grade: 10, subject: "Math", topic: "Triangles", question: "The measure of an exterior angle of a triangle equals ___.", choices: ["180", "The sum of remote interior angles", "90", "The adjacent angle"], answer: 1 },
    { id: "G10-MA-49", grade: 10, subject: "Math", topic: "Triangles", question: "Area of a triangle = ___.", choices: ["length x width", "1/2 base x height", "pi x r^2", "side^2"], answer: 1 },
    { id: "G10-MA-50", grade: 10, subject: "Math", topic: "Similarity", question: "Similar triangles have corresponding angles that are ___.", choices: ["Proportional", "Congruent", "Complementary", "Supplementary"], answer: 1 },

    // --- TOPIC 3: POLYGONS & QUADRILATERALS (25 Questions) ---
    { id: "G10-MA-51", grade: 10, subject: "Math", topic: "Polygons", question: "The sum of interior angles of a polygon with n sides?", choices: ["(n-2) * 180", "n * 180", "360", "(n-1) * 90"], answer: 0 },
    { id: "G10-MA-52", grade: 10, subject: "Math", topic: "Polygons", question: "The sum of exterior angles (one at each vertex) of ANY convex polygon?", choices: ["180", "360", "540", "n * 90"], answer: 1 },
    { id: "G10-MA-53", grade: 10, subject: "Math", topic: "Quads", question: "A quadrilateral with both pairs of opposite sides parallel is a ___.", choices: ["Trapezoid", "Parallelogram", "Kite", "Circle"], answer: 1 },
    { id: "G10-MA-54", grade: 10, subject: "Math", topic: "Quads", question: "A parallelogram with four right angles is a ___.", choices: ["Rhombus", "Rectangle", "Square", "Both B and C"], answer: 3 },
    { id: "G10-MA-55", grade: 10, subject: "Math", topic: "Quads", question: "A parallelogram with four congruent sides is a ___.", choices: ["Rectangle", "Rhombus", "Square", "Both B and C"], answer: 3 },
    { id: "G10-MA-56", grade: 10, subject: "Math", topic: "Quads", question: "Diagonals of a rhombus are always ___.", choices: ["Congruent", "Perpendicular", "Parallel", "Intersect at 45 degrees"], answer: 1 },
    { id: "G10-MA-57", grade: 10, subject: "Math", topic: "Quads", question: "Diagonals of a rectangle are always ___.", choices: ["Perpendicular", "Congruent", "Parallel", "Equal to the sides"], answer: 1 },
    { id: "G10-MA-58", grade: 10, subject: "Math", topic: "Quads", question: "A quadrilateral with exactly one pair of parallel sides is a ___.", choices: ["Parallelogram", "Trapezoid", "Kite", "Rhombus"], answer: 1 },
    { id: "G10-MA-59", grade: 10, subject: "Math", topic: "Quads", question: "The parallel sides of a trapezoid are called ___.", choices: ["Legs", "Bases", "Altitudes", "Medians"], answer: 1 },
    { id: "G10-MA-60", grade: 10, subject: "Math", topic: "Quads", question: "If the legs of a trapezoid are congruent, it is ___.", choices: ["Right", "Isosceles", "Equilateral", "Scalene"], answer: 1 },
    { id: "G10-MA-61", grade: 10, subject: "Math", topic: "Quads", question: "A quadrilateral with two pairs of adjacent congruent sides (no opposite sides parallel) is a ___.", choices: ["Rhombus", "Kite", "Square", "Rectangle"], answer: 1 },
    { id: "G10-MA-62", grade: 10, subject: "Math", topic: "Polygons", question: "A polygon with 5 sides is a ___.", choices: ["Hexagon", "Pentagon", "Heptagon", "Octagon"], answer: 1 },
    { id: "G10-MA-63", grade: 10, subject: "Math", topic: "Polygons", question: "A polygon with 6 sides is a ___.", choices: ["Pentagon", "Hexagon", "Heptagon", "Nonagon"], answer: 1 },
    { id: "G10-MA-64", grade: 10, subject: "Math", topic: "Polygons", question: "A polygon with 8 sides is a ___.", choices: ["Octagon", "Decagon", "Heptagon", "Pentagon"], answer: 0 },
    { id: "G10-MA-65", grade: 10, subject: "Math", topic: "Quads", question: "Opposite angles of a parallelogram are ___.", choices: ["Supplementary", "Congruent", "Right", "Complementary"], answer: 1 },
    { id: "G10-MA-66", grade: 10, subject: "Math", topic: "Quads", question: "Consecutive angles of a parallelogram are ___.", choices: ["Congruent", "Supplementary", "90 degrees", "Complementary"], answer: 1 },
    { id: "G10-MA-67", grade: 10, subject: "Math", topic: "Polygons", question: "A polygon where all sides and angles are congruent is ___.", choices: ["Irregular", "Regular", "Convex", "Concave"], answer: 1 },
    { id: "G10-MA-68", grade: 10, subject: "Math", topic: "Quads", question: "Area of a parallelogram = ___.", choices: ["1/2 bh", "Base x Height", "pi r^2", "Diagonal 1 x Diagonal 2"], answer: 1 },
    { id: "G10-MA-69", grade: 10, subject: "Math", topic: "Quads", question: "Area of a trapezoid = ___.", choices: ["bh", "1/2 (b1+b2)h", "1/2 d1 d2", "lw"], answer: 1 },
    { id: "G10-MA-70", grade: 10, subject: "Math", topic: "Polygons", question: "A dodecagon has ___ sides.", choices: ["10", "12", "20", "15"], answer: 1 },
    { id: "G10-MA-71", grade: 10, subject: "Math", topic: "Quads", question: "The midsegment of a trapezoid is ___ to the bases.", choices: ["Perpendicular", "Parallel", "Equal", "Twice as long"], answer: 1 },
    { id: "G10-MA-72", grade: 10, subject: "Math", topic: "Quads", question: "Can a kite be a parallelogram?", choices: ["Always", "Sometimes", "Never"], answer: 2 },
    { id: "G10-MA-73", grade: 10, subject: "Math", topic: "Similarity", question: "Similar figures have sides that are ___.", choices: ["Congruent", "Proportional", "Parallel", "Equal"], answer: 1 },
    { id: "G10-MA-74", grade: 10, subject: "Math", topic: "Transformations", question: "A 'reflection' is an example of a ___.", choices: ["Rotation", "Flip", "Slide", "Stretch"], answer: 1 },
    { id: "G10-MA-75", grade: 10, subject: "Math", topic: "Transformations", question: "A 'translation' is an example of a ___.", choices: ["Slide", "Rotation", "Reflection", "Dilation"], answer: 0 },

    // --- TOPIC 4: CIRCLES & 3D SHAPES (25 Questions) ---
    { id: "G10-MA-76", grade: 10, subject: "Math", topic: "Circles", question: "The distance from the center to any point on a circle is the ___.", choices: ["Diameter", "Radius", "Chord", "Tangent"], answer: 1 },
    { id: "G10-MA-77", grade: 10, subject: "Math", topic: "Circles", question: "A segment connecting two points on a circle that passes through the center.", choices: ["Radius", "Secant", "Diameter", "Arc"], answer: 2 },
    { id: "G10-MA-78", grade: 10, subject: "Math", topic: "Circles", question: "Circumference of a circle = ___.", choices: ["pi * r^2", "2 * pi * r", "pi * d^2", "r / d"], answer: 1 },
    { id: "G10-MA-79", grade: 10, subject: "Math", topic: "Circles", question: "Area of a circle = ___.", choices: ["2 * pi * r", "pi * r^2", "pi * d", "sqrt(pi) * r"], answer: 1 },
    { id: "G10-MA-80", grade: 10, subject: "Math", topic: "Circles", question: "A line that touches a circle at exactly one point is a ___.", choices: ["Secant", "Tangent", "Chord", "Arc"], answer: 1 },
    { id: "G10-MA-81", grade: 10, subject: "Math", topic: "Circles", question: "A tangent line is ___ to the radius at the point of tangency.", choices: ["Parallel", "Congruent", "Perpendicular", "Skew"], answer: 2 },
    { id: "G10-MA-82", grade: 10, subject: "Math", topic: "Circles", question: "An inscribed angle is ___ the measure of its intercepted arc.", choices: ["Same as", "Half", "Double", "90 degrees"], answer: 1 },
    { id: "G10-MA-83", grade: 10, subject: "Math", topic: "Circles", question: "A central angle is ___ the measure of its intercepted arc.", choices: ["Half", "Same as", "Double", "Complementary"], answer: 1 },
    { id: "G10-MA-84", grade: 10, subject: "Math", topic: "Circles", question: "A semicircle measures ___ degrees.", choices: ["90", "180", "270", "360"], answer: 1 },
    { id: "G10-MA-85", grade: 10, subject: "Math", topic: "Circles", question: "A line that intersects a circle at two points is a ___.", choices: ["Tangent", "Secant", "Radius", "Chord"], answer: 1 },
    { id: "G10-MA-86", grade: 10, subject: "Math", topic: "3D Geometery", question: "Volume of a rectangular prism = ___.", choices: ["l * w * h", "1/2 lwh", "lw + lh", "Bh"], answer: 0 },
    { id: "G10-MA-87", grade: 10, subject: "Math", topic: "3D Geometery", question: "Volume of a cylinder = ___.", choices: ["pi * r^2 * h", "2 * pi * r * h", "1/3 pi * r^2 * h", "pi * d"], answer: 0 },
    { id: "G10-MA-88", grade: 10, subject: "Math", topic: "3D Geometery", question: "Volume of a cone = ___.", choices: ["pi r^2 h", "1/3 pi r^2 h", "4/3 pi r^3", "Bh"], answer: 1 },
    { id: "G10-MA-89", grade: 10, subject: "Math", topic: "3D Geometery", question: "Volume of a sphere = ___.", choices: ["4 pi r^2", "1/3 pi r^2 h", "4/3 pi r^3", "pi r^2"], answer: 2 },
    { id: "G10-MA-90", grade: 10, subject: "Math", topic: "3D Geometery", question: "Surface area of a sphere = ___.", choices: ["4 pi r^2", "4/3 pi r^3", "2 pi r", "pi d"], answer: 0 },
    { id: "G10-MA-91", grade: 10, subject: "Math", topic: "Circles", question: "Standard equation of a circle centered at (h,k)?", choices: ["(x-h)^2 + (y-k)^2 = r^2", "y = mx+b", "Ax + By = C", "x^2 + y^2 = 0"], answer: 0 },
    { id: "G10-MA-92", grade: 10, subject: "Math", topic: "3D Geometery", question: "A point where three or more edges/faces meet in a 3D shape is a ___.", choices: ["Edge", "Vertex", "Face", "Diagonal"], answer: 1 },
    { id: "G10-MA-93", grade: 10, subject: "Math", topic: "3D Geometery", question: "Euler's Formula: Faces + Vertices - Edges = ___.", choices: ["0", "1", "2", "3"], answer: 2 },
    { id: "G10-MA-94", grade: 10, subject: "Math", topic: "3D Geometery", question: "Volume of a pyramid = ___.", choices: ["Bh", "1/3 Bh", "1/2 Bh", "lwh"], answer: 1 },
    { id: "G10-MA-95", grade: 10, subject: "Math", topic: "Similarity", question: "If the scale factor of sides is k, the ratio of areas is ___.", choices: ["k", "2k", "k^2", "sqrt(k)"], answer: 2 },
    { id: "G10-MA-96", grade: 10, subject: "Math", topic: "Similarity", question: "If the scale factor of sides is k, the ratio of volumes is ___.", choices: ["k^2", "k^3", "3k", "sqrt(k)"], answer: 1 },
    { id: "G10-MA-97", grade: 10, subject: "Math", topic: "Circles", question: "A chord that passes through the center is a ___.", choices: ["Radius", "Tangent", "Diameter", "Secant"], answer: 2 },
    { id: "G10-MA-98", grade: 10, subject: "Math", topic: "Circles", question: "Angles inscribed in the same arc are ___.", choices: ["Supplementary", "Congruent", "Right", "Linear"], answer: 1 },
    { id: "G10-MA-99", grade: 10, subject: "Math", topic: "Transformations", question: "A 'dilation' changes the ___ of the figure.", choices: ["Orientation", "Location", "Size", "Color"], answer: 2 },
    { id: "G10-MA-100", grade: 10, subject: "Math", topic: "Transformations", question: "An 'isometry' (like rotation or translation) preserves ___.", choices: ["Size and Shape", "Color", "Only Shape", "Only Size"], answer: 0 }
];

module.exports = G10_MATH_COMPLETE;
