const G10_CHEMISTRY_COMPLETE = [
    // --- TOPIC 1: ATOMIC STRUCTURE & PERIODIC TABLE (25 Questions) ---
    { id: "G10-CH-01", grade: 10, subject: "Chemistry", topic: "Atoms", question: "The smallest unit of an element that retains its properties is the ___.", choices: ["Molecule", "Atom", "Proton", "Compound"], answer: 1 },
    { id: "G10-CH-02", grade: 10, subject: "Chemistry", topic: "Atoms", question: "Protons have a ___ charge.", choices: ["Positive", "Negative", "Neutral", "Double"], answer: 0 },
    { id: "G10-CH-03", grade: 10, subject: "Chemistry", topic: "Atoms", question: "Electrons have a ___ charge.", choices: ["Positive", "Negative", "Neutral", "Infinite"], answer: 1 },
    { id: "G10-CH-04", grade: 10, subject: "Chemistry", topic: "Atoms", question: "Neutrons have a ___ charge.", choices: ["Positive", "Negative", "Neutral", "Zero"], answer: 2 },
    { id: "G10-CH-05", grade: 10, subject: "Chemistry", topic: "Atoms", question: "The center of the atom containing protons and neutrons is the ___.", choices: ["Electron Cloud", "Shell", "Nucleus", "Orbit"], answer: 2 },
    { id: "G10-CH-06", grade: 10, subject: "Chemistry", topic: "Atoms", question: "The atomic number is equal to the number of ___ in an atom.", choices: ["Electrons", "Protons", "Neutrons", "Shells"], answer: 1 },
    { id: "G10-CH-07", grade: 10, subject: "Chemistry", topic: "Atoms", question: "Atoms of the same element with different numbers of neutrons are ___.", choices: ["Ions", "Isotopes", "Molecules", "Isomers"], answer: 1 },
    { id: "G10-CH-08", grade: 10, subject: "Chemistry", topic: "Periodic Table", question: "Vertical columns on the periodic table are called ___.", choices: ["Periods", "Groups/Families", "Sections", "Levels"], answer: 1 },
    { id: "G10-CH-09", grade: 10, subject: "Chemistry", topic: "Periodic Table", question: "Horizontal rows on the periodic table are called ___.", choices: ["Groups", "Families", "Periods", "Series"], answer: 2 },
    { id: "G10-CH-10", grade: 10, subject: "Chemistry", topic: "Periodic Table", question: "Group 18 elements that are non-reactive are the ___.", choices: ["Halogens", "Alkali Metals", "Noble Gases", "Actinides"], answer: 2 },
    { id: "G10-CH-11", grade: 10, subject: "Chemistry", topic: "Atoms", question: "Valence electrons are electrons in the ___ shell.", choices: ["Innermost", "Outermost", "Middle", "Nucleus"], answer: 1 },
    { id: "G10-CH-12", grade: 10, subject: "Chemistry", topic: "Periodic Table", question: "Elements that have properties of both metals and non-metals are ___.", choices: ["Metalloids", "Transition metals", "Noble gases", "Lanthanides"], answer: 0 },
    { id: "G10-CH-13", grade: 10, subject: "Chemistry", topic: "Atoms", question: "An atom that has gained or lost electrons is a(n) ___.", choices: ["Isotope", "Ion", "Molecule", "Crystal"], answer: 1 },
    { id: "G10-CH-14", grade: 10, subject: "Chemistry", topic: "Atoms", question: "A positively charged ion is called a ___.", choices: ["Anion", "Cation", "Positron", "Nucleus"], answer: 1 },
    { id: "G10-CH-15", grade: 10, subject: "Chemistry", topic: "Atoms", question: "A negatively charged ion is called a ___.", choices: ["Cation", "Anion", "Proton", "Neutron"], answer: 1 },
    { id: "G10-CH-16", grade: 10, subject: "Chemistry", topic: "Periodic Table", question: "The most reactive metals are the ___ metals.", choices: ["Alkali", "Alkaline Earth", "Transition", "Noble"], answer: 0 },
    { id: "G10-CH-17", grade: 10, subject: "Chemistry", topic: "Periodic Table", question: "The most reactive non-metals are the ___.", choices: ["Noble Gases", "Halogens", "Metalloids", "Carbon family"], answer: 1 },
    { id: "G10-CH-18", grade: 10, subject: "Chemistry", topic: "Atoms", question: "Mass number is the sum of ___ and neutrons.", choices: ["Electrons", "Protons", "Ions", "Atoms"], answer: 1 },
    { id: "G10-CH-19", grade: 10, subject: "Chemistry", topic: "Atoms", question: "The average atomic mass is usually a ___ on the periodic table.", choices: ["Whole number", "Decimal", "Prime number", "Zero"], answer: 1 },
    { id: "G10-CH-20", grade: 10, subject: "Chemistry", topic: "Atoms", question: "Which particle is responsible for chemical bonding?", choices: ["Proton", "Neutron", "Valence Electron", "Nucleus"], answer: 2 },
    { id: "G10-CH-21", grade: 10, subject: "Chemistry", topic: "Periodic Table", question: "Which element is the lightest and has atomic number 1?", choices: ["Helium", "Hydrogen", "Lithium", "Oxygen"], answer: 1 },
    { id: "G10-CH-22", grade: 10, subject: "Chemistry", topic: "Periodic Table", question: "What is the symbol for Gold?", choices: ["Ag", "Au", "Fe", "Go"], answer: 1 },
    { id: "G10-CH-23", grade: 10, subject: "Chemistry", topic: "Periodic Table", question: "What is the symbol for Silver?", choices: ["Au", "Ag", "Si", "S"], answer: 1 },
    { id: "G10-CH-24", grade: 10, subject: "Chemistry", topic: "Periodic Table", question: "What is the symbol for Iron?", choices: ["Ir", "In", "Fe", "F"], answer: 2 },
    { id: "G10-CH-25", grade: 10, subject: "Chemistry", topic: "Atoms", question: "The Octet Rule states atoms want ___ valence electrons.", choices: ["2", "4", "8", "10"], answer: 2 },

    // --- TOPIC 2: BONDING & CHEMICAL FORMULAS (25 Questions) ---
    { id: "G10-CH-26", grade: 10, subject: "Chemistry", topic: "Bonding", question: "A bond formed by the transfer of electrons is an ___ bond.", choices: ["Covalent", "Ionic", "Metallic", "Hydrogen"], answer: 1 },
    { id: "G10-CH-27", grade: 10, subject: "Chemistry", topic: "Bonding", question: "A bond formed by the sharing of electrons is an ___ bond.", choices: ["Ionic", "Covalent", "Metallic", "Non-polar"], answer: 1 },
    { id: "G10-CH-28", grade: 10, subject: "Chemistry", topic: "Bonding", question: "Ionic bonds usually form between a metal and a ___.", choices: ["Metal", "Non-metal", "Noble gas", "Metalloid"], answer: 1 },
    { id: "G10-CH-29", grade: 10, subject: "Chemistry", topic: "Bonding", question: "Covalent bonds usually form between two ___.", choices: ["Metals", "Non-metals", "Ions", "Gases"], answer: 1 },
    { id: "G10-CH-30", grade: 10, subject: "Chemistry", topic: "Formulas", question: "The common name for Sodium Chloride (NaCl) is ___.", choices: ["Sugar", "Table Salt", "Baking Soda", "Bleach"], answer: 1 },
    { id: "G10-CH-31", grade: 10, subject: "Chemistry", topic: "Formulas", question: "What is the formula for Water?", choices: ["HO2", "H2O", "H2O2", "OH"], answer: 1 },
    { id: "G10-CH-32", grade: 10, subject: "Chemistry", topic: "Formulas", question: "What is the formula for Carbon Dioxide?", choices: ["CO", "CO2", "C2O", "C2O2"], answer: 1 },
    { id: "G10-CH-33", grade: 10, subject: "Chemistry", topic: "Bonding", question: "The 'electron sea' model describes ___ bonding.", choices: ["Ionic", "Covalent", "Metallic", "Network"], answer: 2 },
    { id: "G10-CH-34", grade: 10, subject: "Chemistry", topic: "Bonding", question: "A molecule with an unequal sharing of electrons is ___.", choices: ["Non-polar", "Polar", "Ionic", "Neutral"], answer: 1 },
    { id: "G10-CH-35", grade: 10, subject: "Chemistry", topic: "Formulas", question: "The small number below the line in H2O is called a ___.", choices: ["Coefficient", "Exponent", "Subscript", "Numerator"], answer: 2 },
    { id: "G10-CH-36", grade: 10, subject: "Chemistry", topic: "Formulas", question: "The large number in front of 2H2O is called a ___.", choices: ["Subscript", "Coefficient", "Base", "Factor"], answer: 1 },
    { id: "G10-CH-37", grade: 10, subject: "Chemistry", topic: "Bonding", question: "Ability of an atom to attract electrons in a bond is ___.", choices: ["Ionization", "Electronegativity", "Affinity", "Radius"], answer: 1 },
    { id: "G10-CH-38", grade: 10, subject: "Chemistry", topic: "Formulas", question: "Oxygen gas exists naturally as a ___ molecule (O2).", choices: ["Monomial", "Diatomic", "Triatomic", "Ionic"], answer: 1 },
    { id: "G10-CH-39", grade: 10, subject: "Chemistry", topic: "Bonding", question: "Which type of bond is the strongest?", choices: ["Hydrogen", "Covalent", "Ionic", "Van der Waals"], answer: 1 },
    { id: "G10-CH-40", grade: 10, subject: "Chemistry", topic: "Formulas", question: "What is the name of the compound MgCl2?", choices: ["Magnesium Chlorine", "Magnesium Dichloride", "Magnesium Chloride", "Manganese Chloride"], answer: 2 },
    { id: "G10-CH-41", grade: 10, subject: "Chemistry", topic: "Formulas", question: "What is the name of N2O?", choices: ["Nitrogen Oxygen", "Nitrous Oxide", "Dinitrogen Monoxide", "Nitrogen Dioxide"], answer: 2 },
    { id: "G10-CH-42", grade: 10, subject: "Chemistry", topic: "Formulas", question: "Polyatomic ions are groups of atoms that act as a single ___.", choices: ["Atom", "Ion", "Molecule", "Solid"], answer: 1 },
    { id: "G10-CH-43", grade: 10, subject: "Chemistry", topic: "Bonding", question: "In a Lewis dot structure, the dots represent ___ electrons.", choices: ["All", "Core", "Valence", "Bonded"], answer: 2 },
    { id: "G10-CH-44", grade: 10, subject: "Chemistry", topic: "Bonding", question: "A triple bond involves the sharing of ___ electrons.", choices: ["3", "4", "6", "8"], answer: 2 },
    { id: "G10-CH-45", grade: 10, subject: "Chemistry", topic: "Bonding", question: "Molecules like CH4 have a ___ shape.", choices: ["Linear", "Bent", "Tetrahedral", "Pyramidal"], answer: 2 },
    { id: "G10-CH-46", grade: 10, subject: "Chemistry", topic: "Bonding", question: "Water has a ___ shape due to lone pairs.", choices: ["Linear", "Bent", "Square", "Triangular"], answer: 1 },
    { id: "G10-CH-47", grade: 10, subject: "Chemistry", topic: "Formulas", question: "What is the cation in NaOH?", choices: ["Na+", "OH-", "H+", "O2-"], answer: 0 },
    { id: "G10-CH-48", grade: 10, subject: "Chemistry", topic: "Formulas", question: "What is the anion in NaOH?", choices: ["Na+", "OH-", "H+", "O2-"], answer: 1 },
    { id: "G10-CH-49", grade: 10, subject: "Chemistry", topic: "Bonding", question: "Ionic compounds generally have ___ melting points.", choices: ["Low", "High", "Variable", "Zero"], answer: 1 },
    { id: "G10-CH-50", grade: 10, subject: "Chemistry", topic: "Bonding", question: "Covalent compounds generally have ___ boiling points than ionic.", choices: ["Higher", "Lower", "The same", "None of the above"], answer: 1 },

    // --- TOPIC 3: REACTIONS & STOICHIOMETRY (25 Questions) ---
    { id: "G10-CH-51", grade: 10, subject: "Chemistry", topic: "Reactions", question: "Substances on the left of a chemical equation are ___.", choices: ["Products", "Reactants", "Catalysts", "Solvents"], answer: 1 },
    { id: "G10-CH-52", grade: 10, subject: "Chemistry", topic: "Reactions", question: "Substances on the right of a chemical equation are ___.", choices: ["Reactants", "Products", "Precipitates", "Ionic"], answer: 1 },
    { id: "G10-CH-53", grade: 10, subject: "Chemistry", topic: "Reactions", question: "The Law of Conservation of Mass states mass is neither ___ nor destroyed.", choices: ["Mixed", "Created", "Heated", "Moved"], answer: 1 },
    { id: "G10-CH-54", grade: 10, subject: "Chemistry", topic: "Reactions", question: "A reaction where two elements combine to form a compound: A + B -> AB.", choices: ["Decomposition", "Synthesis", "Combustion", "Single Replacement"], answer: 1 },
    { id: "G10-CH-55", grade: 10, subject: "Chemistry", topic: "Reactions", question: "A reaction where a compound breaks down: AB -> A + B.", choices: ["Synthesis", "Decomposition", "Double Replacement", "Neutralization"], answer: 1 },
    { id: "G10-CH-56", grade: 10, subject: "Chemistry", topic: "Reactions", question: "A reaction involving O2 producing CO2 and H2O is ___.", choices: ["Synthesis", "Combustion", "Decomposition", "Redox"], answer: 1 },
    { id: "G10-CH-57", grade: 10, subject: "Chemistry", topic: "Reactions", question: "The number 6.022 x 10^23 is known as ___ Number.", choices: ["Newton's", "Avogadro's", "Einstein's", "Dalton's"], answer: 1 },
    { id: "G10-CH-58", grade: 10, subject: "Chemistry", topic: "Reactions", question: "One mole of any substance contains ___ particles.", choices: ["100", "1 million", "6.022 x 10^23", "9.8 x 10^2"], answer: 2 },
    { id: "G10-CH-59", grade: 10, subject: "Chemistry", topic: "Math", question: "Molar mass of H2O (H=1, O=16)?", choices: ["17 g/mol", "18 g/mol", "16 g/mol", "2 g/mol"], answer: 1 },
    { id: "G10-CH-60", grade: 10, subject: "Chemistry", topic: "Reactions", question: "A reaction that releases heat is ___.", choices: ["Endothermic", "Exothermic", "Hydraulic", "Static"], answer: 1 },
    { id: "G10-CH-61", grade: 10, subject: "Chemistry", topic: "Reactions", question: "A reaction that absorbs heat is ___.", choices: ["Exothermic", "Endothermic", "Polar", "Acidic"], answer: 1 },
    { id: "G10-CH-62", grade: 10, subject: "Chemistry", topic: "Reactions", question: "Minimum energy needed to start a reaction is ___ energy.", choices: ["Kinetic", "Activation", "Potential", "Thermal"], answer: 1 },
    { id: "G10-CH-63", grade: 10, subject: "Chemistry", topic: "Reactions", question: "A substance that speeds up a reaction without being used is a ___.", choices: ["Reactant", "Catalyst", "Inhibitor", "Product"], answer: 1 },
    { id: "G10-CH-64", grade: 10, subject: "Chemistry", topic: "Reactions", question: "A solid that forms from a liquid reaction is a ___.", choices: ["Precipitate", "Solution", "Gas", "Solvent"], answer: 0 },
    { id: "G10-CH-65", grade: 10, subject: "Chemistry", topic: "Stoichiometry", question: "Stoichiometry is the study of ___ relationships in reactions.", choices: ["Qualitative", "Quantitative/Mass", "Molecular", "Atomic"], answer: 1 },
    { id: "G10-CH-66", grade: 10, subject: "Chemistry", topic: "Reactions", question: "In A + BC -> B + AC, which reaction type is it?", choices: ["Synthesis", "Single Replacement", "Double Replacement", "Combustion"], answer: 1 },
    { id: "G10-CH-67", grade: 10, subject: "Chemistry", topic: "Reactions", question: "In AB + CD -> AD + CB, which reaction type is it?", choices: ["Single Replacement", "Double Replacement", "Synthesis", "Redox"], answer: 1 },
    { id: "G10-CH-68", grade: 10, subject: "Chemistry", topic: "Stoichiometry", question: "To balance an equation, you change the ___.", choices: ["Subscripts", "Coefficients", "Elements", "Atoms"], answer: 1 },
    { id: "G10-CH-69", grade: 10, subject: "Chemistry", topic: "Stoichiometry", question: "The reactant that runs out first and stops the reaction is the ___ reactant.", choices: ["Excess", "Limiting", "Primary", "Main"], answer: 1 },
    { id: "G10-CH-70", grade: 10, subject: "Chemistry", topic: "Stoichiometry", question: "The amount of product actually produced in a lab is the ___ yield.", choices: ["Theoretical", "Actual", "Percent", "Expected"], answer: 1 },
    { id: "G10-CH-71", grade: 10, subject: "Chemistry", topic: "Stoichiometry", question: "Actual yield / Theoretical yield x 100 = ___ yield.", choices: ["Molar", "Percent", "Stoichiometric", "Relative"], answer: 1 },
    { id: "G10-CH-72", grade: 10, subject: "Chemistry", topic: "Matter", question: "Matter that has a fixed volume but takes the shape of its container is ___.", choices: ["Solid", "Liquid", "Gas", "Plasma"], answer: 1 },
    { id: "G10-CH-73", grade: 10, subject: "Chemistry", topic: "Matter", question: "Matter with no fixed shape or volume is ___.", choices: ["Solid", "Liquid", "Gas", "Metal"], answer: 2 },
    { id: "G10-CH-74", grade: 10, subject: "Chemistry", topic: "Matter", question: "Phase change from liquid to gas is ___.", choices: ["Melting", "Evaporation", "Freezing", "Sublimation"], answer: 1 },
    { id: "G10-CH-75", grade: 10, subject: "Chemistry", topic: "Matter", question: "Phase change from solid directly to gas is ___.", choices: ["Melting", "Sublimation", "Deposition", "Boiling"], answer: 1 },

    // --- TOPIC 4: SOLUTIONS, ACIDS & BASES (25 Questions) ---
    { id: "G10-CH-76", grade: 10, subject: "Chemistry", topic: "Solutions", question: "In a solution, the substance being dissolved is the ___.", choices: ["Solvent", "Solute", "Suspension", "Dilution"], answer: 1 },
    { id: "G10-CH-77", grade: 10, subject: "Chemistry", topic: "Solutions", question: "The substance doing the dissolving (like water) is the ___.", choices: ["Solute", "Solvent", "Colloid", "Acid"], answer: 1 },
    { id: "G10-CH-78", grade: 10, subject: "Chemistry", topic: "Solutions", question: "Water is known as the 'universal ___'.", choices: ["Acid", "Base", "Solvent", "Solute"], answer: 2 },
    { id: "G10-CH-79", grade: 10, subject: "Chemistry", topic: "Solutions", question: "Molarity is defined as moles of solute per ___ of solution.", choices: ["Gram", "Liter", "Milliliter", "Kilogram"], answer: 1 },
    { id: "G10-CH-80", grade: 10, subject: "Chemistry", topic: "Solutions", question: "A solution that cannot dissolve any more solute is ___.", choices: ["Unsaturated", "Saturated", "Supersaturated", "Diluted"], answer: 1 },
    { id: "G10-CH-81", grade: 10, subject: "Chemistry", topic: "Acids/Bases", question: "Acids have a pH ___.", choices: ["Less than 7", "Exactly 7", "Greater than 7", "Exactly 0"], answer: 0 },
    { id: "G10-CH-82", grade: 10, subject: "Chemistry", topic: "Acids/Bases", question: "Bases have a pH ___.", choices: ["Less than 7", "Greater than 7", "Between 1 and 3", "Exactly 0"], answer: 1 },
    { id: "G10-CH-83", grade: 10, subject: "Chemistry", topic: "Acids/Bases", question: "Pure water has a neutral pH of ___.", choices: ["0", "7", "14", "1"], answer: 1 },
    { id: "G10-CH-84", grade: 10, subject: "Chemistry", topic: "Acids/Bases", question: "Acids taste ___.", choices: ["Sweet", "Bitter", "Sour", "Salty"], answer: 2 },
    { id: "G10-CH-85", grade: 10, subject: "Chemistry", topic: "Acids/Bases", question: "Bases taste ___ and feel slippery.", choices: ["Sour", "Sweet", "Bitter", "Spicy"], answer: 2 },
    { id: "G10-CH-86", grade: 10, subject: "Chemistry", topic: "Acids/Bases", question: "Acids turn Blue Litmus paper ___.", choices: ["Pink", "Green", "Red", "Yellow"], answer: 2 },
    { id: "G10-CH-87", grade: 10, subject: "Chemistry", topic: "Acids/Bases", question: "Bases turn Red Litmus paper ___.", choices: ["Purple", "Blue", "Orange", "Clear"], answer: 1 },
    { id: "G10-CH-88", grade: 10, subject: "Chemistry", topic: "Acids/Bases", question: "Acids release ___ ions in water.", choices: ["OH-", "H+", "Cl-", "Na+"], answer: 1 },
    { id: "G10-CH-89", grade: 10, subject: "Chemistry", topic: "Acids/Bases", question: "Bases release ___ ions in water.", choices: ["H+", "OH-", "O2-", "H3O+"], answer: 1 },
    { id: "G10-CH-90", grade: 10, subject: "Chemistry", topic: "Acids/Bases", question: "Neutralization reaction: Acid + Base -> ___ + Water.", choices: ["Oil", "Salt", "Gas", "Acid"], answer: 1 },
    { id: "G10-CH-91", grade: 10, subject: "Chemistry", topic: "Solutions", question: "A mixture that appears uniform throughout is ___.", choices: ["Heterogeneous", "Homogeneous", "Suspension", "Layered"], answer: 1 },
    { id: "G10-CH-92", grade: 10, subject: "Chemistry", topic: "Solutions", question: "Stirring or heating generally ___ the rate of dissolving.", choices: ["Decreases", "Increases", "Stops", "Does not change"], answer: 1 },
    { id: "G10-CH-93", grade: 10, subject: "Chemistry", topic: "Solutions", question: "Which is a heterogeneous mixture?", choices: ["Salt water", "Salad", "Air", "Steel"], answer: 1 },
    { id: "G10-CH-94", grade: 10, subject: "Chemistry", topic: "Gases", question: "Pressure and Volume have an ___ relationship (Boyle's Law).", choices: ["Direct", "Inverse", "None", "Linear"], answer: 1 },
    { id: "G10-CH-95", grade: 10, subject: "Chemistry", topic: "Gases", question: "Temperature and Volume have a ___ relationship (Charles's Law).", choices: ["Direct", "Inverse", "Opposite", "Square"], answer: 0 },
    { id: "G10-CH-96", grade: 10, subject: "Chemistry", topic: "Acids/Bases", question: "Strong acids dissociate ___ in water.", choices: ["Partially", "Completely", "Not at all", "Slowly"], answer: 1 },
    { id: "G10-CH-97", grade: 10, subject: "Chemistry", topic: "Energy", question: "Specific heat is the energy needed to raise 1g of a substance by ___ degree.", choices: ["1", "10", "100", "0"], answer: 0 },
    { id: "G10-CH-98", grade: 10, subject: "Chemistry", topic: "Matter", question: "Which is a chemical property?", choices: ["color", "density", "flammability", "melting point"], answer: 2 },
    { id: "G10-CH-99", grade: 10, subject: "Chemistry", topic: "Matter", question: "Which is a physical change?", choices: ["rusting", "burning", "melting ice", "cooking an egg"], answer: 2 },
    { id: "G10-CH-100", grade: 10, subject: "Chemistry", topic: "Lab", question: "Equipment used to measure liquid volume accurately is a ___.", choices: ["Beaker", "Flask", "Graduated Cylinder", "Pipette"], answer: 2 }
];

module.exports = G10_CHEMISTRY_COMPLETE;
