const G11_ELA_COMPLETE = [
    // --- TOPIC 1: AMERICAN LITERATURE (25 Questions) ---
    { id: "G11-ELA-01", grade: 11, subject: "ELA", topic: "American Lit", question: "Which 1925 novel by F. Scott Fitzgerald explores the American Dream?", choices: ["The Great Gatsby", "The Grapes of Wrath", "Moby Dick", "Ulysses"], answer: 0 },
    { id: "G11-ELA-02", grade: 11, subject: "ELA", topic: "American Lit", question: "Who wrote the play 'The Crucible', an allegory for McCarthyism?", choices: ["Tennessee Williams", "Arthur Miller", "Eugene O'Neill", "August Wilson"], answer: 1 },
    { id: "G11-ELA-03", grade: 11, subject: "ELA", topic: "American Lit", question: "Nathaniel Hawthorne’s 'The Scarlet Letter' is set in which Puritan colony?", choices: ["New York", "Massachusetts Bay", "Virginia", "Rhode Island"], answer: 1 },
    { id: "G11-ELA-04", grade: 11, subject: "ELA", topic: "American Lit", question: "The Harlem Renaissance was a cultural movement centering on ___.", choices: ["Western Pioneers", "African American art and literature", "Industrialization", "Immigration from Europe"], answer: 1 },
    { id: "G11-ELA-05", grade: 11, subject: "ELA", topic: "American Lit", question: "Which poet is known for 'I heard a Fly buzz - when I died' and reclusive life?", choices: ["Walt Whitman", "Emily Dickinson", "Robert Frost", "Maya Angelou"], answer: 1 },
    { id: "G11-ELA-06", grade: 11, subject: "ELA", topic: "American Lit", question: "Walt Whitman's 'Leaves of Grass' is famous for its use of ___.", choices: ["Strict rhyming", "Free verse", "Haiku", "Sonnets"], answer: 1 },
    { id: "G11-ELA-07", grade: 11, subject: "ELA", topic: "American Lit", question: "Mark Twain’s 'Huckleberry Finn' uses regional ___ to give voice to characters.", choices: ["Logic", "Dialect", "Scientific terms", "Formal Latin"], answer: 1 },
    { id: "G11-ELA-08", grade: 11, subject: "ELA", topic: "American Lit", question: "The 'Lost Generation' refers to writers who were disillusioned after ___.", choices: ["The Civil War", "World War I", "The Gold Rush", "The Great Depression"], answer: 1 },
    { id: "G11-ELA-09", grade: 11, subject: "ELA", topic: "American Lit", question: "Langston Hughes was a leading figure in the ___ Renaissance.", choices: ["Chicago", "Harlem", "California", "Southern"], answer: 1 },
    { id: "G11-ELA-10", grade: 11, subject: "ELA", topic: "American Lit", question: "Henry David Thoreau’s 'Walden' is an example of ___.", choices: ["Realism", "Transcendentalism", "Naturalism", "Post-Modernism"], answer: 1 },
    { id: "G11-ELA-11", grade: 11, subject: "ELA", topic: "American Lit", question: "Ralph Waldo Emerson’s 'Self-Reliance' emphasizes ___.", choices: ["Following the crown", "Individualism and intuition", "Group conformity", "Strict religious laws"], answer: 1 },
    { id: "G11-ELA-12", grade: 11, subject: "ELA", topic: "American Lit", question: "Which novel by John Steinbeck depicts the Dust Bowl during the Great Depression?", choices: ["Of Mice and Men", "The Grapes of Wrath", "East of Eden", "Travels with Charley"], answer: 1 },
    { id: "G11-ELA-13", grade: 11, subject: "ELA", topic: "American Lit", question: "Edgar Allan Poe is famous for his stories of mystery and the ___.", choices: ["Macabre", "Happy", "Instructional", "Scientific"], answer: 0 },
    { id: "G11-ELA-14", grade: 11, subject: "ELA", topic: "American Lit", question: "The protagonist of 'The Catcher in the Rye' is ___.", choices: ["Jay Gatsby", "Holden Caulfield", "Tom Sawyer", "Nick Carraway"], answer: 1 },
    { id: "G11-ELA-15", grade: 11, subject: "ELA", topic: "American Lit", question: "The term 'Muckrakers' refers to journalists who exposed ___.", choices: ["Gardening tips", "Corruption and social ills", "Sports scores", "Fashion trends"], answer: 1 },
    { id: "G11-ELA-16", grade: 11, subject: "ELA", topic: "American Lit", question: "Which era of American Lit focuses on objective reality and everyday life?", choices: ["Romanticism", "Realism", "Classical", "Abstract"], answer: 1 },
    { id: "G11-ELA-17", grade: 11, subject: "ELA", topic: "American Lit", question: "Naturalism is like Realism but emphasizes that ___ determines human fate.", choices: ["Free will", "Heredity and environment", "Magic", "Karma"], answer: 1 },
    { id: "G11-ELA-18", grade: 11, subject: "ELA", topic: "American Lit", question: "The 'Southern Gothic' genre often features ___.", choices: ["Utopian cities", "Grotesque characters and decaying settings", "Space travel", "Action movies"], answer: 1 },
    { id: "G11-ELA-19", grade: 11, subject: "ELA", topic: "American Lit", question: "Who wrote 'Their Eyes Were Watching God'?", choices: ["Zora Neale Hurston", "Alice Walker", "Toni Morrison", "Maya Angelou"], answer: 0 },
    { id: "G11-ELA-20", grade: 11, subject: "ELA", topic: "American Lit", question: "Modernist literature often uses ___ of consciousness.", choices: ["River", "Stream", "Cloud", "Void"], answer: 1 },
    { id: "G11-ELA-21", grade: 11, subject: "ELA", topic: "American Lit", question: "Which poem by Robert Frost discusses two choices in life?", choices: ["The Road Not Taken", "Mending Wall", "Birches", "Fire and Ice"], answer: 0 },
    { id: "G11-ELA-22", grade: 11, subject: "ELA", topic: "American Lit", question: "The 'Founding Fathers' used ___ to persuade the colonies.", choices: ["Poetry", "Political rhetoric", "Songs", "Magic"], answer: 1 },
    { id: "G11-ELA-23", grade: 11, subject: "ELA", topic: "American Lit", question: "Maya Angelou's 'I Know Why the Caged Bird Sings' is a ___.", choices: ["Fiction", "Memoir", "Fantasy", "Sci-fi"], answer: 1 },
    { id: "G11-ELA-24", grade: 11, subject: "ELA", topic: "American Lit", question: "The Beats (Beat Generation) rejected ___.", choices: ["Writing", "Mainstream American values of the 1950s", "The past", "Technology"], answer: 1 },
    { id: "G11-ELA-25", grade: 11, subject: "ELA", topic: "American Lit", question: "In 'The Great Gatsby', the green light represents Gatsby's ___.", choices: ["Greed", "Money", "Hopes and dreams for the future", "Car"], answer: 2 },

    // --- TOPIC 2: LITERARY ANALYSIS & DEVICES (25 Questions) ---
    { id: "G11-ELA-26", grade: 11, subject: "ELA", topic: "Analysis", question: "An 'Allegory' is a story with a hidden ___.", choices: ["Clue", "Moral/Political meaning", "Character", "Ending"], answer: 1 },
    { id: "G11-ELA-27", grade: 11, subject: "ELA", topic: "Analysis", question: "A 'Motif' is a recurring ___ in a work of art.", choices: ["Mistake", "Theme, image, or idea", "Color", "Character"], answer: 1 },
    { id: "G11-ELA-28", grade: 11, subject: "ELA", topic: "Analysis", question: "Irony that happens when the result is opposite of intention is ___.", choices: ["Verbal", "Situational", "Dramatic", "Sarcastic"], answer: 1 },
    { id: "G11-ELA-29", grade: 11, subject: "ELA", topic: "Analysis", question: "___ irony is when the audience knows more than the character.", choices: ["Situational", "Dramatic", "Verbal", "Historical"], answer: 1 },
    { id: "G11-ELA-30", grade: 11, subject: "ELA", topic: "Analysis", question: "A 'Foil' is a character who ___.", choices: ["Is the villain", "Contrasts with another character", "Leaves early", "Wins everything"], answer: 1 },
    { id: "G11-ELA-31", grade: 11, subject: "ELA", topic: "Analysis", question: "___ is a reference to a well-known person, place, or text.", choices: ["Illusion", "Allusion", "Elision", "Addition"], answer: 1 },
    { id: "G11-ELA-32", grade: 11, subject: "ELA", topic: "Analysis", question: "The author's attitude toward the subject is the ___.", choices: ["Mood", "Tone", "Voice", "Diction"], answer: 1 },
    { id: "G11-ELA-33", grade: 11, subject: "ELA", topic: "Analysis", question: "The atmosphere created for the reader is the ___.", choices: ["Tone", "Mood", "Setting", "Style"], answer: 1 },
    { id: "G11-ELA-34", grade: 11, subject: "ELA", topic: "Analysis", question: "Over-exaggeration for effect is called ___.", choices: ["Understatement", "Hyperbole", "Simile", "Metaphor"], answer: 1 },
    { id: "G11-ELA-35", grade: 11, subject: "ELA", topic: "Analysis", question: "The dictionary definition of a word is its ___.", choices: ["Connotation", "Denotation", "Etymology", "Synonym"], answer: 1 },
    { id: "G11-ELA-36", grade: 11, subject: "ELA", topic: "Analysis", question: "The emotional associations of a word are its ___.", choices: ["Denotation", "Connotation", "Root", "Suffix"], answer: 1 },
    { id: "G11-ELA-37", grade: 11, subject: "ELA", topic: "Analysis", question: "A 'Paradox' is a statement that seems contradictory but ___.", choices: ["Is a lie", "Reveals a truth", "Is a joke", "Has no meaning"], answer: 1 },
    { id: "G11-ELA-38", grade: 11, subject: "ELA", topic: "Analysis", question: "Repeating the same letter at the start of multiple words is ___.", choices: ["Assonance", "Alliteration", "Rhyme", "Meter"], answer: 1 },
    { id: "G11-ELA-39", grade: 11, subject: "ELA", topic: "Analysis", question: "Word choice is also known as ___.", choices: ["Syntax", "Diction", "Phrasing", "Tone"], answer: 1 },
    { id: "G11-ELA-40", grade: 11, subject: "ELA", topic: "Analysis", question: "Sentence structure is also known as ___.", choices: ["Diction", "Syntax", "Vocabulary", "Grammar"], answer: 1 },
    { id: "G11-ELA-41", grade: 11, subject: "ELA", topic: "Analysis", question: "Juxtaposition is placing two things together to highlight ___.", choices: ["Similarities", "Differences/Contrasts", "Wealth", "Colors"], answer: 1 },
    { id: "G11-ELA-42", grade: 11, subject: "ELA", topic: "Analysis", question: "A 'Symbol' is something that represents ___.", choices: ["Itself only", "Something else (abstract)", "Everything", "Nothing"], answer: 1 },
    { id: "G11-ELA-43", grade: 11, subject: "ELA", topic: "Analysis", question: "An 'Oxymoron' is a pair of ___ words (e.g., 'Jumbo Shrimp').", choices: ["Similar", "Contradictory", "Long", "Short"], answer: 1 },
    { id: "G11-ELA-44", grade: 11, subject: "ELA", topic: "Analysis", question: "A 'Soliloquy' occurs when a character speaks ___.", choices: ["To the crowd", "Alone on stage", "To a friend", "In a dream"], answer: 1 },
    { id: "G11-ELA-45", grade: 11, subject: "ELA", topic: "Analysis", question: "The 'Climax' of a story is the ___.", choices: ["Beginning", "Turning point/highest tension", "End", "Middle"], answer: 1 },
    { id: "G11-ELA-46", grade: 11, subject: "ELA", topic: "Analysis", question: "A 'Static' character ___ throughout the story.", choices: ["Changes a lot", "Does not change", "Dies", "Is the hero"], answer: 1 },
    { id: "G11-ELA-47", grade: 11, subject: "ELA", topic: "Analysis", question: "A 'Dynamic' character ___ throughout the story.", choices: ["Stays the same", "Undergoes a major change", "Is boring", "Leaves early"], answer: 1 },
    { id: "G11-ELA-48", grade: 11, subject: "ELA", topic: "Analysis", question: "The point of view using 'I' and 'Me' is ___.", choices: ["1st Person", "2nd Person", "3rd Person limited", "3rd Person omniscient"], answer: 0 },
    { id: "G11-ELA-49", grade: 11, subject: "ELA", topic: "Analysis", question: "A personified object is treated as if it has ___ qualities.", choices: ["Animal", "Human", "God-like", "Invisible"], answer: 1 },
    { id: "G11-ELA-50", grade: 11, subject: "ELA", topic: "Analysis", question: "The central message or 'big idea' of a text is the ___.", choices: ["Plot", "Theme", "Setting", "Conflict"], answer: 1 },

    // --- TOPIC 3: GRAMMAR & COMPOSITION (25 Questions) ---
    { id: "G11-ELA-51", grade: 11, subject: "ELA", topic: "Grammar", question: "A 'Run-on' sentence joins two sentences without proper ___.", choices: ["Nouns", "Punctuation/Conjunctions", "Verbs", "Space"], answer: 1 },
    { id: "G11-ELA-52", grade: 11, subject: "ELA", topic: "Grammar", question: "A 'Fragment' is missing a ___.", choices: ["Period", "Subject or Verb", "Adjective", "Title"], answer: 1 },
    { id: "G11-ELA-53", grade: 11, subject: "ELA", topic: "Grammar", question: "Use a semicolon to join two ___ clauses.", choices: ["Dependent", "Independent", "Short", "Rhyming"], answer: 1 },
    { id: "G11-ELA-54", grade: 11, subject: "ELA", topic: "Grammar", question: "Parallel structure means using the same ___ pattern in a series.", choices: ["Spelling", "Grammatical", "Logical", "Color"], answer: 1 },
    { id: "G11-ELA-55", grade: 11, subject: "ELA", topic: "Grammar", question: "Which is a 'Dangling Modifier'?", choices: ["The boy ran.", "Walking to school, the bell rang.", "She ate an apple.", "Help me."], answer: 1 },
    { id: "G11-ELA-56", grade: 11, subject: "ELA", topic: "Grammar", question: "In 'Active Voice,' the subject ___ the action.", choices: ["Receives", "Performs", "Ignores", "Watches"], answer: 1 },
    { id: "G11-ELA-57", grade: 11, subject: "ELA", topic: "Grammar", question: "In 'Passive Voice,' the subject ___ the action.", choices: ["Performs", "Receives", "Does", "Starts"], answer: 1 },
    { id: "G11-ELA-58", grade: 11, subject: "ELA", topic: "Composition", question: "The first sentence of an essay should be a ___.", choices: ["Conclusion", "Hook", "Reference", "Page number"], answer: 1 },
    { id: "G11-ELA-59", grade: 11, subject: "ELA", topic: "Composition", question: "The main argument of an essay is the ___.", choices: ["Outline", "Thesis Statement", "Body", "Title"], answer: 1 },
    { id: "G11-ELA-60", grade: 11, subject: "ELA", topic: "Grammar", question: "A 'Comma Splice' joins two sentences with ONLY a ___.", choices: ["Period", "Comma", "Dash", "Colon"], answer: 1 },
    { id: "G11-ELA-61", grade: 11, subject: "ELA", topic: "Grammar", question: "Which word is a pronoun?", choices: ["Run", "He", "Fast", "Green"], answer: 1 },
    { id: "G11-ELA-62", grade: 11, subject: "ELA", topic: "Grammar", question: "Which word is an adjective?", choices: ["Quickly", "Beautiful", "Jump", "They"], answer: 1 },
    { id: "G11-ELA-63", grade: 11, subject: "ELA", topic: "Grammar", question: "Which word is an adverb?", choices: ["Table", "Loudly", "Red", "Cat"], answer: 1 },
    { id: "G11-ELA-64", grade: 11, subject: "ELA", topic: "Grammar", question: "Identify the 'Infinitive' form of a verb.", choices: ["Running", "Ran", "To run", "Runs"], answer: 2 },
    { id: "G11-ELA-65", grade: 11, subject: "ELA", topic: "Grammar", question: "Subject-Verb Agreement: 'Neither the box nor the bags ___ here.'", choices: ["is", "are", "be", "were"], answer: 1 },
    { id: "G11-ELA-66", grade: 11, subject: "ELA", topic: "Composition", question: "A 'Bibliography' is a list of ___.", choices: ["Friends", "Sources/Works cited", "Theaters", "Chapters"], answer: 1 },
    { id: "G11-ELA-67", grade: 11, subject: "ELA", topic: "Composition", question: "Standard formatting for research papers in ELA is ___.", choices: ["APA", "MLA", "Chicago", "Harvard"], answer: 1 },
    { id: "G11-ELA-68", grade: 11, subject: "ELA", topic: "Composition", question: "Transition words (e.g., 'However') help maintain ___.", choices: ["Chaos", "Cohesion/Flow", "Tension", "The first page"], answer: 1 },
    { id: "G11-ELA-69", grade: 11, subject: "ELA", topic: "Composition", question: "Synthesizing sources means ___.", choices: ["Copying them", "Combining them to form a new idea", "Deleting them", "Listing them alphabetically"], answer: 1 },
    { id: "G11-ELA-70", grade: 11, subject: "ELA", topic: "Grammar", question: "The part of the sentence that performs the action is the ___.", choices: ["Object", "Subject", "Adjective", "Predicate"], answer: 1 },
    { id: "G11-ELA-71", grade: 11, subject: "ELA", topic: "Grammar", question: "The part of the sentence that describes the action is the ___.", choices: ["Noun", "Verb/Predicate", "Subject", "Article"], answer: 1 },
    { id: "G11-ELA-72", grade: 11, subject: "ELA", topic: "Composition", question: "A 'Counterargument' addresses the ___ side.", choices: ["Same", "Opposite", "True", "False"], answer: 1 },
    { id: "G11-ELA-73", grade: 11, subject: "ELA", topic: "Composition", question: "A 'Rebuttal' is your response to a ___.", choices: ["Thesis", "Counterargument", "Friend", "Teacher"], answer: 1 },
    { id: "G11-ELA-74", grade: 11, subject: "ELA", topic: "Grammar", question: "Use a colon to introduce a ___.", choices: ["Full stop", "List or quote", "Question", "Noun"], answer: 1 },
    { id: "G11-ELA-75", grade: 11, subject: "ELA", topic: "Grammar", question: "Parentheses ( ) are used to enclose ___ information.", choices: ["Crucial", "Extra/Parenthetical", "Forbidden", "Loud"], answer: 1 },

    // --- TOPIC 4: RHETORIC & SPEECH (25 Questions) ---
    { id: "G11-ELA-76", grade: 11, subject: "ELA", topic: "Rhetoric", question: "Logos refers to an appeal to ___.", choices: ["Emotion", "Logic/Reason", "Character", "Time"], answer: 1 },
    { id: "G11-ELA-77", grade: 11, subject: "ELA", topic: "Rhetoric", question: "Pathos refers to an appeal to ___.", choices: ["Logic", "Emotion", "Ethics", "Paper"], answer: 1 },
    { id: "G11-ELA-78", grade: 11, subject: "ELA", topic: "Rhetoric", question: "Ethos refers to an appeal to ___.", choices: ["Energy", "Credibility/Ethics", "Facts", "The sky"], answer: 1 },
    { id: "G11-ELA-79", grade: 11, subject: "ELA", topic: "Rhetoric", question: "Kairos refers to the ___ of an argument.", choices: ["Color", "Timing/Context", "Volume", "Price"], answer: 1 },
    { id: "G11-ELA-80", grade: 11, subject: "ELA", topic: "Rhetoric", question: "A rhetorical question is used to ___.", choices: ["Get an answer", "Emphasize a point", "Confusion", "Waste time"], answer: 1 },
    { id: "G11-ELA-81", grade: 11, subject: "ELA", topic: "Rhetoric", question: "The 'Ad Hominem' fallacy attacks the ___.", choices: ["Idea", "Person", "Logic", "Fact"], answer: 1 },
    { id: "G11-ELA-82", grade: 11, subject: "ELA", topic: "Rhetoric", question: "The 'Slippery Slope' fallacy suggests that ___.", choices: ["Ice is cold", "One event will lead to a chain of others", "Arguments are easy", "Logic is circular"], answer: 1 },
    { id: "G11-ELA-83", grade: 11, subject: "ELA", topic: "Rhetoric", question: "In public speaking, 'Diction' refers to ___.", choices: ["Volume", "Word choice/Pronunciation", "Dance steps", "Lighting"], answer: 1 },
    { id: "G11-ELA-84", grade: 11, subject: "ELA", topic: "Rhetoric", question: "The 'Target Audience' is the group you are ___.", choices: ["Ignoring", "Trying to persuade", "Paying", "Meeting"], answer: 1 },
    { id: "G11-ELA-85", grade: 11, subject: "ELA", topic: "Rhetoric", question: "Non-verbal communication includes ___.", choices: ["Words", "Body language/gestures", "Writing", "Singing"], answer: 1 },
    { id: "G11-ELA-86", grade: 11, subject: "ELA", topic: "Rhetoric", question: "A 'Call to Action' usually occurs at the ___ of a speech.", choices: ["Beginning", "End", "Middle", "None"], answer: 1 },
    { id: "G11-ELA-87", grade: 11, subject: "ELA", topic: "Rhetoric", question: "The 'Straw Man' fallacy involves ___.", choices: ["Scarecrows", "Misrepresenting an opponent's view", "Being honest", "Using facts"], answer: 1 },
    { id: "G11-ELA-88", grade: 11, subject: "ELA", topic: "Rhetoric", question: "___ is the use of humor or irony to criticize foolishness.", choices: ["Drama", "Satire", "Epic", "History"], answer: 1 },
    { id: "G11-ELA-89", grade: 11, subject: "ELA", topic: "Rhetoric", question: "A 'Euphemism' makes something offensive or harsh sound ___.", choices: ["Worse", "Milder/Better", "Funny", "Scientific"], answer: 1 },
    { id: "G11-ELA-90", grade: 11, subject: "ELA", topic: "Rhetoric", question: "Assertion is a ___ of fact or belief.", choices: ["Doubt", "Forceful statement", "Question", "Summary"], answer: 1 },
    { id: "G11-ELA-91", grade: 11, subject: "ELA", topic: "Rhetoric", question: "Bias is a ___ in favor of or against something.", choices: ["Fact", "Prejudice", "Truth", "Measurement"], answer: 1 },
    { id: "G11-ELA-92", grade: 11, subject: "ELA", topic: "Rhetoric", question: "Propaganda is used to ___.", choices: ["Teach math", "Promote a specific political cause/view", "Inform neutrally", "Entertain"], answer: 1 },
    { id: "G11-ELA-93", grade: 11, subject: "ELA", topic: "Rhetoric", question: "Inductive reasoning moves from ___ to general.", choices: ["General", "Specific", "Unknown", "False"], answer: 1 },
    { id: "G11-ELA-94", grade: 11, subject: "ELA", topic: "Rhetoric", question: "Deductive reasoning moves from general to ___.", choices: ["Large", "Specific", "Abstract", "Vague"], answer: 1 },
    { id: "G11-ELA-95", grade: 11, subject: "ELA", topic: "Rhetoric", question: "Parallelism creates a sense of ___.", choices: ["Chaos", "Rhythm and Balance", "Confusion", "Boredom"], answer: 1 },
    { id: "G11-ELA-96", grade: 11, subject: "ELA", topic: "Rhetoric", question: "Repetition is used to reinforce a ___.", choices: ["Lie", "Key point", "Mistake", "Sound"], answer: 1 },
    { id: "G11-ELA-97", grade: 11, subject: "ELA", topic: "Rhetoric", question: "Testimonials use ___ to build credibility.", choices: ["Numbers", "Real people's experiences", "Magic", "History"], answer: 1 },
    { id: "G11-ELA-98", grade: 11, subject: "ELA", topic: "Rhetoric", question: "Loaded language uses words with strong ___ connotations.", choices: ["Neutral", "Emotional", "Dictionary", "Technical"], answer: 1 },
    { id: "G11-ELA-99", grade: 11, subject: "ELA", topic: "Rhetoric", question: "An 'Analogy' is a ___ between two things.", choices: ["Difference", "Comparison", "War", "Distance"], answer: 1 },
    { id: "G11-ELA-100", grade: 11, subject: "ELA", topic: "Rhetoric", question: "The goal of persuasion is to ___ the audience.", choices: ["Anger", "Influence/Change the mind of", "Bore", "Ignore"], answer: 1 }
];

module.exports = G11_ELA_COMPLETE;
