const G11_PHYSICS_COMPLETE = [
    // --- TOPIC 1: MECHANICS & MOTION (25 Questions) ---
    { id: "G11-PH-01", grade: 11, subject: "Physics", topic: "Kinematics", question: "Velocity is the rate of change of ___.", choices: ["Speed", "Displacement", "Acceleration", "Time"], answer: 1 },
    { id: "G11-PH-02", grade: 11, subject: "Physics", topic: "Kinematics", question: "Acceleration is the rate of change of ___.", choices: ["Distance", "Velocity", "Mass", "Force"], answer: 1 },
    { id: "G11-PH-03", grade: 11, subject: "Physics", topic: "Kinematics", question: "A vector quantity has both magnitude and ___.", choices: ["Weight", "Quantity", "Direction", "Volume"], answer: 2 },
    { id: "G11-PH-04", grade: 11, subject: "Physics", topic: "Kinematics", question: "The slope of a position-time graph represents ___.", choices: ["Acceleration", "Velocity", "Displacement", "Force"], answer: 1 },
    { id: "G11-PH-05", grade: 11, subject: "Physics", topic: "Kinematics", question: "The area under a velocity-time graph represents ___.", choices: ["Acceleration", "Displacement", "Speed", "Friction"], answer: 1 },
    { id: "G11-PH-06", grade: 11, subject: "Physics", topic: "Kinematics", question: "Newton's First Law is also known as the Law of ___.", choices: ["Gravity", "Inertia", "Action", "Energy"], answer: 1 },
    { id: "G11-PH-07", grade: 11, subject: "Physics", topic: "Dynamics", question: "Newton's Second Law states that Force = Mass x ___.", choices: ["Velocity", "Acceleration", "Gravity", "Time"], answer: 1 },
    { id: "G11-PH-08", grade: 11, subject: "Physics", topic: "Dynamics", question: "For every action, there is an equal and opposite reaction. This is Newton's ___ Law.", choices: ["First", "Second", "Third", "Fourth"], answer: 2 },
    { id: "G11-PH-09", grade: 11, subject: "Physics", topic: "Dynamics", question: "The force that opposes motion between two surfaces is ___.", choices: ["Inertia", "Friction", "Gravity", "Tension"], answer: 1 },
    { id: "G11-PH-10", grade: 11, subject: "Physics", topic: "Dynamics", question: "Mass is measured in ___.", choices: ["Newtons", "Kilograms", "Joules", "Watts"], answer: 1 },
    { id: "G11-PH-11", grade: 11, subject: "Physics", topic: "Dynamics", question: "Weight is a force measured in ___.", choices: ["Kilograms", "Newtons", "Grams", "Meters"], answer: 1 },
    { id: "G11-PH-12", grade: 11, subject: "Physics", topic: "Kinematics", question: "Acceleration due to gravity on Earth is approximately ___ m/s^2.", choices: ["1.6", "9.8", "25", "273"], answer: 1 },
    { id: "G11-PH-13", grade: 11, subject: "Physics", topic: "Dynamics", question: "A body in equilibrium has a net force of ___.", choices: ["9.8 N", "0 N", "100 N", "Infinity"], answer: 1 },
    { id: "G11-PH-14", grade: 11, subject: "Physics", topic: "Dynamics", question: "Normal force is always ___ to the surface.", choices: ["Parallel", "Perpendicular", "Opposite", "Equal"], answer: 1 },
    { id: "G11-PH-15", grade: 11, subject: "Physics", topic: "Energy", question: "Work is done when a force causes ___.", choices: ["Heat", "Displacement", "Inertia", "Pressure"], answer: 1 },
    { id: "G11-PH-16", grade: 11, subject: "Physics", topic: "Energy", question: "Kinetic energy is the energy of ___.", choices: ["Position", "Motion", "Rest", "Atoms"], answer: 1 },
    { id: "G11-PH-17", grade: 11, subject: "Physics", topic: "Energy", question: "Potential energy is ___ energy based on position.", choices: ["Moving", "Stored", "Lost", "Chemical"], answer: 1 },
    { id: "G11-PH-18", grade: 11, subject: "Physics", topic: "Energy", question: "Mechanical energy is the sum of Kinetic and ___ energy.", choices: ["Thermal", "Potential", "Sound", "Light"], answer: 1 },
    { id: "G11-PH-19", grade: 11, subject: "Physics", topic: "Energy", question: "The unit of energy and work is the ___.", choices: ["Newton", "Joule", "Watt", "Volt"], answer: 1 },
    { id: "G11-PH-20", grade: 11, subject: "Physics", topic: "Energy", question: "Power is the rate at which ___ is done.", choices: ["Velocity", "Work", "Friction", "Gravity"], answer: 1 },
    { id: "G11-PH-21", grade: 11, subject: "Physics", topic: "Energy", question: "The unit of power is the ___.", choices: ["Joule", "Newton", "Watt", "Ampere"], answer: 2 },
    { id: "G11-PH-22", grade: 11, subject: "Physics", topic: "Momentum", question: "Momentum is the product of mass and ___.", choices: ["Acceleration", "Velocity", "Distance", "Force"], answer: 1 },
    { id: "G11-PH-23", grade: 11, subject: "Physics", topic: "Momentum", question: "In an elastic collision, both momentum and ___ are conserved.", choices: ["Heat", "Kinetic Energy", "Potential Energy", "Friction"], answer: 1 },
    { id: "G11-PH-24", grade: 11, subject: "Physics", topic: "Dynamics", question: "Centripetal force acts towards the ___ of a circular path.", choices: ["Outside", "Center", "Bottom", "Tangent"], answer: 1 },
    { id: "G11-PH-25", grade: 11, subject: "Physics", topic: "Gravity", question: "Newton's Law of Universal Gravitation states force is proportional to the product of ___.", choices: ["Speeds", "Masses", "Distances", "Times"], answer: 1 },

    // --- TOPIC 2: WAVES & OPTICS (25 Questions) ---
    { id: "G11-PH-26", grade: 11, subject: "Physics", topic: "Waves", question: "A 'Transverse' wave oscillates ___ to the direction of travel.", choices: ["Parallel", "Perpendicular", "Opposite", "Randomly"], answer: 1 },
    { id: "G11-PH-27", grade: 11, subject: "Physics", topic: "Waves", question: "A 'Longitudinal' wave oscillates ___ to the direction of travel.", choices: ["Perpendicular", "Parallel", "Circularly", "At 45 degrees"], answer: 1 },
    { id: "G11-PH-28", grade: 11, subject: "Physics", topic: "Waves", question: "Sound is a ___ wave.", choices: ["Transverse", "Longitudinal", "Electromagnetic", "Vacuum"], answer: 1 },
    { id: "G11-PH-29", grade: 11, subject: "Physics", topic: "Waves", question: "The distance between two consecutive crests is the ___.", choices: ["Frequency", "Amplitude", "Wavelength", "Period"], answer: 2 },
    { id: "G11-PH-30", grade: 11, subject: "Physics", topic: "Waves", question: "Frequency is measured in ___.", choices: ["Meters", "Seconds", "Hertz", "Joules"], answer: 2 },
    { id: "G11-PH-31", grade: 11, subject: "Physics", topic: "Waves", question: "The maximum displacement from the rest position is the ___.", choices: ["Wavelength", "Amplitude", "Crest", "Period"], answer: 1 },
    { id: "G11-PH-32", grade: 11, subject: "Physics", topic: "Waves", question: "Period is the ___ it takes for one full cycle.", choices: ["Distance", "Time", "Speed", "Frequency"], answer: 1 },
    { id: "G11-PH-33", grade: 11, subject: "Physics", topic: "Optics", question: "Bending of light as it passes from one medium to another is ___.", choices: ["Reflection", "Refraction", "Diffraction", "Absorption"], answer: 1 },
    { id: "G11-PH-34", grade: 11, subject: "Physics", topic: "Optics", question: "The Law of Reflection states the angle of incidence ___ the angle of reflection.", choices: ["Is greater than", "Equals", "Is half of", "Is less than"], answer: 1 },
    { id: "G11-PH-35", grade: 11, subject: "Physics", topic: "Optics", question: "A lens that is thicker in the middle than the edges is a ___ lens.", choices: ["Concave", "Convex", "Flat", "Cylindrical"], answer: 1 },
    { id: "G11-PH-36", grade: 11, subject: "Physics", topic: "Optics", question: "The 'Index of Refraction' measures how much a medium ___ light.", choices: ["Speeds up", "Slows down", "Reflects", "Absorbs"], answer: 1 },
    { id: "G11-PH-37", grade: 11, subject: "Physics", topic: "Waves", question: "___ occurs when two waves overlap and combine.", choices: ["Refraction", "Interference", "Diffusion", "Damping"], answer: 1 },
    { id: "G11-PH-38", grade: 11, subject: "Physics", topic: "Optics", question: "Light is a(n) ___ wave.", choices: ["Mechanical", "Electromagnetic", "Longitudinal", "Sound"], answer: 1 },
    { id: "G11-PH-39", grade: 11, subject: "Physics", topic: "Optics", question: "Snell's Law relates the angle of incidence to the angle of ___.", choices: ["Reflection", "Refraction", "Diffraction", "Absorption"], answer: 1 },
    { id: "G11-PH-40", grade: 11, subject: "Physics", topic: "Waves", question: "The Doppler Effect is a change in ___ due to relative motion.", choices: ["Speed", "Frequency/Pitch", "Amplitude", "Color"], answer: 1 },
    { id: "G11-PH-41", grade: 11, subject: "Physics", topic: "Optics", question: "A mirror that curves inward is a ___ mirror.", choices: ["Plane", "Convex", "Concave", "Cylindrical"], answer: 2 },
    { id: "G11-PH-42", grade: 11, subject: "Physics", topic: "Optics", question: "Total internal reflection occurs when the angle of incidence exceeds the ___ angle.", choices: ["Refractive", "Critical", "Brewster", "Maximum"], answer: 1 },
    { id: "G11-PH-43", grade: 11, subject: "Physics", topic: "Waves", question: "Electromagnetic waves do not require a ___ to travel.", choices: ["Vacuum", "Medium", "Source", "Receiver"], answer: 1 },
    { id: "G11-PH-44", grade: 11, subject: "Physics", topic: "Optics", question: "Dispersion is the separating of white light into ___.", choices: ["Shadows", "Colors (Spectrum)", "Infrared", "Darkness"], answer: 1 },
    { id: "G11-PH-45", grade: 11, subject: "Physics", topic: "Optics", question: "A virtual image is one from which light rays ___ appear to diverge.", choices: ["Always", "Only", "Never", "Do not"], answer: 0 },
    { id: "G11-PH-46", grade: 11, subject: "Physics", topic: "Optics", question: "The 'Focal Point' of a lens is where ___ rays converge.", choices: ["Scattered", "Parallel", "Curved", "Diffused"], answer: 1 },
    { id: "G11-PH-47", grade: 11, subject: "Physics", topic: "Optics", question: "Real images can be projected onto a ___.", choices: ["Mirror", "Lens", "Screen", "Vacuum"], answer: 2 },
    { id: "G11-PH-48", grade: 11, subject: "Physics", topic: "Waves", question: "A 'Standing Wave' is produced by the interference of two ___ waves.", choices: ["Perpendicular", "Identical traveling", "Random", "Sound"], answer: 1 },
    { id: "G11-PH-49", grade: 11, subject: "Physics", topic: "Waves", question: "Constructive interference results in a ___ amplitude.", choices: ["Smaller", "Zero", "Larger", "Constant"], answer: 2 },
    { id: "G11-PH-50", grade: 11, subject: "Physics", topic: "Waves", question: "Destructive interference results in a ___ amplitude.", choices: ["Larger", "Doubled", "Smaller or zero", "Square"], answer: 2 },

    // --- TOPIC 3: ELECTRICITY & MAGNETISM (25 Questions) ---
    { id: "G11-PH-51", grade: 11, subject: "Physics", topic: "Electrostatics", question: "Like charges ___ each other.", choices: ["Attract", "Repel", "Neutralize", "Multiply"], answer: 1 },
    { id: "G11-PH-52", grade: 11, subject: "Physics", topic: "Electrostatics", question: "Opposite charges ___ each other.", choices: ["Repel", "Attract", "Block", "Ignore"], answer: 1 },
    { id: "G11-PH-53", grade: 11, subject: "Physics", topic: "Electrostatics", question: "Current is the flow of ___.", choices: ["Protons", "Neutrons", "Electric charge/Electrons", "Heat"], answer: 2 },
    { id: "G11-PH-54", grade: 11, subject: "Physics", topic: "Circuits", question: "Resistance is measured in ___.", choices: ["Watts", "Ohms", "Volts", "Amps"], answer: 1 },
    { id: "G11-PH-55", grade: 11, subject: "Physics", topic: "Circuits", question: "Ohm's Law: Voltage (V) = ___ x Resistance (R).", choices: ["Power", "Current (I)", "Charge", "Time"], answer: 1 },
    { id: "G11-PH-56", grade: 11, subject: "Physics", topic: "Circuits", question: "Current is measured in ___.", choices: ["Volts", "Amperes", "Ohms", "Joules"], answer: 1 },
    { id: "G11-PH-57", grade: 11, subject: "Physics", topic: "Circuits", question: "Potential difference is measured in ___.", choices: ["Amps", "Ohms", "Volts", "Watts"], answer: 2 },
    { id: "G11-PH-58", grade: 11, subject: "Physics", topic: "Circuits", question: "In a 'Series' circuit, there is ___ path(s) for current.", choices: ["One", "Many", "No", "Three"], answer: 0 },
    { id: "G11-PH-59", grade: 11, subject: "Physics", topic: "Circuits", question: "In a 'Parallel' circuit, there are ___ path(s) for current.", choices: ["One", "Multiple", "Constant", "Rotating"], answer: 1 },
    { id: "G11-PH-60", grade: 11, subject: "Physics", topic: "Magnetism", question: "Magnetic poles always exist in ___ (North and South).", choices: ["Singulars", "Pairs", "Groups of three", "Squares"], answer: 1 },
    { id: "G11-PH-61", grade: 11, subject: "Physics", topic: "Magnetism", question: "Electromagnetic induction is the process of generating ___ with a magnetic field.", choices: ["Heat", "Mass", "Current", "Gravity"], answer: 2 },
    { id: "G11-PH-62", grade: 11, subject: "Physics", topic: "Magnetism", question: "A device that converts mechanical energy into electrical energy is a ___.", choices: ["Motor", "Generator", "Transformer", "Battery"], answer: 1 },
    { id: "G11-PH-63", grade: 11, subject: "Physics", topic: "Magnetism", question: "A device that converts electrical energy into mechanical energy is a ___.", choices: ["Generator", "Motor", "Solar panel", "Heater"], answer: 1 },
    { id: "G11-PH-64", grade: 11, subject: "Physics", topic: "Circuits", question: "Total resistance in series: R_total = ___.", choices: ["R1 + R2 + ...", "1/R1 + 1/R2", "R1 * R2", "R1 - R2"], answer: 0 },
    { id: "G11-PH-65", grade: 11, subject: "Physics", topic: "Circuits", question: "A 'Conductor' is a material that allows charge to flow ___.", choices: ["Hardly", "Easily", "Only in circles", "Not at all"], answer: 1 },
    { id: "G11-PH-66", grade: 11, subject: "Physics", topic: "Circuits", question: "An 'Insulator' is a material that ___ flow of charge.", choices: ["Speeds up", "Slows or stops", "Filters", "Duplicates"], answer: 1 },
    { id: "G11-PH-67", grade: 11, subject: "Physics", topic: "Magnetism", question: "A current-carrying wire wrapped around an iron core is an ___.", choices: ["Insulator", "Electromagnet", "Permanent magnet", "Capacitor"], answer: 1 },
    { id: "G11-PH-68", grade: 11, subject: "Physics", topic: "Power", question: "Power in a circuit is P = I * ___.", choices: ["R", "V", "T", "Q"], answer: 1 },
    { id: "G11-PH-69", grade: 11, subject: "Physics", topic: "Circuits", question: "A 'Fuse' or 'Circuit Breaker' is used for ___.", choices: ["Increasing current", "Safety (breaking the circuit)", "Dimming lights", "Saving power"], answer: 1 },
    { id: "G11-PH-70", grade: 11, subject: "Physics", topic: "Electrostatics", question: "Charging by 'Induction' occurs without ___ contact.", choices: ["Visual", "Physical", "Electric", "Magnetic"], answer: 1 },
    { id: "G11-PH-71", grade: 11, subject: "Physics", topic: "Circuits", question: "What is the role of a battery in a circuit?", choices: ["Increase resistance", "Provide potential difference (voltage)", "Stop flow", "Store sound"], answer: 1 },
    { id: "G11-PH-72", grade: 11, subject: "Physics", topic: "Electrostatics", question: "The charge of an electron is ___.", choices: ["Positive", "Negative", "Neutral", "Variable"], answer: 1 },
    { id: "G11-PH-73", grade: 11, subject: "Physics", topic: "Electrostatics", question: "The charge of a proton is ___.", choices: ["Negative", "Neutral", "Positive", "Zero"], answer: 2 },
    { id: "G11-PH-74", grade: 11, subject: "Physics", topic: "Magnetism", question: "Magnetic field lines go from ___ pole to ___ pole.", choices: ["S to N", "N to S", "Mid to High", "E to W"], answer: 1 },
    { id: "G11-PH-75", grade: 11, subject: "Physics", topic: "Circuits", question: "The current is ___ everywhere in a series circuit.", choices: ["Different", "The same", "Zero", "Random"], answer: 1 },

    // --- TOPIC 4: THERMODYNAMICS & MODERN PHYSICS (25 Questions) ---
    { id: "G11-PH-76", grade: 11, subject: "Physics", topic: "Thermal", question: "Temperature is a measure of the average ___ of particles.", choices: ["Potential energy", "Kinetic energy", "Mass", "Volume"], answer: 1 },
    { id: "G11-PH-77", grade: 11, subject: "Physics", topic: "Thermal", question: "Heat is the transfer of ___ from hot to cold.", choices: ["Fluid", "Thermal energy", "Atoms", "Mass"], answer: 1 },
    { id: "G11-PH-78", grade: 11, subject: "Physics", topic: "Thermal", question: "Conduction is heat transfer through ___.", choices: ["Vacuums", "Direct contact", "Moving fluids", "Waves"], answer: 1 },
    { id: "G11-PH-79", grade: 11, subject: "Physics", topic: "Thermal", question: "Convection is heat transfer through ___.", choices: ["Solids", "Fluids (liquids/gases)", "Radiowaves", "Contact"], answer: 1 },
    { id: "G11-PH-80", grade: 11, subject: "Physics", topic: "Thermal", question: "Radiation is heat transfer through ___ waves.", choices: ["Mechanical", "Electromagnetic", "Pressure", "Sound"], answer: 1 },
    { id: "G11-PH-81", grade: 11, subject: "Physics", topic: "Thermal", question: "Specific heat is energy needed to raise the temp of 1kg by ___ degree.", choices: ["1", "10", "100", "0"], answer: 0 },
    { id: "G11-PH-82", grade: 11, subject: "Physics", topic: "Thermal", question: "Absolute zero is the temperature where particle motion ___.", choices: ["Is fastest", "Stops (minimum energy)", "Is constant", "Reverses"], answer: 1 },
    { id: "G11-PH-83", grade: 11, subject: "Physics", topic: "Thermal", question: "The unit of temperature in the SI system is ___.", choices: ["Celsius", "Kelvin", "Fahrenheit", "Calories"], answer: 1 },
    { id: "G11-PH-84", grade: 11, subject: "Physics", topic: "Modern", question: "Plato proposed light acts as a particle called a ___.", choices: ["Neutron", "Photon", "Proton", "Ion"], answer: 1 },
    { id: "G11-PH-85", grade: 11, subject: "Physics", topic: "Modern", question: "E = mc^2 relates energy to ___.", choices: ["Charge", "Mass", "Speed", "Frequency"], answer: 1 },
    { id: "G11-PH-86", grade: 11, subject: "Physics", topic: "Modern", question: "The photo-electric effect proves the ___ nature of light.", choices: ["Wave", "Particle", "Sound", "Invisible"], answer: 1 },
    { id: "G11-PH-87", grade: 11, subject: "Physics", topic: "Nuclear", question: "Fission is the ___ of a heavy nucleus.", choices: ["Joining", "Splitting", "Heating", "Cooling"], answer: 1 },
    { id: "G11-PH-88", grade: 11, subject: "Physics", topic: "Nuclear", question: "Fusion is the ___ of light nuclei.", choices: ["Splitting", "Combining", "Decaying", "Orbiting"], answer: 1 },
    { id: "G11-PH-89", grade: 11, subject: "Physics", topic: "Modern", question: "Heisenberg's Uncertainty Principle states you cannot know both position and ___ precisely.", choices: ["Mass", "Momentum/Velocity", "Color", "Charge"], answer: 1 },
    { id: "G11-PH-90", grade: 11, subject: "Physics", topic: "Nuclear", question: "Alpha radiation consists of ___ nuclei.", choices: ["Hydrogen", "Helium", "Electron", "Neutron"], answer: 1 },
    { id: "G11-PH-91", grade: 11, subject: "Physics", topic: "Nuclear", question: "Beta radiation consists of high-speed ___.", choices: ["Protons", "Electrons/Positrons", "Photons", "Neutrons"], answer: 1 },
    { id: "G11-PH-92", grade: 11, subject: "Physics", topic: "Nuclear", question: "Gamma radiation is high-energy ___.", choices: ["Electrons", "Particles", "Electromagnetic waves (photoms)", "Helium"], answer: 2 },
    { id: "G11-PH-93", grade: 11, subject: "Physics", topic: "Modern", question: "The 'Half-life' of an isotope is the time for ___ of it to decay.", choices: ["10%", "Half", "All", "90%"], answer: 1 },
    { id: "G11-PH-94", grade: 11, subject: "Physics", topic: "Modern", question: "Who developed the Theory of Relativity?", choices: ["Newton", "Einstein", "Bohr", "Hawking"], answer: 1 },
    { id: "G11-PH-95", grade: 11, subject: "Physics", topic: "Modern", question: "The speed of light in a vacuum is approximately ___ m/s.", choices: ["340", "3 million", "300,000,000", "Infinite"], answer: 2 },
    { id: "G11-PH-96", grade: 11, subject: "Physics", topic: "Thermal", question: "Entropy is a measure of the ___ of a system.", choices: ["Order", "Disorder/Randomness", "Heat", "Mass"], answer: 1 },
    { id: "G11-PH-97", grade: 11, subject: "Physics", topic: "Thermal", question: "Phase change from solid to liquid is ___.", choices: ["Freezing", "Melting", "Boiling", "Sublimation"], answer: 1 },
    { id: "G11-PH-98", grade: 11, subject: "Physics", topic: "Modern", question: "Light shows duality: it is both a ___ and a ___.", choices: ["Solid, Liquid", "Wave, Particle", "Sound, Heat", "Proton, Electron"], answer: 1 },
    { id: "G11-PH-99", grade: 11, subject: "Physics", topic: "Nuclear", question: "Radioactivity is the ___ decay of an unstable nucleus.", choices: ["Forced", "Spontaneous", "Planned", "Slow"], answer: 1 },
    { id: "G11-PH-100", grade: 11, subject: "Physics", topic: "Modern", question: "A 'Black Hole' is a region with gravity so strong that ___ cannot escape.", choices: ["Mass", "Sound", "Light", "Shadows"], answer: 2 }
];

module.exports = G11_PHYSICS_COMPLETE;
