const G11_MATH_COMPLETE = [
    // --- TOPIC 1: ALGEBRA 2 & FUNCTIONS (25 Questions) ---
    { id: "G11-MA-01", grade: 11, subject: "Math", topic: "Functions", question: "If f(x) = x^2 and g(x) = x + 3, find (f ∘ g)(x).", choices: ["x^2 + 3", "(x + 3)^2", "x^2 + x + 3", "x^3 + 3x^2"], answer: 1 },
    { id: "G11-MA-02", grade: 11, subject: "Math", topic: "Functions", question: "The domain of a function refers to all possible ___ values.", choices: ["y", "x", "Slope", "Output"], answer: 1 },
    { id: "G11-MA-03", grade: 11, subject: "Math", topic: "Functions", question: "The range of a function refers to all possible ___ values.", choices: ["x", "y", "Input", "Initial"], answer: 1 },
    { id: "G11-MA-04", grade: 11, subject: "Math", topic: "Inverses", question: "To find the inverse of a function, you switch x and y and then ___.", choices: ["Multiply", "Solve for y", "Divide by x", "Add 10"], answer: 1 },
    { id: "G11-MA-05", grade: 11, subject: "Math", topic: "Complex Numbers", question: "What is the value of i^2?", choices: ["1", "-1", "i", "0"], answer: 1 },
    { id: "G11-MA-06", grade: 11, subject: "Math", topic: "Complex Numbers", question: "Simplify (3 + 2i) + (5 - 4i).", choices: ["8 - 2i", "8 + 6i", "15 - 8i", "2 - 2i"], answer: 0 },
    { id: "G11-MA-07", grade: 11, subject: "Math", topic: "Polynomials", question: "A root of a polynomial is also called a ___.", choices: ["Peak", "Zero", "Vertex", "Slope"], answer: 1 },
    { id: "G11-MA-08", grade: 11, subject: "Math", topic: "Polynomials", question: "The 'Remainder Theorem' states that if f(x) is divided by (x - c), the remainder is ___.", choices: ["f(0)", "f(c)", "0", "c"], answer: 1 },
    { id: "G11-MA-09", grade: 11, subject: "Math", topic: "Polynomials", question: "The 'Factor Theorem' states that (x - c) is a factor if f(c) = ___.", choices: ["1", "c", "0", "-1"], answer: 2 },
    { id: "G11-MA-10", grade: 11, subject: "Math", topic: "Logs", question: "log_b(xy) is equal to ___.", choices: ["log_b(x) * log_b(y)", "log_b(x) + log_b(y)", "log_b(x) / log_b(y)", "x * y"], answer: 1 },
    { id: "G11-MA-11", grade: 11, subject: "Math", topic: "Logs", question: "log_b(x/y) is equal to ___.", choices: ["log_b(x) + log_b(y)", "log_b(x) - log_b(y)", "log_b(x) * log_b(y)", "x/y"], answer: 1 },
    { id: "G11-MA-12", grade: 11, subject: "Math", topic: "Logs", question: "log_b(x^n) is equal to ___.", choices: ["n + log_b(x)", "n * log_b(x)", "log_b(x) / n", "n^x"], answer: 1 },
    { id: "G11-MA-13", grade: 11, subject: "Math", topic: "Logs", question: "What is log_2(8)?", choices: ["2", "3", "4", "16"], answer: 1 },
    { id: "G11-MA-14", grade: 11, subject: "Math", topic: "Logs", question: "The value of log(100) (base 10) is ___.", choices: ["1", "2", "10", "100"], answer: 1 },
    { id: "G11-MA-15", grade: 11, subject: "Math", topic: "Exponents", question: "Solve for x: 2^x = 16", choices: ["2", "3", "4", "8"], answer: 2 },
    { id: "G11-MA-16", grade: 11, subject: "Math", topic: "Rational Functions", question: "An 'asymptote' is a line that a graph ___.", choices: ["Intersects", "Approaches but never touches", "Crosses twice", "Begins at"], answer: 1 },
    { id: "G11-MA-17", grade: 11, subject: "Math", topic: "Rational Functions", question: "A horizontal asymptote of y = (2x + 1)/(x - 3) is ___.", choices: ["y = 3", "y = 2", "y = 0", "No asymptote"], answer: 1 },
    { id: "G11-MA-18", grade: 11, subject: "Math", topic: "Logs", question: "The 'natural logarithm' has a base of ___.", choices: ["10", "2", "e", "pi"], answer: 2 },
    { id: "G11-MA-19", grade: 11, subject: "Math", topic: "Matrices", question: "To add two matrices, they must have the same ___.", choices: ["Values", "Dimensions", "Determinant", "Inverse"], answer: 1 },
    { id: "G11-MA-20", grade: 11, subject: "Math", topic: "Matrices", question: "The product of a matrix and its inverse is the ___ matrix.", choices: ["Zero", "Identity", "Square", "Scalar"], answer: 1 },
    { id: "G11-MA-21", grade: 11, subject: "Math", topic: "Radicals", question: "Simplify √-4 in complex numbers.", choices: ["2", "-2", "2i", "4i"], answer: 2 },
    { id: "G11-MA-22", grade: 11, subject: "Math", topic: "Quadratics", question: "The discriminant of b^2 - 4ac determines the ___ of roots.", choices: ["Value", "Number and nature", "Sign", "Slope"], answer: 1 },
    { id: "G11-MA-23", grade: 11, subject: "Math", topic: "Functions", question: "A function is 'Even' if f(-x) = ___.", choices: ["f(x)", "-f(x)", "1/f(x)", "0"], answer: 0 },
    { id: "G11-MA-24", grade: 11, subject: "Math", topic: "Functions", question: "A function is 'Odd' if f(-x) = ___.", choices: ["f(x)", "-f(x)", "0", "1"], answer: 1 },
    { id: "G11-MA-25", grade: 11, subject: "Math", topic: "Sequences", question: "An arithmetic sequence has a common ___.", choices: ["Ratio", "Difference", "Factor", "Multiple"], answer: 1 },

    // --- TOPIC 2: TRIGONOMETRY (25 Questions) ---
    { id: "G11-MA-26", grade: 11, subject: "Math", topic: "Trig", question: "How many radians are in 180 degrees?", choices: ["pi/2", "pi", "2pi", "pi/4"], answer: 1 },
    { id: "G11-MA-27", grade: 11, subject: "Math", topic: "Trig", question: "Convert 90 degrees to radians.", choices: ["pi", "pi/2", "pi/3", "2pi"], answer: 1 },
    { id: "G11-MA-28", grade: 11, subject: "Math", topic: "Trig", question: "The 'Unit Circle' has a radius of ___.", choices: ["pi", "1", "2", "0.5"], answer: 1 },
    { id: "G11-MA-29", grade: 11, subject: "Math", topic: "Trig", question: "In the unit circle, sin(θ) is equal to which coordinate?", choices: ["x", "y", "r", "slope"], answer: 1 },
    { id: "G11-MA-30", grade: 11, subject: "Math", topic: "Trig", question: "In the unit circle, cos(θ) is equal to which coordinate?", choices: ["x", "y", "slope", "radius"], answer: 0 },
    { id: "G11-MA-31", grade: 11, subject: "Math", topic: "Trig", question: "What is tan(θ) in terms of sin and cos?", choices: ["sin * cos", "cos / sin", "sin / cos", "1 / sin"], answer: 2 },
    { id: "G11-MA-32", grade: 11, subject: "Math", topic: "Trig", question: "Pythagorean Identity: sin^2(θ) + cos^2(θ) = ___.", choices: ["0", "1", "tan^2(θ)", "2"], answer: 1 },
    { id: "G11-MA-33", grade: 11, subject: "Math", topic: "Trig", question: "What is sin(90°)?", choices: ["0", "1", "0.5", "-1"], answer: 1 },
    { id: "G11-MA-34", grade: 11, subject: "Math", topic: "Trig", question: "What is cos(0°)?", choices: ["0", "1", "-1", "pi"], answer: 1 },
    { id: "G11-MA-35", grade: 11, subject: "Math", topic: "Trig", question: "What is the period of y = sin(x)?", choices: ["pi", "2pi", "pi/2", "4pi"], answer: 1 },
    { id: "G11-MA-36", grade: 11, subject: "Math", topic: "Trig", question: "The reciprocal of sin(θ) is ___.", choices: ["cos(θ)", "sec(θ)", "csc(θ)", "tan(θ)"], answer: 2 },
    { id: "G11-MA-37", grade: 11, subject: "Math", topic: "Trig", question: "The reciprocal of cos(θ) is ___.", choices: ["sin(θ)", "sec(θ)", "csc(θ)", "cot(θ)"], answer: 1 },
    { id: "G11-MA-38", grade: 11, subject: "Math", topic: "Trig", question: "What is sin(30°)?", choices: ["1/2", "√3/2", "1", "0"], answer: 0 },
    { id: "G11-MA-39", grade: 11, subject: "Math", topic: "Trig", question: "What is cos(60°)?", choices: ["√2/2", "1/2", "√3/2", "1"], answer: 1 },
    { id: "G11-MA-40", grade: 11, subject: "Math", topic: "Inverse Trig", question: "arcsin(x) is used to find a(n) ___.", choices: ["Side length", "Angle", "Radius", "Area"], answer: 1 },
    { id: "G11-MA-41", grade: 11, subject: "Math", topic: "Trig", question: "Law of Sines: a/sin(A) = ___.", choices: ["b/cos(B)", "b/sin(B)", "sin(a)/A", "c^2"], answer: 1 },
    { id: "G11-MA-42", grade: 11, subject: "Math", topic: "Trig", question: "Law of Cosines: c^2 = a^2 + b^2 - ___.", choices: ["2ab cos(C)", "2ab sin(C)", "ab", "2ab"], answer: 0 },
    { id: "G11-MA-43", grade: 11, subject: "Math", topic: "Trig", question: "Amplitude of y = 3 sin(x) + 1?", choices: ["1", "2", "3", "4"], answer: 2 },
    { id: "G11-MA-44", grade: 11, subject: "Math", topic: "Trig", question: "Vertical shift of y = 2 cos(x) - 5?", choices: ["2", "-5", "5", "0"], answer: 1 },
    { id: "G11-MA-45", grade: 11, subject: "Math", topic: "Trig", question: "Which quadrant is sin positive but cos negative?", choices: ["I", "II", "III", "IV"], answer: 1 },
    { id: "G11-MA-46", grade: 11, subject: "Math", topic: "Trig", question: "tan(45°) is equal to ___.", choices: ["0", "1", "√2", "Undefined"], answer: 1 },
    { id: "G11-MA-47", grade: 11, subject: "Math", topic: "Trig", question: "1 + tan^2(θ) = ___.", choices: ["cot^2(θ)", "csc^2(θ)", "sec^2(θ)", "sin^2(θ)"], answer: 2 },
    { id: "G11-MA-48", grade: 11, subject: "Math", topic: "Trig", question: "Double Angle Formula: sin(2θ) = ___.", choices: ["2 sin(θ) cos(θ)", "sin^2(θ) - cos^2(θ)", "2 sin(θ)", "cos(2θ)"], answer: 0 },
    { id: "G11-MA-49", grade: 11, subject: "Math", topic: "Trig", question: "Reference angle of 150°?", choices: ["50°", "30°", "60°", "45°"], answer: 1 },
    { id: "G11-MA-50", grade: 11, subject: "Math", topic: "Trig", question: "sec(θ) is equal to ___.", choices: ["1/sin(θ)", "1/cos(θ)", "sin/cos", "cos/sin"], answer: 1 },

    // --- TOPIC 3: PRE-CALCULUS & ANALYTIC GEOMETRY (25 Questions) ---
    { id: "G11-MA-51", grade: 11, subject: "Math", topic: "Conics", question: "The graph of x^2/a^2 + y^2/b^2 = 1 is an ___.", choices: ["Parabola", "Circle", "Ellipse", "Hyperbola"], answer: 2 },
    { id: "G11-MA-52", grade: 11, subject: "Math", topic: "Conics", question: "The graph of x^2/a^2 - y^2/b^2 = 1 is a ___.", choices: ["Circle", "Ellipse", "Hyperbola", "Parabola"], answer: 2 },
    { id: "G11-MA-53", grade: 11, subject: "Math", topic: "Conics", question: "If the eccentricity of an ellipse is 0, it is a ___.", choices: ["Line", "Square", "Circle", "Point"], answer: 2 },
    { id: "G11-MA-54", grade: 11, subject: "Math", topic: "Limits", question: "What is the limit of 1/x as x approaches infinity?", choices: ["1", "0", "Infinity", "Undefined"], answer: 1 },
    { id: "G11-MA-55", grade: 11, subject: "Math", topic: "Limits", question: "A limit exists if the left-hand limit ___ the right-hand limit.", choices: ["Exceeds", "Equals", "Is half of", "Is negative of"], answer: 1 },
    { id: "G11-MA-56", grade: 11, subject: "Math", topic: "Limits", question: "The limit of (sin x)/x as x approaches 0 is ___.", choices: ["0", "1", "Infinity", "Undefined"], answer: 1 },
    { id: "G11-MA-57", grade: 11, subject: "Math", topic: "Vectors", question: "A vector has both magnitude and ___.", choices: ["Weight", "Speed", "Direction", "Color"], answer: 2 },
    { id: "G11-MA-58", grade: 11, subject: "Math", topic: "Vectors", question: "The 'Dot Product' of two perpendicular vectors is ___.", choices: ["1", "0", "Infinite", "-1"], answer: 1 },
    { id: "G11-MA-59", grade: 11, subject: "Math", topic: "Polar", question: "In polar coordinates (r, θ), r represents the ___ from the origin.", choices: ["Angle", "Distance", "Slope", "X-coordinate"], answer: 1 },
    { id: "G11-MA-60", grade: 11, subject: "Math", topic: "Polar", question: "The equation r = 5 represents a ___.", choices: ["Line", "Circle", "Spiral", "Rose"], answer: 1 },
    { id: "G11-MA-61", grade: 11, subject: "Math", topic: "Sequences", question: "A geometric sequence has a common ___.", choices: ["Difference", "Ratio", "Sum", "Median"], answer: 1 },
    { id: "G11-MA-62", grade: 11, subject: "Math", topic: "Series", question: "Sum of an infinite geometric series: S = a / (1 - r) only if |r| is ___.", choices: ["> 1", "= 1", "< 1", "= 0"], answer: 2 },
    { id: "G11-MA-63", grade: 11, subject: "Math", topic: "Sums", question: "The symbol Σ (Sigma) represents a ___.", choices: ["Product", "Difference", "Sum", "Mean"], answer: 2 },
    { id: "G11-MA-64", grade: 11, subject: "Math", topic: "Induction", question: "Mathematical Induction is used to prove statements for all ___.", choices: ["Real numbers", "Complex numbers", "Natural numbers (n)", "Negative numbers"], answer: 2 },
    { id: "G11-MA-65", grade: 11, subject: "Math", topic: "Counting", question: "Number of ways to arrange n items (order matters) is ___.", choices: ["Combination", "Permutation", "Factorial (n!)", "Sum"], answer: 2 },
    { id: "G11-MA-66", grade: 11, subject: "Math", topic: "Counting", question: "A combination is used when order ___.", choices: ["Matters", "Does not matter", "Is reversed", "Is alphabetical"], answer: 1 },
    { id: "G11-MA-67", grade: 11, subject: "Math", topic: "Probability", question: "The probability of an event and its complement sum to ___.", choices: ["0", "0.5", "1", "10"], answer: 2 },
    { id: "G11-MA-68", grade: 11, subject: "Math", topic: "Stats", question: "Normal distribution follows a ___ curve.", choices: ["Flat", "Bell-shaped", "Square", "Linear"], answer: 1 },
    { id: "G11-MA-69", grade: 11, subject: "Math", topic: "Stats", question: "A 'z-score' tells you how many ___ a point is from the mean.", choices: ["Units", "Standard Deviations", "Medians", "Percentages"], answer: 1 },
    { id: "G11-MA-70", grade: 11, subject: "Math", topic: "Precalc", question: "A 'De Moivre's Theorem' deals with powers of ___ numbers.", choices: ["Real", "Imaginary/Complex", "Rational", "Prime"], answer: 1 },
    { id: "G11-MA-71", grade: 11, subject: "Math", topic: "Vectors", question: "The magnitude of vector <3, 4> is ___.", choices: ["5", "7", "25", "12"], answer: 0 },
    { id: "G11-MA-72", grade: 11, subject: "Math", topic: "Functions", question: "A 'Piecewise' function is defined by different ___ for different intervals.", choices: ["Domains", "Rules/formulas", "Graph colors", "Slopes"], answer: 1 },
    { id: "G11-MA-73", grade: 11, subject: "Math", topic: "Precalc", question: "Binomial Theorem uses coefficients from ___ Triangle.", choices: ["Pythagoras'", "Pascal's", "Euclid's", "Newton's"], answer: 1 },
    { id: "G11-MA-74", grade: 11, subject: "Math", topic: "Precalc", question: "Parametric equations define x and y in terms of a third variable called a ___.", choices: ["Constant", "Parameter (usually t)", "Scalar", "Vector"], answer: 1 },
    { id: "G11-MA-75", grade: 11, subject: "Math", topic: "Limits", question: "A function is continuous if the limit equals the ___.", choices: ["Slope", "Function value f(c)", "Zero", "Derivative"], answer: 1 },

    // --- TOPIC 4: PROBABILITY & STATISTICS (25 Questions) ---
    { id: "G11-MA-76", grade: 11, subject: "Math", topic: "Stats", question: "The middle value of a data set is the ___.", choices: ["Mean", "Median", "Mode", "Range"], answer: 1 },
    { id: "G11-MA-77", grade: 11, subject: "Math", topic: "Stats", question: "The average of a data set is the ___.", choices: ["Mean", "Median", "Mode", "Standard Deviation"], answer: 0 },
    { id: "G11-MA-78", grade: 11, subject: "Math", topic: "Stats", question: "The most frequent value is the ___.", choices: ["Mean", "Median", "Mode", "Outlier"], answer: 2 },
    { id: "G11-MA-79", grade: 11, subject: "Math", topic: "Stats", question: "Standard Deviation measures the ___ of data.", choices: ["Size", "Accuracy", "Spread/Dispersion", "Total"], answer: 2 },
    { id: "G11-MA-80", grade: 11, subject: "Math", topic: "Probability", question: "The set of all possible outcomes is the ___.", choices: ["Event", "Subset", "Sample Space", "Population"], answer: 2 },
    { id: "G11-MA-81", grade: 11, subject: "Math", topic: "Probability", question: "Independent events: P(A & B) = ___.", choices: ["P(A) + P(B)", "P(A) * P(B)", "P(A) / P(B)", "1"], answer: 1 },
    { id: "G11-MA-82", grade: 11, subject: "Math", topic: "Counting", question: "How many ways to pick a committee of 3 from 10 (order doesn't matter)?", choices: ["10 * 9 * 8", "10!", "10C3", "30"], answer: 2 },
    { id: "G11-MA-83", grade: 11, subject: "Math", topic: "Counting", question: "Evaluate 5! (5 factorial).", choices: ["5", "10", "120", "25"], answer: 2 },
    { id: "G11-MA-84", grade: 11, subject: "Math", topic: "Stats", question: "The 'Empirical Rule' (68-95-99.7) applies to ___ distributions.", choices: ["Uniform", "Normal", "Skewed", "Random"], answer: 1 },
    { id: "G11-MA-85", grade: 11, subject: "Math", topic: "Stats", question: "Which value is an outlier for {1, 2, 2, 3, 100}?", choices: ["1", "2", "3", "100"], answer: 3 },
    { id: "G11-MA-86", grade: 11, subject: "Math", topic: "Probability", question: "A fair die is rolled. Probability of rolling a 4?", choices: ["1/4", "1/6", "4/6", "1/2"], answer: 1 },
    { id: "G11-MA-87", grade: 11, subject: "Math", topic: "Probability", question: "Probability of an event that is CERTAIN to happen?", choices: ["0", "0.5", "1", "100"], answer: 2 },
    { id: "G11-MA-88", grade: 11, subject: "Math", topic: "Probability", question: "Probability of an IMPOSSIBLE event?", choices: ["-1", "0", "1", "Empty"], answer: 1 },
    { id: "G11-MA-89", grade: 11, subject: "Math", topic: "Stats", question: "Correlation coefficient (r) ranges from ___.", choices: ["0 to 1", "-1 to 1", "0 to 100", "-infinity to infinity"], answer: 1 },
    { id: "G11-MA-90", grade: 11, subject: "Math", topic: "Stats", question: "If r = 1, the correlation is perfectly ___.", choices: ["Negative", "Positive", "Random", "Zero"], answer: 1 },
    { id: "G11-MA-91", grade: 11, subject: "Math", topic: "Stats", question: "In a box plot, the line inside the box represents the ___.", choices: ["Mean", "Median", "Mode", "Range"], answer: 1 },
    { id: "G11-MA-92", grade: 11, subject: "Math", topic: "Stats", question: "The difference between Q3 and Q1 is the ___.", choices: ["Range", "Standard Deviation", "Interquartile Range (IQR)", "Mean"], answer: 2 },
    { id: "G11-MA-93", grade: 11, subject: "Math", topic: "Probability", question: "Two events that cannot happen at the same time are ___.", choices: ["Independent", "Mutually Exclusive", "Combined", "Dependent"], answer: 1 },
    { id: "G11-MA-94", grade: 11, subject: "Math", topic: "Stats", question: "A sample that doesn't accurately represent the population is ___.", choices: ["Fair", "Biased", "Random", "Large"], answer: 1 },
    { id: "G11-MA-95", grade: 11, subject: "Math", topic: "Stats", question: "The 'P-value' is used in ___ testing.", choices: ["Algebra", "Hypothesis", "Function", "Matrix"], answer: 1 },
    { id: "G11-MA-96", grade: 11, subject: "Math", topic: "Counting", question: "How many ways to arrange the letters in 'CAT'?", choices: ["3", "6", "9", "27"], answer: 1 },
    { id: "G11-MA-97", grade: 11, subject: "Math", topic: "Probability", question: "Expected Value is the ___ outcome over many trials.", choices: ["Lowest", "Average/Mean", "Highest", "Random"], answer: 1 },
    { id: "G11-MA-98", grade: 11, subject: "Math", topic: "Stats", question: "Qualitative data deals with ___.", choices: ["Numbers", "Categories/Descriptions", "Weights", "Measurements"], answer: 1 },
    { id: "G11-MA-99", grade: 11, subject: "Math", topic: "Stats", question: "Quantitative data deals with ___.", choices: ["Names", "Numbers/Quantities", "Colors", "Feelings"], answer: 1 },
    { id: "G11-MA-100", grade: 11, subject: "Math", topic: "Probability", question: "Conditional Probability: P(A|B) is the probability of A ___ B has happened.", choices: ["Before", "Given that", "Instead of", "Because"], answer: 1 }
];

module.exports = G11_MATH_COMPLETE;
