const G12_MATH_COMPLETE = [
    // --- TOPIC 1: LIMITS & DERIVATIVES (25 Questions) ---
    { id: "G12-MA-01", grade: 12, subject: "Math", topic: "Limits", question: "A limit describes the value a function approaches as the input ___ a certain point.", choices: ["Reaches", "Approaches", "Exceeds", "Avoids"], answer: 1 },
    { id: "G12-MA-02", grade: 12, subject: "Math", topic: "Calculus", question: "The derivative of a function represents its instantaneous ___.", choices: ["Area", "Rate of change (Slope)", "Volume", "Intercept"], answer: 1 },
    { id: "G12-MA-03", grade: 12, subject: "Math", topic: "Calculus", question: "The Power Rule: The derivative of x^n is ___.", choices: ["nx^n", "nx^(n-1)", "x^(n+1)", "1/x"], answer: 1 },
    { id: "G12-MA-04", grade: 12, subject: "Math", topic: "Calculus", question: "The derivative of a constant (like 5) is always ___.", choices: ["1", "5", "0", "x"], answer: 2 },
    { id: "G12-MA-05", grade: 12, subject: "Math", topic: "Calculus", question: "The derivative of sin(x) is ___.", choices: ["cos(x)", "-cos(x)", "tan(x)", "sec(x)"], answer: 0 },
    { id: "G12-MA-06", grade: 12, subject: "Math", topic: "Calculus", question: "The derivative of cos(x) is ___.", choices: ["sin(x)", "-sin(x)", "-cos(x)", "csc(x)"], answer: 1 },
    { id: "G12-MA-07", grade: 12, subject: "Math", topic: "Calculus", question: "A point where the derivative is zero or undefined is called a ___ point.", choices: ["Critical", "Inflection", "Maximum", "Zero"], answer: 0 },
    { id: "G12-MA-08", grade: 12, subject: "Math", topic: "Calculus", question: "The 'Product Rule' is used to find the derivative of two functions being ___.", choices: ["Added", "Divided", "Multiplied", "Squared"], answer: 2 },
    { id: "G12-MA-09", grade: 12, subject: "Math", topic: "Calculus", question: "The 'Chain Rule' is used for the derivative of ___ functions.", choices: ["Linear", "Composite (functions within functions)", "Simple", "Constant"], answer: 1 },
    { id: "G12-MA-10", grade: 12, subject: "Math", topic: "Calculus", question: "The derivative of e^x is ___.", choices: ["xe^x", "e^x", "ln(x)", "1"], answer: 1 },
    { id: "G12-MA-11", grade: 12, subject: "Math", topic: "Calculus", question: "If the second derivative is positive, the graph is concave ___.", choices: ["Up", "Down", "Left", "Right"], answer: 0 },
    { id: "G12-MA-12", grade: 12, subject: "Math", topic: "Calculus", question: "An 'Inflection Point' is where the graph changes ___.", choices: ["Direction", "Concavity", "Slope", "Color"], answer: 1 },
    { id: "G12-MA-13", grade: 12, subject: "Math", topic: "Calculus", question: "L'Hôpital's Rule is used to evaluate limits that result in ___ forms.", choices: ["Linear", "Indeterminate (0/0)", "Negative", "Square"], answer: 1 },
    { id: "G12-MA-14", grade: 12, subject: "Math", topic: "Calculus", question: "The derivative of position with respect to time is ___.", choices: ["Acceleration", "Velocity", "Jerk", "Force"], answer: 1 },
    { id: "G12-MA-15", grade: 12, subject: "Math", topic: "Calculus", question: "The derivative of velocity with respect to time is ___.", choices: ["Position", "Acceleration", "Speed", "Momentum"], answer: 1 },
    { id: "G12-MA-16", grade: 12, subject: "Math", topic: "Calculus", question: "The slope of a 'Tangent Line' to a curve at a point is the ___ at that point.", choices: ["Limit", "Derivative", "Integral", "Y-intercept"], answer: 1 },
    { id: "G12-MA-17", grade: 12, subject: "Math", topic: "Calculus", question: "What is the derivative of x^2 + 3x?", choices: ["2x", "2x + 3", "x + 3", "3x^2"], answer: 1 },
    { id: "G12-MA-18", grade: 12, subject: "Math", topic: "Calculus", question: "Mean Value Theorem: There is a point where the instantaneous rate equals the ___ rate.", choices: ["Maximum", "Average", "Minimum", "Zero"], answer: 1 },
    { id: "G12-MA-19", grade: 12, subject: "Math", topic: "Calculus", question: "The derivative of ln(x) is ___.", choices: ["e^x", "1/x", "x", "ln(x)"], answer: 1 },
    { id: "G12-MA-20", grade: 12, subject: "Math", topic: "Calculus", question: "Implicit differentiation is used when y cannot be easily ___.", choices: ["Added", "Isolated/Solved for", "Squared", "Graphed"], answer: 1 },
    { id: "G12-MA-21", grade: 12, subject: "Math", topic: "Calculus", question: "The derivative of tan(x) is ___.", choices: ["sec^2(x)", "sec(x)tan(x)", "cos^2(x)", "1"], answer: 0 },
    { id: "G12-MA-22", grade: 12, subject: "Math", topic: "Calculus", question: "If a function is differentiable at a point, it must also be ___ at that point.", choices: ["Positive", "Continuous", "Linear", "Increasing"], answer: 1 },
    { id: "G12-MA-23", grade: 12, subject: "Math", topic: "Calculus", question: "Optimization problems involve finding the ___ of a function.", choices: ["Average", "Maximum or Minimum", "Roots", "Limits"], answer: 1 },
    { id: "G12-MA-24", grade: 12, subject: "Math", topic: "Calculus", question: "The 'Quotient Rule' is used for functions being ___.", choices: ["Multiplied", "Divided", "Subtracted", "Inversed"], answer: 1 },
    { id: "G12-MA-25", grade: 12, subject: "Math", topic: "Calculus", question: "Related Rates problems involve derivatives with respect to ___.", choices: ["Distance", "Time (t)", "Area", "Gravity"], answer: 1 },

    // --- TOPIC 2: INTEGRALS & AREA (25 Questions) ---
    { id: "G12-MA-26", grade: 12, subject: "Math", topic: "Calculus", question: "An 'Antiderivative' is also known as an ___.", choices: ["Limit", "Integral", "Derivative", "Power"], answer: 1 },
    { id: "G12-MA-27", grade: 12, subject: "Math", topic: "Calculus", question: "A 'Definite Integral' calculates the ___ under a curve.", choices: ["Slope", "Net Area", "Length", "Curvature"], answer: 1 },
    { id: "G12-MA-28", grade: 12, subject: "Math", topic: "Calculus", question: "The 'Fundamental Theorem of Calculus' links derivatives and ___.", choices: ["Limits", "Integrals", "Algebra", "Geometry"], answer: 1 },
    { id: "G12-MA-29", grade: 12, subject: "Math", topic: "Calculus", question: "When finding an indefinite integral, we must add the constant ___.", choices: ["x", "C", "e", "k"], answer: 1 },
    { id: "G12-MA-30", grade: 12, subject: "Math", topic: "Calculus", question: "The integral of 1/x dx is ___.", choices: ["x^0", "ln|x| + C", "e^x", "-1/x^2"], answer: 1 },
    { id: "G12-MA-31", grade: 12, subject: "Math", topic: "Calculus", question: "The integral of e^x dx is ___.", choices: ["xe^x", "e^x + C", "ln(x)", "1"], answer: 1 },
    { id: "G12-MA-32", grade: 12, subject: "Math", topic: "Calculus", question: "The 'Disk Method' is used to find the ___ of a solid of revolution.", choices: ["Area", "Volume", "Perimeter", "Surface Area"], answer: 1 },
    { id: "G12-MA-33", grade: 12, subject: "Math", topic: "Calculus", question: "U-Substitution is a technique used to reverse the ___.", choices: ["Product Rule", "Chain Rule", "Power Rule", "Quotient Rule"], answer: 1 },
    { id: "G12-MA-34", grade: 12, subject: "Math", topic: "Calculus", question: "Riemann Sums approximate area using ___.", choices: ["Circles", "Rectangles", "Triangles", "Lines"], answer: 1 },
    { id: "G12-MA-35", grade: 12, subject: "Math", topic: "Calculus", question: "The integral of cos(x) dx is ___.", choices: ["sin(x) + C", "-sin(x) + C", "tan(x)", "sec(x)"], answer: 0 },
    { id: "G12-MA-36", grade: 12, subject: "Math", topic: "Calculus", question: "The integral of sin(x) dx is ___.", choices: ["cos(x) + C", "-cos(x) + C", "csc(x)", "0"], answer: 1 },
    { id: "G12-MA-37", grade: 12, subject: "Math", topic: "Calculus", question: "Area between two curves is found by integrating (Top function - ___).", choices: ["Left function", "Bottom function", "X-axis", "Y-axis"], answer: 1 },
    { id: "G12-MA-38", grade: 12, subject: "Math", topic: "Calculus", question: "Integration by Parts is based on the ___.", choices: ["Chain Rule", "Product Rule", "Quotient Rule", "Log Rule"], answer: 1 },
    { id: "G12-MA-39", grade: 12, subject: "Math", topic: "Calculus", question: "An 'Improper Integral' has at least one limit of integration that is ___.", choices: ["Zero", "Infinite", "Negative", "Imaginary"], answer: 1 },
    { id: "G12-MA-40", grade: 12, subject: "Math", topic: "Calculus", question: "The integral of a velocity function gives the change in ___.", choices: ["Acceleration", "Position (Displacement)", "Time", "Force"], answer: 1 },
    { id: "G12-MA-41", grade: 12, subject: "Math", topic: "Calculus", question: "Average Value of a function f(x) on [a,b] is (1/(b-a)) times the ___.", choices: ["Derivative", "Integral", "Limit", "Slope"], answer: 1 },
    { id: "G12-MA-42", grade: 12, subject: "Math", topic: "Calculus", question: "Integration is the process of ___.", choices: ["Differentiating", "Accumulating", "Rounding", "Simplifying"], answer: 1 },
    { id: "G12-MA-43", grade: 12, subject: "Math", topic: "Calculus", question: "What is the integral of 2x dx?", choices: ["x^2 + C", "2", "x + C", "2x^2"], answer: 0 },
    { id: "G12-MA-44", grade: 12, subject: "Math", topic: "Calculus", question: "The 'Washer Method' is a variation of the Disk Method with a ___.", choices: ["Solid core", "Hole/Gap", "Square base", "Triangle"], answer: 1 },
    { id: "G12-MA-45", grade: 12, subject: "Math", topic: "Calculus", question: "A differential equation relates a function to its ___.", choices: ["Inverse", "Derivatives", "Integrals", "Limits"], answer: 1 },
    { id: "G12-MA-46", grade: 12, subject: "Math", topic: "Calculus", question: "The integral of sec^2(x) dx is ___.", choices: ["tan(x) + C", "sec(x) + C", "sin(x)", "cos(x)"], answer: 0 },
    { id: "G12-MA-47", grade: 12, subject: "Math", topic: "Calculus", question: "Fundamental Theorem Part 1 states the derivative of an integral is the ___.", choices: ["Original function", "Second derivative", "Area", "Zero"], answer: 0 },
    { id: "G12-MA-48", grade: 12, subject: "Math", topic: "Calculus", question: "The variable 't' in physics calculus usually stands for ___.", choices: ["Total", "Time", "Temperature", "Tangent"], answer: 1 },
    { id: "G12-MA-49", grade: 12, subject: "Math", topic: "Calculus", question: "If the velocity is positive and acceleration is negative, the object is ___.", choices: ["Speeding up", "Slowing down", "Stopped", "Constant"], answer: 1 },
    { id: "G12-MA-50", grade: 12, subject: "Math", topic: "Calculus", question: "The 'Shell Method' finds volume by integrating along ___ cylinders.", choices: ["Horizontal", "Parallel", "Vertical/Cylindrical shells", "Spherical"], answer: 2 },

    // --- TOPIC 3: STATISTICS & PROBABILITY (25 Questions) ---
    { id: "G12-MA-51", grade: 12, subject: "Math", topic: "Stats", question: "The 'Mean' is the ___ of a data set.", choices: ["Middle", "Most frequent", "Average", "Range"], answer: 2 },
    { id: "G12-MA-52", grade: 12, subject: "Math", topic: "Stats", question: "The 'Median' is the ___ value in an ordered data set.", choices: ["Highest", "Middle", "Lowest", "Average"], answer: 1 },
    { id: "G12-MA-53", grade: 12, subject: "Math", topic: "Stats", question: "The 'Mode' is the value that occurs ___.", choices: ["Least", "Most often", "In the middle", "Never"], answer: 1 },
    { id: "G12-MA-54", grade: 12, subject: "Math", topic: "Stats", question: "Standard Deviation measures the ___ of data from the mean.", choices: ["Sum", "Spread/Dispersion", "Accuracy", "Height"], answer: 1 },
    { id: "G12-MA-55", grade: 12, subject: "Math", topic: "Stats", question: "Variance is the square of the ___.", choices: ["Mean", "Standard Deviation", "Range", "Median"], answer: 1 },
    { id: "G12-MA-56", grade: 12, subject: "Math", topic: "Stats", question: "A 'Z-score' tells you how many ___ a value is from the mean.", choices: ["Points", "Standard Deviations", "Percentages", "Units"], answer: 1 },
    { id: "G12-MA-57", grade: 12, subject: "Math", topic: "Stats", question: "A 'Normal Distribution' is shaped like a ___.", choices: ["Line", "Square", "Bell", "Circle"], answer: 2 },
    { id: "G12-MA-58", grade: 12, subject: "Math", topic: "Stats", question: "The 'Central Limit Theorem' says that sample means follow a ___ distribution.", choices: ["Uniform", "Normal", "Biased", "Random"], answer: 1 },
    { id: "G12-MA-59", grade: 12, subject: "Math", topic: "Stats", question: "A 'Null Hypothesis' (H0) usually assumes ___.", choices: ["A big change", "No effect or no difference", "A mistake", "100% certainty"], answer: 1 },
    { id: "G12-MA-60", grade: 12, subject: "Math", topic: "Stats", question: "The 'p-value' helps determine if results are statistically ___.", choices: ["Large", "Significant", "Normal", "Random"], answer: 1 },
    { id: "G12-MA-61", grade: 12, subject: "Math", topic: "Stats", question: "Correlation (r) values range from ___.", choices: ["0 to 1", "-1 to 1", "-10 to 10", "1 to 100"], answer: 1 },
    { id: "G12-MA-62", grade: 12, subject: "Math", topic: "Stats", question: "If r = 0.9, there is a strong ___ correlation.", choices: ["Negative", "Positive", "Neutral", "Zero"], answer: 1 },
    { id: "G12-MA-63", grade: 12, subject: "Math", topic: "Stats", question: "Correlation does not equal ___.", choices: ["Statistics", "Causation", "Probability", "Math"], answer: 1 },
    { id: "G12-MA-64", grade: 12, subject: "Math", topic: "Stats", question: "A 'Type I Error' is a 'False ___'.", choices: ["Negative", "Positive", "Mean", "Standard"], answer: 1 },
    { id: "G12-MA-65", grade: 12, subject: "Math", topic: "Stats", question: "A 'Type II Error' is a 'False ___'.", choices: ["Positive", "Negative", "Z-score", "Range"], answer: 1 },
    { id: "G12-MA-66", grade: 12, subject: "Math", topic: "Stats", question: "Qualitative data describes ___.", choices: ["Numbers", "Categories/Qualities", "Weights", "Heights"], answer: 1 },
    { id: "G12-MA-67", grade: 12, subject: "Math", topic: "Stats", question: "Quantitative data describes ___.", choices: ["Colors", "Numbers/Quantities", "Names", "Opinions"], answer: 1 },
    { id: "G12-MA-68", grade: 12, subject: "Math", topic: "Stats", question: "A 'Box Plot' shows the ___ of a data set.", choices: ["Mean", "Five-number summary (Min, Q1, Med, Q3, Max)", "Standard Deviation", "Mode"], answer: 1 },
    { id: "G12-MA-69", grade: 12, subject: "Math", topic: "Stats", question: "An 'Outlier' is a data point that is ___.", choices: ["Near the mean", "Significantly far from other data", "In the middle", "Negative"], answer: 1 },
    { id: "G12-MA-70", grade: 12, subject: "Math", topic: "Stats", question: "The 'Range' is the difference between the ___.", choices: ["Mean and Median", "Maximum and Minimum", "Q3 and Q1", "First and Last"], answer: 1 },
    { id: "G12-MA-71", grade: 12, subject: "Math", topic: "Stats", question: "In a 'Skewed Right' distribution, the tail is on the ___.", choices: ["Left", "Right", "Middle", "Both sides"], answer: 1 },
    { id: "G12-MA-72", grade: 12, subject: "Math", topic: "Stats", question: "A 'Random Sample' ensures every member has a(n) ___ chance of selection.", choices: ["Zero", "Equal", "High", "Limited"], answer: 1 },
    { id: "G12-MA-73", grade: 12, subject: "Math", topic: "Stats", question: "A 'Confidence Interval' provides a range of ___ values.", choices: ["Exact", "Plausible", "Wrong", "Imaginary"], answer: 1 },
    { id: "G12-MA-74", grade: 12, subject: "Math", topic: "Stats", question: "The Interquartile Range (IQR) is Q3 minus ___.", choices: ["Q2", "Q1", "Min", "Mean"], answer: 1 },
    { id: "G12-MA-75", grade: 12, subject: "Math", topic: "Stats", question: "A scatter plot is used to observe the ___ between two variables.", choices: ["Sum", "Relationship", "Difference", "Volume"], answer: 1 },

    // --- TOPIC 4: VECTORS, SERIES & ADVANCED ALGEBRA (25 Questions) ---
    { id: "G12-MA-76", grade: 12, subject: "Math", topic: "Vectors", question: "A vector has both magnitude and ___.", choices: ["Weight", "Direction", "Color", "Volume"], answer: 1 },
    { id: "G12-MA-77", grade: 12, subject: "Math", topic: "Vectors", question: "The 'Dot Product' of two perpendicular vectors is ___.", choices: ["1", "0", "-1", "Infinite"], answer: 1 },
    { id: "G12-MA-78", grade: 12, subject: "Math", topic: "Series", question: "A 'Geometric Series' converges if its common ratio |r| is ___.", choices: ["> 1", "< 1", "= 1", "= 0"], answer: 1 },
    { id: "G12-MA-79", grade: 12, subject: "Math", topic: "Series", question: "A 'Taylor Series' approximates a function using ___.", choices: ["Circles", "Polynomials", "Lines", "Sine waves"], answer: 1 },
    { id: "G12-MA-80", grade: 12, subject: "Math", topic: "Advanced", question: "The 'Natural Logarithm' (ln) is log base ___.", choices: ["10", "e", "2", "pi"], answer: 1 },
    { id: "G12-MA-81", grade: 12, subject: "Math", topic: "Advanced", question: "The 'Identity Matrix' (I) acts like the number ___ in matrix multiplication.", choices: ["0", "1", "-1", "10"], answer: 1 },
    { id: "G12-MA-82", grade: 12, subject: "Math", topic: "Calculus", question: "The derivative of the integral of f(x) from a to x is ___.", choices: ["F(x)", "f(x)", "f'(x)", "0"], answer: 1 },
    { id: "G12-MA-83", grade: 12, subject: "Math", topic: "Stats", question: "Independent events: P(A and B) = P(A) ___ P(B).", choices: ["+", "-", "*", "/"], answer: 2 },
    { id: "G12-MA-84", grade: 12, subject: "Math", topic: "Stats", question: "Mutually exclusive events: P(A or B) = P(A) ___ P(B).", choices: ["+", "-", "*", "/"], answer: 0 },
    { id: "G12-MA-85", grade: 12, subject: "Math", topic: "Vectors", question: "The magnitude of vector <3, 4> is ___.", choices: ["5", "7", "12", "25"], answer: 0 },
    { id: "G12-MA-86", grade: 12, subject: "Math", topic: "Calculus", question: "A 'Maclaurin Series' is a Taylor Series centered at ___.", choices: ["1", "0", "e", "pi"], answer: 1 },
    { id: "G12-MA-87", grade: 12, subject: "Math", topic: "Advanced", question: "The inverse of matrix A is denoted as ___.", choices: ["A^2", "A^-1", "1/A", "-A"], answer: 1 },
    { id: "G12-MA-88", grade: 12, subject: "Math", topic: "Calculus", question: "The integral of tan(x) is ___.", choices: ["sec^2(x)", "-ln|cos(x)| + C", "sin(x)", "1"], answer: 1 },
    { id: "G12-MA-89", grade: 12, subject: "Math", topic: "Stats", question: "The sum of probabilities in a sample space must be ___.", choices: ["0", "1", "100", "Infinite"], answer: 1 },
    { id: "G12-MA-90", grade: 12, subject: "Math", topic: "Stats", question: "A 'Binomial Distribution' has only ___ possible outcomes per trial.", choices: ["1", "2", "3", "Infinite"], answer: 1 },
    { id: "G12-MA-91", grade: 12, subject: "Math", topic: "Calculus", question: "If v(t) = 3t^2, what is the acceleration a(t)?", choices: ["t^3", "6t", "3t", "6"], answer: 1 },
    { id: "G12-MA-92", grade: 12, subject: "Math", topic: "Calculus", question: "What is the limit of 1/x as x approaches infinity?", choices: ["1", "Infinity", "0", "Undefined"], answer: 2 },
    { id: "G12-MA-93", grade: 12, subject: "Math", topic: "Series", question: "The Harmonic Series (1 + 1/2 + 1/3 + ...) ___.", choices: ["Converges", "Diverges", "Equals 1", "Equals 2"], answer: 1 },
    { id: "G12-MA-94", grade: 12, subject: "Math", topic: "Vectors", question: "The 'Cross Product' of two vectors results in a ___.", choices: ["Scalar", "Vector", "Matrix", "Constant"], answer: 1 },
    { id: "G12-MA-95", grade: 12, subject: "Math", topic: "Stats", question: "A 'Self-Selected' sample is usually ___.", choices: ["Random", "Biased", "Representative", "Accurate"], answer: 1 },
    { id: "G12-MA-96", grade: 12, subject: "Math", topic: "Advanced", question: "Partial Fraction Decomposition is used to simplify ___ before integration.", choices: ["Polynomials", "Rational functions", "Logs", "Trig"], answer: 1 },
    { id: "G12-MA-97", grade: 12, subject: "Math", topic: "Calculus", question: "What is the derivative of x^e?", choices: ["e*x^(e-1)", "e^x", "ln(x)", "x^e"], answer: 0 },
    { id: "G12-MA-98", grade: 12, subject: "Math", topic: "Calculus", question: "The 'Disk Method' formula involves the integral of ___.", choices: ["r^2", "pi * r^2", "2 * pi * r", "4/3 * pi * r^3"], answer: 1 },
    { id: "G12-MA-99", grade: 12, subject: "Math", topic: "Stats", question: "A 'Frequency Table' shows how ___ each value occurs.", choices: ["Rarely", "Often", "Accurately", "Fast"], answer: 1 },
    { id: "G12-MA-100", grade: 12, subject: "Math", topic: "Advanced", question: "The 'Determinant' of a 2x2 matrix [[a,b],[c,d]] is ___.", choices: ["a+d", "ad - bc", "ab - cd", "ac - bd"], answer: 1 }
];

module.exports = G12_MATH_COMPLETE;
