const G12_ELA_COMPLETE = [
    // --- TOPIC 1: BRITISH & WORLD LITERATURE (25 Questions) ---
    { id: "G12-ELA-01", grade: 12, subject: "ELA", topic: "British Lit", question: "Who is the author of 'Beowulf'?", choices: ["Geoffrey Chaucer", "Anonymous", "William Shakespeare", "John Milton"], answer: 1 },
    { id: "G12-ELA-02", grade: 12, subject: "ELA", topic: "British Lit", question: "'The Canterbury Tales' was written by ___.", choices: ["William Wordsworth", "Geoffrey Chaucer", "Jane Austen", "Charles Dickens"], answer: 1 },
    { id: "G12-ELA-03", grade: 12, subject: "ELA", topic: "British Lit", question: "In Shakespeare's 'Hamlet', the protagonist is the Prince of ___.", choices: ["England", "Denmark", "Scotland", "Norway"], answer: 1 },
    { id: "G12-ELA-04", grade: 12, subject: "ELA", topic: "British Lit", question: "John Milton's 'Paradise Lost' is an epic poem about ___.", choices: ["The French Revolution", "The Fall of Man", "The Trojan War", "King Arthur"], answer: 1 },
    { id: "G12-ELA-05", grade: 12, subject: "ELA", topic: "British Lit", question: "Which 19th-century author wrote 'Pride and Prejudice'?", choices: ["Mary Shelley", "Jane Austen", "Charlotte Brontë", "George Eliot"], answer: 1 },
    { id: "G12-ELA-06", grade: 12, subject: "ELA", topic: "British Lit", question: "Mary Shelley's 'Frankenstein' is a classic of ___ literature.", choices: ["Realist", "Gothic/Romantic", "Modernist", "Post-colonial"], answer: 1 },
    { id: "G12-ELA-07", grade: 12, subject: "ELA", topic: "British Lit", question: "Charles Dickens often wrote about the social ills of ___ England.", choices: ["Medieval", "Victorian", "Elizabethan", "Technological"], answer: 1 },
    { id: "G12-ELA-08", grade: 12, subject: "ELA", topic: "British Lit", question: "William Wordsworth and S.T. Coleridge were leaders of the ___ movement.", choices: ["Enlightenment", "Romantic", "Modernist", "Classicist"], answer: 1 },
    { id: "G12-ELA-09", grade: 12, subject: "ELA", topic: "British Lit", question: "'1984' and 'Animal Farm' were written by ___.", choices: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"], answer: 1 },
    { id: "G12-ELA-10", grade: 12, subject: "ELA", topic: "World Lit", question: "Samuel Beckett's 'Waiting for Godot' is a cornerstone of the Theatre of the ___.", choices: ["Real", "Absurd", "Future", "Past"], answer: 1 },
    { id: "G12-ELA-11", grade: 12, subject: "ELA", topic: "World Lit", question: "Who wrote 'The Metamorphosis', where a man turns into an insect?", choices: ["Albert Camus", "Franz Kafka", "Leo Tolstoy", "James Joyce"], answer: 1 },
    { id: "G12-ELA-12", grade: 12, subject: "ELA", topic: "World Lit", question: "Chinua Achebe's 'Things Fall Apart' depicts the impact of ___ in Nigeria.", choices: ["Farming", "Colonialism", "Technology", "Migration"], answer: 1 },
    { id: "G12-ELA-13", grade: 12, subject: "ELA", topic: "British Lit", question: "The 'Anglo-Saxon' period is also known as the ___ period.", choices: ["Middle English", "Old English", "Modern English", "Latin"], answer: 1 },
    { id: "G12-ELA-14", grade: 12, subject: "ELA", topic: "British Lit", question: "Shakespeare wrote his plays during the ___ era.", choices: ["Victorian", "Elizabethan/Jacobean", "Edwardian", "Romantic"], answer: 1 },
    { id: "G12-ELA-15", grade: 12, subject: "ELA", topic: "British Lit", question: "In 'Macbeth', the protagonist is driven by fatal ___.", choices: ["Love", "Ambition", "Greed", "Laziness"], answer: 1 },
    { id: "G12-ELA-16", grade: 12, subject: "ELA", topic: "British Lit", question: "T.S. Eliot's 'The Waste Land' is a major work of ___ poetry.", choices: ["Romantic", "Modernist", "Medieval", "Victorian"], answer: 1 },
    { id: "G12-ELA-17", grade: 12, subject: "ELA", topic: "World Lit", question: "Gabriel García Márquez is famous for the genre of ___.", choices: ["Realism", "Magical Realism", "Science Fiction", "Biography"], answer: 1 },
    { id: "G12-ELA-18", grade: 12, subject: "ELA", topic: "British Lit", question: "Virginia Woolf is known for her use of ___ of consciousness.", choices: ["River", "Stream", "Flow", "Lake"], answer: 1 },
    { id: "G12-ELA-19", grade: 12, subject: "ELA", topic: "British Lit", question: "Lord Byron and Percy Shelley were part of the ___ generation of Romantics.", choices: ["First", "Second", "Third", "Final"], answer: 1 },
    { id: "G12-ELA-20", grade: 12, subject: "ELA", topic: "British Lit", question: "James Joyce's 'Ulysses' parallels the ancient epic ___.", choices: ["The Iliad", "The Odyssey", "The Aeneid", "Beowulf"], answer: 1 },
    { id: "G12-ELA-21", grade: 12, subject: "ELA", topic: "British Lit", question: "A 'Sonnet' consists of ___ lines.", choices: ["10", "12", "14", "16"], answer: 2 },
    { id: "G12-ELA-22", grade: 12, subject: "ELA", topic: "British Lit", question: "The 'Renaissance' means ___.", choices: ["Discovery", "Rebirth", "Ending", "Conflict"], answer: 1 },
    { id: "G12-ELA-23", grade: 12, subject: "ELA", topic: "British Lit", question: "A 'Parody' is a work that ___ another work for humor.", choices: ["Praises", "Mimics/Imitates", "Deletes", "Ignores"], answer: 1 },
    { id: "G12-ELA-24", grade: 12, subject: "ELA", topic: "British Lit", question: "'Heart of Darkness' was written by ___.", choices: ["Joseph Conrad", "E.M. Forster", "Graham Greene", "D.H. Lawrence"], answer: 0 },
    { id: "G12-ELA-25", grade: 12, subject: "ELA", topic: "World Lit", question: "Dante Alighieri's 'Divine Comedy' describes a journey through ___.", choices: ["Europe", "Hell, Purgatory, and Heaven", "The Americas", "The ocean"], answer: 1 },

    // --- TOPIC 2: LITERARY CRITICISM & THEORY (25 Questions) ---
    { id: "G12-ELA-26", grade: 12, subject: "ELA", topic: "Theory", question: "___ criticism focuses on the role of women in literature.", choices: ["Marxist", "Feminist", "New Criticism", "Formalist"], answer: 1 },
    { id: "G12-ELA-27", grade: 12, subject: "ELA", topic: "Theory", question: "___ criticism focuses on power struggles and class conflict.", choices: ["Psychoanalytic", "Marxist", "Historical", "Biographical"], answer: 1 },
    { id: "G12-ELA-28", grade: 12, subject: "ELA", topic: "Theory", question: "___ criticism focuses on the author's psychological state.", choices: ["Structuralist", "Psychoanalytic", "Reader-Response", "Ecological"], answer: 1 },
    { id: "G12-ELA-29", grade: 12, subject: "ELA", topic: "Theory", question: "___ criticism focuses on the reader's personal reaction to the text.", choices: ["Formalist", "Reader-Response", "New Historicism", "Deconstruction"], answer: 1 },
    { id: "G12-ELA-30", grade: 12, subject: "ELA", topic: "Theory", question: "___ involves looking solely at the text itself, ignoring outside context.", choices: ["New Historicism", "Formalism/New Criticism", "Biographical criticism", "Cultural studies"], answer: 1 },
    { id: "G12-ELA-31", grade: 12, subject: "ELA", topic: "Analysis", question: "An 'Archetype' is a universal ___ that recurs in literature.", choices: ["Mistake", "Symbol, character, or pattern", "Spelling", "Punctuation"], answer: 1 },
    { id: "G12-ELA-32", grade: 12, subject: "ELA", topic: "Analysis", question: "Deconstruction theory suggests that text has ___ meanings.", choices: ["One single", "Multiple, often contradictory", "No", "Hidden digital"], answer: 1 },
    { id: "G12-ELA-33", grade: 12, subject: "ELA", topic: "Analysis", question: "A 'Trope' is a commonly recurring ___.", choices: ["Word", "Literary device or motif", "Line", "Page"], answer: 1 },
    { id: "G12-ELA-34", grade: 12, subject: "ELA", topic: "Analysis", question: "Intertextuality is the relationship between ___.", choices: ["Authors", "Two or more texts", "Chapters", "Words and images"], answer: 1 },
    { id: "G12-ELA-35", grade: 12, subject: "ELA", topic: "Analysis", question: "A 'Canonical' work is one that is ___.", choices: ["Forbidden", "Considered of highest importance/standard", "New", "Short"], answer: 1 },
    { id: "G12-ELA-36", grade: 12, subject: "ELA", topic: "Analysis", question: "Catharsis is the emotional ___ experienced by the audience of a tragedy.", choices: ["Boredom", "Release/Purging", "Confusion", "Anger"], answer: 1 },
    { id: "G12-ELA-37", grade: 12, subject: "ELA", topic: "Analysis", question: "Harmartia is the Greek term for a hero's ___.", choices: ["Weapon", "Tragic flaw", "Home", "Friend"], answer: 1 },
    { id: "G12-ELA-38", grade: 12, subject: "ELA", topic: "Analysis", question: "Hubris is excessive ___.", choices: ["Fear", "Pride", "Hunger", "Wealth"], answer: 1 },
    { id: "G12-ELA-39", grade: 12, subject: "ELA", topic: "Analysis", question: "In a tragedy, the protagonist is usually of ___ birth.", choices: ["Low", "Noble", "Middle", "Unknown"], answer: 1 },
    { id: "G12-ELA-40", grade: 12, subject: "ELA", topic: "Analysis", question: "An 'Epiphany' is a moment of sudden ___.", choices: ["Fear", "Insight/Realization", "Death", "Sleep"], answer: 1 },
    { id: "G12-ELA-41", grade: 12, subject: "ELA", topic: "Analysis", question: "The 'Denouement' is the final ___ of the plot.", choices: ["Conflict", "Resolution/Unraveling", "Climax", "Introduction"], answer: 1 },
    { id: "G12-ELA-42", grade: 12, subject: "ELA", topic: "Analysis", question: "Diction refers to the author's ___.", choices: ["Grammar", "Word choice", "Handwriting", "Speed"], answer: 1 },
    { id: "G12-ELA-43", grade: 12, subject: "ELA", topic: "Analysis", question: "Syntax refers to the ___ of words in a sentence.", choices: ["Meaning", "Arrangement/Structure", "Spelling", "Sound"], answer: 1 },
    { id: "G12-ELA-44", grade: 12, subject: "ELA", topic: "Analysis", question: "Tone is the author's ___.", choices: ["Volume", "Attitude", "Vocabulary", "Success"], answer: 1 },
    { id: "G12-ELA-45", grade: 12, subject: "ELA", topic: "Analysis", question: "Mood is the ___ created for the reader.", choices: ["Opinion", "Atmosphere/Feeling", "Conflict", "Plot"], answer: 1 },
    { id: "G12-ELA-46", grade: 12, subject: "ELA", topic: "Analysis", question: "A 'Metaphor' compares two things ___ using 'like' or 'as'.", choices: ["With", "Without", "Rarely", "Always"], answer: 1 },
    { id: "G12-ELA-47", grade: 12, subject: "ELA", topic: "Analysis", question: "An 'Extened Metaphor' spans ___.", choices: ["One line", "A long passage or whole work", "Two words", "None"], answer: 1 },
    { id: "G12-ELA-48", grade: 12, subject: "ELA", topic: "Analysis", question: "Personification gives human traits to ___.", choices: ["Humans", "Non-human things", "Heroes", "Authors"], answer: 1 },
    { id: "G12-ELA-49", grade: 12, subject: "ELA", topic: "Analysis", question: "Juxtaposition is placing two things together to emphasize ___.", choices: ["Harmony", "Contrast/Differences", "Similarity", "Order"], answer: 1 },
    { id: "G12-ELA-50", grade: 12, subject: "ELA", topic: "Analysis", question: "The 'Anti-hero' lacks traditional ___ qualities.", choices: ["Physical", "Heroic (bravery, idealism)", "Negative", "Human"], answer: 1 },

    // --- TOPIC 3: ADVANCED COMPOSITION & RHETORIC (25 Questions) ---
    { id: "G12-ELA-51", grade: 12, subject: "ELA", topic: "Composition", question: "A 'Synthesis' essay requires you to ___ multiple sources.", choices: ["Ignore", "Combine and integrate", "Copy", "Reject"], answer: 1 },
    { id: "G12-ELA-52", grade: 12, subject: "ELA", topic: "Composition", question: "The 'Thesis Statement' should be ___.", choices: ["Broad and vague", "Specific and arguable", "A question", "A fact"], answer: 1 },
    { id: "G12-ELA-53", grade: 12, subject: "ELA", topic: "Composition", question: "MLA format requires ___ citations.", choices: ["Footnote", "In-text/Parenthetical", "Endnote", "No"], answer: 1 },
    { id: "G12-ELA-54", grade: 12, subject: "ELA", topic: "Composition", question: "Plagiarism is using another's ideas or words ___.", choices: ["With credit", "Without proper credit", "In a quote", "In a book"], answer: 1 },
    { id: "G12-ELA-55", grade: 12, subject: "ELA", topic: "Rhetoric", question: "Ethos is an appeal to ___.", choices: ["Logic", "Credibility/Ethics", "Emotion", "Time"], answer: 1 },
    { id: "G12-ELA-56", grade: 12, subject: "ELA", topic: "Rhetoric", question: "Pathos is an appeal to ___.", choices: ["Reason", "Emotion", "Character", "Price"], answer: 1 },
    { id: "G12-ELA-57", grade: 12, subject: "ELA", topic: "Rhetoric", question: "Logos is an appeal to ___.", choices: ["Feelings", "Logic/Reason", "Ethics", "Sound"], answer: 1 },
    { id: "G12-ELA-58", grade: 12, subject: "ELA", topic: "Rhetoric", question: "Kairos is the ___ of an argument.", choices: ["Volume", "Opportune timing/context", "Length", "Complexity"], answer: 1 },
    { id: "G12-ELA-59", grade: 12, subject: "ELA", topic: "Rhetoric", question: "A 'Rhetorical Analysis' examines ___ a text communicates its message.", choices: ["What", "How", "Whenever", "Who"], answer: 1 },
    { id: "G12-ELA-60", grade: 12, subject: "ELA", topic: "Composition", question: "An 'Annotated Bibliography' includes a summary and ___ of each source.", choices: ["Title", "Evaluation/Critique", "Photo", "Price"], answer: 1 },
    { id: "G12-ELA-61", grade: 12, subject: "ELA", topic: "Composition", question: "A 'Topic Sentence' identifies the main idea of a ___.", choices: ["Book", "Paragraph", "Title", "Conclusion"], answer: 1 },
    { id: "G12-ELA-62", grade: 12, subject: "ELA", topic: "Composition", question: "Which is a 'Primary Source'?", choices: ["A biography", "An original diary", "A textbook", "An encyclopedia"], answer: 1 },
    { id: "G12-ELA-63", grade: 12, subject: "ELA", topic: "Composition", question: "Which is a 'Secondary Source'?", choices: ["The Constitution", "A scholar's analysis of the Constitution", "An original photo", "An interview"], answer: 1 },
    { id: "G12-ELA-64", grade: 12, subject: "ELA", topic: "Grammar", question: "Parallelism means using similar ___ for similar ideas.", choices: ["Spelling", "Grammatical structures", "Colors", "Fonts"], answer: 1 },
    { id: "G12-ELA-65", grade: 12, subject: "ELA", topic: "Grammar", question: "Avoid 'Passive Voice' to make your writing more ___.", choices: ["Wordy", "Direct and active", "Boring", "Historical"], answer: 1 },
    { id: "G12-ELA-66", grade: 12, subject: "ELA", topic: "Rhetoric", question: "A 'Fallacy' is an error in ___.", choices: ["Spelling", "Reasoning/Logic", "Diction", "Syntax"], answer: 1 },
    { id: "G12-ELA-67", grade: 12, subject: "ELA", topic: "Rhetoric", question: "The 'Ad Hominem' fallacy attacks the ___.", choices: ["Argument", "Person", "Fact", "School"], answer: 1 },
    { id: "G12-ELA-68", grade: 12, subject: "ELA", topic: "Rhetoric", question: "The 'Straw Man' fallacy ___ an opponent's argument to make it easier to attack.", choices: ["Supports", "Misrepresents/Exaggerates", "Ignores", "Quotes"], answer: 1 },
    { id: "G12-ELA-69", grade: 12, subject: "ELA", topic: "Rhetoric", question: "___ is the use of humor or irony to expose and criticize stupidity.", choices: ["Tragedy", "Satire", "Epic", "Haiku"], answer: 1 },
    { id: "G12-ELA-70", grade: 12, subject: "ELA", topic: "Composition", question: "A 'Counterargument' is an argument that ___ your thesis.", choices: ["Supports", "Opposes", "Explains", "Repeats"], answer: 1 },
    { id: "G12-ELA-71", grade: 12, subject: "ELA", topic: "Composition", question: "A 'Rebuttal' is your response to a ___.", choices: ["Fact", "Counterargument", "Friend", "Title"], answer: 1 },
    { id: "G12-ELA-72", grade: 12, subject: "ELA", topic: "Grammar", question: "A 'Comma Splice' is a(n) ___ that uses only a comma to join two sentences.", choices: ["Success", "Error", "Option", "Requirement"], answer: 1 },
    { id: "G12-ELA-73", grade: 12, subject: "ELA", topic: "Grammar", question: "Dangling modifiers are often found at the ___ of a sentence.", choices: ["End", "Beginning", "Middle", "None"], answer: 1 },
    { id: "G12-ELA-74", grade: 12, subject: "ELA", topic: "Composition", question: "An 'Abstract' is a short ___ of a research paper.", choices: ["Poem", "Summary", "Critique", "Conclusion"], answer: 1 },
    { id: "G12-ELA-75", grade: 12, subject: "ELA", topic: "Composition", question: "A 'Call to Action' tells the reader what to ___.", choices: ["Read", "Go/Do", "Forget", "Buy"], answer: 1 },

    // --- TOPIC 4: PHILOSOPHY & CRITICAL THINKING (25 Questions) ---
    { id: "G12-ELA-76", grade: 12, subject: "ELA", topic: "Philosophy", question: "Existentialism focuses on individual ___, freedom, and choice.", choices: ["Conformity", "Existence", "Wealth", "History"], answer: 1 },
    { id: "G12-ELA-77", grade: 12, subject: "ELA", topic: "Philosophy", question: "Nihilism is the belief that life is ___.", choices: ["Full of joy", "Meaningless", "Pre-determined", "A loop"], answer: 1 },
    { id: "G12-ELA-78", grade: 12, subject: "ELA", topic: "Philosophy", question: "The Overman (Übermensch) is a concept by ___.", choices: ["Sartre", "Nietzsche", "Plato", "Kant"], answer: 1 },
    { id: "G12-ELA-79", grade: 12, subject: "ELA", topic: "Philosophy", question: "Determinism is the belief that all events are ___.", choices: ["Random", "Preceded by cause/Already decided", "Avoidable", "Imaginary"], answer: 1 },
    { id: "G12-ELA-80", grade: 12, subject: "ELA", topic: "Philosophy", question: "Objectivity refers to being ___.", choices: ["Biased", "Neutral/Unbiased", "Emotional", "Stubborn"], answer: 1 },
    { id: "G12-ELA-81", grade: 12, subject: "ELA", topic: "Philosophy", question: "Subjectivity refers to being influenced by personal ___.", choices: ["Facts", "Feelings/Opinions", "Math", "Laws"], answer: 1 },
    { id: "G12-ELA-82", grade: 12, subject: "ELA", topic: "Critical Thinking", question: "An 'Inference' is a conclusion based on ___.", choices: ["Guesswork", "Evidence and Reasoning", "A dream", "A lie"], answer: 1 },
    { id: "G12-ELA-83", grade: 12, subject: "ELA", topic: "Critical Thinking", question: "Cognitive Bias is a systematic error in ___.", choices: ["Spelling", "Thinking", "Writing", "Typing"], answer: 1 },
    { id: "G12-ELA-84", grade: 12, subject: "ELA", topic: "Philosophy", question: "Plato's 'Allegory of the Cave' explores the nature of ___.", choices: ["Caves", "Reality and Perception", "Shadows", "Sunlight"], answer: 1 },
    { id: "G12-ELA-85", grade: 12, subject: "ELA", topic: "Philosophy", question: "The 'Socratic Method' uses ___ to stimulate critical thinking.", choices: ["Reading", "Questioning", "Singing", "Fighting"], answer: 1 },
    { id: "G12-ELA-86", grade: 12, subject: "ELA", topic: "Philosophy", question: "Epistemology is the study of ___.", choices: ["Stars", "Knowledge", "Plants", "Money"], answer: 1 },
    { id: "G12-ELA-87", grade: 12, subject: "ELA", topic: "Philosophy", question: "Ethics is the study of ___.", choices: ["Numbers", "Morality/Right and Wrong", "Physical movement", "Climate"], answer: 1 },
    { id: "G12-ELA-88", grade: 12, subject: "ELA", topic: "Philosophy", question: "Aesthetics is the study of ___.", choices: ["Math", "Beauty and Art", "Rocks", "History"], answer: 1 },
    { id: "G12-ELA-89", grade: 12, subject: "ELA", topic: "Philosophy", question: "Stoicism emphasizes self-control and ___.", choices: ["Emotional outbursts", "Fortitude", "Greed", "Laziness"], answer: 1 },
    { id: "G12-ELA-90", grade: 12, subject: "ELA", topic: "Philosophy", question: "Hedonism is the pursuit of ___.", choices: ["Pain", "Pleasure", "Work", "Knowledge"], answer: 1 },
    { id: "G12-ELA-91", grade: 12, subject: "ELA", topic: "Critical Thinking", question: "A 'Syllogism' is a form of ___ reasoning.", choices: ["Inductive", "Deductive", "Circular", "None"], answer: 1 },
    { id: "G12-ELA-92", grade: 12, subject: "ELA", topic: "Critical Thinking", question: "Confirmation Bias is the tendency to search for information that ___ your beliefs.", choices: ["Challenges", "Confirms", "Changes", "Ignores"], answer: 1 },
    { id: "G12-ELA-93", grade: 12, subject: "ELA", topic: "Philosophy", question: "The 'Categorical Imperative' is a moral rule by ___.", choices: ["Hume", "Immanuel Kant", "Mill", "Aquinas"], answer: 1 },
    { id: "G12-ELA-94", grade: 12, subject: "ELA", topic: "Philosophy", question: "Utilitarianism seeks the 'greatest ___ for the greatest number'.", choices: ["Pain", "Happiness/Good", "Wealth", "Control"], answer: 1 },
    { id: "G12-ELA-95", grade: 12, subject: "ELA", topic: "Critical Thinking", question: "Post hoc fallacy assumes that because B followed A, A ___ B.", choices: ["Followed", "Caused", "Stopped", "Mirrored"], answer: 1 },
    { id: "G12-ELA-96", grade: 12, subject: "ELA", topic: "Critical Thinking", question: "A 'Non-sequitur' is a conclusion that ___ follow the premises.", choices: ["Does", "Does not", "Must", "Always"], answer: 1 },
    { id: "G12-ELA-97", grade: 12, subject: "ELA", topic: "Critical Thinking", question: "Begging the Question is a form of ___ reasoning.", choices: ["Linear", "Circular", "Square", "Random"], answer: 1 },
    { id: "G12-ELA-98", grade: 12, subject: "ELA", topic: "Philosophy", question: "Tabula Rasa means ___.", choices: ["Full table", "Blank slate", "Round earth", "Clean hands"], answer: 1 },
    { id: "G12-ELA-99", grade: 12, subject: "ELA", topic: "Analysis", question: "Hermeneutics is the theory of ___.", choices: ["Speaking", "Interpretation", "Writing", "Translation"], answer: 1 },
    { id: "G12-ELA-100", grade: 12, subject: "ELA", topic: "Analysis", question: "Dialectic is a method of argument for resolving ___.", choices: ["Math", "Disagreement through rational discussion", "Physics", "War"], answer: 1 }
];

module.exports = G12_ELA_COMPLETE;
