const G12_ECONOMICS_COMPLETE = [
    // --- TOPIC 1: FUNDAMENTALS & MICROECONOMICS (25 Questions) ---
    { id: "G12-EC-01", grade: 12, subject: "Economics", topic: "Fundamentals", question: "Economics is the study of how people make choices subject to ___.", choices: ["Wealth", "Scarcity", "Logic", "Laws"], answer: 1 },
    { id: "G12-EC-02", grade: 12, subject: "Economics", topic: "Fundamentals", question: "The value of the next best alternative given up is called ___.", choices: ["Profit", "Opportunity Cost", "Sunk Cost", "Fixed Cost"], answer: 1 },
    { id: "G12-EC-03", grade: 12, subject: "Economics", topic: "Fundamentals", question: "The four factors of production are Land, Labor, Capital, and ___.", choices: ["Money", "Entrepreneurship", "Technology", "Machinery"], answer: 1 },
    { id: "G12-EC-04", grade: 12, subject: "Economics", topic: "Micro", question: "The Law of Demand states that as price increases, quantity demanded ___.", choices: ["Increases", "Decreases", "Stays the same", "Doubles"], answer: 1 },
    { id: "G12-EC-05", grade: 12, subject: "Economics", topic: "Micro", question: "The Law of Supply states that as price increases, quantity supplied ___.", choices: ["Decreases", "Increases", "Stays the same", "Halves"], answer: 1 },
    { id: "G12-EC-06", grade: 12, subject: "Economics", topic: "Micro", question: "The 'Equilibrium Price' is where quantity demanded equals ___.", choices: ["Profit", "Quantity Supplied", "Cost", "Elasticity"], answer: 1 },
    { id: "G12-EC-07", grade: 12, subject: "Economics", topic: "Micro", question: "A 'Shortage' occurs when quantity demanded is ___ quantity supplied.", choices: ["Less than", "Greater than", "Equal to", "Exactly half of"], answer: 1 },
    { id: "G12-EC-08", grade: 12, subject: "Economics", topic: "Micro", question: "A 'Surplus' occurs when quantity supplied is ___ quantity demanded.", choices: ["Less than", "Greater than", "Equal to", "Zero"], answer: 1 },
    { id: "G12-EC-09", grade: 12, subject: "Economics", topic: "Micro", question: "Elasticity measures the ___ of buyers and sellers to price changes.", choices: ["Wealth", "Responsiveness", "Anger", "Income"], answer: 1 },
    { id: "G12-EC-10", grade: 12, subject: "Economics", topic: "Micro", question: "If a good is 'Inelastic', a price change has ___ effect on quantity demanded.", choices: ["A large", "A very small", "A random", "No"], answer: 1 },
    { id: "G12-EC-11", grade: 12, subject: "Economics", topic: "Fundamentals", question: "The 'Invisible Hand' theory was proposed by ___.", choices: ["Karl Marx", "Adam Smith", "John Maynard Keynes", "Milton Friedman"], answer: 1 },
    { id: "G12-EC-12", grade: 12, subject: "Economics", topic: "Micro", question: "A 'Sole Proprietorship' is a business owned by ___ person.", choices: ["One", "Two", "Many", "The Government"], answer: 0 },
    { id: "G12-EC-13", grade: 12, subject: "Economics", topic: "Micro", question: "A 'Corporation' is a legal entity owned by ___.", choices: ["The state", "Stockholders", "One boss", "Banks"], answer: 1 },
    { id: "G12-EC-14", grade: 12, subject: "Economics", topic: "Micro", question: "A 'Monopoly' exists when one firm controls the ___ market.", choices: ["Entire", "Small part of", "Global", "None of the"], answer: 0 },
    { id: "G12-EC-15", grade: 12, subject: "Economics", topic: "Micro", question: "An 'Oligopoly' is a market dominated by ___ firms.", choices: ["One", "A few large", "Thousands of small", "No"], answer: 1 },
    { id: "G12-EC-16", grade: 12, subject: "Economics", topic: "Micro", question: "Fixed costs ___ change with the level of production.", choices: ["Do not", "Always", "Frequently", "Directly"], answer: 1 },
    { id: "G12-EC-17", grade: 12, subject: "Economics", topic: "Micro", question: "Variable costs ___ change with the level of production.", choices: ["Never", "Do", "Rarely", "Inversely"], answer: 1 },
    { id: "G12-EC-18", grade: 12, subject: "Economics", topic: "Micro", question: "Marginal Cost is the cost of producing ___.", choices: ["The first unit", "One additional unit", "The total batch", "Half a unit"], answer: 1 },
    { id: "G12-EC-19", grade: 12, subject: "Economics", topic: "Micro", question: "Diminishing Marginal Returns says adding more labor eventually leads to ___ output per worker.", choices: ["More", "Less additional", "Constant", "Infinite"], answer: 1 },
    { id: "G12-EC-20", grade: 12, subject: "Economics", topic: "Micro", question: "A Price Ceiling is a maximum legal price that is usually placed ___ the equilibrium.", choices: ["Above", "Below", "At", "Far above"], answer: 1 },
    { id: "G12-EC-21", grade: 12, subject: "Economics", topic: "Micro", question: "A Price Floor is a minimum legal price that is usually placed ___ the equilibrium.", choices: ["Below", "Above", "At", "Exactly at"], answer: 1 },
    { id: "G12-EC-22", grade: 12, subject: "Economics", topic: "Fundamentals", question: "A 'Command Economy' is one where the ___ makes most economic decisions.", choices: ["Market", "People", "Government", "Tradition"], answer: 2 },
    { id: "G12-EC-23", grade: 12, subject: "Economics", topic: "Fundamentals", question: "A 'Market Economy' relies on the ___ to determine prices.", choices: ["Senate", "Price Mechanism (Supply/Demand)", "UN", "Military"], answer: 1 },
    { id: "G12-EC-24", grade: 12, subject: "Economics", topic: "Micro", question: "Externalities occur when a transaction affects a ___ party.", choices: ["First", "Second", "Third", "No"], answer: 2 },
    { id: "G12-EC-25", grade: 12, subject: "Economics", topic: "Micro", question: "Pollution is an example of a ___ externality.", choices: ["Positive", "Negative", "Neutral", "Financial"], answer: 1 },

    // --- TOPIC 2: MACROECONOMICS (25 Questions) ---
    { id: "G12-EC-26", grade: 12, subject: "Economics", topic: "Macro", question: "Gross Domestic Product (GDP) measures the value of all ___ goods and services produced.", choices: ["Used", "Final", "Unfinished", "Imported"], answer: 1 },
    { id: "G12-EC-27", grade: 12, subject: "Economics", topic: "Macro", question: "Inflation is a general ___ in prices.", choices: ["Decrease", "Increase", "Balance", "Stop"], answer: 1 },
    { id: "G12-EC-28", grade: 12, subject: "Economics", topic: "Macro", question: "The Consumer Price Index (CPI) is used to track ___ over time.", choices: ["Employment", "Inflation", "Trade", "Agriculture"], answer: 1 },
    { id: "G12-EC-29", grade: 12, subject: "Economics", topic: "Macro", question: "Structural Unemployment occurs because of a mismatch between ___.", choices: ["Wages", "Skills and jobs available", "Times of year", "Ages"], answer: 1 },
    { id: "G12-EC-30", grade: 12, subject: "Economics", topic: "Macro", question: "Cyclical Unemployment is caused by ___.", choices: ["The weather", "A recession in the business cycle", "Moving between jobs", "Retirement"], answer: 1 },
    { id: "G12-EC-31", grade: 12, subject: "Economics", topic: "Macro", question: "Frictional Unemployment occurs when people are ___.", choices: ["Retired", "Between jobs", "Sick", "Old"], answer: 1 },
    { id: "G12-EC-32", grade: 12, subject: "Economics", topic: "Macro", question: "The 'Business Cycle' includes Expansion, Peak, Contraction, and ___.", choices: ["Slope", "Trough", "Middle", "High"], answer: 1 },
    { id: "G12-EC-33", grade: 12, subject: "Economics", topic: "Policy", question: "Fiscal Policy refers to the government's use of ___ and spending.", choices: ["Interest rates", "Taxing", "Exports", "Loans"], answer: 1 },
    { id: "G12-EC-34", grade: 12, subject: "Economics", topic: "Policy", question: "Monetary Policy refers to actions by the Central Bank to control ___.", choices: ["Tax rates", "Money supply and interest rates", "Elections", "Population"], answer: 1 },
    { id: "G12-EC-35", grade: 12, subject: "Economics", topic: "Policy", question: "The 'Federal Reserve' is the ___ of the United States.", choices: ["Legislative body", "Central Bank", "Executive office", "Treasury"], answer: 1 },
    { id: "G12-EC-36", grade: 12, subject: "Economics", topic: "Policy", question: "To fight a recession, the Fed might ___ interest rates.", choices: ["Raise", "Lower", "Eliminate", "Ignore"], answer: 1 },
    { id: "G12-EC-37", grade: 12, subject: "Economics", topic: "Policy", question: "To fight high inflation, the Fed might ___ the money supply.", choices: ["Increase", "Decrease", "Double", "Keep"], answer: 1 },
    { id: "G12-EC-38", grade: 12, subject: "Economics", topic: "Macro", question: "A 'Recession' is typically defined as two consecutive quarters of negative ___.", choices: ["Trade", "GDP growth", "Inflation", "Taxation"], answer: 1 },
    { id: "G12-EC-39", grade: 12, subject: "Economics", topic: "Macro", question: "A 'Depression' is a prolonged and severe ___.", choices: ["Expansion", "Recession", "Peak", "Stability"], answer: 1 },
    { id: "G12-EC-40", grade: 12, subject: "Economics", topic: "Macro", question: "The 'National Debt' is the total amount of money the government ___.", choices: ["Saves", "Owes", "Gives away", "Earns"], answer: 1 },
    { id: "G12-EC-41", grade: 12, subject: "Economics", topic: "Macro", question: "A 'Budget Surplus' occurs when the government ___ more than it spends.", choices: ["Collects in taxes", "Borrows", "Imports", "Prints"], answer: 0 },
    { id: "G12-EC-42", grade: 12, subject: "Economics", topic: "Macro", question: "A 'Budget Deficit' occurs when government ___ exceeds tax revenue.", choices: ["Saving", "Spending", "Printing", "Earning"], answer: 1 },
    { id: "G12-EC-43", grade: 12, subject: "Economics", topic: "Macro", question: "The Unemployment Rate is the percentage of the labor force that is ___.", choices: ["Retired", "Jobless and actively seeking work", "Working part-time", "In school"], answer: 1 },
    { id: "G12-EC-44", grade: 12, subject: "Economics", topic: "Macro", question: "Aggregate Demand is the total demand for all goods in the ___.", choices: ["Store", "Economy", "State", "City"], answer: 1 },
    { id: "G12-EC-45", grade: 12, subject: "Economics", topic: "Macro", question: "Aggregate Supply is the total supply of all goods in the ___.", choices: ["Firm", "Economy", "Warehouse", "Ship"], answer: 1 },
    { id: "G12-EC-46", grade: 12, subject: "Economics", topic: "Macro", question: "The 'Multiplier Effect' describes how an initial change in spending lead to a ___ change in GDP.", choices: ["Smaller", "Greater", "Zero", "Constant"], answer: 1 },
    { id: "G12-EC-47", grade: 12, subject: "Economics", topic: "Policy", question: "The primary goal of the Federal Reserve is to maintain price ___.", choices: ["Increases", "Stability", "Chaos", "Low"], answer: 1 },
    { id: "G12-EC-48", grade: 12, subject: "Economics", topic: "Macro", question: "Nominal GDP is GDP measured in ___.", choices: ["Constant prices", "Current prices", "Weights", "Gold"], answer: 1 },
    { id: "G12-EC-49", grade: 12, subject: "Economics", topic: "Macro", question: "Real GDP is adjusted for ___.", choices: ["Population", "Inflation", "Trade", "Waste"], answer: 1 },
    { id: "G12-EC-50", grade: 12, subject: "Economics", topic: "Macro", question: "Stagflation is a combination of high inflation and high ___.", choices: ["Economic growth", "Unemployment", "Taxes", "Exports"], answer: 1 },

    // --- TOPIC 3: INTERNATIONAL TRADE & FINANCE (25 Questions) ---
    { id: "G12-EC-51", grade: 12, subject: "Economics", topic: "Trade", question: "A 'Tariff' is a tax on ___ goods.", choices: ["Domestic", "Imported", "Exported", "Used"], answer: 1 },
    { id: "G12-EC-52", grade: 12, subject: "Economics", topic: "Trade", question: "An 'Embargo' is a complete ___ on trade with a country.", choices: ["Increase", "Ban", "Subsidy", "Contract"], answer: 1 },
    { id: "G12-EC-53", grade: 12, subject: "Economics", topic: "Trade", question: "A 'Quota' is a limit on the ___ of a good that can be imported.", choices: ["Price", "Quantity", "Quality", "Weight"], answer: 1 },
    { id: "G12-EC-54", grade: 12, subject: "Economics", topic: "Trade", question: "Comparative Advantage is the ability to produce a good at a lower ___ than others.", choices: ["Financial cost", "Opportunity cost", "Labor cost", "Time cost"], answer: 1 },
    { id: "G12-EC-55", grade: 12, subject: "Economics", topic: "Trade", question: "Absolute Advantage means producing ___ goods than another using the same resources.", choices: ["Fewer", "More", "Different", "Cheaper"], answer: 1 },
    { id: "G12-EC-56", grade: 12, subject: "Economics", topic: "Trade", question: "A 'Trade Deficit' occurs when imports are ___ exports.", choices: ["Less than", "Greater than", "Equal to", "Zero"], answer: 1 },
    { id: "G12-EC-57", grade: 12, subject: "Economics", topic: "Trade", question: "A 'Trade Surplus' occurs when exports are ___ imports.", choices: ["Less than", "Greater than", "Equal to", "Infinite"], answer: 1 },
    { id: "G12-EC-58", grade: 12, subject: "Economics", topic: "Finance", question: "The 'Exchange Rate' is the price of one ___ in terms of another.", choices: ["Stock", "Currency", "Good", "Bank"], answer: 1 },
    { id: "G12-EC-59", grade: 12, subject: "Economics", topic: "Finance", question: "When a currency 'Appreciates', its value ___.", choices: ["Falls", "Increases", "Stays the same", "Crash"], answer: 1 },
    { id: "G12-EC-60", grade: 12, subject: "Economics", topic: "Finance", question: "When a currency 'Depreciates', its value ___.", choices: ["Rises", "Falls", "Stabilizes", "Doubles"], answer: 1 },
    { id: "G12-EC-61", grade: 12, subject: "Economics", topic: "Trade", question: "NAFTA (now USMCA) is a free trade agreement in ___.", choices: ["Europe", "North America", "Asia", "South America"], answer: 1 },
    { id: "G12-EC-62", grade: 12, subject: "Economics", topic: "Trade", question: "The World Trade Organization (WTO) helps resolve ___.", choices: ["Wars", "Trade disputes", "Border issues", "Labor strikes"], answer: 1 },
    { id: "G12-EC-63", grade: 12, subject: "Economics", topic: "Policy", question: "Protectionism is the use of trade barriers to protect ___ industries.", choices: ["Foreign", "Domestic", "Retail", "Space"], answer: 1 },
    { id: "G12-EC-64", grade: 12, subject: "Economics", topic: "Macro", question: "The 'Current Account' tracks the value of trade in ___.", choices: ["Gold", "Goods and services", "Stocks", "Bonds"], answer: 1 },
    { id: "G12-EC-65", grade: 12, subject: "Economics", topic: "Macro", question: "Globalization is the increasing ___ of world economies.", choices: ["Isolation", "Interdependence", "Independence", "Conflict"], answer: 1 },
    { id: "G12-EC-66", grade: 12, subject: "Economics", topic: "Finance", question: "A 'Stock' represents ownership in a ___.", choices: ["Bank", "Corporation", "Government", "Family"], answer: 1 },
    { id: "G12-EC-67", grade: 12, subject: "Economics", topic: "Finance", question: "A 'Bond' is a certificate of ___.", choices: ["Ownership", "Indebtedness (a loan)", "Gold", "Taxes"], answer: 1 },
    { id: "G12-EC-68", grade: 12, subject: "Economics", topic: "Micro", question: "Dividends are payments made by a corporation to its ___.", choices: ["Employees", "Shareholders", "Suppliers", "Consumers"], answer: 1 },
    { id: "G12-EC-69", grade: 12, subject: "Economics", topic: "Macro", question: "A 'Progressive Tax' system takes a higher rate from ___.", choices: ["Variable incomes", "Higher incomes", "Fixed incomes", "Low incomes"], answer: 1 },
    { id: "G12-EC-70", grade: 12, subject: "Economics", topic: "Macro", question: "A 'Regressive Tax' (like sales tax) hits ___ harder as a percentage of income.", choices: ["Wealthy", "Lower-income earners", "Banks", "Businesses"], answer: 1 },
    { id: "G12-EC-71", grade: 12, subject: "Economics", topic: "Macro", question: "A 'Proportional Tax' (flat tax) takes the ___ percentage from everyone.", choices: ["Different", "Same", "High", "Low"], answer: 1 },
    { id: "G12-EC-72", grade: 12, subject: "Economics", topic: "Finance", question: "Capital Gains are profits made from ___ an asset.", choices: ["Buying", "Selling", "Storing", "Destroying"], answer: 1 },
    { id: "G12-EC-73", grade: 12, subject: "Economics", topic: "Finance", question: "Liquidity is the ease with which an asset can be converted into ___.", choices: ["Gold", "Cash", "Stock", "Land"], answer: 1 },
    { id: "G12-EC-74", grade: 12, subject: "Economics", topic: "Finance", question: "Interest is the ___ of borrowing money.", choices: ["Price", "Risk", "Volume", "Security"], answer: 0 },
    { id: "G12-EC-75", grade: 12, subject: "Economics", topic: "Finance", question: "Compound Interest is interest calculated on the initial principal and ___ interest.", choices: ["Future", "Accumulated", "No", "Simple"], answer: 1 },

    // --- TOPIC 4: PERSONAL FINANCE & PRACTICAL ECON (25 Questions) ---
    { id: "G12-EC-76", grade: 12, subject: "Economics", topic: "Finance", question: "A 'Budget' is a plan for ___.", choices: ["Working", "Saving and spending", "Voting", "Travel"], answer: 1 },
    { id: "G12-EC-77", grade: 12, subject: "Economics", topic: "Finance", question: "Your 'Credit Score' affects your ability to ___.", choices: ["Vote", "Borrow money and get good interest rates", "Travel", "Get a passport"], answer: 1 },
    { id: "G12-EC-78", grade: 12, subject: "Economics", topic: "Finance", question: "A 'Premium' is the amount you pay for ___.", choices: ["Taxes", "Insurance", "Groceries", "Rent"], answer: 1 },
    { id: "G12-EC-79", grade: 12, subject: "Economics", topic: "Finance", question: "A 'Deductible' is the amount you pay ___ insurance starts paying.", choices: ["After", "Before", "Instead of", "Twice"], answer: 1 },
    { id: "G12-EC-80", grade: 12, subject: "Economics", topic: "Finance", question: "Investing in a 'Mutual Fund' provides ___ by spreading money across many stocks.", choices: ["Risk", "Diversification", "Debt", "Loss"], answer: 1 },
    { id: "G12-EC-81", grade: 12, subject: "Economics", topic: "Finance", question: "The 'Primary Market' is where ___ are first issued.", choices: ["Used cars", "New stocks", "Old bonds", "Groceries"], answer: 1 },
    { id: "G12-EC-82", grade: 12, subject: "Economics", topic: "Finance", question: "A 'Bear Market' is one where prices are ___.", choices: ["Rising", "Falling", "Stable", "Infinite"], answer: 1 },
    { id: "G12-EC-83", grade: 12, subject: "Economics", topic: "Finance", question: "A 'Bull Market' is one where prices are ___.", choices: ["Falling", "Rising", "Flat", "Crashed"], answer: 1 },
    { id: "G12-EC-84", grade: 12, subject: "Economics", topic: "Finance", question: "Gross Pay is pay ___ taxes are taken out.", choices: ["After", "Before", "Without", "Plus"], answer: 1 },
    { id: "G12-EC-85", grade: 12, subject: "Economics", topic: "Finance", question: "Net Pay (Take-home pay) is pay ___ taxes.", choices: ["Before", "After", "Ignoring", "Double"], answer: 1 },
    { id: "G12-EC-86", grade: 12, subject: "Economics", topic: "Finance", question: "An 'Asset' is something of ___ that you own.", choices: ["Debt", "Value", "Paper", "Weight"], answer: 1 },
    { id: "G12-EC-87", grade: 12, subject: "Economics", topic: "Finance", question: "A 'Liability' is a ___ (something you owe).", choices: ["Gain", "Debt", "Gift", "Profit"], answer: 1 },
    { id: "G12-EC-88", grade: 12, subject: "Economics", topic: "Finance", question: "Net Worth is Assets minus ___.", choices: ["Incomes", "Liabilities", "Taxes", "Savings"], answer: 1 },
    { id: "G12-EC-89", grade: 12, subject: "Economics", topic: "Micro", question: "A 'Grievance' in a laboratory setting often refers to ___.", choices: ["Equipment", "Labor disputes/complaints", "Chemicals", "Safety"], answer: 1 },
    { id: "G12-EC-90", grade: 12, subject: "Economics", topic: "Finance", question: "Mortgage is a loan specifically for ___.", choices: ["A car", "Real estate/Housing", "Education", "Travel"], answer: 1 },
    { id: "G12-EC-91", grade: 12, subject: "Economics", topic: "Micro", question: "A 'Scab' is a worker who works while others are ___.", choices: ["Sleeping", "On strike", "Traveling", "Promoted"], answer: 1 },
    { id: "G12-EC-92", grade: 12, subject: "Economics", topic: "Finance", question: "Bankruptcy is a legal process to get relief from ___.", choices: ["Work", "Debt", "Taxes", "Marriage"], answer: 1 },
    { id: "G12-EC-93", grade: 12, subject: "Economics", topic: "Finance", question: "The FDIC insures deposits in ___.", choices: ["The Stock Market", "Banks", "Casinos", "Homes"], answer: 1 },
    { id: "G12-EC-94", grade: 12, subject: "Economics", topic: "Finance", question: "Risk and Return generally have a ___ relationship.", choices: ["Inverse", "Direct (Higher risk = Higher potential return)", "No", "Negative"], answer: 1 },
    { id: "G12-EC-95", grade: 12, subject: "Economics", topic: "Finance", question: "A '401(k)' is a type of ___ plan.", choices: ["Vacation", "Retirement", "Health", "School"], answer: 1 },
    { id: "G12-EC-96", grade: 12, subject: "Economics", topic: "Macro", question: "Inflation hurts people on ___ incomes the most.", choices: ["Variable", "Fixed", "High", "Bonus"], answer: 1 },
    { id: "G12-EC-97", grade: 12, subject: "Economics", topic: "Policy", question: "The 'Debt Ceiling' is the legal limit on how much the US can ___.", choices: ["Tax", "Borrow", "Spend", "Lend"], answer: 1 },
    { id: "G12-EC-98", grade: 12, subject: "Economics", topic: "Micro", question: "A 'Consumer' is a person who ___ goods and services.", choices: ["Makes", "Uses/Purchases", "Sells", "Transports"], answer: 1 },
    { id: "G12-EC-99", grade: 12, subject: "Economics", topic: "Micro", question: "A 'Producer' is a person or firm that ___ goods and services.", choices: ["Consumes", "Creates/Makes", "Saves", "Destroys"], answer: 1 },
    { id: "G12-EC-100", grade: 12, subject: "Economics", topic: "Fundamentals", question: "The 'Production Possibilities Curve' shows the trade-offs between ___.", choices: ["Prices", "Two different goods", "Buyers", "Countries"], answer: 1 }
];

module.exports = G12_ECONOMICS_COMPLETE;
