const G1_ELA_COMPLETE = [
    // --- TOPIC 1: PHONICS & SPELLING (25 Questions) ---
    { id: "G1-ELA-01", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Which word rhymes with 'Cat'?", choices: ["Dog", "Hat", "Bird", "Sun"], answer: 1 },
    { id: "G1-ELA-02", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "What is the first sound in the word 'Apple'?", choices: ["B", "P", "A", "S"], answer: 2 },
    { id: "G1-ELA-03", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Which word has a long 'A' sound (like in Cake)?", choices: ["Bat", "Lake", "Sad", "Map"], answer: 1 },
    { id: "G1-ELA-04", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Which word starts with the 'Sh' sound?", choices: ["Sun", "Ship", "Chip", "Trip"], answer: 1 },
    { id: "G1-ELA-05", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "How many syllables are in the word 'Banana'?", choices: ["1", "2", "3", "4"], answer: 2 },
    { id: "G1-ELA-06", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Which word ends with the 'ck' sound?", choices: ["Back", "Bat", "Bag", "Ban"], answer: 0 },
    { id: "G1-ELA-07", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Find the word with the short 'o' sound.", choices: ["Boat", "Dog", "Go", "No"], answer: 1 },
    { id: "G1-ELA-08", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Which letter is a vowel?", choices: ["B", "E", "D", "F"], answer: 1 },
    { id: "G1-ELA-09", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Which word rhymes with 'Blue'?", choices: ["Red", "Shoe", "Black", "Pink"], answer: 1 },
    { id: "G1-ELA-10", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Which word has the 'Ch' sound?", choices: ["Chair", "Share", "Where", "There"], answer: 0 },
    { id: "G1-ELA-11", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Choose the word with a 'silent e' at the end.", choices: ["Hop", "Hope", "Hip", "Hot"], answer: 1 },
    { id: "G1-ELA-12", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Which word has two syllables?", choices: ["Apple", "Cat", "Dog", "Fish"], answer: 0 },
    { id: "G1-ELA-13", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "What is the middle sound in 'Pig'?", choices: ["a", "e", "i", "o"], answer: 2 },
    { id: "G1-ELA-14", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Which word rhymes with 'Sing'?", choices: ["Song", "Ring", "Sun", "Sand"], answer: 1 },
    { id: "G1-ELA-15", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Which word starts with a blend (two consonants)?", choices: ["At", "Frog", "In", "Up"], answer: 1 },
    { id: "G1-ELA-16", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "How do you spell the number after one?", choices: ["To", "Too", "Two", "Tow"], answer: 2 },
    { id: "G1-ELA-17", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Which word has the 'th' sound?", choices: ["Tree", "The", "See", "Bee"], answer: 1 },
    { id: "G1-ELA-18", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "What is the ending_sound of 'Duck'?", choices: ["d", "u", "c", "k"], answer: 3 },
    { id: "G1-ELA-19", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Which word has a short 'u' sound?", choices: ["Blue", "Bug", "Use", "Rule"], answer: 1 },
    { id: "G1-ELA-20", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Which word rhymes with 'Light'?", choices: ["Night", "Late", "Look", "Let"], answer: 0 },
    { id: "G1-ELA-21", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "How many letters are in the alphabet?", choices: ["20", "24", "26", "30"], answer: 2 },
    { id: "G1-ELA-22", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Which word has a long 'i' sound?", choices: ["Kit", "Kite", "Kid", "Kiss"], answer: 1 },
    { id: "G1-ELA-23", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Choose the correctly spelled word.", choices: ["Hous", "Howse", "House", "Huse"], answer: 2 },
    { id: "G1-ELA-24", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "What sound does a 'C' make in 'Cat'?", choices: ["s", "k", "ch", "sh"], answer: 1 },
    { id: "G1-ELA-25", grade: 1, subject: "English Language Arts", topic: "Phonics", question: "Which word rhymes with 'Day'?", choices: ["Do", "Play", "Die", "By"], answer: 1 },

    // --- TOPIC 2: GRAMMAR - NOUNS & VERBS (25 Questions) ---
    { id: "G1-ELA-26", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Which word is a noun (a person)?", choices: ["Run", "Happy", "Teacher", "Jump"], answer: 2 },
    { id: "G1-ELA-27", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Which word is an action word (verb)?", choices: ["Apple", "Sleep", "Green", "House"], answer: 1 },
    { id: "G1-ELA-28", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Which word describes a color?", choices: ["Dog", "Big", "Blue", "Run"], answer: 2 },
    { id: "G1-ELA-29", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "How do you make 'Cat' plural (more than one)?", choices: ["Cat", "Cates", "Cats", "Cattes"], answer: 2 },
    { id: "G1-ELA-30", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Which word is a noun (a place)?", choices: ["School", "Eat", "Small", "Quickly"], answer: 0 },
    { id: "G1-ELA-31", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Which pronoun would you use for a girl?", choices: ["He", "She", "It", "They"], answer: 1 },
    { id: "G1-ELA-32", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Which word is an adjective (describes something)?", choices: ["Ball", "Yellow", "Walk", "From"], answer: 1 },
    { id: "G1-ELA-33", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "What is the plural of 'Box'?", choices: ["Boxs", "Boxies", "Boxes", "Boxen"], answer: 2 },
    { id: "G1-ELA-34", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Identify the verb: 'The dog barked.'", choices: ["The", "Dog", "Barked", "None"], answer: 2 },
    { id: "G1-ELA-35", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Which is a proper noun (specific name)?", choices: ["Boy", "City", "New York", "School"], answer: 2 },
    { id: "G1-ELA-36", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Choose the correct word: 'I ___ my bike.'", choices: ["ride", "rides", "riding", "rider"], answer: 0 },
    { id: "G1-ELA-37", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Which is an animal noun?", choices: ["Tree", "Elephant", "Pencil", "Box"], answer: 1 },
    { id: "G1-ELA-38", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "What is the opposite of 'Big'?", choices: ["Large", "Huge", "Small", "Tall"], answer: 2 },
    { id: "G1-ELA-39", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Which word is a thing?", choices: ["Doctor", "Store", "Pencil", "Run"], answer: 2 },
    { id: "G1-ELA-40", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Which word means more than one 'Child'?", choices: ["Childs", "Children", "Childes", "Childer"], answer: 1 },
    { id: "G1-ELA-41", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "What do you call a word that names a person, place, or thing?", choices: ["Verb", "Noun", "Adjective", "Letter"], answer: 1 },
    { id: "G1-ELA-42", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Identify the adjective: 'The little cat.'", choices: ["The", "Little", "Cat", "None"], answer: 1 },
    { id: "G1-ELA-43", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Which verb fits: 'We ___ to the park.'", choices: ["goes", "go", "going", "gone"], answer: 1 },
    { id: "G1-ELA-44", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Which word is the pronoun: 'He is my friend.'", choices: ["He", "Is", "My", "Friend"], answer: 0 },
    { id: "G1-ELA-45", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "What is the plural of 'Foot'?", choices: ["Foots", "Feets", "Feet", "Footes"], answer: 2 },
    { id: "G1-ELA-46", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Which word is a feeling?", choices: ["Sad", "Table", "Jump", "Yellow"], answer: 0 },
    { id: "G1-ELA-47", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Choose the noun in this sentence: 'The ball is red.'", choices: ["The", "Ball", "Is", "Red"], answer: 1 },
    { id: "G1-ELA-48", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Which word is the opposite of 'Up'?", choices: ["High", "Down", "Side", "In"], answer: 1 },
    { id: "G1-ELA-49", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Identify the action: 'Birds fly in the sky.'", choices: ["Birds", "Fly", "Sky", "The"], answer: 1 },
    { id: "G1-ELA-50", grade: 1, subject: "English Language Arts", topic: "Grammar", question: "Which is a month of the year?", choices: ["Monday", "Summer", "October", "Morning"], answer: 2 },

    // --- TOPIC 3: PUNCTUATION & CAPITALIZATION (25 Questions) ---
    { id: "G1-ELA-51", grade: 1, subject: "English Language Arts", topic: "Punctuation", question: "Which punctuation ends a question?", choices: [".", "!", "?", ","], answer: 2 },
    { id: "G1-ELA-52", grade: 1, subject: "English Language Arts", topic: "Capitalization", question: "The first word of a sentence must start with a...?", choices: ["Small letter", "Capital letter", "Number", "Dot"], answer: 1 },
    { id: "G1-ELA-53", grade: 1, subject: "English Language Arts", topic: "Punctuation", question: "Which punctuation mark do you use for a telling sentence?", choices: [".", "?", "!", ","], answer: 0 },
    { id: "G1-ELA-54", grade: 1, subject: "English Language Arts", topic: "Capitalization", question: "Which word should always be capitalized?", choices: ["apple", "i", "run", "house"], answer: 1 },
    { id: "G1-ELA-55", grade: 1, subject: "English Language Arts", topic: "Punctuation", question: "What mark do you use for a very exciting sentence?", choices: [".", "!", "?", ","], answer: 1 },
    { id: "G1-ELA-56", grade: 1, subject: "English Language Arts", topic: "Capitalization", question: "Which name is written correctly?", choices: ["bob", "Bob", "bOB", "boB"], answer: 1 },
    { id: "G1-ELA-57", grade: 1, subject: "English Language Arts", topic: "Punctuation", question: "Where does the period go in a sentence?", choices: ["At the beginning", "In the middle", "At the end", "Nowhere"], answer: 2 },
    { id: "G1-ELA-58", grade: 1, subject: "English Language Arts", topic: "Capitalization", question: "Which day of the week is capitalized correctly?", choices: ["monday", "Monday", "mOnday", "MONday"], answer: 1 },
    { id: "G1-ELA-59", grade: 1, subject: "English Language Arts", topic: "Punctuation", question: "Which is a correct sentence?", choices: ["it is sunny", "It is sunny.", "it is sunny?", "is it sunny."], answer: 1 },
    { id: "G1-ELA-60", grade: 1, subject: "English Language Arts", topic: "Capitalization", question: "The word 'English' is capitalized because it is a...?", choices: ["Verb", "Language/Proper Noun", "Long word", "Action word"], answer: 1 },
    { id: "G1-ELA-61", grade: 1, subject: "English Language Arts", topic: "Punctuation", question: "How many periods are in this sentence: 'I see a dog.'", choices: ["0", "1", "2", "3"], answer: 1 },
    { id: "G1-ELA-62", grade: 1, subject: "English Language Arts", topic: "Capitalization", question: "Which of these should have a capital letter?", choices: ["cat", "street", "america", "blue"], answer: 2 },
    { id: "G1-ELA-63", grade: 1, subject: "English Language Arts", topic: "Punctuation", question: "What is this mark called? ( ! )", choices: ["Question mark", "Period", "Exclamation point", "Comma"], answer: 2 },
    { id: "G1-ELA-64", grade: 1, subject: "English Language Arts", topic: "Capitalization", question: "Do you capitalize the word 'Teacher' if it is not a name?", choices: ["Always", "Never", "Usually not", "Only on Sundays"], answer: 2 },
    { id: "G1-ELA-65", grade: 1, subject: "English Language Arts", topic: "Punctuation", question: "Choose the correct question.", choices: ["Can I play.", "Can I play!", "Can I play?", "can I play"], answer: 2 },
    { id: "G1-ELA-66", grade: 1, subject: "English Language Arts", topic: "Capitalization", question: "Which is correct?", choices: ["my dog is Max.", "My dog is max.", "My dog is Max.", "my dog is max"], answer: 2 },
    { id: "G1-ELA-67", grade: 1, subject: "English Language Arts", topic: "Punctuation", question: "What mark is used to separate items in a list?", choices: [".", "?", "!", ","], answer: 3 },
    { id: "G1-ELA-68", grade: 1, subject: "English Language Arts", topic: "Capitalization", question: "Which month needs a capital?", choices: ["july", "summer", "day", "month"], answer: 0 },
    { id: "G1-ELA-69", grade: 1, subject: "English Language Arts", topic: "Punctuation", question: "Which sentence is an exclamation?", choices: ["I am six.", "How are you?", "Watch out!", "Go away."], answer: 2 },
    { id: "G1-ELA-70", grade: 1, subject: "English Language Arts", topic: "Capitalization", question: "The word 'I' is always capitalized when it is by itself.", choices: ["True", "False", "Sometimes", "Never"], answer: 0 },
    { id: "G1-ELA-71", grade: 1, subject: "English Language Arts", topic: "Punctuation", question: "What is the dot at the end of a sentence called?", choices: ["Question mark", "Exclamation mark", "Period", "Comma"], answer: 2 },
    { id: "G1-ELA-72", grade: 1, subject: "English Language Arts", topic: "Capitalization", question: "Which is the correct way to write your name?", choices: ["sarah", "Sarah", "sARAH", "sarAh"], answer: 1 },
    { id: "G1-ELA-73", grade: 1, subject: "English Language Arts", topic: "Punctuation", question: "Which sentence has correct punctuation?", choices: ["Who is there?", "Who is there.", "Who is there!", "Who is there,"], answer: 0 },
    { id: "G1-ELA-74", grade: 1, subject: "English Language Arts", topic: "Capitalization", question: "The names of cities should be capitalized.", choices: ["True", "False", "Only big cities", "Only in books"], answer: 0 },
    { id: "G1-ELA-75", grade: 1, subject: "English Language Arts", topic: "Punctuation", question: "Which mark shows you are asking something?", choices: ["!", "?", ".", ","], answer: 1 },

    // --- TOPIC 4: READING COMPREHENSION & VOCABULARY (25 Questions) ---
    { id: "G1-ELA-76", grade: 1, subject: "English Language Arts", topic: "Reading", question: "What is the title of a book?", choices: ["The name of the book", "The person who wrote it", "The pictures", "The back cover"], answer: 0 },
    { id: "G1-ELA-77", grade: 1, subject: "English Language Arts", topic: "Reading", question: "Who is the 'Author' of a book?", choices: ["The person who draws", "The person who writes", "The main character", "The reader"], answer: 1 },
    { id: "G1-ELA-78", grade: 1, subject: "English Language Arts", topic: "Reading", question: "What does the 'Illustrator' do?", choices: ["Writes the words", "Draws the pictures", "Reads the story", "Sells the book"], answer: 1 },
    { id: "G1-ELA-79", grade: 1, subject: "English Language Arts", topic: "Reading", question: "What is a 'Character' in a story?", choices: ["The place where it happens", "The people or animals in it", "The ending", "The cover"], answer: 1 },
    { id: "G1-ELA-80", grade: 1, subject: "English Language Arts", topic: "Reading", question: "What is the 'Setting' of a story?", choices: ["The characters", "When and where it happens", "The title", "The words"], answer: 1 },
    { id: "G1-ELA-81", grade: 1, subject: "English Language Arts", topic: "Reading", question: "What happens at the beginning of a story?", choices: ["The end", "The story starts", "The book closes", "The characters say goodbye"], answer: 1 },
    { id: "G1-ELA-82", grade: 1, subject: "English Language Arts", topic: "Reading", question: "Which word means the same as 'Happy'?", choices: ["Sad", "Glad", "Angry", "Sleepy"], answer: 1 },
    { id: "G1-ELA-83", grade: 1, subject: "English Language Arts", topic: "Reading", question: "A story that is NOT real is called...?", choices: ["Fact", "Fiction", "True", "News"], answer: 1 },
    { id: "G1-ELA-84", grade: 1, subject: "English Language Arts", topic: "Reading", question: "A story that is real and true is called...?", choices: ["Fiction", "Make-believe", "Non-fiction", "Storybook"], answer: 2 },
    { id: "G1-ELA-85", grade: 1, subject: "English Language Arts", topic: "Reading", question: "What do we call the main idea of a story?", choices: ["The characters", "What the story is mostly about", "The page numbers", "The drawings"], answer: 1 },
    { id: "G1-ELA-86", grade: 1, subject: "English Language Arts", topic: "Reading", question: "Which word is the opposite of 'Cold'?", choices: ["Cool", "Ice", "Hot", "Blue"], answer: 2 },
    { id: "G1-ELA-87", grade: 1, subject: "English Language Arts", topic: "Reading", question: "What do characters use to talk in a book?", choices: ["Speech bubbles", "Pictures", "The cover", "The title"], answer: 0 },
    { id: "G1-ELA-88", grade: 1, subject: "English Language Arts", topic: "Reading", question: "Where do you find the page numbers?", choices: ["The cover", "The title", "On the pages", "On the spine"], answer: 2 },
    { id: "G1-ELA-89", grade: 1, subject: "English Language Arts", topic: "Reading", question: "What is a 'Retell'?", choices: ["Closing the book", "Telling the story again", "Writing a new book", "Drawing pictures"], answer: 1 },
    { id: "G1-ELA-90", grade: 1, subject: "English Language Arts", topic: "Reading", question: "Which word means the same as 'Little'?", choices: ["Big", "Small", "Tall", "Long"], answer: 1 },
    { id: "G1-ELA-91", grade: 1, subject: "English Language Arts", topic: "Reading", question: "How do you know who is talking in a story?", choices: ["The title", "The quotation marks or dialogue", "The page number", "The colors"], answer: 1 },
    { id: "G1-ELA-92", grade: 1, subject: "English Language Arts", topic: "Reading", question: "The 'Plot' is what happens in the story.", choices: ["True", "False", "Only in movies", "Never"], answer: 0 },
    { id: "G1-ELA-93", grade: 1, subject: "English Language Arts", topic: "Reading", question: "Which is a question word?", choices: ["The", "Who", "And", "See"], answer: 1 },
    { id: "G1-ELA-94", grade: 1, subject: "English Language Arts", topic: "Reading", question: "What is the table of contents for?", choices: ["Drawing", "Finding chapters or sections", "Reading the end", "Looking at covers"], answer: 1 },
    { id: "G1-ELA-95", grade: 1, subject: "English Language Arts", topic: "Reading", question: "Which word is a synonym for 'Quick'?", choices: ["Slow", "Fast", "Quiet", "Heavy"], answer: 1 },
    { id: "G1-ELA-96", grade: 1, subject: "English Language Arts", topic: "Reading", question: "What do we call the problem in a story?", choices: ["The setting", "The conflict", "The title", "The author"], answer: 1 },
    { id: "G1-ELA-97", grade: 1, subject: "English Language Arts", topic: "Reading", question: "What is a 'Fable'?", choices: ["A true story", "A short story with a lesson", "A math book", "A map"], answer: 1 },
    { id: "G1-ELA-98", grade: 1, subject: "English Language Arts", topic: "Reading", question: "What do you do when you 'predict'?", choices: ["Read the end first", "Guess what happens next", "Close your eyes", "Forget the story"], answer: 1 },
    { id: "G1-ELA-99", grade: 1, subject: "English Language Arts", topic: "Reading", question: "Which part of the book protects the pages?", choices: ["The title", "The cover", "The words", "The author"], answer: 1 },
    { id: "G1-ELA-100", grade: 1, subject: "English Language Arts", topic: "Reading", question: "Reading helps your brain grow.", choices: ["True", "False", "Maybe", "Only for teachers"], answer: 0 }
];

module.exports = G1_ELA_COMPLETE;
