const G1_SCIENCE_COMPLETE = [
    // --- TOPIC 1: PLANTS & ANIMALS (25 Questions) ---
    { id: "G1-SCI-01", grade: 1, subject: "Science", topic: "Plants/Animals", question: "What do plants need from the sun to make food?", choices: ["Shadows", "Light", "Heat", "Moonlight"], answer: 1 },
    { id: "G1-SCI-02", grade: 1, subject: "Science", topic: "Plants/Animals", question: "Which part of the plant grows into the soil?", choices: ["Leaves", "Stem", "Roots", "Petals"], answer: 2 },
    { id: "G1-SCI-03", grade: 1, subject: "Science", topic: "Plants/Animals", question: "What is the first stage of a plant's life?", choices: ["Flower", "Leaf", "Seed", "Fruit"], answer: 2 },
    { id: "G1-SCI-04", grade: 1, subject: "Science", topic: "Plants/Animals", question: "Which animal has a life cycle that includes a tadpole stage?", choices: ["Bird", "Dog", "Frog", "Fish"], answer: 2 },
    { id: "G1-SCI-05", grade: 1, subject: "Science", topic: "Plants/Animals", question: "What do animals breathe in to stay alive?", choices: ["Water", "Oxygen", "Food", "Dirt"], answer: 1 },
    { id: "G1-SCI-06", grade: 1, subject: "Science", topic: "Plants/Animals", question: "Which part of a plant carries water to the leaves?", choices: ["Stem", "Roots", "Flower", "Seed"], answer: 0 },
    { id: "G1-SCI-07", grade: 1, subject: "Science", topic: "Plants/Animals", question: "Which animal is a mammal?", choices: ["Snake", "Whale", "Spider", "Frog"], answer: 1 },
    { id: "G1-SCI-08", grade: 1, subject: "Science", topic: "Plants/Animals", question: "What does a caterpillar turn into?", choices: ["Bee", "Ant", "Butterfly", "Spider"], answer: 2 },
    { id: "G1-SCI-09", grade: 1, subject: "Science", topic: "Plants/Animals", question: "Where does a bird usually live?", choices: ["Underwater", "In a hive", "In a nest", "Underground"], answer: 2 },
    { id: "G1-SCI-10", grade: 1, subject: "Science", topic: "Plants/Animals", question: "Which animal has scales?", choices: ["Cat", "Fish", "Bear", "Bird"], answer: 1 },
    { id: "G1-SCI-11", grade: 1, subject: "Science", topic: "Plants/Animals", question: "What is a habitat?", choices: ["A type of food", "A place where an animal lives", "A part of a plant", "A type of weather"], answer: 1 },
    { id: "G1-SCI-12", grade: 1, subject: "Science", topic: "Plants/Animals", question: "Which of these is a living thing?", choices: ["Rock", "Water", "Tree", "Cloud"], answer: 2 },
    { id: "G1-SCI-13", grade: 1, subject: "Science", topic: "Plants/Animals", question: "What part of the plant makes seeds?", choices: ["Roots", "Stem", "Flower", "Leaf"], answer: 2 },
    { id: "G1-SCI-14", grade: 1, subject: "Science", topic: "Plants/Animals", question: "How do fish breathe underwater?", choices: ["Lungs", "Gills", "Nose", "Skin"], answer: 1 },
    { id: "G1-SCI-15", grade: 1, subject: "Science", topic: "Plants/Animals", question: "Which animal hatches from an egg?", choices: ["Dog", "Cow", "Chicken", "Horse"], answer: 2 },
    { id: "G1-SCI-16", grade: 1, subject: "Science", topic: "Plants/Animals", question: "What do plants give off that humans need to breathe?", choices: ["Oxygen", "Carbon Dioxide", "Water", "Sugar"], answer: 0 },
    { id: "G1-SCI-17", grade: 1, subject: "Science", topic: "Plants/Animals", question: "Which animal uses camouflage to hide?", choices: ["Chameleon", "Elephant", "Lion", "Dog"], answer: 0 },
    { id: "G1-SCI-18", grade: 1, subject: "Science", topic: "Plants/Animals", question: "What season do many animals hibernate in?", choices: ["Summer", "Spring", "Winter", "Fall"], answer: 2 },
    { id: "G1-SCI-19", grade: 1, subject: "Science", topic: "Plants/Animals", question: "Which of these is NOT a plant part?", choices: ["Leaf", "Petal", "Wing", "Root"], answer: 2 },
    { id: "G1-SCI-20", grade: 1, subject: "Science", topic: "Plants/Animals", question: "What is the main job of leaves?", choices: ["To hold the plant up", "To make food", "To soak up water", "To look pretty"], answer: 1 },
    { id: "G1-SCI-21", grade: 1, subject: "Science", topic: "Plants/Animals", question: "Which animal is an herbivore (eats only plants)?", choices: ["Wolf", "Shark", "Rabbit", "Owl"], answer: 2 },
    { id: "G1-SCI-22", grade: 1, subject: "Science", topic: "Plants/Animals", question: "What do animals need to grow?", choices: ["Toys", "Food and Water", "Television", "Clothing"], answer: 1 },
    { id: "G1-SCI-23", grade: 1, subject: "Science", topic: "Plants/Animals", question: "What part of an apple contains the seeds?", choices: ["The skin", "The core", "The stem", "The leaves"], answer: 1 },
    { id: "G1-SCI-24", grade: 1, subject: "Science", topic: "Plants/Animals", question: "Which animal lives in a colony?", choices: ["Tiger", "Eagle", "Ant", "Bear"], answer: 2 },
    { id: "G1-SCI-25", grade: 1, subject: "Science", topic: "Plants/Animals", question: "Why do some birds fly south in the winter?", choices: ["To find food", "To play in the snow", "To sleep more", "To hide"], answer: 0 },

    // --- TOPIC 2: EARTH, SUN, & MOON (25 Questions) ---
    { id: "G1-SCI-26", grade: 1, subject: "Science", topic: "Space", question: "Which object is the center of our solar system?", choices: ["Earth", "Moon", "Sun", "Mars"], answer: 2 },
    { id: "G1-SCI-27", grade: 1, subject: "Science", topic: "Space", question: "What time of day can you usually see the stars?", choices: ["Morning", "Noon", "Afternoon", "Night"], answer: 3 },
    { id: "G1-SCI-28", grade: 1, subject: "Science", topic: "Space", question: "The Sun is actually a huge...", choices: ["Planet", "Moon", "Star", "Cloud"], answer: 2 },
    { id: "G1-SCI-29", grade: 1, subject: "Science", topic: "Space", question: "How many moons does Earth have?", choices: ["Zero", "One", "Two", "Ten"], answer: 1 },
    { id: "G1-SCI-30", grade: 1, subject: "Science", topic: "Space", question: "Which tool helps us see objects far away in space?", choices: ["Microscope", "Magnifying glass", "Telescope", "Mirror"], answer: 2 },
    { id: "G1-SCI-31", grade: 1, subject: "Science", topic: "Space", question: "What causes day and night?", choices: ["The Sun moving", "Earth spinning", "The Moon blocking light", "Clouds"], answer: 1 },
    { id: "G1-SCI-32", grade: 1, subject: "Science", topic: "Space", question: "What shape is the Earth?", choices: ["Square", "Flat", "Round", "Triangle"], answer: 2 },
    { id: "G1-SCI-33", grade: 1, subject: "Science", topic: "Space", question: "Which of these provides heat to Earth?", choices: ["The Moon", "The Sun", "The Clouds", "The Ocean"], answer: 1 },
    { id: "G1-SCI-34", grade: 1, subject: "Science", topic: "Space", question: "Does the Moon produce its own light?", choices: ["Yes", "No", "Only in winter", "Only on Tuesdays"], answer: 1 },
    { id: "G1-SCI-35", grade: 1, subject: "Science", topic: "Space", question: "How long does it take for Earth to spin all the way around once?", choices: ["One hour", "One week", "One day", "One month"], answer: 2 },
    { id: "G1-SCI-36", grade: 1, subject: "Science", topic: "Space", question: "Which season comes after Winter?", choices: ["Fall", "Summer", "Spring", "August"], answer: 2 },
    { id: "G1-SCI-37", grade: 1, subject: "Science", topic: "Space", question: "What are the large patterns of stars called?", choices: ["Galleries", "Constellations", "Paintings", "Clouds"], answer: 1 },
    { id: "G1-SCI-38", grade: 1, subject: "Science", topic: "Space", question: "In which direction does the Sun appear to rise?", choices: ["North", "South", "East", "West"], answer: 2 },
    { id: "G1-SCI-39", grade: 1, subject: "Science", topic: "Space", question: "What do we call the different shapes the moon appears to have?", choices: ["Faces", "Phases", "Stages", "Moods"], answer: 1 },
    { id: "G1-SCI-40", grade: 1, subject: "Science", topic: "Space", question: "Which is the hottest part of the day usually?", choices: ["Sunrise", "Midnight", "Afternoon", "Early Morning"], answer: 2 },
    { id: "G1-SCI-41", grade: 1, subject: "Science", topic: "Space", question: "Which planet do we live on?", choices: ["Mars", "Venus", "Earth", "Jupiter"], answer: 2 },
    { id: "G1-SCI-42", grade: 1, subject: "Science", topic: "Space", question: "What are clouds made of?", choices: ["Cotton candy", "Smoke", "Water droplets or ice", "White paint"], answer: 2 },
    { id: "G1-SCI-43", grade: 1, subject: "Science", topic: "Space", question: "What covers most of the Earth's surface?", choices: ["Sand", "Ice", "Water", "Forests"], answer: 2 },
    { id: "G1-SCI-44", grade: 1, subject: "Science", topic: "Space", question: "Why can't we see stars during the day?", choices: ["They go away", "The Sun is too bright", "It is too cold", "They turn off"], answer: 1 },
    { id: "G1-SCI-45", grade: 1, subject: "Science", topic: "Space", question: "Which season has the shortest amount of daylight?", choices: ["Summer", "Spring", "Fall", "Winter"], answer: 3 },
    { id: "G1-SCI-46", grade: 1, subject: "Science", topic: "Space", question: "What is the Moon made of?", choices: ["Cheese", "Rock", "Gas", "Liquid"], answer: 1 },
    { id: "G1-SCI-47", grade: 1, subject: "Science", topic: "Space", question: "What do we call the air that surrounds Earth?", choices: ["Ocean", "Atmosphere", "Space", "Ground"], answer: 1 },
    { id: "G1-SCI-48", grade: 1, subject: "Science", topic: "Space", question: "Which movement causes the seasons?", choices: ["Earth spinning", "Earth orbiting the Sun", "The Sun spinning", "The Moon orbiting Earth"], answer: 1 },
    { id: "G1-SCI-49", grade: 1, subject: "Science", topic: "Space", question: "What color does the Sun usually look near sunset?", choices: ["Green", "Blue", "Orange or Red", "Purple"], answer: 2 },
    { id: "G1-SCI-50", grade: 1, subject: "Science", topic: "Space", question: "Is the Sun a solid, liquid, or gas?", choices: ["Solid", "Liquid", "Gas/Plasma", "Ice"], answer: 2 },

    // --- TOPIC 3: LIGHT & SOUND (25 Questions) ---
    { id: "G1-SCI-51", grade: 1, subject: "Science", topic: "Light/Sound", question: "Which of these is a natural source of light?", choices: ["Flashlight", "The Sun", "A Lamp", "A Candle"], answer: 1 },
    { id: "G1-SCI-52", grade: 1, subject: "Science", topic: "Light/Sound", question: "What is created when an object blocks light?", choices: ["A Reflection", "A Shadow", "A Rainbow", "A Sparkle"], answer: 1 },
    { id: "G1-SCI-53", grade: 1, subject: "Science", topic: "Light/Sound", question: "How does sound travel to your ears?", choices: ["Through Waves", "Through Wires", "It doesn't move", "Through Light"], answer: 0 },
    { id: "G1-SCI-54", grade: 1, subject: "Science", topic: "Light/Sound", question: "Which object is transparent (lets all light through)?", choices: ["A Brick", "A Wooden Door", "Clear Glass", "A Metal Spoon"], answer: 2 },
    { id: "G1-SCI-55", grade: 1, subject: "Science", topic: "Light/Sound", question: "What part of your body do you use to sense sound?", choices: ["Eyes", "Nose", "Ears", "Hands"], answer: 2 },
    { id: "G1-SCI-56", grade: 1, subject: "Science", topic: "Light/Sound", question: "Vibrations cause which of the following?", choices: ["Light", "Heat", "Sound", "Electricity"], answer: 2 },
    { id: "G1-SCI-57", grade: 1, subject: "Science", topic: "Light/Sound", question: "Which surface reflects light the best?", choices: ["A Mirror", "A Black Cloth", "A Piece of Wood", "A Rock"], answer: 0 },
    { id: "G1-SCI-58", grade: 1, subject: "Science", topic: "Light/Sound", question: "What do we call a sound that is very loud?", choices: ["High Pitch", "High Volume", "Low Pitch", "Silence"], answer: 1 },
    { id: "G1-SCI-59", grade: 1, subject: "Science", topic: "Light/Sound", question: "Can light pass through a wall?", choices: ["Yes", "No", "Only on sunny days", "Only at night"], answer: 1 },
    { id: "G1-SCI-60", grade: 1, subject: "Science", topic: "Light/Sound", question: "Which animal uses sound to 'see' in the dark?", choices: ["Owl", "Bat", "Cat", "Snake"], answer: 1 },
    { id: "G1-SCI-61", grade: 1, subject: "Science", topic: "Light/Sound", question: "What makes a shadow get bigger?", choices: ["Moving object closer to light", "Moving object away from light", "Turning off the light", "Painting it black"], answer: 0 },
    { id: "G1-SCI-62", grade: 1, subject: "Science", topic: "Light/Sound", question: "Which instrument do you hit to make sound?", choices: ["Flute", "Guitar", "Drum", "Piano"], answer: 2 },
    { id: "G1-SCI-63", grade: 1, subject: "Science", topic: "Light/Sound", question: "What happens when you pluck a tight rubber band?", choices: ["It melts", "It vibrates and makes sound", "It turns blue", "Nothing"], answer: 1 },
    { id: "G1-SCI-64", grade: 1, subject: "Science", topic: "Light/Sound", question: "What do we see in the sky after it rains and the sun comes out?", choices: ["A Shadow", "A Rainbow", "A Cloud", "A Moon"], answer: 1 },
    { id: "G1-SCI-65", grade: 1, subject: "Science", topic: "Light/Sound", question: "Which is a 'high pitch' sound?", choices: ["A Bird chirping", "A Lion roaring", "A Drum beating", "A Large bell"], answer: 0 },
    { id: "G1-SCI-66", grade: 1, subject: "Science", topic: "Light/Sound", question: "Why do we wear sunglasses?", choices: ["To see in the dark", "To block bright light", "To hear better", "To keep our ears warm"], answer: 1 },
    { id: "G1-SCI-67", grade: 1, subject: "Science", topic: "Light/Sound", question: "What is it called when light hits a mirror and bounces back?", choices: ["Refraction", "Reflection", "Absorption", "Shadowing"], answer: 1 },
    { id: "G1-SCI-68", grade: 1, subject: "Science", topic: "Light/Sound", question: "Does sound travel faster in water or air?", choices: ["Water", "Air", "They are the same", "Sound can't travel in water"], answer: 0 },
    { id: "G1-SCI-69", grade: 1, subject: "Science", topic: "Light/Sound", question: "Which material is 'opaque' (blocks all light)?", choices: ["Air", "Water", "Cardboard", "Plastic Wrap"], answer: 2 },
    { id: "G1-SCI-70", grade: 1, subject: "Science", topic: "Light/Sound", question: "How do you make the pitch of a whistle higher?", choices: ["Blow harder", "Blow softer", "Use a smaller whistle", "Paint it red"], answer: 2 },
    { id: "G1-SCI-71", grade: 1, subject: "Science", topic: "Light/Sound", question: "What do you call a very faint sound?", choices: ["Loud", "Quiet", "Noisy", "Scream"], answer: 1 },
    { id: "G1-SCI-72", grade: 1, subject: "Science", topic: "Light/Sound", question: "Which part of a guitar makes the sound?", choices: ["The handle", "The strings", "The pick", "The case"], answer: 1 },
    { id: "G1-SCI-73", grade: 1, subject: "Science", topic: "Light/Sound", question: "Light travels in a...?", choices: ["Circle", "Straight line", "Zig-zag", "Square"], answer: 1 },
    { id: "G1-SCI-74", grade: 1, subject: "Science", topic: "Light/Sound", question: "What happens when light is completely blocked?", choices: ["Total darkness", "A rainbow", "A reflection", "Heat"], answer: 0 },
    { id: "G1-SCI-75", grade: 1, subject: "Science", topic: "Light/Sound", question: "Which of these makes its own light?", choices: ["The Moon", "A Firefly", "A Mirror", "An Eye"], answer: 1 },

    // --- TOPIC 4: PROPERTIES OF MATTER (25 Questions) ---
    { id: "G1-SCI-76", grade: 1, subject: "Science", topic: "Matter", question: "Which state of matter is a rock?", choices: ["Liquid", "Solid", "Gas", "Plasma"], answer: 1 },
    { id: "G1-SCI-77", grade: 1, subject: "Science", topic: "Matter", question: "What happens to liquid water when it gets very cold?", choices: ["Turns to gas", "Turns to solid ice", "Disappears", "Boils"], answer: 1 },
    { id: "G1-SCI-78", grade: 1, subject: "Science", topic: "Matter", question: "Which of these is a liquid?", choices: ["Milk", "A Cookie", "The Table", "A Pencil"], answer: 0 },
    { id: "G1-SCI-79", grade: 1, subject: "Science", topic: "Matter", question: "Air is an example of a...?", choices: ["Solid", "Liquid", "Gas", "Metal"], answer: 2 },
    { id: "G1-SCI-80", grade: 1, subject: "Science", topic: "Matter", question: "Which material is flexible (easy to bend)?", choices: ["A Glass Bottle", "A Rubber Band", "A Metal Nail", "A Brick"], answer: 1 },
    { id: "G1-SCI-81", grade: 1, subject: "Science", topic: "Matter", question: "Which property describes how something feels?", choices: ["Color", "Texture", "Weight", "Height"], answer: 1 },
    { id: "G1-SCI-82", grade: 1, subject: "Science", topic: "Matter", question: "Which tool measures how much matter is in an object?", choices: ["Ruler", "Balance Scale", "Thermometer", "Clock"], answer: 1 },
    { id: "G1-SCI-83", grade: 1, subject: "Science", topic: "Matter", question: "Which item will float in water?", choices: ["A Heavy Rock", "A Metal Key", "A Plastic Toy Boat", "A Glass Marble"], answer: 2 },
    { id: "G1-SCI-84", grade: 1, subject: "Science", topic: "Matter", question: "What do you call it when a solid turns into a liquid?", choices: ["Freezing", "Melting", "Boiling", "Growing"], answer: 1 },
    { id: "G1-SCI-85", grade: 1, subject: "Science", topic: "Matter", question: "Which of these is magnetic?", choices: ["Paper", "Wood", "A Steel Paperclip", "Plastic"], answer: 2 },
    { id: "G1-SCI-86", grade: 1, subject: "Science", topic: "Matter", question: "What is the texture of sandpaper?", choices: ["Smooth", "Bumpy/Rough", "Soft", "Wet"], answer: 1 },
    { id: "G1-SCI-87", grade: 1, subject: "Science", topic: "Matter", question: "What happens when you heat ice?", choices: ["It gets harder", "It melts", "It turns to wood", "It freezes"], answer: 1 },
    { id: "G1-SCI-88", grade: 1, subject: "Science", topic: "Matter", question: "Which sense do you use to tell if something is sweet?", choices: ["Sight", "Hearing", "Taste", "Smell"], answer: 2 },
    { id: "G1-SCI-89", grade: 1, subject: "Science", topic: "Matter", question: "Which is a natural material from the Earth?", choices: ["Plastic", "Glass", "Wood", "Nylon"], answer: 2 },
    { id: "G1-SCI-90", grade: 1, subject: "Science", topic: "Matter", question: "What state of matter is the steam from a kettle?", choices: ["Solid", "Liquid", "Gas", "Solid"], answer: 2 },
    { id: "G1-SCI-91", grade: 1, subject: "Science", topic: "Matter", question: "Which of these is transparent?", choices: ["Clear Water", "A Wood Box", "A Black Shirt", "A Stone"], answer: 0 },
    { id: "G1-SCI-92", grade: 1, subject: "Science", topic: "Matter", question: "What does 'mass' mean?", choices: ["How tall something is", "How much space it takes", "How much matter is in it", "The color of an object"], answer: 2 },
    { id: "G1-SCI-93", grade: 1, subject: "Science", topic: "Matter", question: "Which of these would be attracted to a magnet?", choices: ["A gold ring", "An iron nail", "A copper penny", "A silver spoon"], answer: 1 },
    { id: "G1-SCI-94", grade: 1, subject: "Science", topic: "Matter", question: "Which material is best for keeping you warm?", choices: ["Wool", "Steel", "Glass", "Water"], answer: 0 },
    { id: "G1-SCI-95", grade: 1, subject: "Science", topic: "Matter", question: "Which of these is a property of a ball?", choices: ["Square", "Round", "Flat", "Sharp"], answer: 1 },
    { id: "G1-SCI-96", grade: 1, subject: "Science", topic: "Matter", question: "What happens to juice if you put it in the freezer?", choices: ["It turns to gas", "It turns to a solid", "It boils", "It disappears"], answer: 1 },
    { id: "G1-SCI-97", grade: 1, subject: "Science", topic: "Matter", question: "What is a characteristic of a gas?", choices: ["It has a fixed shape", "It flows to take the shape of a container", "It spreads out to fill any space", "You can always see it"], answer: 2 },
    { id: "G1-SCI-98", grade: 1, subject: "Science", topic: "Matter", question: "Which material is waterproof?", choices: ["Paper", "Sponge", "Plastic Umbrella", "Cotton Shirt"], answer: 2 },
    { id: "G1-SCI-99", grade: 1, subject: "Science", topic: "Matter", question: "Which solid is soft?", choices: ["A Brick", "A Rock", "A Pillow", "A Table"], answer: 2 },
    { id: "G1-SCI-100", grade: 1, subject: "Science", topic: "Matter", question: "What do we call the stuff everything is made of?", choices: ["Matter", "Magic", "Empty Space", "Air Only"], answer: 0 }
];

module.exports = G1_SCIENCE_COMPLETE;
