const G1_SOCIAL_STUDIES_COMPLETE = [
    // --- TOPIC 1: COMMUNITY HELPERS & JOBS (25 Questions) ---
    { id: "G1-SS-01", grade: 1, subject: "Social Studies", topic: "Community", question: "Who helps people stay healthy and feel better?", choices: ["Chef", "Doctor", "Pilot", "Artist"], answer: 1 },
    { id: "G1-SS-02", grade: 1, subject: "Social Studies", topic: "Community", question: "Who uses a hose and a truck to put out fires?", choices: ["Police Officer", "Mail Carrier", "Firefighter", "Baker"], answer: 2 },
    { id: "G1-SS-03", grade: 1, subject: "Social Studies", topic: "Community", question: "Which helper delivers letters and packages?", choices: ["Librarian", "Mail Carrier", "Farmer", "Dentist"], answer: 1 },
    { id: "G1-SS-04", grade: 1, subject: "Social Studies", topic: "Community", question: "Who teaches students at school?", choices: ["Farmer", "Teacher", "Doctor", "Coach"], answer: 1 },
    { id: "G1-SS-05", grade: 1, subject: "Social Studies", topic: "Community", question: "Which worker grows food and raises animals?", choices: ["Scientist", "Farmer", "Cashier", "Bus Driver"], answer: 1 },
    { id: "G1-SS-06", grade: 1, subject: "Social Studies", topic: "Community", question: "Who keeps us safe and enforces the law?", choices: ["Lifeguard", "Police Officer", "Astronaut", "Clown"], answer: 1 },
    { id: "G1-SS-07", grade: 1, subject: "Social Studies", topic: "Community", question: "Where do you go to borrow books for free?", choices: ["Grocery Store", "Bank", "Library", "Post Office"], answer: 2 },
    { id: "G1-SS-08", grade: 1, subject: "Social Studies", topic: "Community", question: "Who helps keep our teeth clean and healthy?", choices: ["Barber", "Dentist", "Vet", "Painter"], answer: 1 },
    { id: "G1-SS-09", grade: 1, subject: "Social Studies", topic: "Community", question: "A 'Consumer' is someone who:", choices: ["Sells goods", "Buys goods", "Makes goods", "Throws goods away"], answer: 1 },
    { id: "G1-SS-10", grade: 1, subject: "Social Studies", topic: "Community", question: "What do we call a job that helps other people?", choices: ["A Hobby", "A Service", "A Game", "A Trade"], answer: 1 },
    { id: "G1-SS-11", grade: 1, subject: "Social Studies", topic: "Community", question: "Who helps animals when they are sick?", choices: ["Doctor", "Vet", "Zookeeper", "Farmer"], answer: 1 },
    { id: "G1-SS-12", grade: 1, subject: "Social Studies", topic: "Community", question: "Which helper cooks food in a restaurant?", choices: ["Server", "Chef", "Manager", "Owner"], answer: 1 },
    { id: "G1-SS-13", grade: 1, subject: "Social Studies", topic: "Community", question: "Who flies airplanes to take people to new places?", choices: ["Driver", "Pilot", "Captain", "Engineer"], answer: 1 },
    { id: "G1-SS-14", grade: 1, subject: "Social Studies", topic: "Community", question: "What is 'Income'?", choices: ["Money you spend", "Money you earn for working", "A type of tax", "A place to live"], answer: 1 },
    { id: "G1-SS-15", grade: 1, subject: "Social Studies", topic: "Community", question: "A 'Producer' is someone who:", choices: ["Buys things", "Makes or grows things", "Eats food", "Watches TV"], answer: 1 },
    { id: "G1-SS-16", grade: 1, subject: "Social Studies", topic: "Community", question: "Where does the Mayor work?", choices: ["Police Station", "City Hall", "Fire Station", "Hospital"], answer: 1 },
    { id: "G1-SS-17", grade: 1, subject: "Social Studies", topic: "Community", question: "Who builds houses and buildings?", choices: ["Construction Worker", "Artist", "Author", "Chef"], answer: 0 },
    { id: "G1-SS-18", grade: 1, subject: "Social Studies", topic: "Community", question: "What do people use to buy things they need?", choices: ["Toys", "Money", "Leaves", "Sticks"], answer: 1 },
    { id: "G1-SS-19", grade: 1, subject: "Social Studies", topic: "Community", question: "Which person helps people find books in a library?", choices: ["Principal", "Librarian", "Secretary", "Janitor"], answer: 1 },
    { id: "G1-SS-20", grade: 1, subject: "Social Studies", topic: "Community", question: "What is a 'Want'?", choices: ["Something you must have to live", "Something you would like to have", "Air", "Water"], answer: 1 },
    { id: "G1-SS-21", grade: 1, subject: "Social Studies", topic: "Community", question: "What is a 'Need'?", choices: ["A Video Game", "Food and Shelter", "Candy", "A Bicycle"], answer: 1 },
    { id: "G1-SS-22", grade: 1, subject: "Social Studies", topic: "Community", question: "Who helps passengers stay safe on a school bus?", choices: ["Pilot", "Bus Driver", "Mechanic", "Sailor"], answer: 1 },
    { id: "G1-SS-23", grade: 1, subject: "Social Studies", topic: "Community", question: "Which helper cleans and fixes our school building?", choices: ["Teacher", "Janitor", "Principal", "Nurse"], answer: 1 },
    { id: "G1-SS-24", grade: 1, subject: "Social Studies", topic: "Community", question: "Who is the leader of a school?", choices: ["Teacher", "Mayor", "Principal", "President"], answer: 2 },
    { id: "G1-SS-25", grade: 1, subject: "Social Studies", topic: "Community", question: "Saving money means:", choices: ["Spending it all", "Putting it away to use later", "Losing it", "Giving it all away"], answer: 1 },

    // --- TOPIC 2: GEOGRAPHY & MAPS (25 Questions) ---
    { id: "G1-SS-26", grade: 1, subject: "Social Studies", topic: "Geography", question: "What is a drawing of a place from above?", choices: ["Photo", "Map", "Globe", "Painting"], answer: 1 },
    { id: "G1-SS-27", grade: 1, subject: "Social Studies", topic: "Geography", question: "Which model of the Earth is round like a ball?", choices: ["Map", "Globe", "Poster", "Book"], answer: 1 },
    { id: "G1-SS-28", grade: 1, subject: "Social Studies", topic: "Geography", question: "What part of a map explains what the symbols mean?", choices: ["Compass Rose", "Map Key", "Title", "Scale"], answer: 1 },
    { id: "G1-SS-29", grade: 1, subject: "Social Studies", topic: "Geography", question: "Which direction is at the top of a map?", choices: ["South", "East", "North", "West"], answer: 2 },
    { id: "G1-SS-30", grade: 1, subject: "Social Studies", topic: "Geography", question: "What color usually represents water on a map?", choices: ["Green", "Blue", "Brown", "Yellow"], answer: 1 },
    { id: "G1-SS-31", grade: 1, subject: "Social Studies", topic: "Geography", question: "A large body of land is called a:", choices: ["Ocean", "Continent", "River", "Island"], answer: 1 },
    { id: "G1-SS-32", grade: 1, subject: "Social Studies", topic: "Geography", question: "A large body of salt water is called a:", choices: ["Lake", "Pond", "Ocean", "River"], answer: 2 },
    { id: "G1-SS-33", grade: 1, subject: "Social Studies", topic: "Geography", question: "Which direction is at the bottom of a map?", choices: ["North", "South", "East", "West"], answer: 1 },
    { id: "G1-SS-34", grade: 1, subject: "Social Studies", topic: "Geography", question: "What symbol on a map shows directions (N, S, E, W)?", choices: ["Map Key", "Title", "Compass Rose", "Border"], answer: 2 },
    { id: "G1-SS-35", grade: 1, subject: "Social Studies", topic: "Geography", question: "What do we call very high land with steep sides?", choices: ["Valley", "Plain", "Mountain", "River"], answer: 2 },
    { id: "G1-SS-36", grade: 1, subject: "Social Studies", topic: "Geography", question: "Low land between mountains is called a:", choices: ["Peak", "Plateau", "Valley", "Hill"], answer: 2 },
    { id: "G1-SS-37", grade: 1, subject: "Social Studies", topic: "Geography", question: "What is land that is completely surrounded by water?", choices: ["Lake", "Island", "Peninsula", "Desert"], answer: 1 },
    { id: "G1-SS-38", grade: 1, subject: "Social Studies", topic: "Geography", question: "What is your address?", choices: ["Your name", "The place where you live", "Your favorite color", "Your phone number"], answer: 1 },
    { id: "G1-SS-39", grade: 1, subject: "Social Studies", topic: "Geography", question: "Which of these is a human-made feature?", choices: ["River", "Mountain", "Bridge", "Forest"], answer: 2 },
    { id: "G1-SS-40", grade: 1, subject: "Social Studies", topic: "Geography", question: "Where is the North Pole located on a globe?", choices: ["The bottom", "The middle", "The top", "The side"], answer: 2 },
    { id: "G1-SS-41", grade: 1, subject: "Social Studies", topic: "Geography", question: "What color usually represents land on a map?", choices: ["Blue", "Green or Brown", "Purple", "White"], answer: 1 },
    { id: "G1-SS-42", grade: 1, subject: "Social Studies", topic: "Geography", question: "Which ocean is on the East coast of the United States?", choices: ["Pacific", "Arctic", "Atlantic", "Indian"], answer: 2 },
    { id: "G1-SS-43", grade: 1, subject: "Social Studies", topic: "Geography", question: "Which ocean is on the West coast of the United States?", choices: ["Atlantic", "Pacific", "Indian", "Arctic"], answer: 1 },
    { id: "G1-SS-44", grade: 1, subject: "Social Studies", topic: "Geography", question: "How many continents are there on Earth?", choices: ["1", "5", "7", "10"], answer: 2 },
    { id: "G1-SS-45", grade: 1, subject: "Social Studies", topic: "Geography", question: "Which direction does the sun rise in?", choices: ["West", "North", "South", "East"], answer: 3 },
    { id: "G1-SS-46", grade: 1, subject: "Social Studies", topic: "Geography", question: "What is a flow of water that goes into an ocean?", choices: ["Pond", "Lake", "River", "Puddle"], answer: 2 },
    { id: "G1-SS-47", grade: 1, subject: "Social Studies", topic: "Geography", question: "What do we call a dry place with very little rain?", choices: ["Rainforest", "Desert", "Swamp", "Ocean"], answer: 1 },
    { id: "G1-SS-48", grade: 1, subject: "Social Studies", topic: "Geography", question: "Which of these is a natural feature?", choices: ["Road", "River", "House", "School"], answer: 1 },
    { id: "G1-SS-49", grade: 1, subject: "Social Studies", topic: "Geography", question: "What continent do we live on?", choices: ["Africa", "Europe", "North America", "Asia"], answer: 2 },
    { id: "G1-SS-50", grade: 1, subject: "Social Studies", topic: "Geography", question: "A globe is more accurate than a flat map because the Earth is round.", choices: ["True", "False", "Sometimes", "Never"], answer: 0 },

    // --- TOPIC 3: CITIZENSHIP & US SYMBOLS (25 Questions) ---
    { id: "G1-SS-51", grade: 1, subject: "Social Studies", topic: "Civics", question: "What is the name of the US flag?", choices: ["The Stars and Stripes", "The Big Flag", "The Blue Square", "The Red Banner"], answer: 0 },
    { id: "G1-SS-52", grade: 1, subject: "Social Studies", topic: "Civics", question: "How many stars are on the US flag today?", choices: ["13", "25", "50", "100"], answer: 2 },
    { id: "G1-SS-53", grade: 1, subject: "Social Studies", topic: "Civics", question: "What do the 13 stripes on the flag represent?", choices: ["13 states", "13 original colonies", "13 presidents", "13 years"], answer: 1 },
    { id: "G1-SS-54", grade: 1, subject: "Social Studies", topic: "Civics", question: "Which bird is the national symbol of the USA?", choices: ["Blue Jay", "Bald Eagle", "Robin", "Owl"], answer: 1 },
    { id: "G1-SS-55", grade: 1, subject: "Social Studies", topic: "Civics", question: "Who is the leader of the United States?", choices: ["Mayor", "Governor", "President", "King"], answer: 2 },
    { id: "G1-SS-56", grade: 1, subject: "Social Studies", topic: "Civics", question: "Where does the President live and work?", choices: ["The Capitol", "The White House", "The Pentagon", "The Library"], answer: 1 },
    { id: "G1-SS-57", grade: 1, subject: "Social Studies", topic: "Civics", question: "What is the capital city of the United States?", choices: ["New York", "Washington, D.C.", "Los Angeles", "Chicago"], answer: 1 },
    { id: "G1-SS-58", grade: 1, subject: "Social Studies", topic: "Civics", question: "The Statue of Liberty was a gift from which country?", choices: ["England", "Mexico", "France", "Canada"], answer: 2 },
    { id: "G1-SS-59", grade: 1, subject: "Social Studies", topic: "Civics", question: "A rule that everyone must follow is called a:", choices: ["Wish", "Law", "Story", "Suggestion"], answer: 1 },
    { id: "G1-SS-60", grade: 1, subject: "Social Studies", topic: "Civics", question: "Being a 'Good Citizen' means:", choices: ["Being mean", "Helping others and following rules", "Taking toys", "Shouting"], answer: 1 },
    { id: "G1-SS-61", grade: 1, subject: "Social Studies", topic: "Civics", question: "What promise do students say to the flag?", choices: ["A Song", "The Pledge of Allegiance", "A Story", "The Alphabet"], answer: 1 },
    { id: "G1-SS-62", grade: 1, subject: "Social Studies", topic: "Civics", question: "What symbol in Philadelphia has a big crack in it?", choices: ["The Liberty Bell", "The White House", "The Flag", "A Statue"], answer: 0 },
    { id: "G1-SS-63", grade: 1, subject: "Social Studies", topic: "Civics", question: "What colors are on the US flag?", choices: ["Red, White, and Green", "Blue, Yellow, and Red", "Red, White, and Blue", "Black and White"], answer: 2 },
    { id: "G1-SS-64", grade: 1, subject: "Social Studies", topic: "Civics", question: "What holiday do we celebrate on July 4th?", choices: ["Christmas", "Independence Day", "Thanksgiving", "Easter"], answer: 1 },
    { id: "G1-SS-65", grade: 1, subject: "Social Studies", topic: "Civics", question: "Who was the first President of the United States?", choices: ["Abraham Lincoln", "George Washington", "Barack Obama", "John Adams"], answer: 1 },
    { id: "G1-SS-66", grade: 1, subject: "Social Studies", topic: "Civics", question: "Which president is known for helping end slavery?", choices: ["George Washington", "Abraham Lincoln", "Thomas Jefferson", "Teddy Roosevelt"], answer: 1 },
    { id: "G1-SS-67", grade: 1, subject: "Social Studies", topic: "Civics", question: "What is the national anthem of the USA?", choices: ["Happy Birthday", "The Star-Spangled Banner", "Jingle Bells", "Twinkle Twinkle"], answer: 1 },
    { id: "G1-SS-68", grade: 1, subject: "Social Studies", topic: "Civics", question: "Where is the Statue of Liberty located?", choices: ["Texas", "New York", "Florida", "California"], answer: 1 },
    { id: "G1-SS-69", grade: 1, subject: "Social Studies", topic: "Civics", question: "What is a 'right'?", choices: ["A rule you must follow", "A freedom you have", "A type of food", "A job"], answer: 1 },
    { id: "G1-SS-70", grade: 1, subject: "Social Studies", topic: "Civics", question: "What is a 'responsibility'?", choices: ["Something you should do", "A present", "A vacation", "A game"], answer: 0 },
    { id: "G1-SS-71", grade: 1, subject: "Social Studies", topic: "Civics", question: "Which holiday honors people who worked for equal rights?", choices: ["Halloween", "Martin Luther King Jr. Day", "Valentine's Day", "St. Patrick's Day"], answer: 1 },
    { id: "G1-SS-72", grade: 1, subject: "Social Studies", topic: "Civics", question: "Which holiday honors people who served in the military?", choices: ["Veterans Day", "Earth Day", "New Year's Day", "Arbor Day"], answer: 0 },
    { id: "G1-SS-73", grade: 1, subject: "Social Studies", topic: "Civics", question: "How often do we elect a President?", choices: ["Every year", "Every 2 years", "Every 4 years", "Every 10 years"], answer: 2 },
    { id: "G1-SS-74", grade: 1, subject: "Social Studies", topic: "Civics", question: "The Liberty Bell is a symbol of:", choices: ["Money", "Freedom", "Food", "School"], answer: 1 },
    { id: "G1-SS-75", grade: 1, subject: "Social Studies", topic: "Civics", question: "Who was a seamstress who legend says made the first flag?", choices: ["Rosa Parks", "Betsy Ross", "Martha Washington", "Abigail Adams"], answer: 1 },

    // --- TOPIC 4: HISTORY & CULTURE (25 Questions) ---
    { id: "G1-SS-76", grade: 1, subject: "Social Studies", topic: "History", question: "What do we call the time that has already happened?", choices: ["The Future", "The Past", "The Present", "Tomorrow"], answer: 1 },
    { id: "G1-SS-77", grade: 1, subject: "Social Studies", topic: "History", question: "What do we call the time that is happening right now?", choices: ["The Past", "The Future", "The Present", "Yesterday"], answer: 2 },
    { id: "G1-SS-78", grade: 1, subject: "Social Studies", topic: "History", question: "What do we call the time that will happen later?", choices: ["The Past", "The Future", "The Present", "Before"], answer: 1 },
    { id: "G1-SS-79", grade: 1, subject: "Social Studies", topic: "History", question: "A 'Timeline' is used to show:", choices: ["The weather", "Events in the order they happened", "A map of the world", "How much things cost"], answer: 1 },
    { id: "G1-SS-80", grade: 1, subject: "Social Studies", topic: "History", question: "Who were the first people to live in America?", choices: ["Pilgrims", "Native Americans", "Cowboys", "Explorers"], answer: 1 },
    { id: "G1-SS-81", grade: 1, subject: "Social Studies", topic: "History", question: "What was a main way people traveled in the past before cars?", choices: ["Rocket", "Horse and Wagon", "Jet", "Subway"], answer: 1 },
    { id: "G1-SS-82", grade: 1, subject: "Social Studies", topic: "History", question: "Which holiday started with a feast between Pilgrims and Wampanoags?", choices: ["Christmas", "Thanksgiving", "Labor Day", "Memorial Day"], answer: 1 },
    { id: "G1-SS-83", grade: 1, subject: "Social Studies", topic: "History", question: "What is a 'Primary Source'?", choices: ["A story someone made up", "A real item or letter from the past", "A brand new book", "A movie about the future"], answer: 1 },
    { id: "G1-SS-84", grade: 1, subject: "Social Studies", topic: "History", question: "Who was a woman who escaped slavery and helped others to freedom?", choices: ["Harriet Tubman", "Queen Elizabeth", "Betsy Ross", "Susan B. Anthony"], answer: 0 },
    { id: "G1-SS-85", grade: 1, subject: "Social Studies", topic: "History", question: "How did people communicate across long distances before phones?", choices: ["Email", "Letters by mail/horseback", "Video chat", "Texting"], answer: 1 },
    { id: "G1-SS-86", grade: 1, subject: "Social Studies", topic: "History", question: "Which inventors were the first to fly an airplane?", choices: ["The Wright Brothers", "The Smith Brothers", "The Ford Brothers", "The Edison Brothers"], answer: 0 },
    { id: "G1-SS-87", grade: 1, subject: "Social Studies", topic: "History", question: "What is a 'tradition'?", choices: ["A new toy", "A special way of doing things that families repeat", "A math problem", "A type of vegetable"], answer: 1 },
    { id: "G1-SS-88", grade: 1, subject: "Social Studies", topic: "History", question: "The study of the past is called:", choices: ["Science", "History", "Math", "Reading"], answer: 1 },
    { id: "G1-SS-89", grade: 1, subject: "Social Studies", topic: "History", question: "Long ago, most people lived in houses made of:", choices: ["Plastic", "Log/Wood or Sod", "Steel", "Glass"], answer: 1 },
    { id: "G1-SS-90", grade: 1, subject: "Social Studies", topic: "History", question: "What do we use to see dates and months?", choices: ["Clock", "Calendar", "Ruler", "Compass"], answer: 1 },
    { id: "G1-SS-91", grade: 1, subject: "Social Studies", topic: "History", question: "How do things change over time?", choices: ["They always stay the same", "They become newer or different", "They disappear", "They only get smaller"], answer: 1 },
    { id: "G1-SS-92", grade: 1, subject: "Social Studies", topic: "History", question: "Who was a civil rights leader who gave the 'I Have a Dream' speech?", choices: ["George Washington", "Martin Luther King Jr.", "Benjamin Franklin", "Thomas Edison"], answer: 1 },
    { id: "G1-SS-93", grade: 1, subject: "Social Studies", topic: "History", question: "What is an 'Artifact'?", choices: ["A new toy", "An old object made by people", "A type of plant", "A star"], answer: 1 },
    { id: "G1-SS-94", grade: 1, subject: "Social Studies", topic: "History", question: "Long ago, children often went to school in a:", choices: ["Large high school", "One-room schoolhouse", "Computer lab", "University"], answer: 1 },
    { id: "G1-SS-95", grade: 1, subject: "Social Studies", topic: "History", question: "What is a 'Biography'?", choices: ["A book about a person's life", "A book of maps", "A science experiment", "A fairy tale"], answer: 0 },
    { id: "G1-SS-96", grade: 1, subject: "Social Studies", topic: "History", question: "Which inventor created the light bulb?", choices: ["Alexander Graham Bell", "Thomas Edison", "Henry Ford", "Eli Whitney"], answer: 1 },
    { id: "G1-SS-97", grade: 1, subject: "Social Studies", topic: "History", question: "A group of people related to each other is a:", choices: ["Team", "Family", "Class", "Club"], answer: 1 },
    { id: "G1-SS-98", grade: 1, subject: "Social Studies", topic: "History", question: "How did people keep food cold before refrigerators?", choices: ["Microwaves", "Ice boxes", "Leaving it on the table", "Ovens"], answer: 1 },
    { id: "G1-SS-99", grade: 1, subject: "Social Studies", topic: "History", question: "Who was a woman who refused to give up her seat on a bus to fight for fair rules?", choices: ["Rosa Parks", "Sally Ride", "Helen Keller", "Amelia Earhart"], answer: 0 },
    { id: "G1-SS-100", grade: 1, subject: "Social Studies", topic: "History", question: "History helps us understand how the world has changed.", choices: ["True", "False", "Maybe", "Only for adults"], answer: 0 }
];

module.exports = G1_SOCIAL_STUDIES_COMPLETE;
