const G2_ELA_COMPLETE = [
    // --- TOPIC 1: PHONICS & WORD RECOGNITION (25 Questions) ---
    { id: "G2-ELA-01", grade: 2, subject: "English", topic: "Phonics", question: "Which word has a 'long a' sound?", choices: ["Cat", "Late", "Bat", "Fast"], answer: 1 },
    { id: "G2-ELA-02", grade: 2, subject: "English", topic: "Phonics", question: "What is the vowel team in the word 'Team'?", choices: ["ea", "am", "te", "em"], answer: 0 },
    { id: "G2-ELA-03", grade: 2, subject: "English", topic: "Phonics", question: "Which word rhymes with 'Light'?", choices: ["Look", "Late", "Bright", "Bit"], answer: 2 },
    { id: "G2-ELA-04", grade: 2, subject: "English", topic: "Phonics", question: "Which word has two syllables?", choices: ["Dog", "Basket", "Sun", "Jump"], answer: 1 },
    { id: "G2-ELA-05", grade: 2, subject: "English", topic: "Phonics", question: "What sound does 'ph' make in 'Phone'?", choices: ["p", "h", "f", "s"], answer: 2 },
    { id: "G2-ELA-06", grade: 2, subject: "English", topic: "Phonics", question: "Which word is spelled correctly?", choices: ["Wuz", "Was", "Waz", "Whas"], answer: 1 },
    { id: "G2-ELA-07", grade: 2, subject: "English", topic: "Phonics", question: "Find the word with a short 'i' sound.", choices: ["Bike", "Sit", "Like", "Pie"], answer: 1 },
    { id: "G2-ELA-08", grade: 2, subject: "English", topic: "Phonics", question: "Which prefix means 'do again'?", choices: ["Un-", "Re-", "Dis-", "Pre-"], answer: 1 },
    { id: "G2-ELA-09", grade: 2, subject: "English", topic: "Phonics", question: "Which word has a silent 'k'?", choices: ["Kite", "Kick", "Knee", "Keep"], answer: 2 },
    { id: "G2-ELA-10", grade: 2, subject: "English", topic: "Phonics", question: "How many syllables are in 'Elephant'?", choices: ["1", "2", "3", "4"], answer: 2 },
    { id: "G2-ELA-11", grade: 2, subject: "English", topic: "Phonics", question: "Which word ends with a suffix?", choices: ["Helpful", "Help", "The", "Cat"], answer: 0 },
    { id: "G2-ELA-12", grade: 2, subject: "English", topic: "Phonics", question: "What is the base word of 'Running'?", choices: ["Runn", "Run", "Running", "Ran"], answer: 1 },
    { id: "G2-ELA-13", grade: 2, subject: "English", topic: "Phonics", question: "Which word has the 'ch' sound?", choices: ["Ship", "Chip", "Skip", "Trip"], answer: 1 },
    { id: "G2-ELA-14", grade: 2, subject: "English", topic: "Phonics", question: "Which word has a long 'o' sound?", choices: ["Hot", "Top", "Hope", "Fox"], answer: 2 },
    { id: "G2-ELA-15", grade: 2, subject: "English", topic: "Phonics", question: "The ending '-ed' usually means the action happened in the...", choices: ["Future", "Past", "Present", "Morning"], answer: 1 },
    { id: "G2-ELA-16", grade: 2, subject: "English", topic: "Phonics", question: "Which word is a compound word?", choices: ["Happy", "Bedroom", "Table", "School"], answer: 1 },
    { id: "G2-ELA-17", grade: 2, subject: "English", topic: "Phonics", question: "What does 'Un-' mean in 'Unhappy'?", choices: ["Very", "Not", "Double", "Again"], answer: 1 },
    { id: "G2-ELA-18", grade: 2, subject: "English", topic: "Phonics", question: "Which word rhymes with 'Blue'?", choices: ["Tree", "Shoe", "Snow", "Low"], answer: 1 },
    { id: "G2-ELA-19", grade: 2, subject: "English", topic: "Phonics", question: "Choose the correct spelling.", choices: ["Becuz", "Because", "Becuase", "Beclaws"], answer: 1 },
    { id: "G2-ELA-20", grade: 2, subject: "English", topic: "Phonics", question: "Which word has a silent 'e'?", choices: ["Cub", "Cube", "Cut", "Tub"], answer: 1 },
    { id: "G2-ELA-21", grade: 2, subject: "English", topic: "Phonics", question: "What stands for 'Do not'?", choices: ["Don't", "Dont", "Do'nt", "Did'nt"], answer: 0 },
    { id: "G2-ELA-22", grade: 2, subject: "English", topic: "Phonics", question: "What is the plural of 'Baby'?", choices: ["Babys", "Babies", "Baby's", "Babeis"], answer: 1 },
    { id: "G2-ELA-23", grade: 2, subject: "English", topic: "Phonics", question: "Which word has the 'sh' sound?", choices: ["Chair", "Wish", "Watch", "Patch"], answer: 1 },
    { id: "G2-ELA-24", grade: 2, subject: "English", topic: "Phonics", question: "Which word has a hard 'g' sound (like Go)?", choices: ["Gem", "Giraffe", "Garden", "Giant"], answer: 2 },
    { id: "G2-ELA-25", grade: 2, subject: "English", topic: "Phonics", question: "Which word is an abbreviation for 'Mister'?", choices: ["Ms.", "Dr.", "Mr.", "Mrs."], answer: 2 },

    // --- TOPIC 2: GRAMMAR (NOUNS, VERBS, ADJECTIVES) (25 Questions) ---
    { id: "G2-ELA-26", grade: 2, subject: "English", topic: "Grammar", question: "Which word is a proper noun?", choices: ["City", "Chicago", "Town", "Village"], answer: 1 },
    { id: "G2-ELA-27", grade: 2, subject: "English", topic: "Grammar", question: "Identify the adjective: 'The red car is fast.'", choices: ["Red", "Car", "Is", "The"], answer: 0 },
    { id: "G2-ELA-28", grade: 2, subject: "English", topic: "Grammar", question: "What is the past tense of 'Run'?", choices: ["Runned", "Ran", "Running", "Rans"], answer: 1 },
    { id: "G2-ELA-29", grade: 2, subject: "English", topic: "Grammar", question: "Which word is a pronoun?", choices: ["Sally", "She", "Girl", "Sister"], answer: 1 },
    { id: "G2-ELA-30", grade: 2, subject: "English", topic: "Grammar", question: "A verb shows:", choices: ["A person", "A place", "An action", "A feeling only"], answer: 2 },
    { id: "G2-ELA-31", grade: 2, subject: "English", topic: "Grammar", question: "What is an adverb?", choices: ["A word that names a thing", "A word that describes a verb (how something is done)", "A word that connects sentences", "A name"], answer: 1 },
    { id: "G2-ELA-32", grade: 2, subject: "English", topic: "Grammar", question: "Choose the adverb: 'She sang loudly.'", choices: ["She", "Sang", "Loudly", "Song"], answer: 2 },
    { id: "G2-ELA-33", grade: 2, subject: "English", topic: "Grammar", question: "Which is a plural noun?", choices: ["Mice", "Mouse", "Rat", "Cat"], answer: 0 },
    { id: "G2-ELA-34", grade: 2, subject: "English", topic: "Grammar", question: "What is the correct plural of 'Tooth'?", choices: ["Tooths", "Teeth", "Toothes", "Teeths"], answer: 1 },
    { id: "G2-ELA-35", grade: 2, subject: "English", topic: "Grammar", question: "Which word is a conjunction?", choices: ["And", "House", "Run", "Blue"], answer: 0 },
    { id: "G2-ELA-36", grade: 2, subject: "English", topic: "Grammar", question: "Choose the correct verb: 'They ___ playing.'", choices: ["Is", "Am", "Are", "Be"], answer: 2 },
    { id: "G2-ELA-37", grade: 2, subject: "English", topic: "Grammar", question: "Which sentence is a question?", choices: ["I like pizza.", "Do you like pizza?", "Eat your pizza!", "Pizza is good."], answer: 1 },
    { id: "G2-ELA-38", grade: 2, subject: "English", topic: "Grammar", question: "What is a collective noun?", choices: ["A group (like 'Team' or 'Herd')", "A person's name", "An action", "A describing word"], answer: 0 },
    { id: "G2-ELA-39", grade: 2, subject: "English", topic: "Grammar", question: "What is the opposite of 'Strong'?", choices: ["Big", "Weak", "Tall", "Fast"], answer: 1 },
    { id: "G2-ELA-40", grade: 2, subject: "English", topic: "Grammar", question: "Which word relates to 'Time'?", choices: ["Soon", "Table", "Red", "Loud"], answer: 0 },
    { id: "G2-ELA-41", grade: 2, subject: "English", topic: "Grammar", question: "What is a synonym for 'Angry'?", choices: ["Happy", "Mad", "Sad", "Tired"], answer: 1 },
    { id: "G2-ELA-42", grade: 2, subject: "English", topic: "Grammar", question: "Identify the preposition: 'The cat is under the table.'", choices: ["The", "Cat", "Under", "Table"], answer: 2 },
    { id: "G2-ELA-43", grade: 2, subject: "English", topic: "Grammar", question: "Which word is possessive?", choices: ["Boys", "Boy's", "Boies", "Boys's"], answer: 1 },
    { id: "G2-ELA-44", grade: 2, subject: "English", topic: "Grammar", question: "Choose the correct sentence.", choices: ["I seen a dog.", "I saw a dog.", "I seed a dog.", "I see'd a dog."], answer: 1 },
    { id: "G2-ELA-45", grade: 2, subject: "English", topic: "Grammar", question: "Which is a command?", choices: ["Sit down.", "Are you sitting?", "I am sitting.", "The chair is soft."], answer: 0 },
    { id: "G2-ELA-46", grade: 2, subject: "English", topic: "Grammar", question: "What type of noun is 'October'?", choices: ["Common noun", "Proper noun", "Verb", "Adjective"], answer: 1 },
    { id: "G2-ELA-47", grade: 2, subject: "English", topic: "Grammar", question: "What is an antonym for 'Fast'?", choices: ["Quick", "Slow", "Rapid", "Speedy"], answer: 1 },
    { id: "G2-ELA-48", grade: 2, subject: "English", topic: "Grammar", question: "Which word describes a place?", choices: ["Here", "Run", "Blue", "Tall"], answer: 0 },
    { id: "G2-ELA-49", grade: 2, subject: "English", topic: "Grammar", question: "Identify the subject: 'The bird flew away.'", choices: ["The bird", "Flew", "Away", "Flew away"], answer: 0 },
    { id: "G2-ELA-50", grade: 2, subject: "English", topic: "Grammar", question: "Which word connects two ideas?", choices: ["But", "Cat", "Jump", "Soft"], answer: 0 },

    // --- TOPIC 3: SENTENCE STRUCTURE & PUNCTUATION (25 Questions) ---
    { id: "G2-ELA-51", grade: 2, subject: "English", topic: "Writing", question: "Every sentence must start with a...", choices: ["Period", "Capital letter", "Verb", "Noun"], answer: 1 },
    { id: "G2-ELA-52", grade: 2, subject: "English", topic: "Writing", question: "Every sentence needs a...", choices: ["Dog", "Color", "Subject and Verb", "Picture"], answer: 2 },
    { id: "G2-ELA-53", grade: 2, subject: "English", topic: "Writing", question: "Which punctuation mark shows excitement?", choices: ["Period", "Comma", "Question Mark", "Exclamation Point"], answer: 3 },
    { id: "G2-ELA-54", grade: 2, subject: "English", topic: "Writing", question: "Where do commas go in a list: 'Apples oranges and bananas'?", choices: ["Apples, oranges, and bananas", "Apples oranges, and bananas", "Apples, oranges and, bananas", "No commas needed"], answer: 0 },
    { id: "G2-ELA-55", grade: 2, subject: "English", topic: "Writing", question: "Which is a complete sentence?", choices: ["The big dog.", "Ran fast.", "The dog ran.", "Blue sky."], answer: 2 },
    { id: "G2-ELA-56", grade: 2, subject: "English", topic: "Writing", question: "What is a 'Run-on' sentence?", choices: ["A sentence that is too short", "Two sentences joined incorrectly", "A sentence about running", "A sentence with no verb"], answer: 1 },
    { id: "G2-ELA-57", grade: 2, subject: "English", topic: "Writing", question: "Which word starts the days of the week?", choices: ["A lower case letter", "A capital letter", "A number", "A symbol"], answer: 1 },
    { id: "G2-ELA-58", grade: 2, subject: "English", topic: "Writing", question: "What is the correct contraction for 'Is not'?", choices: ["Isnt", "Isn't", "Is'nt", "I'snt"], answer: 1 },
    { id: "G2-ELA-59", grade: 2, subject: "English", topic: "Writing", question: "When do you use a comma in a date?", choices: ["Between the month and day", "Between the day and year", "After the year", "Nowhere"], answer: 1 },
    { id: "G2-ELA-60", grade: 2, subject: "English", topic: "Writing", question: "Which title is written correctly?", choices: ["the cat in the hat", "The Cat In The Hat", "The Cat in the Hat", "the Cat In the Hat"], answer: 2 },
    { id: "G2-ELA-61", grade: 2, subject: "English", topic: "Writing", question: "What is an apostrophe used for?", choices: ["To stop a sentence", "To show possession or contractions", "To ask a question", "To list items"], answer: 1 },
    { id: "G2-ELA-62", grade: 2, subject: "English", topic: "Writing", question: "Which is a greeting in a letter?", choices: ["Dear Mom,", "Love,", "Sincerely,", "From,"], answer: 0 },
    { id: "G2-ELA-63", grade: 2, subject: "English", topic: "Writing", question: "Which is a closing in a letter?", choices: ["Dear Sir,", "Sincerely,", "Hello,", "To:"], answer: 1 },
    { id: "G2-ELA-64", grade: 2, subject: "English", topic: "Writing", question: "What is a 'Fragment'?", choices: ["A complete sentence", "An incomplete sentence", "A long story", "A poem"], answer: 1 },
    { id: "G2-ELA-65", grade: 2, subject: "English", topic: "Writing", question: "Correct this sentence: 'me and him went home.'", choices: ["Him and I went home.", "He and I went home.", "Me and he went home.", "Him and me went home."], answer: 1 },
    { id: "G2-ELA-66", grade: 2, subject: "English", topic: "Writing", question: "What punctuation ends a command?", choices: ["Question mark", "Period or Exclamation point", "Comma", "Apostrophe"], answer: 1 },
    { id: "G2-ELA-67", grade: 2, subject: "English", topic: "Writing", question: "Which is the correct possessive form?", choices: ["The dogs bone", "The dog's bone", "The dogs' bone (for one dog)", "The dog bone"], answer: 1 },
    { id: "G2-ELA-68", grade: 2, subject: "English", topic: "Writing", question: "When do you capitalize 'Mom'?", choices: ["Always", "Never", "When used as a name", "Only at the end of a sentence"], answer: 2 },
    { id: "G2-ELA-69", grade: 2, subject: "English", topic: "Writing", question: "Which sentence matches the picture (of a sleeping cat)?", choices: ["The cat is running.", "The cat is sleeping.", "The cat is eating.", "The cat is barking."], answer: 1 },
    { id: "G2-ELA-70", grade: 2, subject: "English", topic: "Writing", question: "What indentation do you use for a new paragraph?", choices: ["None", "Indent the first line", "Indent every line", "Skip a page"], answer: 1 },
    { id: "G2-ELA-71", grade: 2, subject: "English", topic: "Writing", question: "Which is correct?", choices: ["The books title", "The book's title", "The books's title", "The book title's"], answer: 1 },
    { id: "G2-ELA-72", grade: 2, subject: "English", topic: "Writing", question: "What is a 'Compound Sentence'?", choices: ["One short sentence", "Two sentences joined by a conjunction", "A sentence with big words", "A question"], answer: 1 },
    { id: "G2-ELA-73", grade: 2, subject: "English", topic: "Writing", question: "Which word should NOT be capitalized?", choices: ["Monday", "Sarah", "School (unless a specific name)", "Texas"], answer: 2 },
    { id: "G2-ELA-74", grade: 2, subject: "English", topic: "Writing", question: "Which mark separates city and state? (e.g., Dallas, Texas)", choices: ["Period", "Comma", "Dash", "Colon"], answer: 1 },
    { id: "G2-ELA-75", grade: 2, subject: "English", topic: "Writing", question: "Which contraction means 'We are'?", choices: ["Were", "We're", "Where", "Wear"], answer: 1 },

    // --- TOPIC 4: READING COMPREHENSION & LITERARY ELEMENTS (25 Questions) ---
    { id: "G2-ELA-76", grade: 2, subject: "English", topic: "Reading", question: "What is the 'Main Idea'?", choices: ["The first sentence", "The last sentence", "What the story is mostly about", "The title"], answer: 2 },
    { id: "G2-ELA-77", grade: 2, subject: "English", topic: "Reading", question: "Details help support the:", choices: ["Main idea", "Cover", "Page numbers", "Spine"], answer: 0 },
    { id: "G2-ELA-78", grade: 2, subject: "English", topic: "Reading", question: "What is 'Cause and Effect'?", choices: ["The title and author", "Why something happens and what happens", "The beginning and end", "True and False"], answer: 1 },
    { id: "G2-ELA-79", grade: 2, subject: "English", topic: "Reading", question: "The 'Setting' is:", choices: ["Who is in the story", "Where and when the story takes place", "The problem", "The solution"], answer: 1 },
    { id: "G2-ELA-80", grade: 2, subject: "English", topic: "Reading", question: "What is the 'Plot'?", choices: ["The drawings", "The events in the story", "The author's name", "The cover"], answer: 1 },
    { id: "G2-ELA-81", grade: 2, subject: "English", topic: "Reading", question: "Fact or Opinion: 'Ice cream is delicious.'", choices: ["Fact", "Opinion", "Both", "Neither"], answer: 1 },
    { id: "G2-ELA-82", grade: 2, subject: "English", topic: "Reading", question: "Fact or Opinion: 'Dogs have four legs.'", choices: ["Fact", "Opinion", "Both", "Neither"], answer: 0 },
    { id: "G2-ELA-83", grade: 2, subject: "English", topic: "Reading", question: "What does 'Table of Contents' tell you?", choices: ["How to read", "Chapter names and page numbers", "Who wrote the book", "The price"], answer: 1 },
    { id: "G2-ELA-84", grade: 2, subject: "English", topic: "Reading", question: "Who tells the story in a first-person story?", choices: ["An outside narrator", "A character using 'I'", "The reader", "No one"], answer: 1 },
    { id: "G2-ELA-85", grade: 2, subject: "English", topic: "Reading", question: "What is a 'Glossary'?", choices: ["A list of definitions at the back of a book", "The cover", "A funny story", "A map"], answer: 0 },
    { id: "G2-ELA-86", grade: 2, subject: "English", topic: "Reading", question: "A story written about a real person's life is a:", choices: ["Fairy Tale", "Biography", "Fantasy", "Mystery"], answer: 1 },
    { id: "G2-ELA-87", grade: 2, subject: "English", topic: "Reading", question: "What is the 'Moral' of a story?", choices: ["The end", "The lesson learned", "The villain", "The title"], answer: 1 },
    { id: "G2-ELA-88", grade: 2, subject: "English", topic: "Reading", question: "Comparing two things means finding:", choices: ["Differences", "Similarities", "Both similarities and differences", "Nothing"], answer: 2 },
    { id: "G2-ELA-89", grade: 2, subject: "English", topic: "Reading", question: "What helps you find a specific word in the back of a book?", choices: ["Glossary", "Index", "Title Page", "Table of Contents"], answer: 1 },
    { id: "G2-ELA-90", grade: 2, subject: "English", topic: "Reading", question: "What is 'Fiction'?", choices: ["A true story", "A made-up story", "A history book", "A dictionary"], answer: 1 },
    { id: "G2-ELA-91", grade: 2, subject: "English", topic: "Reading", question: "What is 'Non-Fiction'?", choices: ["A fairy tale", "A book of facts/real information", "A comic book", "A poem"], answer: 1 },
    { id: "G2-ELA-92", grade: 2, subject: "English", topic: "Reading", question: "Sequencing means putting events in:", choices: ["Order", "Reverse", "Random", "Pairs"], answer: 0 },
    { id: "G2-ELA-93", grade: 2, subject: "English", topic: "Reading", question: "Using clues to make a guess is called:", choices: ["Sleeping", "Inferencing", "Drawing", "Copying"], answer: 1 },
    { id: "G2-ELA-94", grade: 2, subject: "English", topic: "Reading", question: "What is a 'Simile'?", choices: ["A rhyme", "Comparing using 'like' or 'as'", "A loud noise", "A question"], answer: 1 },
    { id: "G2-ELA-95", grade: 2, subject: "English", topic: "Reading", question: "Which is a 'Fairy Tale' character?", choices: ["George Washington", "Cinderella", "Abraham Lincoln", "Your teacher"], answer: 1 },
    { id: "G2-ELA-96", grade: 2, subject: "English", topic: "Reading", question: "What is the 'Resolution'?", choices: ["The beginning", "The conflict", "How the problem is solved", "The cover"], answer: 2 },
    { id: "G2-ELA-97", grade: 2, subject: "English", topic: "Reading", question: "Bold words in a text usually mean:", choices: ["The printer broke", "The word is important/vocabulary", "The author made a mistake", "Read quietly"], answer: 1 },
    { id: "G2-ELA-98", grade: 2, subject: "English", topic: "Reading", question: "A 'Caption' tells you about a:", choices: ["Picture or Photo", "Chapter", "Book", "Page"], answer: 0 },
    { id: "G2-ELA-99", grade: 2, subject: "English", topic: "Reading", question: "What are 'Stanzas'?", choices: ["Paragraphs in a story", "Groups of lines in a poem", "Chapters", "Pictures"], answer: 1 },
    { id: "G2-ELA-100", grade: 2, subject: "English", topic: "Reading", question: "What is the author's purpose?", choices: ["Why they wrote the text (Persuade, Inform, Entertain)", "Their name", "Where they live", "How old they are"], answer: 0 }
];

module.exports = G2_ELA_COMPLETE;
