const G2_MATH_COMPLETE = [
    // --- TOPIC 1: PLACE VALUE & NUMBER SENSE (25 Questions) ---
    { id: "G2-MA-01", grade: 2, subject: "Math", topic: "Place Value", question: "What is the value of the 5 in the number 528?", choices: ["5", "50", "500", "5000"], answer: 2 },
    { id: "G2-MA-02", grade: 2, subject: "Math", topic: "Place Value", question: "How do you write 300 + 40 + 2 in standard form?", choices: ["342", "3042", "243", "3402"], answer: 0 },
    { id: "G2-MA-03", grade: 2, subject: "Math", topic: "Place Value", question: "Which number is 'Even'?", choices: ["13", "21", "44", "57"], answer: 2 },
    { id: "G2-MA-04", grade: 2, subject: "Math", topic: "Place Value", question: "Which number is 'Odd'?", choices: ["10", "22", "35", "48"], answer: 2 },
    { id: "G2-MA-05", grade: 2, subject: "Math", topic: "Place Value", question: "Skip count by 5s: 5, 10, 15, 20, _?", choices: ["21", "25", "30", "35"], answer: 1 },
    { id: "G2-MA-06", grade: 2, subject: "Math", topic: "Place Value", question: "Which number is 100 more than 450?", choices: ["460", "550", "451", "350"], answer: 1 },
    { id: "G2-MA-07", grade: 2, subject: "Math", topic: "Place Value", question: "Count back by 10s: 90, 80, 70, _?", choices: ["69", "65", "60", "50"], answer: 2 },
    { id: "G2-MA-08", grade: 2, subject: "Math", topic: "Place Value", question: "Compare: 782 _ 728", choices: [">", "<", "=", "+"], answer: 0 },
    { id: "G2-MA-09", grade: 2, subject: "Math", topic: "Place Value", question: "What is the largest 3-digit number?", choices: ["100", "900", "999", "1000"], answer: 2 },
    { id: "G2-MA-10", grade: 2, subject: "Math", topic: "Place Value", question: "How many tens are in 100?", choices: ["1", "5", "10", "100"], answer: 2 },
    { id: "G2-MA-11", grade: 2, subject: "Math", topic: "Place Value", question: "What is the word form of 205?", choices: ["Twenty-five", "Two hundred five", "Two hundred fifty", "Twenty-zero-five"], answer: 1 },
    { id: "G2-MA-12", grade: 2, subject: "Math", topic: "Place Value", question: "Which number has 7 in the ones place?", choices: ["71", "17", "700", "770"], answer: 1 },
    { id: "G2-MA-13", grade: 2, subject: "Math", topic: "Place Value", question: "How many hundreds are in 841?", choices: ["8", "4", "1", "800"], answer: 0 },
    { id: "G2-MA-14", grade: 2, subject: "Math", topic: "Place Value", question: "Skip count by 100s: 300, 400, 500, _?", choices: ["510", "600", "700", "501"], answer: 1 },
    { id: "G2-MA-15", grade: 2, subject: "Math", topic: "Place Value", question: "Which is true?", choices: ["100 < 99", "250 > 205", "40 = 400", "15 > 51"], answer: 1 },
    { id: "G2-MA-16", grade: 2, subject: "Math", topic: "Place Value", question: "What number is 10 less than 100?", choices: ["110", "99", "90", "80"], answer: 2 },
    { id: "G2-MA-17", grade: 2, subject: "Math", topic: "Place Value", question: "Which digit is in the tens place in 394?", choices: ["3", "9", "4", "39"], answer: 1 },
    { id: "G2-MA-18", grade: 2, subject: "Math", topic: "Place Value", question: "What is the expanded form of 67?", choices: ["6+7", "60+7", "600+7", "70+6"], answer: 1 },
    { id: "G2-MA-19", grade: 2, subject: "Math", topic: "Place Value", question: "How many ones are in 5 tens?", choices: ["5", "15", "50", "500"], answer: 2 },
    { id: "G2-MA-20", grade: 2, subject: "Math", topic: "Place Value", question: "Count by 2s: 2, 4, 6, 8, _?", choices: ["9", "10", "11", "12"], answer: 1 },
    { id: "G2-MA-21", grade: 2, subject: "Math", topic: "Place Value", question: "Which number is between 145 and 147?", choices: ["144", "146", "148", "150"], answer: 1 },
    { id: "G2-MA-22", grade: 2, subject: "Math", topic: "Place Value", question: "What is 100 + 100 + 100?", choices: ["200", "300", "400", "1000"], answer: 1 },
    { id: "G2-MA-23", grade: 2, subject: "Math", topic: "Place Value", question: "True or False: 0 is an even number.", choices: ["True", "False", "Only in Math", "Never"], answer: 0 },
    { id: "G2-MA-24", grade: 2, subject: "Math", topic: "Place Value", question: "What number comes just before 1000?", choices: ["900", "990", "999", "1001"], answer: 2 },
    { id: "G2-MA-25", grade: 2, subject: "Math", topic: "Place Value", question: "How many digits are in the number 456?", choices: ["1", "2", "3", "4"], answer: 2 },

    // --- TOPIC 2: 2-DIGIT ADDITION & SUBTRACTION (25 Questions) ---
    { id: "G2-MA-26", grade: 2, subject: "Math", topic: "Addition", question: "What is 25 + 10?", choices: ["30", "35", "45", "55"], answer: 1 },
    { id: "G2-MA-27", grade: 2, subject: "Math", topic: "Subtraction", question: "What is 50 - 20?", choices: ["20", "30", "40", "70"], answer: 1 },
    { id: "G2-MA-28", grade: 2, subject: "Math", topic: "Addition", question: "What is 15 + 15?", choices: ["20", "25", "30", "35"], answer: 2 },
    { id: "G2-MA-29", grade: 2, subject: "Math", topic: "Addition", question: "Solve: 44 + 22", choices: ["60", "64", "66", "88"], answer: 2 },
    { id: "G2-MA-30", grade: 2, subject: "Math", topic: "Subtraction", question: "Solve: 36 - 12", choices: ["22", "24", "26", "28"], answer: 1 },
    { id: "G2-MA-31", grade: 2, subject: "Math", topic: "Addition", question: "What is 60 + 40?", choices: ["80", "90", "100", "110"], answer: 2 },
    { id: "G2-MA-32", grade: 2, subject: "Math", topic: "Addition", question: "What is 12 + 13?", choices: ["23", "24", "25", "26"], answer: 2 },
    { id: "G2-MA-33", grade: 2, subject: "Math", topic: "Subtraction", question: "What is 100 - 1?", choices: ["0", "90", "99", "101"], answer: 2 },
    { id: "G2-MA-34", grade: 2, subject: "Math", topic: "Addition", question: "Solve: 20 + 30 + 10", choices: ["40", "50", "60", "70"], answer: 2 },
    { id: "G2-MA-35", grade: 2, subject: "Math", topic: "Addition", question: "If you add 0 to any number, the number...", choices: ["Gets bigger", "Gets smaller", "Stays the same", "Turns to zero"], answer: 2 },
    { id: "G2-MA-36", grade: 2, subject: "Math", topic: "Addition", question: "What is 55 + 5?", choices: ["50", "60", "65", "100"], answer: 1 },
    { id: "G2-MA-37", grade: 2, subject: "Math", topic: "Subtraction", question: "What is 88 - 8?", choices: ["70", "80", "81", "96"], answer: 1 },
    { id: "G2-MA-38", grade: 2, subject: "Math", topic: "Addition", question: "Solve: 11 + 11", choices: ["12", "21", "22", "33"], answer: 2 },
    { id: "G2-MA-39", grade: 2, subject: "Math", topic: "Subtraction", question: "Solve: 45 - 5", choices: ["40", "35", "50", "0"], answer: 0 },
    { id: "G2-MA-40", grade: 2, subject: "Math", topic: "Addition", question: "What is 7 + 7 + 7?", choices: ["14", "21", "28", "30"], answer: 1 },
    { id: "G2-MA-41", grade: 2, subject: "Math", topic: "Addition", question: "What is 80 + 20?", choices: ["60", "90", "100", "120"], answer: 2 },
    { id: "G2-MA-42", grade: 2, subject: "Math", topic: "Subtraction", question: "What is 19 - 9?", choices: ["", "10", "11", "20"], answer: 1 },
    { id: "G2-MA-43", grade: 2, subject: "Math", topic: "Addition", question: "Solve: 33 + 33", choices: ["60", "63", "66", "99"], answer: 2 },
    { id: "G2-MA-44", grade: 2, subject: "Math", topic: "Addition", question: "Find the sum of 40 and 40.", choices: ["0", "40", "80", "100"], answer: 2 },
    { id: "G2-MA-45", grade: 2, subject: "Math", topic: "Subtraction", question: "What is 25 - 25?", choices: ["0", "1", "25", "50"], answer: 0 },
    { id: "G2-MA-46", grade: 2, subject: "Math", topic: "Addition", question: "What is 10 + 10 + 10 + 10?", choices: ["20", "30", "40", "50"], answer: 2 },
    { id: "G2-MA-47", grade: 2, subject: "Math", topic: "Subtraction", question: "Solve: 60 - 30", choices: ["20", "30", "40", "90"], answer: 1 },
    { id: "G2-MA-48", grade: 2, subject: "Math", topic: "Addition", question: "What is 2 + 2 + 2 + 2 + 2?", choices: ["8", "10", "12", "20"], answer: 1 },
    { id: "G2-MA-49", grade: 2, subject: "Math", topic: "Subtraction", question: "What is 75 - 25?", choices: ["25", "40", "50", "100"], answer: 2 },
    { id: "G2-MA-50", grade: 2, subject: "Math", topic: "Addition", question: "Solve: 90 + 9", choices: ["90", "99", "100", "109"], answer: 1 },

    // --- TOPIC 3: MEASUREMENT & GEOMETRY (25 Questions) ---
    { id: "G2-MA-51", grade: 2, subject: "Math", topic: "Measurement", question: "How many inches are in a foot?", choices: ["10", "12", "24", "36"], answer: 1 },
    { id: "G2-MA-52", grade: 2, subject: "Math", topic: "Geometry", question: "A cube has how many faces?", choices: ["4", "6", "8", "12"], answer: 1 },
    { id: "G2-MA-53", grade: 2, subject: "Math", topic: "Measurement", question: "Which tool measures length?", choices: ["Clock", "Ruler", "Scale", "Cup"], answer: 1 },
    { id: "G2-MA-54", grade: 2, subject: "Math", topic: "Geometry", question: "Which shape has 5 sides?", choices: ["Square", "Hexagon", "Pentagon", "Octagon"], answer: 2 },
    { id: "G2-MA-55", grade: 2, subject: "Math", topic: "Measurement", question: "Which is longer: 1 inch or 1 centimeter?", choices: ["1 inch", "1 centimeter", "They are the same", "None"], answer: 0 },
    { id: "G2-MA-56", grade: 2, subject: "Math", topic: "Geometry", question: "What is a shape with 4 equal sides called?", choices: ["Triangle", "Rectangle", "Square", "Circle"], answer: 2 },
    { id: "G2-MA-57", grade: 2, subject: "Math", topic: "Measurement", question: "How many centimeters are usually on a small ruler?", choices: ["12", "30", "50", "100"], answer: 1 },
    { id: "G2-MA-58", grade: 2, subject: "Math", topic: "Geometry", question: "Which shape has no vertices (corners)?", choices: ["Triangle", "Square", "Circle", "Pentagon"], answer: 2 },
    { id: "G2-MA-59", grade: 2, subject: "Math", topic: "Measurement", question: "Which unit would you use to measure a pencil?", choices: ["Miles", "Inches", "Yards", "Kilometers"], answer: 1 },
    { id: "G2-MA-60", grade: 2, subject: "Math", topic: "Geometry", question: "How many sides does a hexagon have?", choices: ["4", "5", "6", "8"], answer: 2 },
    { id: "G2-MA-61", grade: 2, subject: "Math", topic: "Measurement", question: "3 feet is equal to 1 ____?", choices: ["Inch", "Yard", "Mile", "Meter"], answer: 1 },
    { id: "G2-MA-62", grade: 2, subject: "Math", topic: "Geometry", question: "What do you call a 3D circle?", choices: ["Cube", "Sphere", "Cone", "Cylinder"], answer: 1 },
    { id: "G2-MA-63", grade: 2, subject: "Math", topic: "Measurement", question: "Which is heavier: a feather or a brick?", choices: ["Feather", "Brick", "Same", "None"], answer: 1 },
    { id: "G2-MA-64", grade: 2, subject: "Math", topic: "Geometry", question: "How many angles does a triangle have?", choices: ["1", "2", "3", "4"], answer: 2 },
    { id: "G2-MA-65", grade: 2, subject: "Math", topic: "Measurement", question: "What does a thermometer measure?", choices: ["Time", "Length", "Temperature", "Weight"], answer: 2 },
    { id: "G2-MA-66", grade: 2, subject: "Math", topic: "Geometry", question: "Which shape looks like a stop sign?", choices: ["Hexagon", "Pentagon", "Octagon", "Square"], answer: 2 },
    { id: "G2-MA-67", grade: 2, subject: "Math", topic: "Measurement", question: "Which is the shortest unit?", choices: ["Meter", "Centimeter", "Kilometer", "Inch"], answer: 1 },
    { id: "G2-MA-68", grade: 2, subject: "Math", topic: "Geometry", question: "A rectangle has how many sides?", choices: ["2", "3", "4", "5"], answer: 2 },
    { id: "G2-MA-69", grade: 2, subject: "Math", topic: "Measurement", question: "Which tool measures liquid?", choices: ["Ruler", "Scale", "Measuring Cup", "Clock"], answer: 2 },
    { id: "G2-MA-70", grade: 2, subject: "Math", topic: "Geometry", question: "Which 3D shape has a circular base and a point at the top?", choices: ["Cube", "Cone", "Sphere", "Sphere"], answer: 1 },
    { id: "G2-MA-71", grade: 2, subject: "Math", topic: "Measurement", question: "A ruler is usually how many inches long?", choices: ["6", "10", "12", "20"], answer: 2 },
    { id: "G2-MA-72", grade: 2, subject: "Math", topic: "Geometry", question: "Two squares put side-by-side can make a...?", choices: ["Circle", "Triangle", "Rectangle", "Pentagon"], answer: 2 },
    { id: "G2-MA-73", grade: 2, subject: "Math", topic: "Measurement", question: "If a line is 5cm and another is 3cm, how long are they together?", choices: ["2cm", "7cm", "8cm", "10cm"], answer: 2 },
    { id: "G2-MA-74", grade: 2, subject: "Math", topic: "Geometry", question: "Which shape is 2D (flat)?", choices: ["Cube", "Sphere", "Triangle", "Cylinder"], answer: 2 },
    { id: "G2-MA-75", grade: 2, subject: "Math", topic: "Measurement", question: "How many sides does a circle have?", choices: ["0", "1", "2", "4"], answer: 0 },

    // --- TOPIC 4: TIME & MONEY (25 Questions) ---
    { id: "G2-MA-76", grade: 2, subject: "Math", topic: "Money", question: "How much is a quarter worth?", choices: ["5 cents", "10 cents", "25 cents", "50 cents"], answer: 2 },
    { id: "G2-MA-77", grade: 2, subject: "Math", topic: "Time", question: "How many minutes are in one hour?", choices: ["30", "60", "100", "12"], answer: 1 },
    { id: "G2-MA-78", grade: 2, subject: "Math", topic: "Money", question: "Which coin is worth 10 cents?", choices: ["Penny", "Nickel", "Dime", "Quarter"], answer: 2 },
    { id: "G2-MA-79", grade: 2, subject: "Math", topic: "Time", question: "What time is 'Half Past 2'?", choices: ["2:00", "2:15", "2:30", "2:45"], answer: 2 },
    { id: "G2-MA-80", grade: 2, subject: "Math", topic: "Money", question: "How many nickels make a quarter?", choices: ["2", "5", "10", "25"], answer: 1 },
    { id: "G2-MA-81", grade: 2, subject: "Math", topic: "Time", question: "A.M. means the time is in the...?", choices: ["Morning", "Afternoon", "Night", "Evening"], answer: 0 },
    { id: "G2-MA-82", grade: 2, subject: "Math", topic: "Money", question: "How much is 2 dimes and 1 nickel?", choices: ["20 cents", "25 cents", "30 cents", "15 cents"], answer: 1 },
    { id: "G2-MA-83", grade: 2, subject: "Math", topic: "Time", question: "How many hours are in a full day?", choices: ["12", "24", "48", "60"], answer: 1 },
    { id: "G2-MA-84", grade: 2, subject: "Math", topic: "Money", question: "Which coin is the largest in size?", choices: ["Dime", "Penny", "Nickel", "Quarter"], answer: 3 },
    { id: "G2-MA-85", grade: 2, subject: "Math", topic: "Time", question: "What does P.M. stand for?", choices: ["Pre Morning", "Past Midnight", "Afternoon/Night", "Priority Mail"], answer: 2 },
    { id: "G2-MA-86", grade: 2, subject: "Math", topic: "Money", question: "How many pennies make a dollar?", choices: ["10", "50", "100", "500"], answer: 2 },
    { id: "G2-MA-87", grade: 2, subject: "Math", topic: "Time", question: "The 'short hand' on a clock shows the...?", choices: ["Minutes", "Hours", "Seconds", "Days"], answer: 1 },
    { id: "G2-MA-88", grade: 2, subject: "Math", topic: "Money", question: "How many quarters make 1 dollar?", choices: ["2", "4", "5", "10"], answer: 1 },
    { id: "G2-MA-89", grade: 2, subject: "Math", topic: "Time", question: "The 'long hand' on a clock shows the...?", choices: ["Minutes", "Hours", "Seconds", "Years"], answer: 0 },
    { id: "G2-MA-90", grade: 2, subject: "Math", topic: "Money", question: "If you have 3 dimes, how much money do you have?", choices: ["3 cents", "15 cents", "30 cents", "75 cents"], answer: 2 },
    { id: "G2-MA-91", grade: 2, subject: "Math", topic: "Time", question: "What is 15 minutes after 4:00?", choices: ["4:05", "4:15", "4:30", "5:00"], answer: 1 },
    { id: "G2-MA-92", grade: 2, subject: "Math", topic: "Money", question: "Which bill has George Washington on it?", choices: ["$1 bill", "$5 bill", "$10 bill", "$20 bill"], answer: 0 },
    { id: "G2-MA-93", grade: 2, subject: "Math", topic: "Time", question: "How many minutes are in half an hour?", choices: ["15", "30", "45", "60"], answer: 1 },
    { id: "G2-MA-94", grade: 2, subject: "Math", topic: "Money", question: "How much is 1 quarter and 1 dime?", choices: ["26 cents", "30 cents", "35 cents", "40 cents"], answer: 2 },
    { id: "G2-MA-95", grade: 2, subject: "Math", topic: "Time", question: "If it is 10:00 now, what time was it one hour ago?", choices: ["9:00", "11:00", "10:30", "12:00"], answer: 0 },
    { id: "G2-MA-96", grade: 2, subject: "Math", topic: "Money", question: "Which coin is brown?", choices: ["Dime", "Penny", "Nickel", "Quarter"], answer: 1 },
    { id: "G2-MA-97", grade: 2, subject: "Math", topic: "Time", question: "What is another way to say 6:45?", choices: ["Half past 6", "Quarter to 7", "Quarter after 6", "6 o'clock"], answer: 1 },
    { id: "G2-MA-98", grade: 2, subject: "Math", topic: "Money", question: "If an apple costs 50 cents, which coins could you use?", choices: ["1 dime", "2 quarters", "3 nickels", "1 penny"], answer: 1 },
    { id: "G2-MA-99", grade: 2, subject: "Math", topic: "Time", question: "Which of these is a time you would sleep?", choices: ["12:00 PM", "2:00 AM", "8:00 AM", "4:00 PM"], answer: 1 },
    { id: "G2-MA-100", grade: 2, subject: "Math", topic: "Money", question: "10 dimes is equal to how many dollars?", choices: ["$1", "$2", "$5", "$10"], answer: 0 }
];

module.exports = G2_MATH_COMPLETE;
