const G2_SOCIAL_STUDIES_COMPLETE = [
    // --- TOPIC 1: GOVERNMENT & CITIZENSHIP (25 Questions) ---
    { id: "G2-SS-01", grade: 2, subject: "Social Studies", topic: "Civics", question: "Who is the leader of a city or town?", choices: ["President", "Governor", "Mayor", "Principal"], answer: 2 },
    { id: "G2-SS-02", grade: 2, subject: "Social Studies", topic: "Civics", question: "Who is the leader of an entire state?", choices: ["Mayor", "Governor", "King", "Senator"], answer: 1 },
    { id: "G2-SS-03", grade: 2, subject: "Social Studies", topic: "Civics", question: "What are the three branches of the US Government?", choices: ["North, South, East", "City, State, Country", "Legislative, Executive, Judicial", "Red, White, Blue"], answer: 2 },
    { id: "G2-SS-04", grade: 2, subject: "Social Studies", topic: "Civics", question: "Which branch of government makes the laws?", choices: ["Judicial", "Executive", "Legislative (Congress)", "The Police"], answer: 2 },
    { id: "G2-SS-05", grade: 2, subject: "Social Studies", topic: "Civics", question: "Which branch of government decides if a law is fair?", choices: ["Legislative", "Judicial (Courts)", "Executive", "The Mayor"], answer: 1 },
    { id: "G2-SS-06", grade: 2, subject: "Social Studies", topic: "Civics", question: "What is the 'Constitution'?", choices: ["A book of maps", "The set of main rules for our country", "A type of flag", "A holiday"], answer: 1 },
    { id: "G2-SS-07", grade: 2, subject: "Social Studies", topic: "Civics", question: "What is a 'Right'?", choices: ["A rule you must follow", "A freedom protected by law", "The opposite of left", "A job"], answer: 1 },
    { id: "G2-SS-08", grade: 2, subject: "Social Studies", topic: "Civics", question: "Voting is a way for citizens to:", choices: ["Make money", "Choose their leaders", "Go on vacation", "Pay taxes"], answer: 1 },
    { id: "G2-SS-09", grade: 2, subject: "Social Studies", topic: "Civics", question: "How old must a citizen be to vote in the USA?", choices: ["16", "18", "21", "35"], answer: 1 },
    { id: "G2-SS-10", grade: 2, subject: "Social Studies", topic: "Civics", question: "What is a 'Tax'?", choices: ["Money paid to the government for services", "A type of car", "A gift from the President", "A rule in school"], answer: 0 },
    { id: "G2-SS-11", grade: 2, subject: "Social Studies", topic: "Civics", question: "Where does the US Congress meet to make laws?", choices: ["The White House", "The U.S. Capitol Building", "The Supreme Court", "The Library"], answer: 1 },
    { id: "G2-SS-12", grade: 2, subject: "Social Studies", topic: "Civics", question: "Who carries out (enforces) the laws for the country?", choices: ["The President", "The Judge", "The Teacher", "The Mayor"], answer: 0 },
    { id: "G2-SS-13", grade: 2, subject: "Social Studies", topic: "Civics", question: "A change to the Constitution is called an:", choices: ["Option", "Amendment", "Addition", "Ending"], answer: 1 },
    { id: "G2-SS-14", grade: 2, subject: "Social Studies", topic: "Civics", question: "What do we call the first ten amendments to the Constitution?", choices: ["The Rules of Ten", "The Bill of Rights", "The Freedom List", "The Declaration"], answer: 1 },
    { id: "G2-SS-15", grade: 2, subject: "Social Studies", topic: "Civics", question: "Which of these is a responsibility of a citizen?", choices: ["Playing video games", "Following laws", "Watching TV", "Sleeping"], answer: 1 },
    { id: "G2-SS-16", grade: 2, subject: "Social Studies", topic: "Civics", question: "The Supreme Court is made up of 9 experts called:", choices: ["Presidents", "Justices", "Mayors", "Captains"], answer: 1 },
    { id: "G2-SS-17", grade: 2, subject: "Social Studies", topic: "Civics", question: "What is the name of the document that said the US was free from England?", choices: ["The Constitution", "The Declaration of Independence", "The Gettysburg Address", "The Bill of Rights"], answer: 1 },
    { id: "G2-SS-18", grade: 2, subject: "Social Studies", topic: "Civics", question: "A person who is a legal member of a country is a:", choices: ["Tourist", "Citizen", "Neighbor", "Leader"], answer: 1 },
    { id: "G2-SS-19", grade: 2, subject: "Social Studies", topic: "Civics", question: "Which level of government provides police and fire departments?", choices: ["Only National", "Local Government", "Only the President", "School Board"], answer: 1 },
    { id: "G2-SS-20", grade: 2, subject: "Social Studies", topic: "Civics", question: "Who is in charge of a court?", choices: ["A Mayor", "A Judge", "A Police Officer", "A Librarian"], answer: 1 },
    { id: "G2-SS-21", grade: 2, subject: "Social Studies", topic: "Civics", question: "What does the 'Executive Branch' do?", choices: ["Makes laws", "Explains laws", "Signs or vetoes laws", "Builds roads"], answer: 2 },
    { id: "G2-SS-22", grade: 2, subject: "Social Studies", topic: "Civics", question: "What is a 'public service'?", choices: ["A job that helps the community", "A private party", "A video game", "A store"], answer: 0 },
    { id: "G2-SS-23", grade: 2, subject: "Social Studies", topic: "Civics", question: "We celebrate Veterans Day to honor:", choices: ["Teachers", "People who served in the military", "Presidents", "Police"], answer: 1 },
    { id: "G2-SS-24", grade: 2, subject: "Social Studies", topic: "Civics", question: "What symbol represents freedom and stands in New York Harbor?", choices: ["The Liberty Bell", "The Statue of Liberty", "The White House", "Mount Rushmore"], answer: 1 },
    { id: "G2-SS-25", grade: 2, subject: "Social Studies", topic: "Civics", question: "The 'Preamble' is the beginning of which document?", choices: ["A Storybook", "The Constitution", "A Map", "A Dictionary"], answer: 1 },

    // --- TOPIC 2: GEOGRAPHY & LANDFORMS (25 Questions) ---
    { id: "G2-SS-26", grade: 2, subject: "Social Studies", topic: "Geography", question: "What are the four cardinal directions?", choices: ["Up, Down, Left, Right", "North, South, East, West", "Red, Blue, Green, Yellow", "Winter, Spring, Summer, Fall"], answer: 1 },
    { id: "G2-SS-27", grade: 2, subject: "Social Studies", topic: "Geography", question: "What is an imaginary line that circles the middle of the Earth?", choices: ["The Pole", "The Equator", "The Border", "The Road"], answer: 1 },
    { id: "G2-SS-28", grade: 2, subject: "Social Studies", topic: "Geography", question: "How many continents are there?", choices: ["4", "5", "7", "10"], answer: 2 },
    { id: "G2-SS-29", grade: 2, subject: "Social Studies", topic: "Geography", question: "Which ocean is the largest on Earth?", choices: ["Atlantic", "Indian", "Pacific", "Arctic"], answer: 2 },
    { id: "G2-SS-30", grade: 2, subject: "Social Studies", topic: "Geography", question: "What map feature tells you how far apart places are?", choices: ["Title", "Compass Rose", "Map Scale", "Key"], answer: 2 },
    { id: "G2-SS-31", grade: 2, subject: "Social Studies", topic: "Geography", question: "Which continent is also a country?", choices: ["Asia", "Australia", "Europe", "Africa"], answer: 1 },
    { id: "G2-SS-32", grade: 2, subject: "Social Studies", topic: "Geography", question: "The weather a place usually has over a long time is its:", choices: ["Season", "Climate", "Storm", "Temperature"], answer: 1 },
    { id: "G2-SS-33", grade: 2, subject: "Social Studies", topic: "Geography", question: "What is a large, flat area of land?", choices: ["Mountain", "Plain", "Valley", "Hill"], answer: 1 },
    { id: "G2-SS-34", grade: 2, subject: "Social Studies", topic: "Geography", question: "Which landform is surrounded by water on all sides?", choices: ["Peninsula", "Island", "Canyon", "Plain"], answer: 1 },
    { id: "G2-SS-35", grade: 2, subject: "Social Studies", topic: "Geography", question: "Which landform is surrounded by water on three sides?", choices: ["Island", "Peninsula", "Mountain", "Desert"], answer: 1 },
    { id: "G2-SS-36", grade: 2, subject: "Social Studies", topic: "Geography", question: "What is the largest continent by size?", choices: ["North America", "Asia", "Antarctica", "Africa"], answer: 1 },
    { id: "G2-SS-37", grade: 2, subject: "Social Studies", topic: "Geography", question: "Which continent is at the very south of the Earth and covered in ice?", choices: ["Europe", "Antarctica", "South America", "Australia"], answer: 1 },
    { id: "G2-SS-38", grade: 2, subject: "Social Studies", topic: "Geography", question: "A 'Physical Map' shows:", choices: ["Cities and roads", "Mountains and rivers", "Weather", "Population"], answer: 1 },
    { id: "G2-SS-39", grade: 2, subject: "Social Studies", topic: "Geography", question: "A 'Political Map' shows:", choices: ["Mountains", "Borders and capitals", "Forests", "Oceans"], answer: 1 },
    { id: "G2-SS-40", grade: 2, subject: "Social Studies", topic: "Geography", question: "Which ocean is near the North Pole?", choices: ["Indian", "Arctic", "Pacific", "Atlantic"], answer: 1 },
    { id: "G2-SS-41", grade: 2, subject: "Social Studies", topic: "Geography", question: "What is a deep valley with steep rock sides?", choices: ["Plateau", "Canyon", "Plain", "Forest"], answer: 1 },
    { id: "G2-SS-42", grade: 2, subject: "Social Studies", topic: "Geography", question: "What do we call the half of the Earth north of the Equator?", choices: ["Southern Hemisphere", "Northern Hemisphere", "Eastern Hemisphere", "Western Hemisphere"], answer: 1 },
    { id: "G2-SS-43", grade: 2, subject: "Social Studies", topic: "Geography", question: "What is a 'Natural Resource'?", choices: ["Something made in a factory", "Something from nature that people use", "A type of money", "A textbook"], answer: 1 }
];

module.exports = G2_SOCIAL_STUDIES_COMPLETE;
