const G2_SCIENCE_COMPLETE = [
    // --- TOPIC 1: HABITATS & ECOSYSTEMS (25 Questions) ---
    { id: "G2-SCI-01", grade: 2, subject: "Science", topic: "Habitats", question: "Which habitat is very cold and covered in ice?", choices: ["Desert", "Tundra", "Rainforest", "Ocean"], answer: 1 },
    { id: "G2-SCI-02", grade: 2, subject: "Science", topic: "Habitats", question: "In which habitat would you find a cactus?", choices: ["Forest", "Ocean", "Desert", "Wetland"], answer: 2 },
    { id: "G2-SCI-03", grade: 2, subject: "Science", topic: "Habitats", question: "Which habitat has mostly salt water?", choices: ["Lake", "River", "Ocean", "Pond"], answer: 2 },
    { id: "G2-SCI-04", grade: 2, subject: "Science", topic: "Habitats", question: "What do animals get from their habitat to survive?", choices: ["Toys", "Food, Water, and Shelter", "Clothing", "Television"], answer: 1 },
    { id: "G2-SCI-05", grade: 2, subject: "Science", topic: "Habitats", question: "Which habitat is very hot and gets a lot of rain?", choices: ["Desert", "Tundra", "Tropical Rainforest", "Grassland"], answer: 2 },
    { id: "G2-SCI-06", grade: 2, subject: "Science", topic: "Habitats", question: "A place where a plant or animal lives is called a:", choices: ["House", "Habitat", "Kitchen", "Box"], answer: 1 },
    { id: "G2-SCI-07", grade: 2, subject: "Science", topic: "Habitats", question: "Which animal lives in a wetland?", choices: ["Camel", "Alligator", "Polar Bear", "Mountain Goat"], answer: 1 },
    { id: "G2-SCI-08", grade: 2, subject: "Science", topic: "Habitats", question: "What is an ecosystem?", choices: ["A type of weather", "Living and non-living things working together", "A planet", "A tool for measuring"], answer: 1 },
    { id: "G2-SCI-09", grade: 2, subject: "Science", topic: "Habitats", question: "Which habitat is a large, flat area with lots of grass?", choices: ["Mountain", "Grassland", "Forest", "Cave"], answer: 1 },
    { id: "G2-SCI-10", grade: 2, subject: "Science", topic: "Habitats", question: "How do polar bears stay warm in the Arctic?", choices: ["They wear coats", "They have thick fur and blubber", "They sit by fires", "They migrate south"], answer: 1 },
    { id: "G2-SCI-11", grade: 2, subject: "Science", topic: "Habitats", question: "Which habitat is underwater and made of coral?", choices: ["Coral Reef", "Forest", "Desert", "Prairie"], answer: 0 },
    { id: "G2-SCI-12", grade: 2, subject: "Science", topic: "Habitats", question: "Where would you find an animal with a blowhole?", choices: ["On a mountain", "In the ocean", "In a forest", "In a desert"], answer: 1 },
    { id: "G2-SCI-13", grade: 2, subject: "Science", topic: "Habitats", question: "What happens to animals if their habitat is destroyed?", choices: ["They get happy", "They must find a new home or they may die", "They turn into new animals", "Nothing"], answer: 1 },
    { id: "G2-SCI-14", grade: 2, subject: "Science", topic: "Habitats", question: "Which habitat has many trees that lose their leaves in fall?", choices: ["Rainforest", "Deciduous Forest", "Desert", "Ocean"], answer: 1 },
    { id: "G2-SCI-15", grade: 2, subject: "Science", topic: "Habitats", question: "Fresh water can be found in a:", choices: ["Ocean", "River", "Salt Lake", "Sea"], answer: 1 },
    { id: "G2-SCI-16", grade: 2, subject: "Science", topic: "Habitats", question: "Why do some animals blend into their habitat?", choices: ["To be pretty", "To hide from predators (camouflage)", "To get warm", "To find friends"], answer: 1 },
    { id: "G2-SCI-17", grade: 2, subject: "Science", topic: "Habitats", question: "Which of these is a non-living part of a habitat?", choices: ["Rocks", "Birds", "Trees", "Insects"], answer: 0 },
    { id: "G2-SCI-18", grade: 2, subject: "Science", topic: "Habitats", question: "What is a predator?", choices: ["An animal that eats plants", "An animal that hunts other animals", "A type of plant", "A rock"], answer: 1 },
    { id: "G2-SCI-19", grade: 2, subject: "Science", topic: "Habitats", question: "What is 'prey'?", choices: ["An animal that is hunted", "The hunter", "A type of tree", "Rainfall"], answer: 0 },
    { id: "G2-SCI-20", grade: 2, subject: "Science", topic: "Habitats", question: "Where do monkeys usually live?", choices: ["Tundra", "Rainforest", "Desert", "Ocean"], answer: 1 },
    { id: "G2-SCI-21", grade: 2, subject: "Science", topic: "Habitats", question: "An animal that eats only other animals is a:", choices: ["Herbivore", "Carnivore", "Omnivore", "Producer"], answer: 1 },
    { id: "G2-SCI-22", grade: 2, subject: "Science", topic: "Habitats", question: "An animal that eats only plants is a:", choices: ["Carnivore", "Herbivore", "Omnivore", "Decomposer"], answer: 1 },
    { id: "G2-SCI-23", grade: 2, subject: "Science", topic: "Habitats", question: "An animal that eats both plants and animals is a:", choices: ["Herbivore", "Carnivore", "Omnivore", "Plant"], answer: 2 },
    { id: "G2-SCI-24", grade: 2, subject: "Science", topic: "Habitats", question: "What do we call a habitat with very little water?", choices: ["Wetland", "Desert", "Ocean", "River"], answer: 1 },
    { id: "G2-SCI-25", grade: 2, subject: "Science", topic: "Habitats", question: "Where would you find a pond?", choices: ["In the middle of the ocean", "In a forest or field", "In a volcano", "In the clouds"], answer: 1 },

    // --- TOPIC 2: PROPERTIES OF MATTER (25 Questions) ---
    { id: "G2-SCI-26", grade: 2, subject: "Science", topic: "Matter", question: "Which property tells you if an object is rough or smooth?", choices: ["Weight", "Color", "Texture", "Shape"], answer: 2 },
    { id: "G2-SCI-27", grade: 2, subject: "Science", topic: "Matter", question: "What happens when you heat chocolate?", choices: ["It freezes", "It melts", "It turns into a gas", "It stays the same"], answer: 1 },
    { id: "G2-SCI-28", grade: 2, subject: "Science", topic: "Matter", question: "Which of these is a reversible change?", choices: ["Burning wood", "Baking a cake", "Melting ice", "Frying an egg"], answer: 2 },
    { id: "G2-SCI-29", grade: 2, subject: "Science", topic: "Matter", question: "Which of these is an irreversible change?", choices: ["Melting butter", "Freezing water", "Cooking a pancake", "Folding paper"], answer: 2 },
    { id: "G2-SCI-30", grade: 2, subject: "Science", topic: "Matter", question: "What is it called when a liquid turns into a gas?", choices: ["Freezing", "Melting", "Evaporation", "Condensation"], answer: 2 },
    { id: "G2-SCI-31", grade: 2, subject: "Science", topic: "Matter", question: "Which state of matter has its own shape?", choices: ["Liquid", "Solid", "Gas", "Air"], answer: 1 },
    { id: "G2-SCI-32", grade: 2, subject: "Science", topic: "Matter", question: "Which state of matter takes the shape of its container?", choices: ["Solid", "Liquid", "Rock", "Wood"], answer: 1 },
    { id: "G2-SCI-33", grade: 2, subject: "Science", topic: "Matter", question: "Matter is anything that has mass and...", choices: ["Is green", "Takes up space", "Can move", "Is heavy"], answer: 1 },
    { id: "G2-SCI-34", grade: 2, subject: "Science", topic: "Matter", question: "Which of these is a gas?", choices: ["Water", "Steam", "Ice", "Juice"], answer: 1 },
    { id: "G2-SCI-35", grade: 2, subject: "Science", topic: "Matter", question: "What do we call a material that allows heat to move through it easily?", choices: ["Insulator", "Conductor", "Blocker", "Solid"], answer: 1 },
    { id: "G2-SCI-36", grade: 2, subject: "Science", topic: "Matter", question: "Which tool measures temperature?", choices: ["Ruler", "Scale", "Thermometer", "Clock"], answer: 2 },
    { id: "G2-SCI-37", grade: 2, subject: "Science", topic: "Matter", question: "What is flexibility?", choices: ["How heavy something is", "How easily something bends", "The color of an object", "How much light it blocks"], answer: 1 },
    { id: "G2-SCI-38", grade: 2, subject: "Science", topic: "Matter", question: "If you break a pencil, is it still made of the same matter?", choices: ["Yes", "No", "Only if it's yellow", "Maybe"], answer: 0 },
    { id: "G2-SCI-39", grade: 2, subject: "Science", topic: "Matter", question: "Which material is best for an umbrella?", choices: ["Cotton", "Paper", "Waterproof Plastic", "Wood"], answer: 2 },
    { id: "G2-SCI-40", grade: 2, subject: "Science", topic: "Matter", question: "Which state of matter is the hardest to see?", choices: ["Solid", "Liquid", "Gas", "Ice"], answer: 2 },
    { id: "G2-SCI-41", grade: 2, subject: "Science", topic: "Matter", question: "What happens to gas when it is cooled down a lot?", choices: ["It turns to liquid", "It disappears", "It gets hotter", "It stays the same"], answer: 0 },
    { id: "G2-SCI-42", grade: 2, subject: "Science", topic: "Matter", question: "What do we call a material that does NOT let heat move through easily?", choices: ["Conductor", "Insulator", "Mirror", "Metal"], answer: 1 },
    { id: "G2-SCI-43", grade: 2, subject: "Science", topic: "Matter", question: "Which of these can change its volume to fill a room?", choices: ["Solid", "Liquid", "Gas", "Table"], answer: 2 },
    { id: "G2-SCI-44", grade: 2, subject: "Science", topic: "Matter", question: "What is buoyancy?", choices: ["How hard something is", "Ability to float", "The color of an object", "The smell of matter"], answer: 1 },
    { id: "G2-SCI-45", grade: 2, subject: "Science", topic: "Matter", question: "What are the three main states of matter?", choices: ["Hot, Cold, Warm", "Red, Blue, Green", "Solid, Liquid, Gas", "Hard, Soft, Bumpy"], answer: 2 },
    { id: "G2-SCI-46", grade: 2, subject: "Science", topic: "Matter", question: "Is air matter?", choices: ["Yes", "No", "Only when it's windy", "Only in space"], answer: 0 },
    { id: "G2-SCI-47", grade: 2, subject: "Science", topic: "Matter", question: "Which is a property of a metal spoon?", choices: ["Soft", "Flexible", "Hard and shiny", "Gas"], answer: 2 },
    { id: "G2-SCI-48", grade: 2, subject: "Science", topic: "Matter", question: "What do you call a mixture of two or more types of matter?", choices: ["Solution", "Pure", "Solid", "Gas"], answer: 0 },
    { id: "G2-SCI-49", grade: 2, subject: "Science", topic: "Matter", question: "Which will dissolve in water?", choices: ["Sand", "Sugar", "Rocks", "Plastic"], answer: 1 },
    { id: "G2-SCI-50", grade: 2, subject: "Science", topic: "Matter", question: "What do we call the amount of matter in an object?", choices: ["Size", "Weight", "Mass", "Length"], answer: 2 },

    // --- TOPIC 3: EROSION & EARTH'S SURFACE (25 Questions) ---
    { id: "G2-SCI-51", grade: 2, subject: "Science", topic: "Earth", question: "What do we call it when wind or water moves soil and rocks?", choices: ["Planting", "Erosion", "Gravity", "Building"], answer: 1 },
    { id: "G2-SCI-52", grade: 2, subject: "Science", topic: "Earth", question: "What is a very slow change to the Earth's surface?", choices: ["Earthquake", "Volcano", "Erosion", "Landslide"], answer: 2 },
    { id: "G2-SCI-53", grade: 2, subject: "Science", topic: "Earth", question: "What is a fast change to the Earth's surface?", choices: ["Erosion", "A Volcano erupting", "A river forming", "Rocks wearing down"], answer: 1 },
    { id: "G2-SCI-54", grade: 2, subject: "Science", topic: "Earth", question: "What can help prevent wind erosion?", choices: ["Cutting down trees", "Planting grass and trees", "Removing rocks", "Digging holes"], answer: 1 },
    { id: "G2-SCI-55", grade: 2, subject: "Science", topic: "Earth", question: "What is a large, moving mass of ice?", choices: ["River", "Glacier", "Ice cube", "Ocean"], answer: 1 },
    { id: "G2-SCI-56", grade: 2, subject: "Science", topic: "Earth", question: "Where is liquid rock (lava) found?", choices: ["In a lake", "Inside a volcano", "In a cloud", "In a tree"], answer: 1 },
    { id: "G2-SCI-57", grade: 2, subject: "Science", topic: "Earth", question: "What happens during an earthquake?", choices: ["The ground shakes", "It rains a lot", "The sun disappears", "Trees grow fast"], answer: 0 },
    { id: "G2-SCI-58", grade: 2, subject: "Science", topic: "Earth", question: "What do we call the breaking down of rocks into smaller pieces?", choices: ["Weathering", "Polishing", "Gluing", "Painting"], answer: 0 },
    { id: "G2-SCI-59", grade: 2, subject: "Science", topic: "Earth", question: "Which of these is a landform?", choices: ["River", "Mountain", "Ocean", "Rain"], answer: 1 },
    { id: "G2-SCI-60", grade: 2, subject: "Science", topic: "Earth", question: "A 'Canyon' is often carved out by a...", choices: ["Mountain", "River", "Forest", "Cloud"], answer: 1 },
    { id: "G2-SCI-61", grade: 2, subject: "Science", topic: "Earth", question: "What is the top layer of the Earth where plants grow?", choices: ["Lava", "Soil", "Metal", "Ice"], answer: 1 },
    { id: "G2-SCI-62", grade: 2, subject: "Science", topic: "Earth", question: "How can water break a rock?", choices: ["By being blue", "By freezing in cracks and expanding", "By staying still", "It can't"], answer: 1 },
    { id: "G2-SCI-63", grade: 2, subject: "Science", topic: "Earth", question: "Which map shows the height of landforms?", choices: ["Road map", "Topographic map", "City map", "Star map"], answer: 1 },
    { id: "G2-SCI-64", grade: 2, subject: "Science", topic: "Earth", question: "What is a 'Plain'?", choices: ["A tall mountain", "A large area of flat land", "A deep hole", "A forest"], answer: 1 },
    { id: "G2-SCI-65", grade: 2, subject: "Science", topic: "Earth", question: "What does an 'extinct' volcano mean?", choices: ["It is erupting", "It will never erupt again", "It is very small", "It is made of water"], answer: 1 },
    { id: "G2-SCI-66", grade: 2, subject: "Science", topic: "Earth", question: "Which of these can cause erosion?", choices: ["Wind, Water, and Ice", "Sunlight only", "Moonlight", "Sound"], answer: 0 },
    { id: "G2-SCI-67", grade: 2, subject: "Science", topic: "Earth", question: "Where would you see a 'Delta'?", choices: ["On top of a mountain", "At the mouth of a river", "In a desert", "In a cave"], answer: 1 },
    { id: "G2-SCI-68", grade: 2, subject: "Science", topic: "Earth", question: "What do we call small bits of rock and soil moved by water?", choices: ["Lava", "Sediment", "Glaciers", "Boulders"], answer: 1 },
    { id: "G2-SCI-69", grade: 2, subject: "Science", topic: "Earth", question: "What is a landslide?", choices: ["When soil and rocks slide down a slope", "A type of dance", "A way to plant seeds", "A flat area"], answer: 0 },
    { id: "G2-SCI-70", grade: 2, subject: "Science", topic: "Earth", question: "Earth is mostly covered by:", choices: ["Sand", "Water", "Ice", "Forests"], answer: 1 },
    { id: "G2-SCI-71", grade: 2, subject: "Science", topic: "Earth", question: "What color is fertile soil usually?", choices: ["White", "Dark brown or black", "Bright red", "Yellow"], answer: 1 },
    { id: "G2-SCI-72", grade: 2, subject: "Science", topic: "Earth", question: "Which of these takes thousands of years?", choices: ["An earthquake", "A landslide", "Carving a canyon", "A lightning strike"], answer: 2 },
    { id: "G2-SCI-73", grade: 2, subject: "Science", topic: "Earth", question: "Where do we find most of Earth's liquid water?", choices: ["Glaciers", "Oceans", "Underground", "Clouds"], answer: 1 },
    { id: "G2-SCI-74", grade: 2, subject: "Science", topic: "Earth", question: "Can plants cause weathering?", choices: ["Yes, roots can grow into rock cracks", "No", "Only in the ocean", "Only at night"], answer: 0 },
    { id: "G2-SCI-75", grade: 2, subject: "Science", topic: "Earth", question: "What is the study of the Earth called?", choices: ["Biology", "Geology", "Chemistry", "Physics"], answer: 1 },

    // --- TOPIC 4: POLLINATION & SEED DISPERSAL (25 Questions) ---
    { id: "G2-SCI-76", grade: 2, subject: "Science", topic: "Plants", question: "What is it called when pollen is moved from one flower to another?", choices: ["Erosion", "Pollination", "Evaporation", "Hibernation"], answer: 1 },
    { id: "G2-SCI-77", grade: 2, subject: "Science", topic: "Plants", question: "Which of these is a common pollinator?", choices: ["Bee", "Spider", "Worm", "Fish"], answer: 0 },
    { id: "G2-SCI-78", grade: 2, subject: "Science", topic: "Plants", question: "How can seeds travel to new places?", choices: ["Wind", "Animals", "Water", "All of the above"], answer: 3 },
    { id: "G2-SCI-79", grade: 2, subject: "Science", topic: "Plants", question: "Why do flowers have bright colors and sweet smells?", choices: ["To hide", "To attract pollinators", "To stay warm", "To scare birds"], answer: 1 },
    { id: "G2-SCI-80", grade: 2, subject: "Science", topic: "Plants", question: "What is 'Seed Dispersal'?", choices: ["Planting seeds in a pot", "Moving seeds away from the parent plant", "Watering a seed", "Eating a seed"], answer: 1 },
    { id: "G2-SCI-81", grade: 2, subject: "Science", topic: "Plants", question: "Which animal might carry a seed in its fur?", choices: ["Fish", "Bird", "Squirrel", "Frog"], answer: 2 },
    { id: "G2-SCI-82", grade: 2, subject: "Science", topic: "Plants", question: "What part of the plant turns into a fruit?", choices: ["Leaf", "Stem", "Flower", "Root"], answer: 2 },
    { id: "G2-SCI-83", grade: 2, subject: "Science", topic: "Plants", question: "How does a dandelion disperse its seeds?", choices: ["By sticking to fur", "By floating in the wind", "By exploding", "By swimming"], answer: 1 },
    { id: "G2-SCI-84", grade: 2, subject: "Science", topic: "Plants", question: "What is inside a seed?", choices: ["Just food", "A tiny baby plant (embryo)", "A flower", "Soil"], answer: 1 },
    { id: "G2-SCI-85", grade: 2, subject: "Science", topic: "Plants", question: "Plants need water, light, and ___ to grow.", choices: ["Soda", "Space", "Toys", "Darkness"], answer: 1 },
    { id: "G2-SCI-86", grade: 2, subject: "Science", topic: "Plants", question: "What is the yellow dust found on flowers?", choices: ["Sand", "Pollen", "Sugar", "Dirt"], answer: 1 },
    { id: "G2-SCI-87", grade: 2, subject: "Science", topic: "Plants", question: "Which pollinator is most active at night?", choices: ["Butterfly", "Bee", "Moth", "Bird"], answer: 2 },
    { id: "G2-SCI-88", grade: 2, subject: "Science", topic: "Plants", question: "What happens during germination?", choices: ["A plant dies", "A seed starts to grow", "A flower opens", "A leaf falls"], answer: 1 },
    { id: "G2-SCI-89", grade: 2, subject: "Science", topic: "Plants", question: "Some seeds have 'hooks' to stick to animals. Which one does this?", choices: ["Maple seed", "Burdock/Burr", "Coconut", "Dandelion"], answer: 1 },
    { id: "G2-SCI-90", grade: 2, subject: "Science", topic: "Plants", question: "What do we call animals that move pollen?", choices: ["Predators", "Pollinators", "Producers", "Prey"], answer: 1 },
    { id: "G2-SCI-91", grade: 2, subject: "Science", topic: "Plants", question: "How does a coconut disperse its seed?", choices: ["Wind", "Water", "Animals", "Explosion"], answer: 1 },
    { id: "G2-SCI-92", grade: 2, subject: "Science", topic: "Plants", question: "Why do plants want their seeds to move far away?", choices: ["So they don't have to share sun and water", "Because seeds like to travel", "To be closer to the ocean", "They don't"], answer: 0 },
    { id: "G2-SCI-93", grade: 2, subject: "Science", topic: "Plants", question: "What do bees get from flowers?", choices: ["Nothing", "Nectar (food)", "Water", "Soil"], answer: 1 },
    { id: "G2-SCI-94", grade: 2, subject: "Science", topic: "Plants", question: "Which part of the plant grows first from a seed?", choices: ["Leaves", "Stem", "Roots", "Flower"], answer: 2 },
    { id: "G2-SCI-95", grade: 2, subject: "Science", topic: "Plants", question: "Do all plants have flowers?", choices: ["Yes", "No", "Only in the summer", "Only if they are red"], answer: 1 },
    { id: "G2-SCI-96", grade: 2, subject: "Science", topic: "Plants", question: "Which of these is a way humans help pollination?", choices: ["Cutting grass", "Keeping beehives", "Driving cars", "Watching TV"], answer: 1 },
    { id: "G2-SCI-97", grade: 2, subject: "Science", topic: "Plants", question: "What is nectar?", choices: ["A type of leaf", "A sugary liquid in flowers", "Pollen", "Water"], answer: 1 },
    { id: "G2-SCI-98", grade: 2, subject: "Science", topic: "Plants", question: "How do butterflies help plants?", choices: ["By eating leaves", "By moving pollen", "By laying eggs", "By flying"], answer: 1 },
    { id: "G2-SCI-99", grade: 2, subject: "Science", topic: "Plants", question: "Seeds need three things to sprout: Water, Oxygen, and ___.", choices: ["Sunlight", "Warmth", "Soda", "Salt"], answer: 1 },
    { id: "G2-SCI-100", grade: 2, subject: "Science", topic: "Plants", question: "Which of these is NOT a pollinator?", choices: ["Bat", "Hummingbird", "Rock", "Butterfly"], answer: 2 }
];

module.exports = G2_SCIENCE_COMPLETE;
