const G3_ELA_COMPLETE = [
    // --- TOPIC 1: PARTS OF SPEECH & GRAMMAR (25 Questions) ---
    { id: "G3-ELA-01", grade: 3, subject: "English", topic: "Grammar", question: "Which word is an adverb (describes an action)?", choices: ["Quick", "Quickly", "Runner", "Fastest"], answer: 1 },
    { id: "G3-ELA-02", grade: 3, subject: "English", topic: "Grammar", question: "Which of these is an 'Abstract Noun' (something you cannot touch)?", choices: ["Table", "Happiness", "Apple", "Dog"], answer: 1 },
    { id: "G3-ELA-03", grade: 3, subject: "English", topic: "Grammar", question: "Find the conjunction in this sentence: 'I like milk and cookies.'", choices: ["I", "like", "and", "cookies"], answer: 2 },
    { id: "G3-ELA-04", grade: 3, subject: "English", topic: "Grammar", question: "Which pronoun fits: 'The boys are here. ___ are playing.'", choices: ["He", "She", "It", "They"], answer: 3 },
    { id: "G3-ELA-05", grade: 3, subject: "English", topic: "Grammar", question: "What is the 'subject' of this sentence: 'The hungry cat meowed.'", choices: ["Hungry", "The cat", "Meowed", "The"], answer: 1 },
    { id: "G3-ELA-06", grade: 3, subject: "English", topic: "Grammar", question: "Which word is a verb?", choices: ["Elephant", "Beautiful", "Sprinted", "Slowly"], answer: 2 },
    { id: "G3-ELA-07", grade: 3, subject: "English", topic: "Grammar", question: "Find the adjective: 'The shiny trophy sat on the shelf.'", choices: ["Shiny", "Trophy", "Sat", "Shelf"], answer: 0 },
    { id: "G3-ELA-08", grade: 3, subject: "English", topic: "Grammar", question: "Which is a 'Proper Noun'?", choices: ["City", "Country", "Paris", "Street"], answer: 2 },
    { id: "G3-ELA-09", grade: 3, subject: "English", topic: "Grammar", question: "What is the plural of 'Child'?", choices: ["Childs", "Children", "Childrens", "Childes"], answer: 1 },
    { id: "G3-ELA-10", grade: 3, subject: "English", topic: "Grammar", question: "Choose the correct verb: 'She ___ to the park yesterday.'", choices: ["Go", "Goes", "Went", "Going"], answer: 2 },
    { id: "G3-ELA-11", grade: 3, subject: "English", topic: "Grammar", question: "Which word is a 'Preposition'?", choices: ["Under", "Run", "Blue", "And"], answer: 0 },
    { id: "G3-ELA-12", grade: 3, subject: "English", topic: "Grammar", question: "What does an adverb usually end with?", choices: ["-ed", "-ing", "-ly", "-s"], answer: 2 },
    { id: "G3-ELA-13", grade: 3, subject: "English", topic: "Grammar", question: "Which sentence uses the correct 'Subject-Verb' agreement?", choices: ["The dogs bark.", "The dogs barks.", "The dog bark.", "They barks."], answer: 0 },
    { id: "G3-ELA-14", grade: 3, subject: "English", topic: "Grammar", question: "What is the 'Predicate' of: 'The sun shines brightly.'", choices: ["The sun", "Shines brightly", "Sun", "Brightly"], answer: 1 },
    { id: "G3-ELA-15", grade: 3, subject: "English", topic: "Grammar", question: "Which is a collective noun?", choices: ["Person", "Team", "Building", "Ocean"], answer: 1 },
    { id: "G3-ELA-16", grade: 3, subject: "English", topic: "Grammar", question: "Find the 'helping verb': 'I am eating lunch.'", choices: ["I", "am", "eating", "lunch"], answer: 1 },
    { id: "G3-ELA-17", grade: 3, subject: "English", topic: "Grammar", question: "Which is a 'Compound Sentence'?", choices: ["I like pie.", "He ran home.", "I like tea, but she likes coffee.", "The dog barked."], answer: 2 },
    { id: "G3-ELA-18", grade: 3, subject: "English", topic: "Grammar", question: "What is the comparative form of 'Good'?", choices: ["Gooder", "Better", "Best", "Goodly"], answer: 1 },
    { id: "G3-ELA-19", grade: 3, subject: "English", topic: "Grammar", question: "What is the superlative form of 'Fast'?", choices: ["Faster", "Fastest", "Fastly", "More fast"], answer: 1 },
    { id: "G3-ELA-20", grade: 3, subject: "English", topic: "Grammar", question: "Which punctuation mark shows excitement?", choices: ["Period", "Comma", "Question Mark", "Exclamation Point"], answer: 3 },
    { id: "G3-ELA-21", grade: 3, subject: "English", topic: "Grammar", question: "Where do you put a comma in a date?", choices: ["After the month", "Between the day and the year", "After the year", "No commas"], answer: 1 },
    { id: "G3-ELA-22", grade: 3, subject: "English", topic: "Grammar", question: "Which word is an article?", choices: ["The", "Walk", "Pretty", "Today"], answer: 0 },
    { id: "G3-ELA-23", grade: 3, subject: "English", topic: "Grammar", question: "Choose the correct pronoun: '___ is my best friend.'", choices: ["Me", "Him", "He", "Us"], answer: 2 },
    { id: "G3-ELA-24", grade: 3, subject: "English", topic: "Grammar", question: "What is the past tense of 'Drink'?", choices: ["Drinked", "Drank", "Drunk", "Drinks"], answer: 1 },
    { id: "G3-ELA-25", grade: 3, subject: "English", topic: "Grammar", question: "Which is a 'Complex' word (has a prefix and suffix)?", choices: ["Happy", "Unhappily", "Unhappy", "Happily"], answer: 1 },

    // --- TOPIC 2: FIGURATIVE LANGUAGE (25 Questions) ---
    { id: "G3-ELA-26", grade: 3, subject: "English", topic: "Reading", question: "What is a 'Simile'?", choices: ["A type of smile", "A comparison using 'like' or 'as'", "A comparison NOT using 'like' or 'as'", "The opposite of a word"], answer: 1 },
    { id: "G3-ELA-27", grade: 3, subject: "English", topic: "Reading", question: "Identify the simile: 'She is as brave as a lion.'", choices: ["She is", "Brave as a lion", "Lions are brave", "No simile here"], answer: 1 },
    { id: "G3-ELA-28", grade: 3, subject: "English", topic: "Reading", question: "What is a 'Metaphor'?", choices: ["A comparison using 'like'", "A direct comparison saying one thing IS another", "A rhyming poem", "The name of a character"], answer: 1 },
    { id: "G3-ELA-29", grade: 3, subject: "English", topic: "Reading", question: "Identify the metaphor: 'The snow was a white blanket.'", choices: ["The snow was white", "The snow was a blanket", "Blankets are warm", "Like a blanket"], answer: 1 },
    { id: "G3-ELA-30", grade: 3, subject: "English", topic: "Reading", question: "What is an 'Idiom'?", choices: ["A word that sounds like a sound", "A phrase that means something different than the literal words", "A type of dictionary", "A story with animals"], answer: 1 },
    { id: "G3-ELA-31", grade: 3, subject: "English", topic: "Reading", question: "What does 'Break a leg' mean as an idiom?", choices: ["Go to the doctor", "Good luck", "Fall down", "You are hurt"], answer: 1 },
    { id: "G3-ELA-32", grade: 3, subject: "English", topic: "Reading", question: "What is 'Personification'?", choices: ["Writing a biography", "Giving human qualities to non-human things", "The main character", "Talking to a friend"], answer: 1 },
    { id: "G3-ELA-33", grade: 3, subject: "English", topic: "Reading", question: "Identify the personification: 'The wind whispered through the trees.'", choices: ["The wind whispered", "The trees were tall", "It was windy", "Walking in woods"], answer: 0 },
    { id: "G3-ELA-34", grade: 3, subject: "English", topic: "Reading", question: "What is an 'Onomatopoeia'?", choices: ["A long poem", "A word that imitates a sound (like Buzz)", "A type of metaphor", "A silent letter"], answer: 1 },
    { id: "G3-ELA-35", grade: 3, subject: "English", topic: "Reading", question: "Which word is an onomatopoeia?", choices: ["Jump", "Splash", "Run", "Fast"], answer: 1 },
    { id: "G3-ELA-36", grade: 3, subject: "English", topic: "Reading", question: "What is 'Alliteration'?", choices: ["Repeating vowel sounds", "Repeating the same starting consonant sounds", "A list of books", "A long sentence"], answer: 1 },
    { id: "G3-ELA-37", grade: 3, subject: "English", topic: "Reading", question: "Identify the alliteration: 'Peter Piper picked a peck...'", choices: ["Peter Piper picked", "He liked peppers", "It is a tongue twister", "Rhyming"], answer: 0 },
    { id: "G3-ELA-38", grade: 3, subject: "English", topic: "Reading", question: "A 'Literal' meaning is:", choices: ["A funny joke", "Exactly what the words say", "A secret code", "A fake story"], answer: 1 },
    { id: "G3-ELA-39", grade: 3, subject: "English", topic: "Reading", question: "What does 'It's raining cats and dogs' mean?", choices: ["Pets are falling from the sky", "It is raining very hard", "Animals are outside", "The weather is nice"], answer: 1 },
    { id: "G3-ELA-40", grade: 3, subject: "English", topic: "Reading", question: "What is the purpose of figurative language?", choices: ["To make writing more boring", "To make writing more descriptive and interesting", "To use fewer words", "To confuse the reader"], answer: 1 },
    { id: "G3-ELA-41", grade: 3, subject: "English", topic: "Reading", question: "Which is a simile?", choices: ["He is a rock.", "He is as strong as an ox.", "He is strong.", "The ox is strong."], answer: 1 },
    { id: "G3-ELA-42", grade: 3, subject: "English", topic: "Reading", question: "Which is a metaphor?", choices: ["You are like a star.", "You are a star.", "You shine bright.", "Stars are in the sky."], answer: 1 },
    { id: "G3-ELA-43", grade: 3, subject: "English", topic: "Reading", question: "What does 'A piece of cake' mean?", choices: ["A dessert", "Something very easy", "A birthday party", "To cut food"], answer: 1 },
    { id: "G3-ELA-44", grade: 3, subject: "English", topic: "Reading", question: "Which word 'sounds' like its meaning?", choices: ["Boom", "House", "Tree", "Book"], answer: 0 },
    { id: "G3-ELA-45", grade: 3, subject: "English", topic: "Reading", question: "In 'The stars danced in the sky,' what is 'dancing'?", choices: ["People", "The stars", "The moon", "The wind"], answer: 1 },
    { id: "G3-ELA-46", grade: 3, subject: "English", topic: "Reading", question: "A 'Hyperbole' is an extreme:", choices: ["Truth", "Exaggeration", "Understatement", "Question"], answer: 1 },
    { id: "G3-ELA-47", grade: 3, subject: "English", topic: "Reading", question: "Identify the hyperbole: 'I'm so hungry I could eat a horse!'", choices: ["I'm hungry", "Eat a horse", "I want lunch", "Like a horse"], answer: 1 },
    { id: "G3-ELA-48", grade: 3, subject: "English", topic: "Reading", question: "What is the opposite of 'Literal'?", choices: ["Real", "Non-literal / Figurative", "Simple", "Small"], answer: 1 },
    { id: "G3-ELA-49", grade: 3, subject: "English", topic: "Reading", question: "The phrase 'Busy as a bee' is a:", choices: ["Metaphor", "Simile", "Personification", "Onomatopoeia"], answer: 1 },
    { id: "G3-ELA-50", grade: 3, subject: "English", topic: "Reading", question: "The 'apple of my eye' is an example of an:", choices: ["Simile", "Idiom", "Alliteration", "Adverb"], answer: 1 },

    // --- TOPIC 3: POINT OF VIEW & TEXT STRUCTURE (25 Questions) ---
    { id: "G3-ELA-51", grade: 3, subject: "English", topic: "Reading", question: "What is 'First-Person' point of view?", choices: ["The author is a character (uses 'I' or 'me')", "The author is an outsider (uses 'he' or 'she')", "A story about a robot", "A news report"], answer: 0 },
    { id: "G3-ELA-52", grade: 3, subject: "English", topic: "Reading", question: "What is 'Third-Person' point of view?", choices: ["The narrator is in the story", "The narrator is an observer (uses 'they', 'he', 'she')", "The reader is the main character", "A poem"], answer: 1 },
    { id: "G3-ELA-53", grade: 3, subject: "English", topic: "Reading", question: "Which word signals 1st person point of view?", choices: ["He", "She", "I", "They"], answer: 2 },
    { id: "G3-ELA-54", grade: 3, subject: "English", topic: "Reading", question: "Which word signals 3rd person point of view?", choices: ["I", "Me", "We", "They"], answer: 3 },
    { id: "G3-ELA-55", grade: 3, subject: "English", topic: "Reading", question: "A story about 'Cause and Effect' explains:", choices: ["Where things are located", "Why something happened and what occurred because of it", "The life of a person", "A list of dates"], answer: 1 },
    { id: "G3-ELA-56", grade: 3, subject: "English", topic: "Reading", question: "What is 'Compare and Contrast'?", choices: ["Telling a story from the end", "Showing how things are alike and different", "Using big words", "Drawing a picture"], answer: 1 },
    { id: "G3-ELA-57", grade: 3, subject: "English", topic: "Reading", question: "A text structure that goes in time order is called:", choices: ["Chronological", "Random", "Persuasive", "Problem/Solution"], answer: 0 },
    { id: "G3-ELA-58", grade: 3, subject: "English", topic: "Reading", question: "Which structure presents a trouble and how to fix it?", choices: ["Cause/Effect", "Problem/Solution", "Compare/Contrast", "Description"], answer: 1 },
    { id: "G3-ELA-59", grade: 3, subject: "English", topic: "Reading", question: "A 'Paragraph' is a group of sentences about:", choices: ["Different topics", "One main idea", "Two different people", "The whole book"], answer: 1 },
    { id: "G3-ELA-60", grade: 3, subject: "English", topic: "Reading", question: "The 'Main Idea' is:", choices: ["The characters' names", "What the text is mostly about", "The first word of the story", "The author's favorite food"], answer: 1 },
    { id: "G3-ELA-61", grade: 3, subject: "English", topic: "Reading", question: "Supporting details are used to:", choices: ["Make the book longer", "Prove or explain the main idea", "Introduce new characters", "Change the ending"], answer: 1 },
    { id: "G3-ELA-62", grade: 3, subject: "English", topic: "Reading", question: "Where is the 'Topic Sentence' usually found?", choices: ["At the end", "In the middle", "At the beginning", "On the cover"], answer: 2 },
    { id: "G3-ELA-63", grade: 3, subject: "English", topic: "Reading", question: "Which is a 'Non-Fiction' text feature?", choices: ["Magic wands", "Table of Contents", "Talking animals", "Fairies"], answer: 1 },
    { id: "G3-ELA-64", grade: 3, subject: "English", topic: "Reading", question: "An 'Illustration' is a:", choices: ["Word", "Picture or drawing", "Chapter", "Title"], answer: 1 },
    { id: "G3-ELA-65", grade: 3, subject: "English", topic: "Reading", question: "A 'Caption' is text that:", choices: ["Is the title", "Explains a picture", "Is at the back of the book", "Is in a dictionary"], answer: 1 },
    { id: "G3-ELA-66", grade: 3, subject: "English", topic: "Reading", question: "What does 'Persuade' mean?", choices: ["To tell a funny story", "To try to get someone to think or do something", "To give facts", "To explain how to build a toy"], answer: 1 },
    { id: "G3-ELA-67", grade: 3, subject: "English", topic: "Reading", question: "What does 'Inform' mean?", choices: ["To trick someone", "To give facts and information", "To tell a scary story", "To sing a song"], answer: 1 },
    { id: "G3-ELA-68", grade: 3, subject: "English", topic: "Reading", question: "What is an 'Author's Purpose'?", choices: ["The price of the book", "The reason why the author wrote the text", "The name of the illustrator", "The number of pages"], answer: 1 },
    { id: "G3-ELA-69", grade: 3, subject: "English", topic: "Reading", question: "Which point of view uses 'You'?", choices: ["1st Person", "2nd Person", "3rd Person", "No Person"], answer: 1 },
    { id: "G3-ELA-70", grade: 3, subject: "English", topic: "Reading", question: "What is the 'Setting' of a story?", choices: ["The characters", "The time and place", "The problem", "The ending"], answer: 1 },
    { id: "G3-ELA-71", grade: 3, subject: "English", topic: "Reading", question: "The 'Plot' is:", choices: ["The sequence of events in a story", "The type of paper used", "The author's signature", "A small garden"], answer: 0 },
    { id: "G3-ELA-72", grade: 3, subject: "English", topic: "Reading", question: "The 'Resolution' of a story is:", choices: ["The beginning", "The middle", "How the problem is solved", "The table of contents"], answer: 2 },
    { id: "G3-ELA-73", grade: 3, subject: "English", topic: "Reading", question: "What is a 'Theme'?", choices: ["The title", "The lesson or message", "The main character's name", "The setting"], answer: 1 },
    { id: "G3-ELA-74", grade: 3, subject: "English", topic: "Reading", question: "A 'Dialogue' is when characters:", choices: ["Eat", "Sleep", "Talk to each other", "Run"], answer: 2 },
    { id: "G3-ELA-75", grade: 3, subject: "English", topic: "Reading", question: "Which word means 'the person who tells the story'?", choices: ["Author", "Narrator", "Editor", "Character"], answer: 1 },

    // --- TOPIC 4: VOCABULARY & WORD ANALYSIS (25 Questions) ---
    { id: "G3-ELA-76", grade: 3, subject: "English", topic: "Vocabulary", question: "What are 'Synonyms'?", choices: ["Words that mean the same", "Words that mean the opposite", "Words that sound the same", "Rhyming words"], answer: 0 },
    { id: "G3-ELA-77", grade: 3, subject: "English", topic: "Vocabulary", question: "What are 'Antonyms'?", choices: ["Words that mean the same", "Words that mean the opposite", "Words that rhyme", "Words with two meanings"], answer: 1 },
    { id: "G3-ELA-78", grade: 3, subject: "English", topic: "Vocabulary", question: "What are 'Homophones'?", choices: ["Words that mean the same", "Words that sound the same but have different meanings/spellings", "Opposite words", "Big words"], answer: 1 },
    { id: "G3-ELA-79", grade: 3, subject: "English", topic: "Vocabulary", question: "Which are homophones?", choices: ["Big / Large", "Sun / Son", "Hot / Cold", "Run / Ran"], answer: 1 },
    { id: "G3-ELA-80", grade: 3, subject: "English", topic: "Vocabulary", question: "What does the prefix 'pre-' mean?", choices: ["After", "Before", "Not", "Again"], answer: 1 },
    { id: "G3-ELA-81", grade: 3, subject: "English", topic: "Vocabulary", question: "What does the prefix 'mis-' mean?", choices: ["Correct", "Wrongly/Badly", "Again", "Not"], answer: 1 },
    { id: "G3-ELA-82", grade: 3, subject: "English", topic: "Vocabulary", question: "What does the suffix '-less' mean?", choices: ["Full of", "Without", "Able to", "State of"], answer: 1 },
    { id: "G3-ELA-83", grade: 3, subject: "English", topic: "Vocabulary", question: "What does the suffix '-able' mean?", choices: ["Full of", "Able to be", "Not", "Before"], answer: 1 },
    { id: "G3-ELA-84", grade: 3, subject: "English", topic: "Vocabulary", question: "What is a 'Root Word'?", choices: ["The ending of a word", "The base part of a word that has meaning", "A word about trees", "A silent letter"], answer: 1 },
    { id: "G3-ELA-85", grade: 3, subject: "English", topic: "Vocabulary", question: "In the word 'Replay', what is the root word?", choices: ["Re", "Play", "Ay", "Repl"], answer: 1 },
    { id: "G3-ELA-86", grade: 3, subject: "English", topic: "Vocabulary", question: "What does 'Bilingual' mean?", choices: ["Speaking one language", "Speaking two languages", "Speaking many languages", "Not speaking"], answer: 1 },
    { id: "G3-ELA-87", grade: 3, subject: "English", topic: "Vocabulary", question: "Which word is a synonym for 'Beautiful'?", choices: ["Ugly", "Pretty", "Mean", "Fast"], answer: 1 },
    { id: "G3-ELA-88", grade: 3, subject: "English", topic: "Vocabulary", question: "Which word is an antonym for 'Giant'?", choices: ["Huge", "Tiny", "Large", "Big"], answer: 1 },
    { id: "G3-ELA-89", grade: 3, subject: "English", topic: "Vocabulary", question: "Context clues are found:", choices: ["In a dictionary", "In the words around an unknown word", "On the cover", "In the index"], answer: 1 },
    { id: "G3-ELA-90", grade: 3, subject: "English", topic: "Vocabulary", question: "Which word uses the prefix 'dis-' correctly?", choices: ["Disapple", "Disagree", "Disrun", "Dishappy"], answer: 1 },
    { id: "G3-ELA-91", grade: 3, subject: "English", topic: "Vocabulary", question: "What does 'Tri-' mean as a prefix?", choices: ["One", "Two", "Three", "Four"], answer: 2 },
    { id: "G3-ELA-92", grade: 3, subject: "English", topic: "Vocabulary", question: "What does the suffix '-er' often mean in a job title (like Teacher)?", choices: ["Small", "One who does", "Not", "Again"], answer: 1 },
    { id: "G3-ELA-93", grade: 3, subject: "English", topic: "Vocabulary", question: "Which word is spelled correctly?", choices: ["Believe", "Beleeve", "Belive", "Beleive"], answer: 0 },
    { id: "G3-ELA-94", grade: 3, subject: "English", topic: "Vocabulary", question: "What are 'Compound Words'?", choices: ["Two words put together to make a new word", "Words that rhyme", "Short words", "Words with prefixes"], answer: 0 },
    { id: "G3-ELA-95", grade: 3, subject: "English", topic: "Vocabulary", question: "Which is a compound word?", choices: ["Skateboard", "Running", "Happy", "Teacher"], answer: 0 },
    { id: "G3-ELA-96", grade: 3, subject: "English", topic: "Vocabulary", question: "The word 'Unlucky' means:", choices: ["Very lucky", "Not lucky", "Lucky again", "Lucky before"], answer: 1 },
    { id: "G3-ELA-97", grade: 3, subject: "English", topic: "Vocabulary", question: "Which homophone fits: 'I want to go ___ the store.'", choices: ["Two", "Too", "To", "Toe"], answer: 2 },
    { id: "G3-ELA-98", grade: 3, subject: "English", topic: "Vocabulary", question: "Which homophone fits: 'The ___ is very bright today.'", choices: ["Sun", "Son", "Soon", "Seen"], answer: 0 },
    { id: "G3-ELA-99", grade: 3, subject: "English", topic: "Vocabulary", question: "What does 'non-' mean?", choices: ["With", "Not", "Again", "Very"], answer: 1 },
    { id: "G3-ELA-100", grade: 3, subject: "English", topic: "Vocabulary", question: "Which word means 'to write again'?", choices: ["Prewrite", "Rewrite", "Unwrite", "Writer"], answer: 1 }
];

module.exports = G3_ELA_COMPLETE;
