const G3_MATH_COMPLETE = [
    // --- TOPIC 1: MULTIPLICATION & DIVISION (25 Questions) ---
    { id: "G3-MA-01", grade: 3, subject: "Math", topic: "Multiplication", question: "What is 5 x 4?", choices: ["9", "15", "20", "25"], answer: 2 },
    { id: "G3-MA-02", grade: 3, subject: "Math", topic: "Division", question: "What is 12 ÷ 3?", choices: ["3", "4", "6", "9"], answer: 1 },
    { id: "G3-MA-03", grade: 3, subject: "Math", topic: "Multiplication", question: "Any number multiplied by 0 is...", choices: ["The same number", "0", "1", "10"], answer: 1 },
    { id: "G3-MA-04", grade: 3, subject: "Math", topic: "Multiplication", question: "What is 9 x 2?", choices: ["11", "16", "18", "20"], answer: 2 },
    { id: "G3-MA-05", grade: 3, subject: "Math", topic: "Multiplication", question: "Which is the same as 3 + 3 + 3 + 3?", choices: ["3 x 3", "4 x 3", "3 + 4", "3 x 5"], answer: 1 },
    { id: "G3-MA-06", grade: 3, subject: "Math", topic: "Division", question: "What is 20 ÷ 5?", choices: ["2", "4", "5", "10"], answer: 1 },
    { id: "G3-MA-07", grade: 3, subject: "Math", topic: "Multiplication", question: "What is 10 x 7?", choices: ["17", "70", "107", "700"], answer: 1 },
    { id: "G3-MA-08", grade: 3, subject: "Math", topic: "Multiplication", question: "If 3 x 8 = 24, then 24 ÷ 3 = _?", choices: ["3", "8", "24", "11"], answer: 1 },
    { id: "G3-MA-09", grade: 3, subject: "Math", topic: "Multiplication", question: "What is 6 x 3?", choices: ["9", "12", "18", "21"], answer: 2 },
    { id: "G3-MA-10", grade: 3, subject: "Math", topic: "Multiplication", question: "What property says 2 x 5 is the same as 5 x 2?", choices: ["Zero Property", "Commutative Property", "Identity Property", "Grouping Property"], answer: 1 },
    { id: "G3-MA-11", grade: 3, subject: "Math", topic: "Division", question: "What is 45 ÷ 5?", choices: ["7", "8", "9", "10"], answer: 2 },
    { id: "G3-MA-12", grade: 3, subject: "Math", topic: "Multiplication", question: "What is 8 x 5?", choices: ["35", "40", "45", "50"], answer: 1 },
    { id: "G3-MA-13", grade: 3, subject: "Math", topic: "Multiplication", question: "What is 7 x 3?", choices: ["10", "21", "24", "27"], answer: 1 },
    { id: "G3-MA-14", grade: 3, subject: "Math", topic: "Division", question: "What is 18 ÷ 2?", choices: ["7", "8", "9", "10"], answer: 2 },
    { id: "G3-MA-15", grade: 3, subject: "Math", topic: "Multiplication", question: "What is 4 x 4?", choices: ["8", "12", "16", "20"], answer: 2 },
    { id: "G3-MA-16", grade: 3, subject: "Math", topic: "Multiplication", question: "What is 0 x 100?", choices: ["0", "1", "100", "1000"], answer: 0 },
    { id: "G3-MA-17", grade: 3, subject: "Math", topic: "Multiplication", question: "What is 1 x 55?", choices: ["0", "1", "55", "56"], answer: 2 },
    { id: "G3-MA-18", grade: 3, subject: "Math", topic: "Division", question: "What is 30 ÷ 10?", choices: ["3", "10", "20", "30"], answer: 0 },
    { id: "G3-MA-19", grade: 3, subject: "Math", topic: "Multiplication", question: "Solve: 2 x 2 x 2", choices: ["4", "6", "8", "10"], answer: 2 },
    { id: "G3-MA-20", grade: 3, subject: "Math", topic: "Division", question: "What is 14 ÷ 7?", choices: ["1", "2", "3", "4"], answer: 1 },
    { id: "G3-MA-21", grade: 3, subject: "Math", topic: "Multiplication", question: "What is 9 x 3?", choices: ["12", "18", "24", "27"], answer: 3 },
    { id: "G3-MA-22", grade: 3, subject: "Math", topic: "Multiplication", question: "What is 6 x 4?", choices: ["20", "24", "28", "32"], answer: 1 },
    { id: "G3-MA-23", grade: 3, subject: "Math", topic: "Division", question: "What is 24 ÷ 4?", choices: ["4", "6", "8", "12"], answer: 1 },
    { id: "G3-MA-24", grade: 3, subject: "Math", topic: "Multiplication", question: "What is 5 x 5?", choices: ["10", "20", "25", "30"], answer: 2 },
    { id: "G3-MA-25", grade: 3, subject: "Math", topic: "Division", question: "What is 50 ÷ 5?", choices: ["5", "10", "15", "20"], answer: 1 },

    // --- TOPIC 2: FRACTIONS (25 Questions) ---
    { id: "G3-MA-26", grade: 3, subject: "Math", topic: "Fractions", question: "In the fraction 1/4, what is the number 4 called?", choices: ["Numerator", "Denominator", "Whole", "Half"], answer: 1 },
    { id: "G3-MA-27", grade: 3, subject: "Math", topic: "Fractions", question: "In the fraction 2/3, what is the number 2 called?", choices: ["Denominator", "Whole", "Numerator", "Half"], answer: 2 },
    { id: "G3-MA-28", grade: 3, subject: "Math", topic: "Fractions", question: "Which fraction represents a half?", choices: ["1/1", "1/2", "1/3", "1/4"], answer: 1 },
    { id: "G3-MA-29", grade: 3, subject: "Math", topic: "Fractions", question: "If you cut a pizza into 8 equal slices and eat 1, what fraction is left?", choices: ["1/8", "7/8", "8/8", "1/7"], answer: 1 },
    { id: "G3-MA-30", grade: 3, subject: "Math", topic: "Fractions", question: "Which is larger: 1/2 or 1/4?", choices: ["1/2", "1/4", "They are equal", "Neither"], answer: 0 },
    { id: "G3-MA-31", grade: 3, subject: "Math", topic: "Fractions", question: "What is 4/4 equal to?", choices: ["0", "1/4", "1", "4"], answer: 2 },
    { id: "G3-MA-32", grade: 3, subject: "Math", topic: "Fractions", question: "Which fraction is equal to 2/4?", choices: ["1/2", "1/3", "1/4", "2/2"], answer: 0 },
    { id: "G3-MA-33", grade: 3, subject: "Math", topic: "Fractions", question: "How many thirds make a whole?", choices: ["1", "2", "3", "4"], answer: 2 },
    { id: "G3-MA-34", grade: 3, subject: "Math", topic: "Fractions", question: "What fraction of a dollar is a quarter?", choices: ["1/2", "1/4", "1/10", "1/5"], answer: 1 },
    { id: "G3-MA-35", grade: 3, subject: "Math", topic: "Fractions", question: "Where does the numerator sit?", choices: ["Top", "Bottom", "Middle", "Side"], answer: 0 },
    { id: "G3-MA-36", grade: 3, subject: "Math", topic: "Fractions", question: "What is 1/3 + 1/3?", choices: ["1/6", "2/6", "2/3", "1/3"], answer: 2 },
    { id: "G3-MA-37", grade: 3, subject: "Math", topic: "Fractions", question: "Which fraction is the smallest?", choices: ["1/2", "1/3", "1/4", "1/8"], answer: 3 },
    { id: "G3-MA-38", grade: 3, subject: "Math", topic: "Fractions", question: "Is 3/1 the same as 3?", choices: ["Yes", "No", "Only for even numbers", "Never"], answer: 0 },
    { id: "G3-MA-39", grade: 3, subject: "Math", topic: "Fractions", question: "How many fourths are in 2 wholes?", choices: ["4", "6", "8", "10"], answer: 2 },
    { id: "G3-MA-40", grade: 3, subject: "Math", topic: "Fractions", question: "Which fraction represents 'three fourths'?", choices: ["3/1", "1/3", "3/4", "4/3"], answer: 2 },
    { id: "G3-MA-41", grade: 3, subject: "Math", topic: "Fractions", question: "What is 1 - 1/4?", choices: ["0", "1/4", "2/4", "3/4"], answer: 3 },
    { id: "G3-MA-42", grade: 3, subject: "Math", topic: "Fractions", question: "Which represents one sixth?", choices: ["1/6", "6/1", "1/16", "6/6"], answer: 0 },
    { id: "G3-MA-43", grade: 3, subject: "Math", topic: "Fractions", question: "If the numerator and denominator are the same, the fraction equals...", choices: ["Zero", "One", "Ten", "Infinity"], answer: 1 },
    { id: "G3-MA-44", grade: 3, subject: "Math", topic: "Fractions", question: "Divide 1 into 10 equal parts. Each part is...", choices: ["1/2", "1/5", "1/10", "10/1"], answer: 2 },
    { id: "G3-MA-45", grade: 3, subject: "Math", topic: "Fractions", question: "Which fraction is equivalent to 1?", choices: ["0/1", "1/2", "5/5", "1/5"], answer: 2 },
    { id: "G3-MA-46", grade: 3, subject: "Math", topic: "Fractions", question: "What is the numerator in 5/8?", choices: ["5", "8", "13", "3"], answer: 0 },
    { id: "G3-MA-47", grade: 3, subject: "Math", topic: "Fractions", question: "What is the denominator in 7/9?", choices: ["7", "9", "16", "2"], answer: 1 },
    { id: "G3-MA-48", grade: 3, subject: "Math", topic: "Fractions", question: "Which is closer to 1: 1/10 or 9/10?", choices: ["1/10", "9/10", "Both are equal", "Neither"], answer: 1 },
    { id: "G3-MA-49", grade: 3, subject: "Math", topic: "Fractions", question: "How do you write 'two fifths'?", choices: ["2/1", "2/5", "5/2", "1/5"], answer: 1 },
    { id: "G3-MA-50", grade: 3, subject: "Math", topic: "Fractions", question: "Compare: 1/3 _ 1/2", choices: [">", "<", "=", "+"], answer: 1 },

    // --- TOPIC 3: MEASUREMENT, AREA & PERIMETER (25 Questions) ---
    { id: "G3-MA-51", grade: 3, subject: "Math", topic: "Geometry", question: "What is the perimeter of a square with 3-inch sides?", choices: ["6 inches", "9 inches", "12 inches", "15 inches"], answer: 2 },
    { id: "G3-MA-52", grade: 3, subject: "Math", topic: "Geometry", question: "How do you find the Area of a rectangle?", choices: ["Add all sides", "Length x Width", "Length + Width", "Side x 3"], answer: 1 },
    { id: "G3-MA-53", grade: 3, subject: "Math", topic: "Geometry", question: "What is the area of a rectangle that is 5cm long and 2cm wide?", choices: ["7 sq cm", "10 sq cm", "14 sq cm", "20 sq cm"], answer: 1 },
    { id: "G3-MA-54", grade: 3, subject: "Math", topic: "Geometry", question: "Perimeter is the distance ____ a shape.", choices: ["Inside", "Around the outside", "Through the middle", "Above"], answer: 1 },
    { id: "G3-MA-55", grade: 3, subject: "Math", topic: "Geometry", question: "Area is the space ____ a shape.", choices: ["Inside", "Around", "Under", "Beside"], answer: 0 },
    { id: "G3-MA-56", grade: 3, subject: "Math", topic: "Measurement", question: "What is the mass of a paperclip roughly?", choices: ["1 gram", "1 kilogram", "1 pound", "1 ton"], answer: 0 },
    { id: "G3-MA-57", grade: 3, subject: "Math", topic: "Measurement", question: "How many grams are in 1 kilogram?", choices: ["10", "100", "1000", "10000"], answer: 2 },
    { id: "G3-MA-58", grade: 3, subject: "Math", topic: "Measurement", question: "Which unit measures liquid volume?", choices: ["Grams", "Liters", "Meters", "Degrees"], answer: 1 },
    { id: "G3-MA-59", grade: 3, subject: "Math", topic: "Geometry", question: "A polygon with 4 sides is called a:", choices: ["Triangle", "Pentagon", "Quadrilateral", "Hexagon"], answer: 2 },
    { id: "G3-MA-60", grade: 3, subject: "Math", topic: "Geometry", question: "How many sides does a pentagon have?", choices: ["4", "5", "6", "8"], answer: 1 },
    { id: "G3-MA-61", grade: 3, subject: "Math", topic: "Measurement", question: "What time is 30 minutes after 1:15?", choices: ["1:30", "1:45", "2:00", "2:15"], answer: 1 },
    { id: "G3-MA-62", grade: 3, subject: "Math", topic: "Geometry", question: "A triangle with a 90-degree angle is a:", choices: ["Wrong triangle", "Right triangle", "Left triangle", "Acute triangle"], answer: 1 },
    { id: "G3-MA-63", grade: 3, subject: "Math", topic: "Measurement", question: "How many milliliters are in 1 liter?", choices: ["10", "100", "1000", "500"], answer: 2 },
    { id: "G3-MA-64", grade: 3, subject: "Math", topic: "Geometry", question: "Find the perimeter of a triangle with sides 5, 5, and 5.", choices: ["10", "15", "20", "25"], answer: 1 },
    { id: "G3-MA-65", grade: 3, subject: "Math", topic: "Geometry", question: "Which shape is a quadrilateral?", choices: ["Circle", "Triangle", "Rectangle", "Hexagon"], answer: 2 },
    { id: "G3-MA-66", grade: 3, subject: "Math", topic: "Measurement", question: "Which is heavier: 1 kilogram or 1 gram?", choices: ["1 kilogram", "1 gram", "Same", "Neither"], answer: 0 },
    { id: "G3-MA-67", grade: 3, subject: "Math", topic: "Geometry", question: "How many vertices does a cube have?", choices: ["4", "6", "8", "12"], answer: 2 },
    { id: "G3-MA-68", grade: 3, subject: "Math", topic: "Measurement", question: "If a movie starts at 4:00 and lasts 2 hours, it ends at:", choices: ["5:00", "6:00", "7:00", "8:00"], answer: 1 },
    { id: "G3-MA-69", grade: 3, subject: "Math", topic: "Geometry", question: "A hexagon has how many angles?", choices: ["4", "5", "6", "8"], answer: 2 },
    { id: "G3-MA-70", grade: 3, subject: "Math", topic: "Measurement", question: "What tool measures the mass of an object?", choices: ["Ruler", "Scale", "Clock", "Compass"], answer: 1 },
    { id: "G3-MA-71", grade: 3, subject: "Math", topic: "Geometry", question: "Which shape has 8 sides?", choices: ["Hexagon", "Pentagon", "Octagon", "Square"], answer: 2 },
    { id: "G3-MA-72", grade: 3, subject: "Math", topic: "Measurement", question: "How many minutes are in 2 hours?", choices: ["60", "100", "120", "200"], answer: 2 },
    { id: "G3-MA-73", grade: 3, subject: "Math", topic: "Geometry", question: "Area is measured in ____ units.", choices: ["Linear", "Square", "Cubic", "Round"], answer: 1 },
    { id: "G3-MA-74", grade: 3, subject: "Math", topic: "Measurement", question: "If you have two 500ml bottles, how many liters do you have?", choices: ["1 Liter", "2 Liters", "5 Liters", "10 Liters"], answer: 0 },
    { id: "G3-MA-75", grade: 3, subject: "Math", topic: "Geometry", question: "Parallel lines...", choices: ["Cross each other", "Never cross each other", "Are always short", "Form a circle"], answer: 1 },

    // --- TOPIC 4: PLACE VALUE & ROUNDING (25 Questions) ---
    { id: "G3-MA-76", grade: 3, subject: "Math", topic: "Place Value", question: "What is 456 rounded to the nearest ten?", choices: ["450", "460", "500", "400"], answer: 1 },
    { id: "G3-MA-77", grade: 3, subject: "Math", topic: "Place Value", question: "What is 782 rounded to the nearest hundred?", choices: ["700", "780", "800", "900"], answer: 2 },
    { id: "G3-MA-78", grade: 3, subject: "Math", topic: "Place Value", question: "In 5,231, which digit is in the thousands place?", choices: ["5", "2", "3", "1"], answer: 0 },
    { id: "G3-MA-79", grade: 3, subject: "Math", topic: "Place Value", question: "What is 1,000 + 400 + 20 + 9?", choices: ["1429", "10429", "14029", "14209"], answer: 0 },
    { id: "G3-MA-80", grade: 3, subject: "Math", topic: "Place Value", question: "Round 15 to the nearest ten.", choices: ["10", "20", "15", "0"], answer: 1 },
    { id: "G3-MA-81", grade: 3, subject: "Math", topic: "Place Value", question: "What is the value of the 7 in 7,402?", choices: ["7", "70", "700", "7000"], answer: 3 },
    { id: "G3-MA-82", grade: 3, subject: "Math", topic: "Place Value", question: "Which number is greater than 5,089?", choices: ["5,088", "5,090", "4,999", "5,000"], answer: 1 },
    { id: "G3-MA-83", grade: 3, subject: "Math", topic: "Place Value", question: "Round 99 to the nearest ten.", choices: ["90", "100", "95", "110"], answer: 1 },
    { id: "G3-MA-84", grade: 3, subject: "Math", topic: "Place Value", question: "Round 321 to the nearest hundred.", choices: ["300", "400", "320", "350"], answer: 0 },
    { id: "G3-MA-85", grade: 3, subject: "Math", topic: "Place Value", question: "What is 100 more than 2,900?", choices: ["2,910", "3,000", "2,800", "3,100"], answer: 1 },
    { id: "G3-MA-86", grade: 3, subject: "Math", topic: "Place Value", question: "Which digit is in the tens place of 8,142?", choices: ["8", "1", "4", "2"], answer: 2 },
    { id: "G3-MA-87", grade: 3, subject: "Math", topic: "Place Value", question: "What is the smallest 4-digit number?", choices: ["1000", "1111", "9999", "1001"], answer: 0 },
    { id: "G3-MA-88", grade: 3, subject: "Math", topic: "Place Value", question: "Round 2,450 to the nearest thousand.", choices: ["2,000", "3,000", "2,500", "2,400"], answer: 0 },
    { id: "G3-MA-89", grade: 3, subject: "Math", topic: "Place Value", question: "What is 10 less than 5,000?", choices: ["4,990", "5,010", "4,900", "4,000"], answer: 0 },
    { id: "G3-MA-90", grade: 3, subject: "Math", topic: "Place Value", question: "In the number 6,789, what is the value of 8?", choices: ["8", "80", "800", "8000"], answer: 1 },
    { id: "G3-MA-91", grade: 3, subject: "Math", topic: "Place Value", question: "Round 84 to the nearest ten.", choices: ["80", "90", "85", "100"], answer: 0 },
    { id: "G3-MA-92", grade: 3, subject: "Math", topic: "Place Value", question: "What is 4,000 + 60 + 2?", choices: ["462", "4062", "4602", "40062"], answer: 1 },
    { id: "G3-MA-93", grade: 3, subject: "Math", topic: "Place Value", question: "Which number is even?", choices: ["4,501", "3,222", "1,113", "7,775"], answer: 1 },
    { id: "G3-MA-94", grade: 3, subject: "Math", topic: "Place Value", question: "What is 5,123 in word form?", choices: ["Five thousand one hundred twenty three", "Fifty one hundred two three", "Five one two three", "Five thousand twelve three"], answer: 0 },
    { id: "G3-MA-95", grade: 3, subject: "Math", topic: "Place Value", question: "Which is true?", choices: ["1,200 > 1,300", "4,500 < 4,050", "2,999 < 3,000", "1,000 = 100"], answer: 2 },
    { id: "G3-MA-96", grade: 3, subject: "Math", topic: "Place Value", question: "What is 500 rounded to the nearest hundred?", choices: ["400", "500", "600", "1000"], answer: 1 },
    { id: "G3-MA-97", grade: 3, subject: "Math", topic: "Place Value", question: "Round 6,800 to the nearest thousand.", choices: ["6,000", "7,000", "6,500", "7,500"], answer: 1 },
    { id: "G3-MA-98", grade: 3, subject: "Math", topic: "Place Value", question: "Which digit is in the hundreds place of 9,012?", choices: ["9", "0", "1", "2"], answer: 1 },
    { id: "G3-MA-99", grade: 3, subject: "Math", topic: "Place Value", question: "What is 1,000 more than 8,500?", choices: ["8,600", "9,500", "7,500", "10,500"], answer: 1 },
    { id: "G3-MA-100", grade: 3, subject: "Math", topic: "Place Value", question: "What is the largest 4-digit number?", choices: ["1000", "9000", "9999", "10000"], answer: 2 }
];

module.exports = G3_MATH_COMPLETE;
