const G3_SCIENCE_COMPLETE = [
    // --- TOPIC 1: LIFE CYCLES & HEREDITY (25 Questions) ---
    { id: "G3-SCI-01", grade: 3, subject: "Science", topic: "Life Cycles", question: "Which stage comes after the egg in a butterfly's life cycle?", choices: ["Pupa", "Larva (Caterpillar)", "Adult", "Seed"], answer: 1 },
    { id: "G3-SCI-02", grade: 3, subject: "Science", topic: "Life Cycles", question: "What is metamorphosis?", choices: ["A type of rock", "A major change in body shape during a life cycle", "The way plants make food", "A planet"], answer: 1 },
    { id: "G3-SCI-03", grade: 3, subject: "Science", topic: "Heredity", question: "Traits like eye color are passed from parents to offspring. This is called:", choices: ["Selection", "Inheritance", "Environment", "Habit"], answer: 1 },
    { id: "G3-SCI-04", grade: 3, subject: "Science", topic: "Life Cycles", question: "Which animal undergoes 'incomplete' metamorphosis (no pupa stage)?", choices: ["Butterfly", "Moth", "Grasshopper", "Bee"], answer: 2 },
    { id: "G3-SCI-05", grade: 3, subject: "Science", topic: "Adaptation", question: "Why do some animals hibernate in winter?", choices: ["To have fun", "To save energy when food is scarce", "To find a mate", "To grow thicker fur"], answer: 1 },
    { id: "G3-SCI-06", grade: 3, subject: "Science", topic: "Life Cycles", question: "What do we call the stage where a caterpillar builds a hard shell?", choices: ["Egg", "Larva", "Pupa (Chrysalis)", "Adult"], answer: 2 },
    { id: "G3-SCI-07", grade: 3, subject: "Science", topic: "Adaptation", question: "A polar bear's white fur is an example of:", choices: ["Camouflage", "Hibernation", "Pollination", "Metamorphosis"], answer: 0 },
    { id: "G3-SCI-08", grade: 3, subject: "Science", topic: "Life Cycles", question: "How does a frog breathe when it is a tadpole?", choices: ["Lungs", "Gills", "Skin only", "It doesn't breathe"], answer: 1 },
    { id: "G3-SCI-09", grade: 3, subject: "Science", topic: "Heredity", question: "Which of these is an 'acquired' trait (not inherited)?", choices: ["Hair color", "A scar from a fall", "Height", "Shape of nose"], answer: 1 },
    { id: "G3-SCI-10", grade: 3, subject: "Science", topic: "Adaptation", question: "What is the purpose of a cactus having spines?", choices: ["To look pretty", "To collect rain", "To protect itself from being eaten", "To help it grow tall"], answer: 2 },
    { id: "G3-SCI-11", grade: 3, subject: "Science", topic: "Life Cycles", question: "Which part of a plant life cycle involves a seed starting to grow?", choices: ["Pollination", "Germination", "Photosynthesis", "Death"], answer: 1 },
    { id: "G3-SCI-12", grade: 3, subject: "Science", topic: "Ecosystems", question: "An animal that is hunted and eaten by another animal is called:", choices: ["Predator", "Prey", "Producer", "Herbivore"], answer: 1 },
    { id: "G3-SCI-13", grade: 3, subject: "Science", topic: "Adaptation", question: "Mimicry is when an animal:", choices: ["Sleeps all winter", "Looks like another dangerous animal to stay safe", "Moves to a warmer place", "Changes color"], answer: 1 },
    { id: "G3-SCI-14", grade: 3, subject: "Science", topic: "Heredity", question: "Offspring usually look like their parents because of:", choices: ["Diet", "Genes", "Exercise", "Luck"], answer: 1 },
    { id: "G3-SCI-15", grade: 3, subject: "Science", topic: "Life Cycles", question: "Most mammals are born:", choices: ["From eggs", "Live", "In cocoons", "From seeds"], answer: 1 },
    { id: "G3-SCI-16", grade: 3, subject: "Science", topic: "Adaptation", question: "Webbed feet on a duck are an adaptation for:", choices: ["Flying", "Swimming", "Walking on sand", "Climbing trees"], answer: 1 },
    { id: "G3-SCI-17", grade: 3, subject: "Science", topic: "Ecosystems", question: "What is the primary source of energy for almost all food chains?", choices: ["Water", "Soil", "The Sun", "Plants"], answer: 2 },
    { id: "G3-SCI-18", grade: 3, subject: "Science", topic: "Life Cycles", question: "How many stages are in 'complete' metamorphosis?", choices: ["2", "3", "4", "5"], answer: 2 },
    { id: "G3-SCI-19", grade: 3, subject: "Science", topic: "Adaptation", question: "Migration is when animals:", choices: ["Sleep for a long time", "Travel to another place for food or weather", "Change their skin color", "Grow larger"], answer: 1 },
    { id: "G3-SCI-20", grade: 3, subject: "Science", topic: "Ecosystems", question: "Organisms that break down dead plants and animals are:", choices: ["Producers", "Consumers", "Decomposers", "Predators"], answer: 2 },
    { id: "G3-SCI-21", grade: 3, subject: "Science", topic: "Heredity", question: "Which is a behavioral trait (not physical)?", choices: ["Bird building a nest", "Blue feathers", "Long beak", "Sharp claws"], answer: 0 },
    { id: "G3-SCI-22", grade: 3, subject: "Science", topic: "Life Cycles", question: "A conifer tree produces seeds in:", choices: ["Flowers", "Cones", "Leaves", "Roots"], answer: 1 },
    { id: "G3-SCI-23", grade: 3, subject: "Science", topic: "Adaptation", question: "Blubber helps whales:", choices: ["Swim faster", "Stay warm in cold water", "Breath underwater", "Find food"], answer: 1 },
    { id: "G3-SCI-24", grade: 3, subject: "Science", topic: "Ecosystems", question: "All the living and nonliving things in an area make up:", choices: ["A population", "A community", "An ecosystem", "A habitat"], answer: 2 },
    { id: "G3-SCI-25", grade: 3, subject: "Science", topic: "Life Cycles", question: "What is the adult stage of a tadpole?", choices: ["Fish", "Newt", "Frog", "Lizard"], answer: 2 },

    // --- TOPIC 2: PLANETS & THE SOLAR SYSTEM (25 Questions) ---
    { id: "G3-SCI-26", grade: 3, subject: "Science", topic: "Space", question: "Which planet is known as the 'Red Planet'?", choices: ["Venus", "Mars", "Jupiter", "Saturn"], answer: 1 },
    { id: "G3-SCI-27", grade: 3, subject: "Science", topic: "Space", question: "How long does it take Earth to orbit the Sun once?", choices: ["One day", "One month", "One year", "Ten years"], answer: 2 },
    { id: "G3-SCI-28", grade: 3, subject: "Science", topic: "Space", question: "Earth's rotation on its axis causes:", choices: ["The seasons", "Day and night", "Eclipses", "Tides"], answer: 1 },
    { id: "G3-SCI-29", grade: 3, subject: "Science", topic: "Space", question: "Which is the largest planet in our solar system?", choices: ["Earth", "Neptune", "Jupiter", "Saturn"], answer: 2 },
    { id: "G3-SCI-30", grade: 3, subject: "Science", topic: "Space", question: "What is at the center of our solar system?", choices: ["The Earth", "The Moon", "The Sun", "A Black Hole"], answer: 2 },
    { id: "G3-SCI-31", grade: 3, subject: "Science", topic: "Space", question: "Which planet is closest to the Sun?", choices: ["Venus", "Mars", "Mercury", "Earth"], answer: 2 },
    { id: "G3-SCI-32", grade: 3, subject: "Science", topic: "Space", question: "The Moon shines because it:", choices: ["Produces its own light", "Reflects light from the Sun", "Is made of hot gas", "Reflects light from Earth"], answer: 1 },
    { id: "G3-SCI-33", grade: 3, subject: "Science", topic: "Space", question: "Which planet is famous for its bright, beautiful rings?", choices: ["Uranus", "Jupiter", "Saturn", "Mars"], answer: 2 },
    { id: "G3-SCI-34", grade: 3, subject: "Science", topic: "Space", question: "A scientist who studies space is called an:", choices: ["Astrologer", "Astronomer", "Geologist", "Biologist"], answer: 1 },
    { id: "G3-SCI-35", grade: 3, subject: "Science", topic: "Space", question: "Which is the 'hottest' planet due to its thick atmosphere?", choices: ["Mercury", "Venus", "Mars", "Jupiter"], answer: 1 },
    { id: "G3-SCI-36", grade: 3, subject: "Science", topic: "Space", question: "How many planets are in our solar system?", choices: ["7", "8", "9", "10"], answer: 1 },
    { id: "G3-SCI-37", grade: 3, subject: "Science", topic: "Space", question: "What do we call the different shapes the moon appears to have?", choices: ["Cycles", "Stages", "Phases", "Faces"], answer: 2 },
    { id: "G3-SCI-38", grade: 3, subject: "Science", topic: "Space", question: "Which planet is known as the 'Blue Planet'?", choices: ["Neptune", "Uranus", "Earth", "Venus"], answer: 2 },
    { id: "G3-SCI-39", grade: 3, subject: "Science", topic: "Space", question: "The path a planet takes around the Sun is its:", choices: ["Axis", "Orbit", "Rotation", "Spin"], answer: 1 },
    { id: "G3-SCI-40", grade: 3, subject: "Science", topic: "Space", question: "Stars are made mostly of:", choices: ["Rock", "Ice", "Hot glowing gases", "Liquid water"], answer: 2 },
    { id: "G3-SCI-41", grade: 3, subject: "Science", topic: "Space", question: "What causes Earth's seasons?", choices: ["The distance from the sun", "The tilt of Earth's axis", "The speed of rotation", "The Moon"], answer: 1 },
    { id: "G3-SCI-42", grade: 3, subject: "Science", topic: "Space", question: "A group of stars that form a pattern is a:", choices: ["Galaxy", "Constellation", "Solar System", "Planet"], answer: 1 },
    { id: "G3-SCI-43", grade: 3, subject: "Science", topic: "Space", question: "Which planet is furthest from the Sun?", choices: ["Uranus", "Neptune", "Saturn", "Jupiter"], answer: 1 },
    { id: "G3-SCI-44", grade: 3, subject: "Science", topic: "Space", question: "What is a 'New Moon'?", choices: ["A moon that just formed", "When we cannot see the moon from Earth", "A full bright moon", "A moon on a different planet"], answer: 1 },
    { id: "G3-SCI-45", grade: 3, subject: "Science", topic: "Space", question: "The Sun is a:", choices: ["Planet", "Moon", "Star", "Asteroid"], answer: 2 },
    { id: "G3-SCI-46", grade: 3, subject: "Science", topic: "Space", question: "What force keeps the planets in orbit around the Sun?", choices: ["Magnetism", "Gravity", "Electricity", "Wind"], answer: 1 },
    { id: "G3-SCI-47", grade: 3, subject: "Science", topic: "Space", question: "Which planet is tilted almost completely on its side?", choices: ["Saturn", "Uranus", "Neptune", "Mars"], answer: 1 },
    { id: "G3-SCI-48", grade: 3, subject: "Science", topic: "Space", question: "What is the Milky Way?", choices: ["A candy bar", "Our galaxy", "A type of star", "A moon phase"], answer: 1 },
    { id: "G3-SCI-49", grade: 3, subject: "Science", topic: "Space", question: "Tides are caused by the pull of the:", choices: ["Sun", "Moon", "Earth's core", "Wind"], answer: 1 },
    { id: "G3-SCI-50", grade: 3, subject: "Science", topic: "Space", question: "How many moons does Earth have?", choices: ["0", "1", "2", "Many"], answer: 1 },

    // --- TOPIC 3: FORCES, MOTION & MAGNETS (25 Questions) ---
    { id: "G3-SCI-51", grade: 3, subject: "Science", topic: "Forces", question: "A push or a pull is called a:", choices: ["Speed", "Force", "Motion", "Gravity"], answer: 1 },
    { id: "G3-SCI-52", grade: 3, subject: "Science", topic: "Forces", question: "Which force pulls everything toward the center of the Earth?", choices: ["Friction", "Magnetism", "Gravity", "Air Resistance"], answer: 2 },
    { id: "G3-SCI-53", grade: 3, subject: "Science", topic: "Forces", question: "The force that happens when two objects rub against each other is:", choices: ["Gravity", "Friction", "Inertia", "Magnetism"], answer: 1 },
    { id: "G3-SCI-54", grade: 3, subject: "Science", topic: "Magnets", question: "Like poles of a magnet (North and North) will:", choices: ["Attract", "Repel (push away)", "Stick together", "Explode"], answer: 1 },
    { id: "G3-SCI-55", grade: 3, subject: "Science", topic: "Magnets", question: "Opposite poles of a magnet (North and South) will:", choices: ["Attract", "Repel", "Do nothing", "Turn into wood"], answer: 0 },
    { id: "G3-SCI-56", grade: 3, subject: "Science", topic: "Forces", question: "Which surface would create the MOST friction for a toy car?", choices: ["Ice", "Glass", "Sandpaper", "Polished wood"], answer: 2 },
    { id: "G3-SCI-57", grade: 3, subject: "Science", topic: "Magnets", question: "Which of these materials is attracted to a magnet?", choices: ["Plastic", "Iron", "Wood", "Glass"], answer: 1 },
    { id: "G3-SCI-58", grade: 3, subject: "Science", topic: "Forces", question: "If you push an object harder, it will move:", choices: ["Slower", "Faster", "Not at all", "In the opposite direction"], answer: 1 },
    { id: "G3-SCI-59", grade: 3, subject: "Science", topic: "Forces", question: "When forces on an object are 'balanced', the object:", choices: ["Speeds up", "Stays still or keeps the same motion", "Falls down", "Changes shape"], answer: 1 },
    { id: "G3-SCI-60", grade: 3, subject: "Science", topic: "Magnets", question: "Every magnet has two poles. They are:", choices: ["Up and Down", "Left and Right", "North and South", "Red and Blue"], answer: 2 },
    { id: "G3-SCI-61", grade: 3, subject: "Science", topic: "Forces", question: "Work is done when a force moves an object a:", choices: ["Time", "Distance", "Weight", "Color"], answer: 1 },
    { id: "G3-SCI-62", grade: 3, subject: "Science", topic: "Forces", question: "An object with more mass requires ____ force to move.", choices: ["Less", "More", "Zero", "Equal"], answer: 1 },
    { id: "G3-SCI-63", grade: 3, subject: "Science", topic: "Forces", question: "What tool is used to measure force?", choices: ["Ruler", "Thermometer", "Spring Scale", "Balance"], answer: 2 },
    { id: "G3-SCI-64", grade: 3, subject: "Science", topic: "Forces", question: "Magnetism is a force that can act:", choices: ["Only when touching", "Without touching", "Only in space", "Only in water"], answer: 1 },
    { id: "G3-SCI-65", grade: 3, subject: "Science", topic: "Forces", question: "Which is a non-contact force?", choices: ["Kicking a ball", "Pushing a door", "Gravity", "Pulling a wagon"], answer: 2 },
    { id: "G3-SCI-66", grade: 3, subject: "Science", topic: "Forces", question: "Friction always acts in the ____ direction of motion.", choices: ["Same", "Opposite", "Upward", "Circular"], answer: 1 },
    { id: "G3-SCI-67", grade: 3, subject: "Science", topic: "Forces", question: "What happens when you apply an 'unbalanced' force to a still object?", choices: ["It stays still", "It begins to move", "It turns invisible", "It gets lighter"], answer: 1 },
    { id: "G3-SCI-68", grade: 3, subject: "Science", topic: "Magnets", question: "A compass works because the Earth acts like a giant:", choices: ["Ball of water", "Magnet", "Light bulb", "Cloud"], answer: 1 },
    { id: "G3-SCI-69", grade: 3, subject: "Science", topic: "Forces", question: "The measure of how fast an object moves is:", choices: ["Weight", "Mass", "Speed", "Force"], answer: 2 },
    { id: "G3-SCI-70", grade: 3, subject: "Science", topic: "Forces", question: "Which of these can stop a moving ball?", choices: ["Friction", "Gravity", "Another force", "All of the above"], answer: 3 },
    { id: "G3-SCI-71", grade: 3, subject: "Science", topic: "Forces", question: "What is 'Inertia'?", choices: ["A type of speed", "The tendency of an object to resist change in motion", "A force like gravity", "The weight of an object"], answer: 1 },
    { id: "G3-SCI-72", grade: 3, subject: "Science", topic: "Forces", question: "On which planet would you weigh the least?", choices: ["Jupiter (Large mass)", "Earth (Medium mass)", "Mars (Small mass)", "Weight is always the same"], answer: 2 },
    { id: "G3-SCI-73", grade: 3, subject: "Science", topic: "Magnets", question: "The space around a magnet where it can pull objects is the:", choices: ["Magnetic Field", "Pole", "Gravity Well", "Magic Zone"], answer: 0 },
    { id: "G3-SCI-74", grade: 3, subject: "Science", topic: "Forces", question: "Air resistance is a type of:", choices: ["Gravity", "Friction", "Magnetism", "Light"], answer: 1 },
    { id: "G3-SCI-75", grade: 3, subject: "Science", topic: "Forces", question: "If you want to speed up a car, you must apply:", choices: ["No force", "An unbalanced force", "A balanced force", "Friction"], answer: 1 },

    // --- TOPIC 4: WEATHER & CLIMATE (25 Questions) ---
    { id: "G3-SCI-76", grade: 3, subject: "Science", topic: "Weather", question: "What tool measures air temperature?", choices: ["Barometer", "Thermometer", "Anemometer", "Rain Gauge"], answer: 1 },
    { id: "G3-SCI-77", grade: 3, subject: "Science", topic: "Weather", question: "What tool measures wind speed?", choices: ["Thermometer", "Rain Gauge", "Anemometer", "Compass"], answer: 2 },
    { id: "G3-SCI-78", grade: 3, subject: "Science", topic: "Weather", question: "What tool measures the amount of precipitation (rain)?", choices: ["Rain Gauge", "Hygrometer", "Barometer", "Scale"], answer: 0 },
    { id: "G3-SCI-79", grade: 3, subject: "Science", topic: "Weather", question: "The condition of the air at a certain time and place is:", choices: ["Climate", "Weather", "Season", "Atmosphere"], answer: 1 },
    { id: "G3-SCI-80", grade: 3, subject: "Science", topic: "Weather", question: "Average weather patterns in an area over a long time (years) is:", choices: ["Weather", "Forecast", "Climate", "Pollution"], answer: 2 },
    { id: "G3-SCI-81", grade: 3, subject: "Science", topic: "Weather", question: "Which clouds look like white, puffy cotton balls?", choices: ["Stratus", "Cumulus", "Cirrus", "Nimbus"], answer: 1 },
    { id: "G3-SCI-82", grade: 3, subject: "Science", topic: "Weather", question: "Which clouds are thin and wispy, high in the sky?", choices: ["Cumulus", "Cirrus", "Stratus", "Fog"], answer: 1 },
    { id: "G3-SCI-83", grade: 3, subject: "Science", topic: "Weather", question: "Which clouds look like a flat, gray blanket covering the sky?", choices: ["Cirrus", "Stratus", "Cumulus", "Thunderhead"], answer: 1 },
    { id: "G3-SCI-84", grade: 3, subject: "Science", topic: "Weather", question: "Water that falls from the sky is called:", choices: ["Condensation", "Evaporation", "Precipitation", "Humidity"], answer: 2 },
    { id: "G3-SCI-85", grade: 3, subject: "Science", topic: "Weather", question: "A person who studies and predicts weather is a:", choices: ["Geologist", "Meteorologist", "Biologist", "Chemist"], answer: 1 },
    { id: "G3-SCI-86", grade: 3, subject: "Science", topic: "Weather", question: "The movement of water from Earth to the sky and back is the:", choices: ["Rock Cycle", "Water Cycle", "Life Cycle", "Food Chain"], answer: 1 },
    { id: "G3-SCI-87", grade: 3, subject: "Science", topic: "Weather", question: "What is it called when water vapor turns into liquid water (clouds)?", choices: ["Evaporation", "Condensation", "Precipitation", "Collection"], answer: 1 },
    { id: "G3-SCI-88", grade: 3, subject: "Science", topic: "Weather", question: "What is it called when liquid water turns into gas (water vapor)?", choices: ["Condensation", "Freezing", "Evaporation", "Melting"], answer: 2 },
    { id: "G3-SCI-89", grade: 3, subject: "Science", topic: "Weather", question: "A severe storm with a spinning funnel of wind is a:", choices: ["Hurricane", "Tornado", "Blizzard", "Flood"], answer: 1 },
    { id: "G3-SCI-90", grade: 3, subject: "Science", topic: "Weather", question: "A huge storm that forms over warm ocean water is a:", choices: ["Tornado", "Hurricane", "Sandstorm", "Thunderstorm"], answer: 1 },
    { id: "G3-SCI-91", grade: 3, subject: "Science", topic: "Weather", question: "What is 'Humidity'?", choices: ["The temperature of the air", "The amount of water vapor in the air", "The speed of the wind", "The weight of the air"], answer: 1 },
    { id: "G3-SCI-92", grade: 3, subject: "Science", topic: "Weather", question: "Lightning is a giant spark of:", choices: ["Light", "Static Electricity", "Magnetism", "Fire"], answer: 1 },
    { id: "G3-SCI-93", grade: 3, subject: "Science", topic: "Weather", question: "What causes thunder?", choices: ["Clouds bumping together", "The rapid expansion of air heated by lightning", "Rain hitting the ground", "The wind"], answer: 1 },
    { id: "G3-SCI-94", grade: 3, subject: "Science", topic: "Weather", question: "Which climate is very dry and gets very little rain?", choices: ["Tropical", "Polar", "Arid (Desert)", "Temperate"], answer: 2 },
    { id: "G3-SCI-95", grade: 3, subject: "Science", topic: "Weather", question: "Which climate is very cold year-round?", choices: ["Tropical", "Polar", "Desert", "Temperate"], answer: 1 },
    { id: "G3-SCI-96", grade: 3, subject: "Science", topic: "Weather", question: "Air pressure is measured with a:", choices: ["Thermometer", "Anemometer", "Barometer", "Rain Gauge"], answer: 2 },
    { id: "G3-SCI-97", grade: 3, subject: "Science", topic: "Weather", question: "What do we call a period of time with very little rain?", choices: ["Flood", "Drought", "Blizzard", "Hurricane"], answer: 1 },
    { id: "G3-SCI-98", grade: 3, subject: "Science", topic: "Weather", question: "Snow, rain, hail, and sleet are all types of:", choices: ["Weather", "Climate", "Precipitation", "Water vapor"], answer: 2 },
    { id: "G3-SCI-99", grade: 3, subject: "Science", topic: "Weather", question: "Wind is moving:", choices: ["Water", "Air", "Clouds", "Dust"], answer: 1 },
    { id: "G3-SCI-100", grade: 3, subject: "Science", topic: "Weather", question: "Where is the safest place to be during a tornado?", choices: ["Under a tree", "In a basement or interior room", "In a car", "Near a window"], answer: 1 }
];

module.exports = G3_SCIENCE_COMPLETE;
