const G4_ELA_PARTIAL = [
    // --- TOPIC 1: READING COMPREHENSION & THEME (25 Questions) ---
    { id: "G4-EL-01", grade: 4, subject: "ELA", topic: "Reading", question: "What is the 'Theme' of a story?", choices: ["The color of the book", "The main message or lesson the author wants to share", "The name of the main character", "The place where the story happens"], answer: 1 },
    { id: "G4-EL-02", grade: 4, subject: "ELA", topic: "Reading", question: "A 'Summary' should contain:", choices: ["Every tiny detail", "Only the main points and key events", "The author's life story", "Mostly pictures"], answer: 1 },
    { id: "G4-EL-03", grade: 4, subject: "ELA", topic: "Reading", question: "What is 'Inference'?", choices: ["Reading the words exactly as they are", "Using clues from the text and your own knowledge to understand something not stated", "A type of punctuation", "Writing a new story"], answer: 1 },
    { id: "G4-EL-04", grade: 4, subject: "ELA", topic: "Reading", question: "The 'Setting' of a story is:", choices: ["The problem", "The time and place", "The characters", "The ending"], answer: 1 },
    { id: "G4-EL-05", grade: 4, subject: "ELA", topic: "Reading", question: "Who is the 'Protagonist'?", choices: ["The bad guy", "The main character or hero", "The person who tells the story", "A minor character"], answer: 1 },
    { id: "G4-EL-06", grade: 4, subject: "ELA", topic: "Reading", question: "Who is the 'Antagonist'?", choices: ["The hero", "The character who opposes the protagonist", "The author", "The reader"], answer: 1 },
    { id: "G4-EL-07", grade: 4, subject: "ELA", topic: "Reading", question: "What is 'Point of View'?", choices: ["The direction the book is facing", "The perspective from which a story is told", "The height of the characters", "The climax of the story"], answer: 1 },
    { id: "G4-EL-08", grade: 4, subject: "ELA", topic: "Reading", question: "First-person point of view uses words like:", choices: ["He, She, They", "I, Me, We", "You, Your", "None of these"], answer: 1 },
    { id: "G4-EL-09", grade: 4, subject: "ELA", topic: "Reading", question: "Third-person point of view uses words like:", choices: ["I, My", "He, She, They", "We, Us", "I and You"], answer: 1 },
    { id: "G4-EL-10", grade: 4, subject: "ELA", topic: "Reading", question: "What is 'Context Clues'?", choices: ["Hints in a sentence that help you find a word's meaning", "A map of the library", "The title of the book", "The number of pages"], answer: 0 },
    { id: "G4-EL-11", grade: 4, subject: "ELA", topic: "Reading", question: "The 'Main Idea' is:", choices: ["The first sentence", "What the text is mostly about", "A funny part of the story", "The author's name"], answer: 1 },
    { id: "G4-EL-12", grade: 4, subject: "ELA", topic: "Reading", question: "Characters have 'Traits', which are:", choices: ["Things they eat", "Qualities that describe their personality", "Their clothes", "Their height"], answer: 1 },
    { id: "G4-EL-13", grade: 4, subject: "ELA", topic: "Reading", question: "What are 'Supporting Details'?", choices: ["The cover of the book", "Facts and examples that explain the main idea", "Different books", "The table of contents"], answer: 1 },
    { id: "G4-EL-14", grade: 4, subject: "ELA", topic: "Reading", question: "What is 'Dialogue'?", choices: ["The pictures in a book", "The words characters say to each other", "The glossary", "The page numbers"], answer: 1 },
    { id: "G4-EL-15", grade: 4, subject: "ELA", topic: "Reading", question: "What is a 'Genre'?", choices: ["A type or category of literature", "A character trait", "The ending of a book", "A difficult word"], answer: 0 },
    { id: "G4-EL-16", grade: 4, subject: "ELA", topic: "Reading", question: "Informational text is written to:", choices: ["Tell a joke", "Give facts and information", "Entertain with a fairy tale", "Hide a secret"], answer: 1 },
    { id: "G4-EL-17", grade: 4, subject: "ELA", topic: "Reading", question: "What is 'Chronological Order'?", choices: ["In order of importance", "In order of time/sequence", "By character name", "By the color of the pages"], answer: 1 },
    { id: "G4-EL-18", grade: 4, subject: "ELA", topic: "Reading", question: "A 'Cause and Effect' relationship means:", choices: ["Two things happen at once", "One event (cause) makes another event period (effect) happen", "They both mean the same thing", "It's a secret"], answer: 1 },
    { id: "G4-EL-19", grade: 4, subject: "ELA", topic: "Reading", question: "Compare and Contrast means finding:", choices: ["Similarities and Differences", "Only the end", "Only the beginning", "The author's age"], answer: 0 },
    { id: "G4-EL-20", grade: 4, subject: "ELA", topic: "Reading", question: "What is 'Fact'?", choices: ["Someone's feeling", "Something that can be proven true", "A guess", "A prediction"], answer: 1 },
    { id: "G4-EL-21", grade: 4, subject: "ELA", topic: "Reading", question: "What is 'Opinion'?", choices: ["A proven fact", "A belief or feeling about something", "The truth", "A scientific law"], answer: 1 },
    { id: "G4-EL-22", grade: 4, subject: "ELA", topic: "Reading", question: "Propaganda or Bias in a text means:", choices: ["Sharing only one side of an argument", "Telling the whole truth", "A type of fiction", "A book's price"], answer: 0 },
    { id: "G4-EL-23", grade: 4, subject: "ELA", topic: "Reading", question: "What is the 'Conflict' in a story?", choices: ["The happy ending", "The main problem or struggle", "The setting", "The title"], answer: 1 },
    { id: "G4-EL-24", grade: 4, subject: "ELA", topic: "Reading", question: "What is the 'Resolution'?", choices: ["The beginning", "How the conflict is solved", "The middle", "A new problem"], answer: 1 },
    { id: "G4-EL-25", grade: 4, subject: "ELA", topic: "Reading", question: "Plot is the:", choices: ["Sequence of events in a story", "Grass field", "Drawing in a book", "List of characters"], answer: 0 },

    // --- TOPIC 2: GRAMMAR, PUNCTUATION & VOCABULARY (25 Questions) ---
    { id: "G4-EL-26", grade: 4, subject: "ELA", topic: "Grammar", question: "What is a 'Common Noun'?", choices: ["A specific name like 'New York'", "A general person, place, or thing", "An action", "A describing word"], answer: 1 },
    { id: "G4-EL-27", grade: 4, subject: "ELA", topic: "Grammar", question: "What is a 'Proper Noun'?", choices: ["A specific name of a person, place, or thing", "A general word", "An adjective", "A verb"], answer: 0 },
    { id: "G4-EL-28", grade: 4, subject: "ELA", topic: "Grammar", question: "Identify the verb: 'The dog barked loudly.'", choices: ["Dog", "Barked", "Loudly", "The"], answer: 1 },
    { id: "G4-EL-29", grade: 4, subject: "ELA", topic: "Grammar", question: "What is an 'Adjective'?", choices: ["An action word", "A word that describes a noun", "A person's name", "A connecting word"], answer: 1 },
    { id: "G4-EL-30", grade: 4, subject: "ELA", topic: "Grammar", question: "What is an 'Adverb'?", choices: ["Describes a noun", "Describes a verb, adjective, or another adverb", "A person", "A place"], answer: 1 },
    { id: "G4-EL-31", grade: 4, subject: "ELA", topic: "Grammar", question: "Which word is a conjunction?", choices: ["Run", "Happy", "And", "Apple"], answer: 2 },
    { id: "G4-EL-32", grade: 4, subject: "ELA", topic: "Grammar", question: "What is a 'Pronoun'?", choices: ["A word that takes the place of a noun", "A strong action", "A punctuation mark", "A capital letter"], answer: 0 },
    { id: "G4-EL-33", grade: 4, subject: "ELA", topic: "Grammar", question: "Which is a 'Preposition'?", choices: ["Jump", "In", "Wow", "Green"], answer: 1 },
    { id: "G4-EL-34", grade: 4, subject: "ELA", topic: "Grammar", question: "What do you use at the end of a question?", choices: ["Period", "Question Mark", "Exclamation Point", "Comma"], answer: 1 },
    { id: "G4-EL-35", grade: 4, subject: "ELA", topic: "Grammar", question: "What do you use for strong excitement?", choices: ["Comma", "Period", "Exclamation Point", "Semicolon"], answer: 2 },
    { id: "G4-EL-36", grade: 4, subject: "ELA", topic: "Grammar", question: "A 'Synonym' is a word that:", choices: ["Means the opposite", "Means almost the same", "Sounds the same but spells different", "Has no meaning"], answer: 1 },
    { id: "G4-EL-37", grade: 4, subject: "ELA", topic: "Grammar", question: "An 'Antonym' is a word that:", choices: ["Means the same", "Means the opposite", "Is very long", "Is very short"], answer: 1 },
    { id: "G4-EL-38", grade: 4, subject: "ELA", topic: "Grammar", question: "What are 'Homophones'?", choices: ["Words that mean the same", "Words that sound the same but have different meanings/spellings", "Opposite words", "Rhyming words"], answer: 1 },
    { id: "G4-EL-39", grade: 4, subject: "ELA", topic: "Grammar", question: "Which pair are homophones?", choices: ["Big/Large", "See/Sea", "Up/Down", "Hot/Cold"], answer: 1 },
    { id: "G4-EL-40", grade: 4, subject: "ELA", topic: "Grammar", question: "What is a 'Prefix'?", choices: ["Added to the end of a word", "Added to the beginning of a word", "The middle of a word", "A whole word"], answer: 1 },
    { id: "G4-EL-41", grade: 4, subject: "ELA", topic: "Grammar", question: "What is a 'Suffix'?", choices: ["Added to the beginning", "Added to the end of a word", "A type of comma", "A funny story"], answer: 1 },
    { id: "G4-EL-42", grade: 4, subject: "ELA", topic: "Grammar", question: "Compound words are:", choices: ["Words with no meaning", "Two words joined together to make a new word", "Hidden words", "Scientific words"], answer: 1 },
    { id: "G4-EL-43", grade: 4, subject: "ELA", topic: "Grammar", question: "Which is a compound word?", choices: ["Library", "Butterfly", "Running", "Slowly"], answer: 1 },
    { id: "G4-EL-44", grade: 4, subject: "ELA", topic: "Grammar", question: "A 'Stanza' is found in:", choices: ["A dictionary", "A poem", "A recipe", "A map"], answer: 1 },
    { id: "G4-EL-45", grade: 4, subject: "ELA", topic: "Grammar", question: "What is 'Alliteration'?", choices: ["Rhyming words", "Repetition of initial consonant sounds", "The main idea", "A long pause"], answer: 1 },
    { id: "G4-EL-46", grade: 4, subject: "ELA", topic: "Grammar", question: "What is a 'Simile'?", choices: ["A funny face", "A comparison using 'like' or 'as'", "The ending", "A true fact"], answer: 1 },
    { id: "G4-EL-47", grade: 4, subject: "ELA", topic: "Grammar", question: "What is a 'Metaphor'?", choices: ["Comparison NOT using like or as", "A type of bug", "A long sentence", "A question"], answer: 0 },
    { id: "G4-EL-48", grade: 4, subject: "ELA", topic: "Grammar", question: "What is 'Onomatopoeia'?", choices: ["The study of bugs", "Words that imitate sounds (like 'Boom' or 'Buzz')", "A Greek god", "A type of plant"], answer: 1 },
    { id: "G4-EL-49", grade: 4, subject: "ELA", topic: "Grammar", question: "A 'Fragment' is:", choices: ["A complete thought", "An incomplete sentence", "A very long paragraph", "A title"], answer: 1 },
    { id: "G4-EL-50", grade: 4, subject: "ELA", topic: "Grammar", question: "Quotation marks are used to:", choices: ["End a sentence", "Show someone is speaking", "Capitalize a name", "Separate items in a list"], answer: 1 }
];

module.exports = G4_ELA_PARTIAL;
