const G4_MATH_COMPLETE = [
    // --- TOPIC 1: PLACE VALUE & MULTI-DIGIT OPERATIONS (25 Questions) ---
    { id: "G4-MA-01", grade: 4, subject: "Math", topic: "Numbers", question: "What is the value of the digit 5 in the number 4,523?", choices: ["5", "50", "500", "5,000"], answer: 2 },
    { id: "G4-MA-02", grade: 4, subject: "Math", topic: "Numbers", question: "Which number is ten times as much as 40?", choices: ["4", "400", "4,000", "44"], answer: 1 },
    { id: "G4-MA-03", grade: 4, subject: "Math", topic: "Numbers", question: "What is 1,234 rounded to the nearest hundred?", choices: ["1,000", "1,200", "1,300", "1,230"], answer: 1 },
    { id: "G4-MA-04", grade: 4, subject: "Math", topic: "Numbers", question: "Write 5,000 + 300 + 4 in standard form.", choices: ["5,340", "5,034", "5,304", "534"], answer: 2 },
    { id: "G4-MA-05", grade: 4, subject: "Math", topic: "Numbers", question: "What is 7,890 + 2,110?", choices: ["9,000", "10,000", "9,990", "10,100"], answer: 1 },
    { id: "G4-MA-06", grade: 4, subject: "Math", topic: "Numbers", question: "What is 5,000 - 1,250?", choices: ["3,750", "3,850", "4,250", "3,250"], answer: 0 },
    { id: "G4-MA-07", grade: 4, subject: "Math", topic: "Numbers", question: "Compare: 45,678 ___ 45,768", choices: ["<", ">", "=", "None"], answer: 0 },
    { id: "G4-MA-08", grade: 4, subject: "Math", topic: "Operations", question: "Multiply 45 by 10.", choices: ["45", "450", "4,500", "540"], answer: 1 },
    { id: "G4-MA-09", grade: 4, subject: "Math", topic: "Operations", question: "What is 12 x 12?", choices: ["124", "132", "144", "154"], answer: 2 },
    { id: "G4-MA-10", grade: 4, subject: "Math", topic: "Operations", question: "Multiply 32 by 3.", choices: ["64", "96", "99", "102"], answer: 1 },
    { id: "G4-MA-11", grade: 4, subject: "Math", topic: "Operations", question: "Multiply 25 by 4.", choices: ["75", "100", "125", "150"], answer: 1 },
    { id: "G4-MA-12", grade: 4, subject: "Math", topic: "Operations", question: "What is 100 divided by 4?", choices: ["20", "25", "40", "50"], answer: 1 },
    { id: "G4-MA-13", grade: 4, subject: "Math", topic: "Operations", question: "Divide 81 by 9.", choices: ["7", "8", "9", "10"], answer: 2 },
    { id: "G4-MA-14", grade: 4, subject: "Math", topic: "Operations", question: "A factor of 15 is:", choices: ["2", "4", "5", "6"], answer: 2 },
    { id: "G4-MA-15", grade: 4, subject: "Math", topic: "Operations", question: "Which number is a multiple of 6?", choices: ["10", "12", "15", "20"], answer: 1 },
    { id: "G4-MA-16", grade: 4, subject: "Math", topic: "Operations", question: "Is 7 a prime or composite number?", choices: ["Prime", "Composite"], answer: 0 },
    { id: "G4-MA-17", grade: 4, subject: "Math", topic: "Operations", question: "Is 10 a prime or composite number?", choices: ["Prime", "Composite"], answer: 1 },
    { id: "G4-MA-18", grade: 4, subject: "Math", topic: "Operations", question: "What is 4,000 x 2?", choices: ["6,000", "8,000", "10,000", "4,002"], answer: 1 },
    { id: "G4-MA-19", grade: 4, subject: "Math", topic: "Operations", question: "Divide 1,000 by 10.", choices: ["1", "10", "100", "1,000"], answer: 2 },
    { id: "G4-MA-20", grade: 4, subject: "Math", topic: "Operations", question: "What is the remainder of 10 divided by 3?", choices: ["0", "1", "2", "3"], answer: 1 },
    { id: "G4-MA-21", grade: 4, subject: "Math", topic: "Numbers", question: "Which is the largest number?", choices: ["1,234", "1,324", "1,423", "1,142"], answer: 2 },
    { id: "G4-MA-22", grade: 4, subject: "Math", topic: "Operations", question: "Multiply 15 by 2.", choices: ["20", "25", "30", "45"], answer: 2 },
    { id: "G4-MA-23", grade: 4, subject: "Math", topic: "Operations", question: "Divide 60 by 5.", choices: ["10", "12", "15", "20"], answer: 1 },
    { id: "G4-MA-24", grade: 4, subject: "Math", topic: "Numbers", question: "What is 9,999 + 1?", choices: ["10,000", "1,000", "9,990", "10,001"], answer: 0 },
    { id: "G4-MA-25", grade: 4, subject: "Math", topic: "Operations", question: "A rectangle has 3 rows and 4 columns of tiles. How many tiles total?", choices: ["7", "12", "14", "16"], answer: 1 },

    // --- TOPIC 2: FRACTIONS & DECIMALS (25 Questions) ---
    { id: "G4-MA-26", grade: 4, subject: "Math", topic: "Fractions", question: "Which fraction is equivalent to 1/2?", choices: ["2/4", "1/3", "1/4", "3/4"], answer: 0 },
    { id: "G4-MA-27", grade: 4, subject: "Math", topic: "Fractions", question: "Compare: 1/4 ___ 3/4", choices: ["<", ">", "=", "None"], answer: 0 },
    { id: "G4-MA-28", grade: 4, subject: "Math", topic: "Fractions", question: "Add: 1/5 + 2/5", choices: ["3/10", "3/5", "1/5", "5/5"], answer: 1 },
    { id: "G4-MA-29", grade: 4, subject: "Math", topic: "Fractions", question: "Subtract: 7/8 - 3/8", choices: ["4/16", "4/8", "10/8", "1/2"], answer: 1 },
    { id: "G4-MA-30", grade: 4, subject: "Math", topic: "Fractions", question: "Which is a mixed number?", choices: ["1/2", "3", "1 1/2", "0.5"], answer: 2 },
    { id: "G4-MA-31", grade: 4, subject: "Math", topic: "Fractions", question: "Convert 5/4 to a mixed number.", choices: ["1 1/4", "1 1/2", "4/5", "1 1/5"], answer: 0 },
    { id: "G4-MA-32", grade: 4, subject: "Math", topic: "Fractions", question: "What is 3 x (1/4)?", choices: ["1/4", "3/4", "3/12", "4/3"], answer: 1 },
    { id: "G4-MA-33", grade: 4, subject: "Math", topic: "Decimals", question: "Write 7/10 as a decimal.", choices: ["0.07", "0.7", "7.0", "7.10"], answer: 1 },
    { id: "G4-MA-34", grade: 4, subject: "Math", topic: "Decimals", question: "Write 5/100 as a decimal.", choices: ["0.5", "0.05", "5.0", "0.005"], answer: 1 },
    { id: "G4-MA-35", grade: 4, subject: "Math", topic: "Decimals", question: "Compare: 0.3 ___ 0.29", choices: ["<", ">", "=", "None"], answer: 1 },
    { id: "G4-MA-36", grade: 4, subject: "Math", topic: "Fractions", question: "A fraction with a numerator of 3 and denominator of 4 is:", choices: ["4/3", "3/4", "0.75", "3.4"], answer: 1 },
    { id: "G4-MA-37", grade: 4, subject: "Math", topic: "Fractions", question: "Which is greater: 1/3 or 1/2?", choices: ["1/3", "1/2", "They are equal"], answer: 1 },
    { id: "G4-MA-38", grade: 4, subject: "Math", topic: "Decimals", question: "0.2 + 0.5 =", choices: ["0.07", "0.7", "7.0", "0.10"], answer: 1 },
    { id: "G4-MA-39", grade: 4, subject: "Math", topic: "Decimals", question: "1.0 - 0.4 =", choices: ["0.6", "1.4", "0.4", "1.6"], answer: 0 },
    { id: "G4-MA-40", grade: 4, subject: "Math", topic: "Fractions", question: "Which fraction is equal to 1 whole?", choices: ["1/2", "2/2", "0/1", "1/0"], answer: 1 },
    { id: "G4-MA-41", grade: 4, subject: "Math", topic: "Fractions", question: "Break 3/4 into unit fractions.", choices: ["1/4+1/4+1/4", "1/2+1/2", "3+4", "1/4+1/2"], answer: 0 },
    { id: "G4-MA-42", grade: 4, subject: "Math", topic: "Fractions", question: "Multiply: 2 x 1/3", choices: ["1/3", "2/3", "2/6", "3/2"], answer: 1 },
    { id: "G4-MA-43", grade: 4, subject: "Math", topic: "Decimals", question: "What is 0.50 same as?", choices: ["0.05", "0.5", "5.0", "50.0"], answer: 1 },
    { id: "G4-MA-44", grade: 4, subject: "Math", topic: "Decimals", question: "Add: 0.3 + 0.04", choices: ["0.7", "0.34", "0.07", "3.4"], answer: 1 },
    { id: "G4-MA-45", grade: 4, subject: "Math", topic: "Fractions", question: "10/10 is equal to:", choices: ["0", "1", "10", "100"], answer: 1 },
    { id: "G4-MA-46", grade: 4, subject: "Math", topic: "Fractions", question: "Simplify 2/10.", choices: ["1/2", "1/5", "2/5", "1/10"], answer: 1 },
    { id: "G4-MA-47", grade: 4, subject: "Math", topic: "Fractions", question: "Which is bigger: 9/10 or 1/10?", choices: ["1/10", "9/10", "Equal"], answer: 1 },
    { id: "G4-MA-48", grade: 4, subject: "Math", topic: "Decimals", question: "How many tenths are in 1 whole?", choices: ["1", "10", "100", "0.1"], answer: 1 },
    { id: "G4-MA-49", grade: 4, subject: "Math", topic: "Decimals", question: "How many hundredths are in 1 whole?", choices: ["1", "10", "100", "0.01"], answer: 2 },
    { id: "G4-MA-50", grade: 4, subject: "Math", topic: "Decimals", question: "Compare: 0.8 ___ 0.80", choices: ["<", ">", "=", "None"], answer: 2 },

    // --- TOPIC 3: GEOMETRY & MEASUREMENT (25 Questions - AI Generated) ---
    { id: "G4-MA-51", grade: 4, subject: "Math", topic: "Geometry", question: "Which shape has 4 equal sides and 4 right angles?", choices: ["Rectangle", "Square", "Triangle", "Circle"], answer: 1 },
    { id: "G4-MA-52", grade: 4, subject: "Math", topic: "Geometry", question: "What do you call a line that travels in one direction and has one endpoint?", choices: ["Line", "Line segment", "Ray", "Point"], answer: 2 },
    { id: "G4-MA-53", grade: 4, subject: "Math", topic: "Geometry", question: "An angle that measures exactly 90 degrees is a ___ angle.", choices: ["Acute", "Obtuse", "Right", "Straight"], answer: 2 },
    { id: "G4-MA-54", grade: 4, subject: "Math", topic: "Geometry", question: "An angle less than 90 degrees is called ___.", choices: ["Obtuse", "Acute", "Right", "Straight"], answer: 1 },
    { id: "G4-MA-55", grade: 4, subject: "Math", topic: "Geometry", question: "An angle greater than 90 degrees but less than 180 is called ___.", choices: ["Acute", "Obtuse", "Right", "Square"], answer: 1 },
    { id: "G4-MA-56", grade: 4, subject: "Math", topic: "Geometry", question: "Lines that never cross and are the same distance apart are ___.", choices: ["Intersecting", "Perpendicular", "Parallel", "Curved"], answer: 2 },
    { id: "G4-MA-57", grade: 4, subject: "Math", topic: "Geometry", question: "Lines that cross at a right angle are ___.", choices: ["Parallel", "Perpendicular", "Symmetric", "Horizontal"], answer: 1 },
    { id: "G4-MA-58", grade: 4, subject: "Math", topic: "Geometry", question: "How many degrees are in a straight line?", choices: ["90", "180", "360", "45"], answer: 1 },
    { id: "G4-MA-59", grade: 4, subject: "Math", topic: "Measurement", question: "The distance around the outside of a shape is called the ___.", choices: ["Area", "Volume", "Perimeter", "Mass"], answer: 2 },
    { id: "G4-MA-60", grade: 4, subject: "Math", topic: "Measurement", question: "What is the perimeter of a square with a side of 5 cm?", choices: ["10 cm", "20 cm", "25 cm", "15 cm"], answer: 1 },
    { id: "G4-MA-61", grade: 4, subject: "Math", topic: "Measurement", question: "The space inside a flat shape is called its ___.", choices: ["Perimeter", "Area", "Length", "Radius"], answer: 1 },
    { id: "G4-MA-62", grade: 4, subject: "Math", topic: "Measurement", question: "What is the area of a rectangle with length 6 and width 4?", choices: ["10", "20", "24", "12"], answer: 2 },
    { id: "G4-MA-63", grade: 4, subject: "Math", topic: "Measurement", question: "How many inches are in 1 foot?", choices: ["10", "12", "14", "24"], answer: 1 },
    { id: "G4-MA-64", grade: 4, subject: "Math", topic: "Measurement", question: "How many feet are in 1 yard?", choices: ["2", "3", "4", "12"], answer: 1 },
    { id: "G4-MA-65", grade: 4, subject: "Math", topic: "Measurement", question: "How many milliliters are in 1 liter?", choices: ["10", "100", "1,000", "500"], answer: 2 },
    { id: "G4-MA-66", grade: 4, subject: "Math", topic: "Measurement", question: "How many grams are in 1 kilogram?", choices: ["10", "100", "1,000", "2,000"], answer: 2 },
    { id: "G4-MA-67", grade: 4, subject: "Math", topic: "Geometry", question: "Which triangle has all sides equal?", choices: ["Scalene", "Isosceles", "Equilateral", "Right"], answer: 2 },
    { id: "G4-MA-68", grade: 4, subject: "Math", topic: "Geometry", question: "Which triangle has no equal sides?", choices: ["Equilateral", "Isosceles", "Scalene", "Acute"], answer: 2 },
    { id: "G4-MA-69", grade: 4, subject: "Math", topic: "Geometry", question: "How many sides does a pentagon have?", choices: ["4", "5", "6", "8"], answer: 1 },
    { id: "G4-MA-70", grade: 4, subject: "Math", topic: "Geometry", question: "How many sides does an octagon have?", choices: ["5", "6", "8", "10"], answer: 2 },
    { id: "G4-MA-71", grade: 4, subject: "Math", topic: "Measurement", question: "The basic unit for measuring length in the metric system is the ___.", choices: ["Gram", "Liter", "Meter", "Yard"], answer: 2 },
    { id: "G4-MA-72", grade: 4, subject: "Math", topic: "Measurement", question: "About how many centimeters are in 1 inch?", choices: ["1", "2.54", "5", "10"], answer: 1 },
    { id: "G4-MA-73", grade: 4, subject: "Math", topic: "Measurement", question: "How many minutes are in 2 hours?", choices: ["60", "100", "120", "200"], answer: 2 },
    { id: "G4-MA-74", grade: 4, subject: "Math", topic: "Measurement", question: "How many seconds are in 1 minute?", choices: ["10", "30", "60", "100"], answer: 2 },
    { id: "G4-MA-75", grade: 4, subject: "Math", topic: "Geometry", question: "A line of symmetry ___ a shape into two identical parts.", choices: ["Doubles", "Divides", "Multiplies", "Hides"], answer: 1 },

    // --- TOPIC 4: DATA, PATTERNS & MIXED REVIEW (25 Questions - AI Generated) ---
    { id: "G4-MA-76", grade: 4, subject: "Math", topic: "Patterns", question: "What is the next number in the pattern: 2, 4, 6, 8, ___?", choices: ["9", "10", "12", "11"], answer: 1 },
    { id: "G4-MA-77", grade: 4, subject: "Math", topic: "Patterns", question: "What is the next number in the pattern: 3, 6, 12, 24, ___?", choices: ["30", "36", "48", "60"], answer: 2 },
    { id: "G4-MA-78", grade: 4, subject: "Math", topic: "Patterns", question: "A rule is 'add 5'. If you start at 10, what is the next number?", choices: ["10", "15", "50", "5"], answer: 1 },
    { id: "G4-MA-79", grade: 4, subject: "Math", topic: "Data", question: "A graph that uses pictures to represent data is a ___.", choices: ["Bar graph", "Line plot", "Pictograph", "Pie chart"], answer: 2 },
    { id: "G4-MA-80", grade: 4, subject: "Math", topic: "Data", question: "A graph that uses bars to show data is a ___.", choices: ["Bar graph", "Line plot", "Pictograph", "Map"], answer: 0 },
    { id: "G4-MA-81", grade: 4, subject: "Math", topic: "Data", question: "What do you call the difference between the highest and lowest values in a set?", choices: ["Mean", "Median", "Mode", "Range"], answer: 3 },
    { id: "G4-MA-82", grade: 4, subject: "Math", topic: "Algebra", question: "Find x: 10 + x = 25.", choices: ["10", "15", "25", "35"], answer: 1 },
    { id: "G4-MA-83", grade: 4, subject: "Math", topic: "Algebra", question: "Find y: 5 * y = 20.", choices: ["2", "4", "5", "15"], answer: 1 },
    { id: "G4-MA-84", grade: 4, subject: "Math", topic: "Logic", question: "I am a number. Double me and I become 10. Who am I?", choices: ["5", "10", "2", "20"], answer: 0 },
    { id: "G4-MA-85", grade: 4, subject: "Math", topic: "Numbers", question: "Which is 100 less than 1,250?", choices: ["1,150", "250", "1,350", "1,050"], answer: 0 },
    { id: "G4-MA-86", grade: 4, subject: "Math", topic: "Numbers", question: "Round 45,678 to the nearest thousand.", choices: ["45,000", "46,000", "40,000", "50,000"], answer: 1 },
    { id: "G4-MA-87", grade: 4, subject: "Math", topic: "Operations", question: "What is 0 multiplied by anything?", choices: ["The number itself", "0", "1", "Infinity"], answer: 1 },
    { id: "G4-MA-88", grade: 4, subject: "Math", topic: "Operations", question: "What is any number divided by 1?", choices: ["0", "1", "The number itself", "10"], answer: 2 },
    { id: "G4-MA-89", grade: 4, subject: "Math", topic: "Operations", question: "What is 100 - (10 * 5)?", choices: ["450", "50", "90", "100"], answer: 1 },
    { id: "G4-MA-90", grade: 4, subject: "Math", topic: "Operations", question: "Estimation: 48 * 2 is roughly ___.", choices: ["50", "80", "100", "200"], answer: 2 },
    { id: "G4-MA-91", grade: 4, subject: "Math", topic: "Decimals", question: "Which is smaller: 0.1 or 0.01?", choices: ["0.1", "0.01", "Equal"], answer: 1 },
    { id: "G4-MA-92", grade: 4, subject: "Math", topic: "Fractions", question: "3/10 is the same as how many hundredths?", choices: ["3/100", "13/100", "30/100", "300/100"], answer: 2 },
    { id: "G4-MA-93", grade: 4, subject: "Math", topic: "Measurement", question: "How many weeks are in 1 year (roughly)?", choices: ["12", "24", "52", "365"], answer: 2 },
    { id: "G4-MA-94", grade: 4, subject: "Math", topic: "Numbers", question: "What digit is in the ten-thousands place of 134,567?", choices: ["1", "3", "4", "5"], answer: 1 },
    { id: "G4-MA-95", grade: 4, subject: "Math", topic: "Geometry", question: "How many lines of symmetry does a square have?", choices: ["1", "2", "4", "Infinitely many"], answer: 2 },
    { id: "G4-MA-96", grade: 4, subject: "Math", topic: "Geometry", question: "A circle's diameter is ___ its radius.", choices: ["Half", "Double", "Same as", "Triple"], answer: 1 },
    { id: "G4-MA-97", grade: 4, subject: "Math", topic: "Time", question: "If it is 3:15, what time will it be in 45 minutes?", choices: ["3:45", "4:00", "4:15", "3:30"], answer: 1 },
    { id: "G4-MA-98", grade: 4, subject: "Math", topic: "Money", question: "If you have 4 quarters and 2 dimes, how much money do you have?", choices: ["$1.00", "$1.20", "$0.60", "$1.10"], answer: 1 },
    { id: "G4-MA-99", grade: 4, subject: "Math", topic: "Operations", question: "What is 1,200 * 0?", choices: ["1,200", "120", "0", "1"], answer: 2 },
    { id: "G4-MA-100", grade: 4, subject: "Math", topic: "Algebra", question: "If a + 5 = b, and a = 10, what is b?", choices: ["5", "10", "15", "50"], answer: 2 }
];

module.exports = G4_MATH_COMPLETE;
