const G5_MATH_COMPLETE = [
    // --- TOPIC 1: PLACE VALUE & MULTI-DIGIT OPERATIONS (25 Questions) ---
    { id: "G5-MA-01", grade: 5, subject: "Math", topic: "Operations", question: "What is 1.5 x 10?", choices: ["1.5", "15", "150", "0.15"], answer: 1 },
    { id: "G5-MA-02", grade: 5, subject: "Math", topic: "Operations", question: "Divide 1,200 by 100.", choices: ["1.2", "12", "120", "12,000"], answer: 1 },
    { id: "G5-MA-03", grade: 5, subject: "Math", topic: "Operations", question: "What is 10 to the 3rd power (10³)?", choices: ["30", "100", "1,000", "3,000"], answer: 2 },
    { id: "G5-MA-04", grade: 5, subject: "Math", topic: "Operations", question: "In the number 5,555, the 5 in the hundreds place is ___ the value of the 5 in the tens place.", choices: ["1/10", "Equal to", "10 times", "100 times"], answer: 2 },
    { id: "G5-MA-05", grade: 5, subject: "Math", topic: "Operations", question: "Solve: 25 x 42", choices: ["1,000", "1,050", "1,100", "950"], answer: 1 },
    { id: "G5-MA-06", grade: 5, subject: "Math", topic: "Operations", question: "What is 156 ÷ 12?", choices: ["11", "12", "13", "14"], answer: 2 },
    { id: "G5-MA-07", grade: 5, subject: "Math", topic: "Operations", question: "Round 12.456 to the nearest hundredth.", choices: ["12.45", "12.46", "12.5", "12.4"], answer: 1 },
    { id: "G5-MA-08", grade: 5, subject: "Math", topic: "Operations", question: "Compare: 0.405 _ 0.45", choices: [">", "<", "=", "none"], answer: 1 },
    { id: "G5-MA-09", grade: 5, subject: "Math", topic: "Operations", question: "Solve: 345 x 12", choices: ["3,140", "4,140", "4,040", "3,450"], answer: 1 },
    { id: "G5-MA-10", grade: 5, subject: "Math", topic: "Operations", question: "Divide: 500 ÷ 25", choices: ["10", "20", "25", "50"], answer: 1 },
    { id: "G5-MA-11", grade: 5, subject: "Math", topic: "Operations", question: "Write 10 x 10 x 10 x 10 in exponential form.", choices: ["10 x 4", "10⁴", "4¹⁰", "40"], answer: 1 },
    { id: "G5-MA-12", grade: 5, subject: "Math", topic: "Operations", question: "What is 0.08 x 100?", choices: ["0.8", "8", "80", "800"], answer: 1 },
    { id: "G5-MA-13", grade: 5, subject: "Math", topic: "Operations", question: "Round 0.999 to the nearest whole number.", choices: ["0.9", "1", "0.1", "0.10"], answer: 1 },
    { id: "G5-MA-14", grade: 5, subject: "Math", topic: "Operations", question: "Find the product: 1.1 x 1.1", choices: ["1.1", "1.21", "2.1", "12.1"], answer: 1 },
    { id: "G5-MA-15", grade: 5, subject: "Math", topic: "Operations", question: "Solve: (10 + 5) x 2", choices: ["20", "30", "25", "15"], answer: 1 },
    { id: "G5-MA-16", grade: 5, subject: "Math", topic: "Operations", question: "What is 1,000 ÷ 10²?", choices: ["1", "10", "100", "0"], answer: 1 },
    { id: "G5-MA-17", grade: 5, subject: "Math", topic: "Operations", question: "Solve: 1.5 + 2.75", choices: ["4.25", "3.25", "4.0", "3.5"], answer: 0 },
    { id: "G5-MA-18", grade: 5, subject: "Math", topic: "Operations", question: "Find the difference: 10 - 4.5", choices: ["6.5", "5.5", "5.0", "6.0"], answer: 1 },
    { id: "G5-MA-19", grade: 5, subject: "Math", topic: "Operations", question: "Multiply: 0.5 x 0.5", choices: ["2.5", "0.25", "0.05", "1.0"], answer: 1 },
    { id: "G5-MA-20", grade: 5, subject: "Math", topic: "Operations", question: "Divide: 4.8 ÷ 2", choices: ["2.4", "0.24", "24", "4.2"], answer: 0 },
    { id: "G5-MA-21", grade: 5, subject: "Math", topic: "Operations", question: "Value of expression: 5 + 3 x 2", choices: ["16", "11", "10", "13"], answer: 1 },
    { id: "G5-MA-22", grade: 5, subject: "Math", topic: "Operations", question: "What is 750 x 0?", choices: ["750", "1", "0", "75"], answer: 2 },
    { id: "G5-MA-23", grade: 5, subject: "Math", topic: "Operations", question: "1/10 of 500 is?", choices: ["5", "50", "500", "0.5"], answer: 1 },
    { id: "G5-MA-24", grade: 5, subject: "Math", topic: "Operations", question: "Compare: 3.1 _ 3.09", choices: [">", "<", "=", "none"], answer: 0 },
    { id: "G5-MA-25", grade: 5, subject: "Math", topic: "Operations", question: "Round 5.67 to the nearest tenth.", choices: ["5.6", "5.7", "6.0", "5.0"], answer: 1 },

    // --- TOPIC 2: FRACTIONS & MIXED NUMBERS (25 Questions) ---
    { id: "G5-MA-26", grade: 5, subject: "Math", topic: "Fractions", question: "What is 1/2 + 1/3?", choices: ["2/5", "5/6", "1/5", "3/6"], answer: 1 },
    { id: "G5-MA-27", grade: 5, subject: "Math", topic: "Fractions", question: "Solve: 4/5 - 1/2", choices: ["3/3", "3/10", "3/5", "1/3"], answer: 1 },
    { id: "G5-MA-28", grade: 5, subject: "Math", topic: "Fractions", question: "Multiply: 1/2 x 1/2", choices: ["1", "1/4", "1/2", "0"], answer: 1 },
    { id: "G5-MA-29", grade: 5, subject: "Math", topic: "Fractions", question: "What is 1/2 ÷ 2?", choices: ["1", "1/4", "4", "1/2"], answer: 1 },
    { id: "G5-MA-30", grade: 5, subject: "Math", topic: "Fractions", question: "What is 2 ÷ 1/2?", choices: ["1", "4", "1/4", "2"], answer: 1 },
    { id: "G5-MA-31", grade: 5, subject: "Math", topic: "Fractions", question: "Simplify 10/20.", choices: ["1/2", "1/4", "2/1", "5/10"], answer: 0 },
    { id: "G5-MA-32", grade: 5, subject: "Math", topic: "Fractions", question: "What is 3/4 of 12?", choices: ["6", "9", "8", "3"], answer: 1 },
    { id: "G5-MA-33", grade: 5, subject: "Math", topic: "Fractions", question: "Find a common denominator for 1/4 and 1/6.", choices: ["4", "6", "12", "10"], answer: 2 },
    { id: "G5-MA-34", grade: 5, subject: "Math", topic: "Fractions", question: "Solve: 1 and 1/2 + 2 and 1/2", choices: ["3", "4", "3 and 1/2", "5"], answer: 1 },
    { id: "G5-MA-35", grade: 5, subject: "Math", topic: "Fractions", question: "1/5 as a decimal is:", choices: ["0.1", "0.2", "0.5", "0.05"], answer: 1 },
    { id: "G5-MA-36", grade: 5, subject: "Math", topic: "Fractions", question: "3/10 + 4/100 =", choices: ["7/100", "34/100", "7/10", "34/10"], answer: 1 },
    { id: "G5-MA-37", grade: 5, subject: "Math", topic: "Fractions", question: "Is 1/3 greater than 1/4?", choices: ["Yes", "No", "They are equal", "Maybe"], answer: 0 },
    { id: "G5-MA-38", grade: 5, subject: "Math", topic: "Fractions", question: "Which is the numerator in 7/11?", choices: ["7", "11", "0", "1"], answer: 0 },
    { id: "G5-MA-39", grade: 5, subject: "Math", topic: "Fractions", question: "What is 5 x 2/5?", choices: ["1", "2", "5", "10"], answer: 1 },
    { id: "G5-MA-40", grade: 5, subject: "Math", topic: "Fractions", question: "Convert 0.75 to a fraction.", choices: ["1/2", "3/4", "1/4", "2/3"], answer: 1 },
    { id: "G5-MA-41", grade: 5, subject: "Math", topic: "Fractions", question: "Add: 0.1 + 0.01", choices: ["0.2", "0.11", "0.02", "1.1"], answer: 1 },
    { id: "G5-MA-42", grade: 5, subject: "Math", topic: "Fractions", question: "Divide 1 by 3. Result is:", choices: ["0.3", "0.33...", "1/3", "Both B and C"], answer: 3 },
    { id: "G5-MA-43", grade: 5, subject: "Math", topic: "Fractions", question: "What is half of 0.5?", choices: ["0.25", "0.1", "0.5", "1.0"], answer: 0 },
    { id: "G5-MA-44", grade: 5, subject: "Math", topic: "Fractions", question: "Multiply: 2/3 x 3/4", choices: ["6/12", "1/2", "5/7", "Both A and B"], answer: 3 },
    { id: "G5-MA-45", grade: 5, subject: "Math", topic: "Fractions", question: "What is 10/10 equal to?", choices: ["0", "1", "10", "100"], answer: 1 },
    { id: "G5-MA-46", grade: 5, subject: "Math", topic: "Fractions", question: "Convert 13/5 to a mixed number.", choices: ["2 and 3/5", "1 and 3/5", "2 and 1/5", "3"], answer: 0 },
    { id: "G5-MA-47", grade: 5, subject: "Math", topic: "Fractions", question: "Subtract: 1 - 5/8", choices: ["3/8", "5/8", "1/8", "0"], answer: 0 },
    { id: "G5-MA-48", grade: 5, subject: "Math", topic: "Fractions", question: "Least Common Multiple of 3 and 5 is:", choices: ["8", "10", "15", "30"], answer: 2 },
    { id: "G5-MA-49", grade: 5, subject: "Math", topic: "Fractions", question: "Are 2/4 and 4/8 equivalent?", choices: ["Yes", "No"], answer: 0 },
    { id: "G5-MA-50", grade: 5, subject: "Math", topic: "Fractions", question: "Complete: 1/10, 2/10, ___", choices: ["3/10", "1/5", "0.3", "All are correct"], answer: 3 },

    // --- TOPIC 3: GEOMETRY & VOLUME (25 Questions - AI Generated) ---
    { id: "G5-MA-51", grade: 5, subject: "Math", topic: "Geometry", question: "Volume of a rectangular prism = Length x Width x ___.", choices: ["Area", "Height", "Weight", "Diagonal"], answer: 1 },
    { id: "G5-MA-52", grade: 5, subject: "Math", topic: "Geometry", question: "Volume is measured in ___ units.", choices: ["Square", "Cubic", "Linear", "Weight"], answer: 1 },
    { id: "G5-MA-53", grade: 5, subject: "Math", topic: "Geometry", question: "Find the volume of a box: L=2, W=3, H=4.", choices: ["9", "12", "24", "14"], answer: 2 },
    { id: "G5-MA-54", grade: 5, subject: "Math", topic: "Geometry", question: "A unit cube has a side length of ___.", choices: ["1", "5", "10", "100"], answer: 0 },
    { id: "G5-MA-55", grade: 5, subject: "Math", topic: "Geometry", question: "A polygon with 5 sides is a ___.", choices: ["Square", "Pentagon", "Hexagon", "Octagon"], answer: 1 },
    { id: "G5-MA-56", grade: 5, subject: "Math", topic: "Geometry", question: "A polygon with 6 sides is a ___.", choices: ["Pentagon", "Hexagon", "Octagon", "Nonagon"], answer: 1 },
    { id: "G5-MA-57", grade: 5, subject: "Math", topic: "Geometry", question: "A triangle with all sides equal is ___.", choices: ["Isosceles", "Equilateral", "Scalene", "Right"], answer: 1 },
    { id: "G5-MA-58", grade: 5, subject: "Math", topic: "Geometry", question: "A triangle with two equal sides is ___.", choices: ["Scalene", "Isosceles", "Equilateral", "Obtuse"], answer: 1 },
    { id: "G5-MA-59", grade: 5, subject: "Math", topic: "Geometry", question: "A triangle with NO equal sides is ___.", choices: ["Scalene", "Isosceles", "Equilateral", "Right"], answer: 0 },
    { id: "G5-MA-60", grade: 5, subject: "Math", topic: "Geometry", question: "The sum of angles in any triangle is ___ degrees.", choices: ["90", "180", "360", "45"], answer: 1 },
    { id: "G5-MA-61", grade: 5, subject: "Math", topic: "Geometry", question: "How many degrees are in a right angle?", choices: ["45", "90", "180", "360"], answer: 1 },
    { id: "G5-MA-62", grade: 5, subject: "Math", topic: "Geometry", question: "Parallel lines ___ intersect.", choices: ["Always", "Never", "Sometimes", "Once"], answer: 1 },
    { id: "G5-MA-63", grade: 5, subject: "Math", topic: "Geometry", question: "Perpendicular lines intersect at a ___ degree angle.", choices: ["0", "90", "180", "45"], answer: 1 },
    { id: "G5-MA-64", grade: 5, subject: "Math", topic: "Geometry", question: "A quadrilateral with 4 equal sides and 4 right angles is a ___.", choices: ["Rectangle", "Rhombus", "Square", "Trapezoid"], answer: 2 },
    { id: "G5-MA-65", grade: 5, subject: "Math", topic: "Geometry", question: "A quadrilateral with only one pair of parallel sides is a ___.", choices: ["Rectangle", "Parallelogram", "Trapezoid", "Rhombus"], answer: 2 },
    { id: "G5-MA-66", grade: 5, subject: "Math", topic: "Geometry", question: "The point (0,0) on a coordinate plane is the ___.", choices: ["End", "Origin", "Apex", "Center"], answer: 1 },
    { id: "G5-MA-67", grade: 5, subject: "Math", topic: "Coordinate", question: "In (x,y), the first number is the ___ coordinate.", choices: ["x", "y", "z", "Origin"], answer: 0 },
    { id: "G5-MA-68", grade: 5, subject: "Math", topic: "Coordinate", question: "To plot (3,2), you move ___ 3 and ___ 2.", choices: ["Up, Right", "Right, Up", "Left, Down", "Down, Right"], answer: 1 },
    { id: "G5-MA-69", grade: 5, subject: "Math", topic: "Geometry", question: "Area of a rectangle = ___ x Width.", choices: ["Height", "Length", "Diagonal", "Sum"], answer: 1 },
    { id: "G5-MA-70", grade: 5, subject: "Math", topic: "Geometry", question: "Perimeter is the distance ___ a shape.", choices: ["Inside", "Around", "Through", "Across"], answer: 1 },
    { id: "G5-MA-71", grade: 5, subject: "Math", topic: "Geometry", question: "A 3D shape with 6 square faces is a ___.", choices: ["Prism", "Pyramid", "Cube", "Sphere"], answer: 2 },
    { id: "G5-MA-72", grade: 5, subject: "Math", topic: "Geometry", question: "The long side of a right triangle is the ___.", choices: ["Leg", "Hypotenuse", "Base", "Apex"], answer: 1 },
    { id: "G5-MA-73", grade: 5, subject: "Math", topic: "Geometry", question: "A circle has ___ sides.", choices: ["1", "4", "0", "Infinite"], answer: 2 },
    { id: "G5-MA-74", grade: 5, subject: "Math", topic: "Geometry", question: "A line from the center to the edge of a circle is the ___.", choices: ["Diameter", "Radius", "Circumference", "Tangent"], answer: 1 },
    { id: "G5-MA-75", grade: 5, subject: "Math", topic: "Geometry", question: "The distance around a circle is the ___.", choices: ["Area", "Circumference", "Diameter", "Radius"], answer: 1 },

    // --- TOPIC 4: DATA, MEASUREMENT & ALGEBRAIC THINKING (25 Questions - AI Generated) ---
    { id: "G5-MA-76", grade: 5, subject: "Math", topic: "Algebra", question: "In the expression 2n, if n=5, the value is ___.", choices: ["7", "10", "25", "3"], answer: 1 },
    { id: "G5-MA-77", grade: 5, subject: "Math", topic: "Algebra", question: "Evaluate: 10 - (2 x 3)", choices: ["24", "4", "15", "8"], answer: 1 },
    { id: "G5-MA-78", grade: 5, subject: "Math", topic: "Algebra", question: "What is the next number: 2, 4, 6, 8, ___?", choices: ["9", "10", "12", "14"], answer: 1 },
    { id: "G5-MA-79", grade: 5, subject: "Math", topic: "Measurement", question: "How many centimeters in 1 meter?", choices: ["10", "100", "1,000", "50"], answer: 1 },
    { id: "G5-MA-80", grade: 5, subject: "Math", topic: "Measurement", question: "How many grams in 1 kilogram?", choices: ["100", "1,000", "10,000", "10"], answer: 1 },
    { id: "G5-MA-81", grade: 5, subject: "Math", topic: "Measurement", question: "How many milliliters in 1 liter?", choices: ["10", "100", "1,000", "500"], answer: 2 },
    { id: "G5-MA-82", grade: 5, subject: "Math", topic: "Measurement", question: "How many inches in 1 foot?", choices: ["10", "12", "24", "36"], answer: 1 },
    { id: "G5-MA-83", grade: 5, subject: "Math", topic: "Measurement", question: "How many feet in 1 yard?", choices: ["1", "2", "3", "4"], answer: 2 },
    { id: "G5-MA-84", grade: 5, subject: "Math", topic: "Data", question: "The average of a set of numbers is the ___.", choices: ["Median", "Mode", "Mean", "Range"], answer: 2 },
    { id: "G5-MA-85", grade: 5, subject: "Math", topic: "Data", question: "The number that appears most often in a set is the ___.", choices: ["Mean", "Median", "Mode", "Range"], answer: 2 },
    { id: "G5-MA-86", grade: 5, subject: "Math", topic: "Data", question: "The middle value in an ordered set is the ___.", choices: ["Mean", "Median", "Mode", "Range"], answer: 1 },
    { id: "G5-MA-87", grade: 5, subject: "Math", topic: "Data", question: "Difference between the highest and lowest values is the ___.", choices: ["Sum", "Mean", "Range", "Mode"], answer: 2 },
    { id: "G5-MA-88", grade: 5, subject: "Math", topic: "Measurement", question: "1 mile is equal to ___ feet.", choices: ["5,000", "5,280", "4,280", "1,000"], answer: 1 },
    { id: "G5-MA-89", grade: 5, subject: "Math", topic: "Algebra", question: "If x + 5 = 12, then x = ___.", choices: ["5", "7", "17", "6"], answer: 1 },
    { id: "G5-MA-90", grade: 5, subject: "Math", topic: "Algebra", question: "If 3y = 15, then y = ___.", choices: ["3", "5", "12", "45"], answer: 1 },
    { id: "G5-MA-91", grade: 5, subject: "Math", topic: "Measurement", question: "How many ounces in 1 pound?", choices: ["8", "12", "16", "24"], answer: 2 },
    { id: "G5-MA-92", grade: 5, subject: "Math", topic: "Measurement", question: "How many cups in 1 pint?", choices: ["1", "2", "4", "8"], answer: 1 },
    { id: "G5-MA-93", grade: 5, subject: "Math", topic: "Measurement", question: "How many pints in 1 quart?", choices: ["2", "4", "8", "10"], answer: 0 },
    { id: "G5-MA-94", grade: 5, subject: "Math", topic: "Measurement", question: "How many quarts in 1 gallon?", choices: ["2", "4", "8", "16"], answer: 1 },
    { id: "G5-MA-95", grade: 5, subject: "Math", topic: "Data", question: "A graph that uses points to show data trends is a ___ graph.", choices: ["Bar", "Pie", "Line", "Histogram"], answer: 2 },
    { id: "G5-MA-96", grade: 5, subject: "Math", topic: "Algebra", question: "The result of multiplication is the ___.", choices: ["Sum", "Difference", "Product", "Quotient"], answer: 2 },
    { id: "G5-MA-97", grade: 5, subject: "Math", topic: "Algebra", question: "The result of division is the ___.", choices: ["Sum", "Product", "Remainder", "Quotient"], answer: 3 },
    { id: "G5-MA-98", grade: 5, subject: "Math", topic: "Algebra", question: "PEMDAS tells you the ___ of operations.", choices: ["Speed", "Order", "Number", "History"], answer: 1 },
    { id: "G5-MA-99", grade: 5, subject: "Math", topic: "Measurement", question: "Freezing point of water in Celsius is ___ degrees.", choices: ["0", "32", "100", "212"], answer: 0 },
    { id: "G5-MA-100", grade: 5, subject: "Math", topic: "Algebra", question: "What is 10 x 0.1?", choices: ["0.1", "1", "10", "100"], answer: 1 }
];

module.exports = G5_MATH_COMPLETE;
