const G6_ELA_COMPLETE = [
    // --- TOPIC 1: READING LITERATURE & TEXT (25 Questions) ---
    { id: "G6-ELA-01", grade: 6, subject: "ELA", topic: "Literature", question: "The central message or lesson of a story is the ___.", choices: ["Plot", "Theme", "Setting", "Climax"], answer: 1 },
    { id: "G6-ELA-02", grade: 6, subject: "ELA", topic: "Literature", question: "Which point of view uses the pronoun 'I'?", choices: ["First-person", "Second-person", "Third-person limited", "Third-person omniscient"], answer: 0 },
    { id: "G6-ELA-03", grade: 6, subject: "ELA", topic: "Literature", question: "The high point or turning point of a story is the ___.", choices: ["Exposition", "Rising Action", "Climax", "Resolution"], answer: 2 },
    { id: "G6-ELA-04", grade: 6, subject: "ELA", topic: "Text Evidence", question: "To 'infer' means to make a guess based on ___.", choices: ["Random thoughts", "Evidence and reasoning", "The title only", "The back cover"], answer: 1 },
    { id: "G6-ELA-05", grade: 6, subject: "ELA", topic: "Literature", question: "The antagonist in a story is the character who ___.", choices: ["Is the hero", "Opposes the protagonist", "Narrates the story", "Is a minor character"], answer: 1 },
    { id: "G6-ELA-06", grade: 6, subject: "ELA", topic: "Informational", question: "A short summary should only include ___.", choices: ["Minor details", "Your opinion", "Main ideas", "The ending only"], answer: 2 },
    { id: "G6-ELA-07", grade: 6, subject: "ELA", topic: "Literature", question: "The time and place of a story is the ___.", choices: ["Theme", "Conflict", "Setting", "Genre"], answer: 2 },
    { id: "G6-ELA-08", grade: 6, subject: "ELA", topic: "Text Evidence", question: "Which phrase is used to cite evidence?", choices: ["I think...", "The author states...", "Once upon a time...", "In my opinion..."], answer: 1 },
    { id: "G6-ELA-09", grade: 6, subject: "ELA", topic: "Literature", question: "A struggle between opposing forces is called ___.", choices: ["Theme", "Plot", "Conflict", "Resolution"], answer: 2 },
    { id: "G6-ELA-10", grade: 6, subject: "ELA", topic: "Informational", question: "Which text feature explains an image?", choices: ["Heading", "Index", "Caption", "Glossary"], answer: 2 },
    { id: "G6-ELA-11", grade: 6, subject: "ELA", topic: "Literature", question: "A character that changes during a story is ___.", choices: ["Static", "Dynamic", "Flat", "Minor"], answer: 1 },
    { id: "G6-ELA-12", grade: 6, subject: "ELA", topic: "Informational", question: "The 'main idea' is also known as the ___.", choices: ["Central idea", "Supporting detail", "Evidence", "Topic sentence"], answer: 0 },
    { id: "G6-ELA-13", grade: 6, subject: "ELA", topic: "Literature", question: "The 'Resolution' occurs at the ___ of the story.", choices: ["Beginning", "Middle", "End", "Climax"], answer: 2 },
    { id: "G6-ELA-14", grade: 6, subject: "ELA", topic: "Informational", question: "Biographies are written in which point of view?", choices: ["First-person", "Third-person", "Second-person", "None"], answer: 1 },
    { id: "G6-ELA-15", grade: 6, subject: "ELA", topic: "Literature", question: "A hint about what will happen later in a story is ___.", choices: ["Flashback", "Foreshadowing", "Irony", "Metaphor"], answer: 1 },
    { id: "G6-SCI-16", grade: 6, subject: "ELA", topic: "Literature", question: "Third-person 'omniscient' means the narrator knows ___.", choices: ["Only one character's thoughts", "Nothing", "Everything about all characters", "The future"], answer: 2 },
    { id: "G6-ELA-17", grade: 6, subject: "ELA", topic: "Informational", question: "Which organizational pattern uses 'first, next, finally'?", choices: ["Cause/Effect", "Chronological/Sequence", "Compare/Contrast", "Problem/Solution"], answer: 1 },
    { id: "G6-ELA-18", grade: 6, subject: "ELA", topic: "Text Evidence", question: "To paraphrase means to ___.", choices: ["Copy word for word", "Put it in your own words", "Skip the text", "Change the meaning"], answer: 1 },
    { id: "G6-ELA-19", grade: 6, subject: "ELA", topic: "Literature", question: "Internal conflict happens ___.", choices: ["Between two friends", "Inside a character's mind", "Against nature", "Against society"], answer: 1 },
    { id: "G6-ELA-20", grade: 6, subject: "ELA", topic: "Informational", question: "An 'objective' summary is free of ___.", choices: ["Facts", "Main ideas", "Opinions", "Verbs"], answer: 2 },
    { id: "G6-ELA-21", grade: 6, subject: "ELA", topic: "Literature", question: "The way an author makes the reader feel is the ___.", choices: ["Tone", "Mood", "Voice", "Style"], answer: 1 },
    { id: "G6-ELA-22", grade: 6, subject: "ELA", topic: "Literature", question: "The author's attitude toward a subject is the ___.", choices: ["Tone", "Mood", "Theme", "Setting"], answer: 0 },
    { id: "G6-ELA-23", grade: 6, subject: "ELA", topic: "Informational", question: "What is the purpose of a 'Heading'?", choices: ["To define a word", "To tell what a section is about", "To list page numbers", "To provide a quote"], answer: 1 },
    { id: "G6-ELA-24", grade: 6, subject: "ELA", topic: "Literature", question: "Historical fiction takes place in ___.", choices: ["The future", "The past", "Outer space", "A dream"], answer: 1 },
    { id: "G6-ELA-25", grade: 6, subject: "ELA", topic: "Text Evidence", question: "A 'claim' is a statement that ___.", choices: ["Is always true", "Needs to be supported by evidence", "Is a question", "Is the same as a fact"], answer: 1 },

    // --- TOPIC 2: GRAMMAR & USAGE (25 Questions) ---
    { id: "G6-ELA-26", grade: 6, subject: "ELA", topic: "Grammar", question: "Which is a subjective pronoun?", choices: ["Me", "Him", "I", "Them"], answer: 2 },
    { id: "G6-ELA-27", grade: 6, subject: "ELA", topic: "Grammar", question: "Which is an objective pronoun?", choices: ["She", "He", "Us", "We"], answer: 2 },
    { id: "G6-ELA-28", grade: 6, subject: "ELA", topic: "Grammar", question: "A pronoun must agree with its ___.", choices: ["Verb", "Adverb", "Antecedent", "Object"], answer: 2 },
    { id: "G6-ELA-29", grade: 6, subject: "ELA", topic: "Punctuation", question: "What punctuation is used to show a pause or list?", choices: ["Period", "Comma", "Exclamation", "Question mark"], answer: 1 },
    { id: "G6-ELA-30", grade: 6, subject: "ELA", topic: "Grammar", question: "Which is an intensive pronoun?", choices: ["Him", "Them", "Myself", "Each"], answer: 2 },
    { id: "G6-ELA-31", grade: 6, subject: "ELA", topic: "Grammar", question: "Find the possessive pronoun: 'That book is ___.'", choices: ["Mine", "Me", "I", "My"], answer: 0 },
    { id: "G6-ELA-32", grade: 6, subject: "ELA", topic: "Grammar", question: "A 'run-on' sentence is two sentences ___.", choices: ["Joined correctly", "Missing a verb", "Joined without punctuation", "That are too short"], answer: 2 },
    { id: "G6-ELA-33", grade: 6, subject: "ELA", topic: "Grammar", question: "Identify the conjunction: 'I like cake and pie.'", choices: ["I", "Like", "And", "Cake"], answer: 2 },
    { id: "G6-ELA-34", grade: 6, subject: "ELA", topic: "Grammar", question: "Which is a 'Proper Noun'?", choices: ["city", "country", "France", "river"], answer: 2 },
    { id: "G6-ELA-35", grade: 6, subject: "ELA", topic: "Grammar", question: "An 'adjective' describes a ___.", choices: ["Verb", "Noun", "Adverb", "Preposition"], answer: 1 },
    { id: "G6-ELA-36", grade: 6, subject: "ELA", topic: "Grammar", question: "An 'adverb' often ends in ___.", choices: ["-ed", "-ing", "-ly", "-s"], answer: 2 },
    { id: "G6-ELA-37", grade: 6, subject: "ELA", topic: "Grammar", question: "Which is a 'fragment'?", choices: ["I ran.", "Because it was raining.", "The dog barked.", "She is tall."], answer: 1 },
    { id: "G6-ELA-38", grade: 6, subject: "ELA", topic: "Punctuation", question: "What is used to show someone is speaking?", choices: ["Parentheses", "Quotation marks", "Apostrophes", "Hyphens"], answer: 1 },
    { id: "G6-ELA-39", grade: 6, subject: "ELA", topic: "Grammar", question: "The 'subject' of a sentence is ___.", choices: ["The action", "The person/thing doing the action", "The location", "The ending"], answer: 1 },
    { id: "G6-ELA-40", grade: 6, subject: "ELA", topic: "Grammar", question: "Which pronoun is vague? 'They said it was closed.'", choices: ["It", "They", "Was", "Closed"], answer: 1 },
    { id: "G6-ELA-41", grade: 6, subject: "ELA", topic: "Grammar", question: "Which is a plural noun?", choices: ["Cat", "Box", "Children", "Child"], answer: 2 },
    { id: "G6-ELA-42", grade: 6, subject: "ELA", topic: "Punctuation", question: "Use an 'apostrophe' for ___.", choices: ["Lists", "Contractions", "Endings", "Starts"], answer: 1 },
    { id: "G6-ELA-43", grade: 6, subject: "ELA", topic: "Grammar", question: "A 'compound' sentence has ___.", choices: ["One subject", "Two independent clauses", "No verb", "Only adjectives"], answer: 1 },
    { id: "G6-ELA-44", grade: 6, subject: "ELA", topic: "Grammar", question: "Which is a preposition?", choices: ["Under", "Fast", "Jump", "Yellow"], answer: 0 },
    { id: "G6-ELA-45", grade: 6, subject: "ELA", topic: "Grammar", question: "The word 'quickly' is a/an ___.", choices: ["Noun", "Verb", "Adjective", "Adverb"], answer: 3 },
    { id: "G6-ELA-46", grade: 6, subject: "ELA", topic: "Grammar", question: "Which is a 'helping verb'?", choices: ["Run", "Was", "Apple", "Slowly"], answer: 1 },
    { id: "G6-ELA-47", grade: 6, subject: "ELA", topic: "Grammar", question: "Comparative adjectives (comparing 2) often end in ___.", choices: ["-est", "-er", "-ing", "-ly"], answer: 1 },
    { id: "G6-ELA-48", grade: 6, subject: "ELA", topic: "Grammar", question: "Superlative adjectives (comparing 3+) often end in ___.", choices: ["-est", "-er", "-ing", "-ly"], answer: 0 },
    { id: "G6-ELA-49", grade: 6, subject: "ELA", topic: "Grammar", question: "Which sentence is in 'past tense'?", choices: ["I run.", "I will run.", "I ran.", "I am running."], answer: 2 },
    { id: "G6-ELA-50", grade: 6, subject: "ELA", topic: "Grammar", question: "Identify the interjection.", choices: ["Wow!", "And", "The", "Blue"], answer: 0 },

    // --- TOPIC 3: WRITING TYPES (25 Questions) ---
    { id: "G6-ELA-51", grade: 6, subject: "ELA", topic: "Writing", question: "Writing that tells a story is ___.", choices: ["Argumentative", "Narrative", "Expository", "Persuasive"], answer: 1 },
    { id: "G6-ELA-52", grade: 6, subject: "ELA", topic: "Writing", question: "The main argument of an essay is the ___.", choices: ["Introduction", "Thesis Statement", "Body Paragraph", "Hook"], answer: 1 },
    { id: "G6-ELA-53", grade: 6, subject: "ELA", topic: "Writing", question: "A 'Hook' is designed to ___.", choices: ["End the essay", "Grab the reader's attention", "List sources", "Define words"], answer: 1 },
    { id: "G6-ELA-54", grade: 6, subject: "ELA", topic: "Writing", question: "Which writing type explains a topic?", choices: ["Narrative", "Expository", "Science Fiction", "Poetry"], answer: 1 },
    { id: "G6-ELA-55", grade: 6, subject: "ELA", topic: "Writing", question: "Transitions like 'However' show ___.", choices: ["Agreement", "Contrast", "Sequence", "Addition"], answer: 1 },
    { id: "G6-ELA-56", grade: 6, subject: "ELA", topic: "Writing", question: "A 'counter-argument' is ___.", choices: ["The same as your claim", "The opposite side of the argument", "A summary", "A bibliography"], answer: 1 },
    { id: "G6-ELA-57", grade: 6, subject: "ELA", topic: "Writing", question: "In a narrative, 'dialogue' is ___.", choices: ["Setting the scene", "Characters talking", "The conclusion", "A list of facts"], answer: 1 },
    { id: "G6-ELA-58", grade: 6, subject: "ELA", topic: "Writing", question: "Sensory details appeal to the five ___.", choices: ["Senses", "Paragraphs", "Sentences", "Friends"], answer: 0 },
    { id: "G6-ELA-59", grade: 6, subject: "ELA", topic: "Writing", question: "Which is a credible source for a research paper?", choices: ["An anonymous blog", "A government website (.gov)", "A social media post", "A comic book"], answer: 1 },
    { id: "G6-ELA-60", grade: 6, subject: "ELA", topic: "Writing", question: "The final paragraph of an essay is the ___.", choices: ["Introduction", "Body", "Conclusion", "Hook"], answer: 2 },
    { id: "G6-ELA-61", grade: 6, subject: "ELA", topic: "Writing", question: "Argumentative writing requires ___ to be effective.", choices: ["Only opinions", "Logic and evidence", "Pictures", "A happy ending"], answer: 1 },
    { id: "G6-ELA-62", grade: 6, subject: "ELA", topic: "Writing", question: "Plagiarism is ___.", choices: ["Citing a source", "Using someone else's work as your own", "Writing a summary", "Checking spelling"], answer: 1 },
    { id: "G6-ELA-63", grade: 6, subject: "ELA", topic: "Writing", question: "Formal writing should avoid ___.", choices: ["Facts", "Slang and contractions", "Thesis statements", "Transitions"], answer: 1 },
    { id: "G6-ELA-64", grade: 6, subject: "ELA", topic: "Writing", question: "The 'audience' is ___.", choices: ["The person writing", "The people reading the work", "The main character", "The publisher"], answer: 1 },
    { id: "G6-ELA-65", grade: 6, subject: "ELA", topic: "Writing", question: "To 'revise' means to ___.", choices: ["Fix spelling", "Improve ideas and structure", "Delete the whole thing", "Print the paper"], answer: 1 },
    { id: "G6-ELA-66", grade: 6, subject: "ELA", topic: "Writing", question: "To 'edit' means to ___.", choices: ["Add new chapters", "Fix grammar and mechanics", "Change the thesis", "Interview an author"], answer: 1 },
    { id: "G6-ELA-67", grade: 6, subject: "ELA", topic: "Writing", question: "Which transition shows 'Cause and Effect'?", choices: ["First", "Therefore", "Similarly", "For example"], answer: 1 },
    { id: "G6-ELA-68", grade: 6, subject: "ELA", topic: "Writing", question: "What is a 'Draft'?", choices: ["The final version", "A preliminary version of writing", "A spelling test", "A list of ideas"], answer: 1 },
    { id: "G6-ELA-69", grade: 6, subject: "ELA", topic: "Writing", question: "Writing to convince someone is ___.", choices: ["Expository", "Persuasive", "Narrative", "Descriptive"], answer: 1 },
    { id: "G6-ELA-70", grade: 6, subject: "ELA", topic: "Writing", question: "What is the purpose of 'Brainstorming'?", choices: ["To finish the paper", "To generate ideas", "To check grammar", "To cite sources"], answer: 1 },
    { id: "G6-ELA-71", grade: 6, subject: "ELA", topic: "Writing", question: "An 'anecdote' is a ___.", choices: ["Definition", "Short, interesting story", "Mathematical proof", "Large book"], answer: 1 },
    { id: "G6-ELA-72", grade: 6, subject: "ELA", topic: "Writing", question: "Bibliography is a list of ___.", choices: ["Characters", "Sources used", "Spelling words", "Synonyms"], answer: 1 },
    { id: "G6-ELA-73", grade: 6, subject: "ELA", topic: "Writing", question: "A 'Clincher' sentence is found in the ___.", choices: ["Introduction", "Conclusion", "Middle of a body paragraph", "Title"], answer: 1 },
    { id: "G6-ELA-74", grade: 6, subject: "ELA", topic: "Writing", question: "Word choice is also called ___.", choices: ["Diction", "Syntax", "Punctuation", "Format"], answer: 0 },
    { id: "G6-ELA-75", grade: 6, subject: "ELA", topic: "Writing", question: "A topic sentence tells ___.", choices: ["The main idea of a paragraph", "The end of the story", "A character's name", "Where to find the index"], answer: 0 },

    // --- TOPIC 4: VOCABULARY & FIGURATIVE LANGUAGE (25 Questions) ---
    { id: "G6-ELA-76", grade: 6, subject: "ELA", topic: "Figurative", question: "A comparison using 'like' or 'as' is a ___.", choices: ["Metaphor", "Simile", "Personification", "Hyperbole"], answer: 1 },
    { id: "G6-ELA-77", grade: 6, subject: "ELA", topic: "Figurative", question: "'The wind whispered' is an example of ___.", choices: ["Simile", "Personification", "Alliteration", "Onomatopoeia"], answer: 1 },
    { id: "G6-ELA-78", grade: 6, subject: "ELA", topic: "Vocabulary", question: "Words with the same meaning are ___.", choices: ["Antonyms", "Synonyms", "Homophones", "Prefixes"], answer: 1 },
    { id: "G6-ELA-79", grade: 6, subject: "ELA", topic: "Vocabulary", question: "Words with opposite meanings are ___.", choices: ["Synonyms", "Antonyms", "Analogies", "Roots"], answer: 1 },
    { id: "G6-ELA-80", grade: 6, subject: "ELA", topic: "Figurative", question: "An extreme exaggeration is a ___.", choices: ["Simile", "Metaphor", "Hyperbole", "Idiom"], answer: 2 },
    { id: "G6-ELA-81", grade: 6, subject: "ELA", topic: "Figurative", question: "A direct comparison NOT using 'like/as' is a ___.", choices: ["Simile", "Metaphor", "Hyperbole", "Oxymoron"], answer: 1 },
    { id: "G6-ELA-82", grade: 6, subject: "ELA", topic: "Vocabulary", question: "The dictionary definition of a word is its ___.", choices: ["Connotation", "Denotation", "Context", "Etymology"], answer: 1 },
    { id: "G6-ELA-83", grade: 6, subject: "ELA", topic: "Vocabulary", question: "The emotional feeling of a word is its ___.", choices: ["Denotation", "Connotation", "Spelling", "Root"], answer: 1 },
    { id: "G6-ELA-84", grade: 6, subject: "ELA", topic: "Figurative", question: "Words that sound like what they mean (e.g., 'Pop!') are ___.", choices: ["Alliteration", "Onomatopoeia", "Simile", "Hyperbole"], answer: 1 },
    { id: "G6-ELA-85", grade: 6, subject: "ELA", topic: "Vocabulary", question: "An 'Affix' added to the start of a word is a ___.", choices: ["Suffix", "Prefix", "Root", "Stem"], answer: 1 },
    { id: "G6-ELA-86", grade: 6, subject: "ELA", topic: "Vocabulary", question: "An 'Affix' added to the end of a word is a ___.", choices: ["Prefix", "Suffix", "Root", "Homonym"], answer: 1 },
    { id: "G6-ELA-87", grade: 6, subject: "ELA", topic: "Figurative", question: "Repeating the same starting consonant sound is ___.", choices: ["Rhyme", "Alliteration", "Metaphor", "Idiom"], answer: 1 },
    { id: "G6-ELA-88", grade: 6, subject: "ELA", topic: "Vocabulary", question: "Context clues help you find a word's ___.", choices: ["Spelling", "Meaning", "History", "Page number"], answer: 1 },
    { id: "G6-ELA-89", grade: 6, subject: "ELA", topic: "Vocabulary", question: "Words that sound the same but have different meanings/spellings?", choices: ["Homophones", "Synonyms", "Antonyms", "Pronouns"], answer: 0 },
    { id: "G6-ELA-90", grade: 6, subject: "ELA", topic: "Figurative", question: "A common phrase that means something different than its literal words?", choices: ["Simile", "Idiom", "Metaphor", "Cliché"], answer: 1 },
    { id: "G6-ELA-91", grade: 6, subject: "ELA", topic: "Vocabulary", question: "What is the 'root' of the word 'unhappy'?", choices: ["un-", "happy", "unhappy", "py"], answer: 1 },
    { id: "G6-ELA-92", grade: 6, subject: "ELA", topic: "Vocabulary", question: "A 'thesaurus' is used to find ___.", choices: ["Definitions", "Synonyms", "Pronunciation", "History"], answer: 1 },
    { id: "G6-ELA-93", grade: 6, subject: "ELA", topic: "Figurative", question: "'Life is a roller coaster' is a ___.", choices: ["Simile", "Metaphor", "Hyperbole", "Personification"], answer: 1 },
    { id: "G6-ELA-94", grade: 6, subject: "ELA", topic: "Figurative", question: "'I have a million things to do' is a ___.", choices: ["Hyperbole", "Simile", "Metaphor", "Idiom"], answer: 0 },
    { id: "G6-ELA-95", grade: 6, subject: "ELA", topic: "Vocabulary", question: "The origin and history of a word is its ___.", choices: ["Biology", "Etymology", "Geography", "Thesaurus"], answer: 1 },
    { id: "G6-ELA-96", grade: 6, subject: "ELA", topic: "Figurative", question: "An 'Oxymoron' is a phrase that ___.", choices: ["Exaggerates", "Contradicts itself", "Rhymes", "Is very long"], answer: 1 },
    { id: "G6-ELA-97", grade: 6, subject: "ELA", topic: "Vocabulary", question: "A word that represents a person, place, or thing is a ___.", choices: ["Noun", "Verb", "Adjective", "Pronoun"], answer: 0 },
    { id: "G6-ELA-98", grade: 6, subject: "ELA", topic: "Figurative", question: "Giving human traits to non-human things is ___.", choices: ["Simile", "Personification", "Alliteration", "Metaphor"], answer: 1 },
    { id: "G6-ELA-99", grade: 6, subject: "ELA", topic: "Vocabulary", question: "What does the prefix 'pre-' mean?", choices: ["After", "Before", "Not", "Again"], answer: 1 },
    { id: "G6-ELA-100", grade: 6, subject: "ELA", topic: "Vocabulary", question: "What does the suffix '-less' mean?", choices: ["More", "Without", "Full of", "Like"], answer: 1 }
];

module.exports = G6_ELA_COMPLETE;
