const G6_MATH_COMPLETE = [
    // --- TOPIC 1: RATIOS & RATES (25 Questions) ---
    { id: "G6-MA-01", grade: 6, subject: "Math", topic: "Ratios", question: "A ratio is a comparison of two quantities using ___.", choices: ["Addition", "Division", "Subtraction", "Parentheses"], answer: 1 },
    { id: "G6-MA-02", grade: 6, subject: "Math", topic: "Ratios", question: "Simplest form of 12:16?", choices: ["6:8", "3:4", "2:3", "1:2"], answer: 1 },
    { id: "G6-MA-03", grade: 6, subject: "Math", topic: "Rates", question: "A unit rate always has a denominator of ___.", choices: ["0", "1", "10", "100"], answer: 1 },
    { id: "G6-MA-04", grade: 6, subject: "Math", topic: "Rates", question: "If 3 apples cost $6, the unit rate is:", choices: ["$2/apple", "$3/apple", "$18 total", "$0.50/apple"], answer: 0 },
    { id: "G6-MA-05", grade: 6, subject: "Math", topic: "Percents", question: "Percent means 'per ___'.", choices: ["Ten", "Million", "Hundred", "Thousand"], answer: 2 },
    { id: "G6-MA-06", grade: 6, subject: "Math", topic: "Ratios", question: "Ratio of 2 red to 3 blue. How many red if there are 6 blue?", choices: ["4", "5", "9", "12"], answer: 0 },
    { id: "G6-MA-07", grade: 6, subject: "Math", topic: "Percents", question: "What is 25% of 80?", choices: ["20", "25", "40", "10"], answer: 0 },
    { id: "G6-MA-08", grade: 6, subject: "Math", topic: "Rates", question: "A car goes 120 miles in 2 hours. Speed?", choices: ["50 mph", "60 mph", "70 mph", "120 mph"], answer: 1 },
    { id: "G6-MA-09", grade: 6, subject: "Math", topic: "Percents", question: "0.05 as a percent is:", choices: ["0.5%", "5%", "50%", "500%"], answer: 1 },
    { id: "G6-MA-10", grade: 6, subject: "Math", topic: "Ratios", question: "A tape diagram is best used for ___.", choices: ["Volume", "Comparing parts of a ratio", "Division", "Decimals"], answer: 1 },
    { id: "G6-MA-11", grade: 6, subject: "Math", topic: "Rates", question: "50 miles per gallon is a ___ rate.", choices: ["Total", "Unit", "Inverse", "Square"], answer: 1 },
    { id: "G6-MA-12", grade: 6, subject: "Math", topic: "Percents", question: "1/2 as a percent is:", choices: ["20%", "50%", "12%", "2%"], answer: 1 },
    { id: "G6-MA-13", grade: 6, subject: "Math", topic: "Ratios", question: "Are 1:3 and 3:9 equivalent?", choices: ["Yes", "No"], answer: 0 },
    { id: "G6-MA-14", grade: 6, subject: "Math", topic: "Percents", question: "What is 100% of 45?", choices: ["1", "45", "100", "0"], answer: 1 },
    { id: "G6-MA-15", grade: 6, subject: "Math", topic: "Rates", question: "Which is cheaper: 2 for $5 or 4 for $9?", choices: ["2 for $5", "4 for $9", "Equal", "None"], answer: 1 },
    { id: "G6-MA-16", grade: 6, subject: "Math", topic: "Ratios", question: "Ratio of 5 boys to 10 girls. Simplest form?", choices: ["1:2", "2:1", "5:10", "1:5"], answer: 0 },
    { id: "G6-MA-17", grade: 6, subject: "Math", topic: "Percents", question: "What is 10% of 70?", choices: ["7", "10", "17", "70"], answer: 0 },
    { id: "G6-MA-18", grade: 6, subject: "Math", topic: "Ratios", question: "If a=2 and b=3, ratio a:b is:", choices: ["2:3", "3:2", "2:5", "5:3"], answer: 0 },
    { id: "G6-MA-19", grade: 6, subject: "Math", topic: "Rates", question: "Heart beats 150 times in 2 minutes. BPM?", choices: ["75", "150", "300", "50"], answer: 0 },
    { id: "G6-MA-20", grade: 6, subject: "Math", topic: "Percents", question: "Convert 3/4 to percent.", choices: ["34%", "75%", "30%", "43%"], answer: 1 },
    { id: "G6-MA-21", grade: 6, subject: "Math", topic: "Ratios", question: "In a ratio table, you multiply or divide by a ___.", choices: ["Sum", "Constant factor", "Random number", "Difference"], answer: 1 },
    { id: "G6-MA-22", grade: 6, subject: "Math", topic: "Percents", question: "40 is 50% of what number?", choices: ["20", "80", "100", "60"], answer: 1 },
    { id: "G6-MA-23", grade: 6, subject: "Math", topic: "Rates", question: "A typist does 200 words in 4 mins. WPM?", choices: ["40", "50", "60", "800"], answer: 1 },
    { id: "G6-MA-24", grade: 6, subject: "Math", topic: "Ratios", question: "3 to 4 can be written as ___.", choices: ["3-4", "3:4", "4/3", "3+4"], answer: 1 },
    { id: "G6-MA-25", grade: 6, subject: "Math", topic: "Percents", question: "Percent of 20 that is 5?", choices: ["5%", "20%", "25%", "50%"], answer: 2 },

    // --- TOPIC 2: THE NUMBER SYSTEM (25 Questions) ---
    { id: "G6-MA-26", grade: 6, subject: "Math", topic: "Division", question: "Divide: 1/2 ÷ 1/4", choices: ["1/8", "2", "1/2", "4"], answer: 1 },
    { id: "G6-MA-27", grade: 6, subject: "Math", topic: "Factors", question: "Greatest Common Factor (GCF) of 12 and 8?", choices: ["2", "4", "6", "12"], answer: 1 },
    { id: "G6-MA-28", grade: 6, subject: "Math", topic: "Factors", question: "Least Common Multiple (LCM) of 3 and 5?", choices: ["3", "5", "8", "15"], answer: 3 },
    { id: "G6-MA-29", grade: 6, subject: "Math", topic: "Decimals", question: "Solve: 1.5 + 2.75", choices: ["3.25", "4.25", "3.80", "4.0"], answer: 1 },
    { id: "G6-MA-30", grade: 6, subject: "Math", topic: "Integers", question: "The absolute value of -10 is:", choices: ["-10", "0", "10", "1"], answer: 2 },
    { id: "G6-MA-31", grade: 6, subject: "Math", topic: "Integers", question: "Which is less: -5 or -2?", choices: ["-5", "-2", "They are equal"], answer: 0 },
    { id: "G6-MA-32", grade: 6, subject: "Math", topic: "Integers", question: "The point (0,0) is the ___.", choices: ["Corner", "Axis", "Origin", "End"], answer: 2 },
    { id: "G6-MA-33", grade: 6, subject: "Math", topic: "Decimals", question: "1.2 x 0.3 =", choices: ["3.6", "0.36", "0.036", "36"], answer: 1 },
    { id: "G6-MA-34", grade: 6, subject: "Math", topic: "Integers", question: "Opposite of 7?", choices: ["1/7", "7", "-7", "0"], answer: 2 },
    { id: "G6-MA-35", grade: 6, subject: "Math", topic: "Fractions", question: "Multiplicative inverse of 2/3?", choices: ["-2/3", "3/2", "2/3", "1"], answer: 1 },
    { id: "G6-MA-36", grade: 6, subject: "Math", topic: "Integers", question: "Point (-2, 3) is in which quadrant?", choices: ["I", "II", "III", "IV"], answer: 1 },
    { id: "G6-MA-37", grade: 6, subject: "Math", topic: "Decimals", question: "Divide: 0.5 ÷ 0.1", choices: ["0.05", "0.5", "5", "50"], answer: 2 },
    { id: "G6-MA-38", grade: 6, subject: "Math", topic: "Factors", question: "GCF of prime numbers is always:", choices: ["0", "1", "The sum", "The product"], answer: 1 },
    { id: "G6-MA-39", grade: 6, subject: "Math", topic: "Integers", question: "Absolute value measures ___ from zero.", choices: ["Direction", "Distance", "Weight", "Size"], answer: 1 },
    { id: "G6-MA-40", grade: 6, subject: "Math", topic: "Decimals", question: "4.8 - 1.25 =", choices: ["3.55", "3.65", "2.55", "3.60"], answer: 0 },
    { id: "G6-MA-41", grade: 6, subject: "Math", topic: "Integers", question: "Positive integers are ___ than zero.", choices: ["Greater", "Less", "Same"], answer: 0 },
    { id: "G6-MA-42", grade: 6, subject: "Math", topic: "Integers", question: "Sea level is represented by the integer ___.", choices: ["1", "-1", "0", "100"], answer: 2 },
    { id: "G6-MA-43", grade: 6, subject: "Math", topic: "Fractions", question: "Reciprocal of 5?", choices: ["-5", "1/5", "5/1", "0.5"], answer: 1 },
    { id: "G6-MA-44", grade: 6, subject: "Math", topic: "Decimals", question: "Move decimal ___ when multiplying by 10.", choices: ["Left", "Right", "Down", "Up"], answer: 1 },
    { id: "G6-MA-45", grade: 6, subject: "Math", topic: "Integers", question: "Quadrant III has ___ x and ___ y.", choices: ["+, +", "-, -", "+, -", "-, +"], answer: 1 },
    { id: "G6-MA-46", grade: 6, subject: "Math", topic: "Factors", question: "LCM of 4 and 10?", choices: ["40", "20", "10", "4"], answer: 1 },
    { id: "G6-MA-47", grade: 6, subject: "Math", topic: "Fractions", question: "KCF in fraction division stands for:", choices: ["Keep Change Flip", "Keep Clear Fast", "Know Cell Form", "Key Change Fact"], answer: 0 },
    { id: "G6-MA-48", grade: 6, subject: "Math", topic: "Integers", question: "Integer for 'Withdrawal of $20'?", choices: ["20", "-20", "0", "40"], answer: 1 },
    { id: "G6-MA-49", grade: 6, subject: "Math", topic: "Decimals", question: "Align the ___ when adding decimals.", choices: ["Last digits", "Decimal points", "First digits", "Zeroes"], answer: 1 },
    { id: "G6-MA-50", grade: 6, subject: "Math", topic: "Factors", question: "List factors of 6.", choices: ["1, 2, 3, 6", "6, 12, 18", "1, 6", "2, 3"], answer: 0 },

    // --- TOPIC 3: EXPRESSIONS & EQUATIONS (25 Questions) ---
    { id: "G6-MA-51", grade: 6, subject: "Math", topic: "Algebra", question: "A letter representing a number is a ___.", choices: ["Constant", "Variable", "Operator", "Equation"], answer: 1 },
    { id: "G6-MA-52", grade: 6, subject: "Math", topic: "Exponents", question: "What is 3 squared (3²)?", choices: ["6", "9", "3", "5"], answer: 1 },
    { id: "G6-MA-53", grade: 6, subject: "Math", topic: "Order of Ops", question: "P in PEMDAS stands for:", choices: ["Plus", "Parentheses", "Power", "Product"], answer: 1 },
    { id: "G6-MA-54", grade: 6, subject: "Math", topic: "Algebra", question: "Coefficient in 4x?", choices: ["x", "4", "4x", "none"], answer: 1 },
    { id: "G6-MA-55", grade: 6, subject: "Math", topic: "Equations", question: "Solve for x: x + 5 = 12", choices: ["7", "17", "60", "5"], answer: 0 },
    { id: "G6-MA-56", grade: 6, subject: "Math", topic: "Algebra", question: "Simplify 2(x + 3):", choices: ["2x + 3", "2x + 6", "5x", "x + 6"], answer: 1 },
    { id: "G6-MA-57", grade: 6, subject: "Math", topic: "Exponents", question: "What is 10³?", choices: ["30", "100", "1000", "10"], answer: 2 },
    { id: "G6-MA-58", grade: 6, subject: "Math", topic: "Equations", question: "Solve for y: 3y = 15", choices: ["5", "12", "18", "45"], answer: 0 },
    { id: "G6-MA-59", grade: 6, subject: "Math", topic: "Inequalities", question: "Which symbol means 'greater than or equal to'?", choices: [">", "<", "≥", "≤"], answer: 2 },
    { id: "G6-MA-60", grade: 6, subject: "Math", topic: "Algebra", question: "Evaluate 2n + 1 if n = 4.", choices: ["7", "9", "11", "5"], answer: 1 },
    { id: "G6-MA-61", grade: 6, subject: "Math", topic: "Order of Ops", question: "Solve: 10 - 2 × 3", choices: ["24", "4", "18", "8"], answer: 1 },
    { id: "G6-MA-62", grade: 6, subject: "Math", topic: "Equations", question: "If 10 = x - 2, then x =", choices: ["8", "12", "20", "5"], answer: 1 },
    { id: "G6-MA-63", grade: 6, subject: "Math", topic: "Exponents", question: "In 5³, the number 5 is the ___.", choices: ["Exponent", "Base", "Power", "Coefficient"], answer: 1 },
    { id: "G6-MA-64", grade: 6, subject: "Math", topic: "Algebra", question: "An expression has no ___.", choices: ["Numbers", "Variables", "Equal sign", "Operations"], answer: 2 },
    { id: "G6-MA-65", grade: 6, subject: "Math", topic: "Inequalities", question: "If x < 5, which could be x?", choices: ["5", "6", "4", "10"], answer: 2 },
    { id: "G6-MA-66", grade: 6, subject: "Math", topic: "Equations", question: "Solve: z / 2 = 10", choices: ["5", "12", "20", "100"], answer: 2 },
    { id: "G6-MA-67", grade: 6, subject: "Math", topic: "Algebra", question: "Which is a constant in 3x + 7?", choices: ["3", "x", "7", "3x"], answer: 2 },
    { id: "G6-MA-68", grade: 6, subject: "Math", topic: "Order of Ops", question: "Solve: (2+3)²", choices: ["10", "25", "13", "7"], answer: 1 },
    { id: "G6-MA-69", grade: 6, subject: "Math", topic: "Algebra", question: "Term for 'twice a number'?", choices: ["n + 2", "n - 2", "2n", "n^2"], answer: 2 },
    { id: "G6-MA-70", grade: 6, subject: "Math", topic: "Equations", question: "Solve: 10 + m = 10", choices: ["0", "1", "10", "20"], answer: 0 },
    { id: "G6-MA-71", grade: 6, subject: "Math", topic: "Algebra", question: "Like terms have the same ___.", choices: ["Numbers", "Variables", "Coefficients", "Signs"], answer: 1 },
    { id: "G6-MA-72", grade: 6, subject: "Math", topic: "Inequalities", question: "Graph of x > 2 has an ___ circle.", choices: ["Open", "Closed", "Empty", "Solid"], answer: 0 },
    { id: "G6-MA-73", grade: 6, subject: "Math", topic: "Exponents", question: "Value of 7⁰?", choices: ["0", "7", "1", "70"], answer: 2 },
    { id: "G6-MA-74", grade: 6, subject: "Math", topic: "Algebra", question: "Property used in 3(x+y) = 3x+3y?", choices: ["Commutative", "Associative", "Distributive", "Identity"], answer: 2 },
    { id: "G6-MA-75", grade: 6, subject: "Math", topic: "Algebra", question: "Sum of a and b is written as:", choices: ["ab", "a-b", "a/b", "a+b"], answer: 3 },

    // --- TOPIC 4: GEOMETRY & STATISTICS (25 Questions) ---
    { id: "G6-MA-76", grade: 6, subject: "Math", topic: "Geometry", question: "Area of a triangle formula?", choices: ["bh", "1/2 bh", "lw", "2b+2h"], answer: 1 },
    { id: "G6-MA-77", grade: 6, subject: "Math", topic: "Statistics", question: "The average of a data set is the ___.", choices: ["Mode", "Median", "Mean", "Range"], answer: 2 },
    { id: "G6-MA-78", grade: 6, subject: "Math", topic: "Geometry", question: "Area of a rectangle with length 5 and width 4?", choices: ["9", "20", "18", "1"], answer: 1 },
    { id: "G6-MA-79", grade: 6, subject: "Math", topic: "Statistics", question: "The middle number in an ordered list is the ___.", choices: ["Mean", "Median", "Mode", "Range"], answer: 1 },
    { id: "G6-MA-80", grade: 6, subject: "Math", topic: "Geometry", question: "How many faces on a cube?", choices: ["4", "6", "8", "12"], answer: 1 },
    { id: "G6-MA-81", grade: 6, subject: "Math", topic: "Statistics", question: "The most frequent number in a set is the ___.", choices: ["Mean", "Median", "Mode", "Range"], answer: 2 },
    { id: "G6-MA-82", grade: 6, subject: "Math", topic: "Geometry", question: "Volume of a prism formula?", choices: ["Bh", "1/2 Bh", "lw", "s^2"], answer: 0 },
    { id: "G6-MA-83", grade: 6, subject: "Math", topic: "Statistics", question: "Difference between highest and lowest values is ___.", choices: ["Mean", "Median", "Mode", "Range"], answer: 3 },
    { id: "G6-MA-84", grade: 6, subject: "Math", topic: "Geometry", question: "A 2D pattern that folds into a 3D shape is a ___.", choices: ["Grid", "Net", "Map", "Plot"], answer: 1 },
    { id: "G6-MA-85", grade: 6, subject: "Math", topic: "Statistics", question: "What is the median of 1, 3, 5?", choices: ["1", "3", "5", "9"], answer: 1 },
    { id: "G6-MA-86", grade: 6, subject: "Math", topic: "Geometry", question: "Area of a parallelogram with base 10 and height 4?", choices: ["14", "40", "20", "28"], answer: 1 },
    { id: "G6-MA-87", grade: 6, subject: "Math", topic: "Statistics", question: "A dot plot shows the ___ of data.", choices: ["Volume", "Frequency", "Shape", "Size"], answer: 1 },
    { id: "G6-MA-88", grade: 6, subject: "Math", topic: "Geometry", question: "Total area of all surfaces of a 3D shape is ___.", choices: ["Volume", "Surface Area", "Perimeter", "Capacity"], answer: 1 },
    { id: "G6-MA-89", grade: 6, subject: "Math", topic: "Statistics", question: "A data point far from others is an ___.", choices: ["Inlier", "Outlier", "Average", "Error"], answer: 1 },
    { id: "G6-MA-90", grade: 6, subject: "Math", topic: "Geometry", question: "Distance around a circle is ___.", choices: ["Diameter", "Radius", "Circumference", "Area"], answer: 2 },
    { id: "G6-MA-91", grade: 6, subject: "Math", topic: "Statistics", question: "Sum of 2, 4, 6 divided by 3 is the ___.", choices: ["Mean", "Median", "Mode", "Range"], answer: 0 },
    { id: "G6-MA-92", grade: 6, subject: "Math", topic: "Geometry", question: "Polygon with 6 sides is a ___.", choices: ["Pentagon", "Hexagon", "Octagon", "Heptagon"], answer: 1 },
    { id: "G6-MA-93", grade: 6, subject: "Math", topic: "Statistics", question: "A histogram displays ___ data.", choices: ["Categorical", "Numerical", "Single", "Random"], answer: 1 },
    { id: "G6-MA-94", grade: 6, subject: "Math", topic: "Geometry", question: "Point where two sides meet is a ___.", choices: ["Edge", "Vertex", "Face", "Line"], answer: 1 },
    { id: "G6-MA-95", grade: 6, subject: "Math", topic: "Statistics", question: "Mode of 2, 2, 3, 4, 5?", choices: ["2", "3", "4", "5"], answer: 0 },
    { id: "G6-MA-96", grade: 6, subject: "Math", topic: "Geometry", question: "Complementary angles sum to ___.", choices: ["45°", "90°", "180°", "360°"], answer: 1 },
    { id: "G6-MA-97", grade: 6, subject: "Math", topic: "Statistics", question: "A box plot shows the ___ of a data set.", choices: ["Mean", "Five-number summary", "Mode", "Total"], answer: 1 },
    { id: "G6-MA-98", grade: 6, subject: "Math", topic: "Geometry", question: "Vertical angles are always ___.", choices: ["90°", "Supplementary", "Equal", "Acute"], answer: 2 },
    { id: "G6-MA-99", grade: 6, subject: "Math", topic: "Statistics", question: "Range of 10, 20, 30?", choices: ["10", "20", "30", "60"], answer: 1 },
    { id: "G6-MA-100", grade: 6, subject: "Math", topic: "Geometry", question: "Volume of a cube with side 3?", choices: ["9", "12", "27", "81"], answer: 2 }
];

module.exports = G6_MATH_COMPLETE;
