const G6_SCIENCE_COMPLETE = [
    // --- TOPIC 1: EARTH'S LAYERS & PLATE TECTONICS (25 Questions) ---
    { id: "G6-SCI-01", grade: 6, subject: "Science", topic: "Earth Layers", question: "Which layer is a dense ball of solid metal?", choices: ["Crust", "Mantle", "Outer Core", "Inner Core"], answer: 3 },
    { id: "G6-SCI-02", grade: 6, subject: "Science", topic: "Plates", question: "Where is the crust the thinnest?", choices: ["Mountains", "Ocean Floor", "Deserts", "Continents"], answer: 1 },
    { id: "G6-SCI-03", grade: 6, subject: "Science", topic: "Plates", question: "Tectonic plates 'float' on the ___.", choices: ["Inner Core", "Asthenosphere", "Atmosphere", "Hydrosphere"], answer: 1 },
    { id: "G6-SCI-04", grade: 6, subject: "Science", topic: "Earth Layers", question: "The mantle is primarily made of ___.", choices: ["Liquid Iron", "Hot Solid Rock", "Gas", "Ice"], answer: 1 },
    { id: "G6-SCI-05", grade: 6, subject: "Science", topic: "Plates", question: "A convergent boundary is where plates ___.", choices: ["Move apart", "Slide past", "Collide", "Stop"], answer: 2 },
    { id: "G6-SCI-06", grade: 6, subject: "Science", topic: "Plates", question: "Sea-floor spreading occurs at ___.", choices: ["Trenches", "Mid-ocean ridges", "Transform faults", "Mountains"], answer: 1 },
    { id: "G6-SCI-07", grade: 6, subject: "Science", topic: "Plates", question: "The San Andreas Fault is which type of boundary?", choices: ["Convergent", "Divergent", "Transform", "Subduction"], answer: 2 },
    { id: "G6-SCI-08", grade: 6, subject: "Science", topic: "Plates", question: "What is the name of the ancient supercontinent?", choices: ["Pangea", "Atlantis", "Gondwana", "Laurasia"], answer: 0 },
    { id: "G6-SCI-09", grade: 6, subject: "Science", topic: "Plates", question: "What drives the movement of tectonic plates?", choices: ["Ocean currents", "Wind", "Convection currents", "Magnetism"], answer: 2 },
    { id: "G6-SCI-10", grade: 6, subject: "Science", topic: "Plates", question: "Subduction occurs when one plate ___.", choices: ["Rises up", "Slides past", "Sinks under another", "Melts into air"], answer: 2 },
    { id: "G6-SCI-11", grade: 6, subject: "Science", topic: "Earth Layers", question: "Which layer is liquid?", choices: ["Inner Core", "Outer Core", "Crust", "Mantle"], answer: 1 },
    { id: "G6-SCI-12", grade: 6, subject: "Science", topic: "Plates", question: "The Himalayan Mountains formed at a ___ boundary.", choices: ["Convergent", "Divergent", "Transform", "Volcanic"], answer: 0 },
    { id: "G6-SCI-13", grade: 6, subject: "Science", topic: "Plates", question: "Deep-ocean trenches are signs of ___.", choices: ["Rifting", "Subduction", "Transforming", "Folding"], answer: 1 },
    { id: "G6-SCI-14", grade: 6, subject: "Science", topic: "Earth Layers", question: "The lithosphere includes the crust and ___.", choices: ["Entire mantle", "Upper mantle", "Outer core", "Inner core"], answer: 1 },
    { id: "G6-SCI-15", grade: 6, subject: "Science", topic: "Earth Layers", question: "Which layer is the thickest?", choices: ["Crust", "Mantle", "Outer Core", "Inner Core"], answer: 1 },
    { id: "G6-SCI-16", grade: 6, subject: "Science", topic: "Plates", question: "Rift valleys form at ___ boundaries.", choices: ["Convergent", "Divergent", "Transform", "Passive"], answer: 1 },
    { id: "G6-SCI-17", grade: 6, subject: "Science", topic: "Plates", question: "The theory of continental drift was proposed by ___.", choices: ["Newton", "Darwin", "Wegener", "Einstein"], answer: 2 },
    { id: "G6-SCI-18", grade: 6, subject: "Science", topic: "Plates", question: "Where is new crust created?", choices: ["Trenches", "Mid-ocean ridges", "Fault lines", "Volcanoes"], answer: 1 },
    { id: "G6-SCI-19", grade: 6, subject: "Science", topic: "Plates", question: "Oceanic crust is mostly made of ___.", choices: ["Granite", "Basalt", "Sandstone", "Marble"], answer: 1 },
    { id: "G6-SCI-20", grade: 6, subject: "Science", topic: "Plates", question: "Continental crust is mostly made of ___.", choices: ["Basalt", "Granite", "Obsidian", "Coal"], answer: 1 },
    { id: "G6-SCI-21", grade: 6, subject: "Science", topic: "Plates", question: "What instrument measures earthquakes?", choices: ["Barometer", "Seismograph", "Thermometer", "Hygrometer"], answer: 1 },
    { id: "G6-SCI-22", grade: 6, subject: "Science", topic: "Plates", question: "The point where an earthquake starts underground is the ___.", choices: ["Epicenter", "Focus", "Fault", "Core"], answer: 1 },
    { id: "G6-SCI-23", grade: 6, subject: "Science", topic: "Plates", question: "The point on the surface above the focus is the ___.", choices: ["Epicenter", "Apex", "Peak", "Crust"], answer: 0 },
    { id: "G6-SCI-24", grade: 6, subject: "Science", topic: "Plates", question: "Magma that reaches the surface is called ___.", choices: ["Lava", "Ash", "Sediment", "Basalt"], answer: 0 },
    { id: "G6-SCI-25", grade: 6, subject: "Science", topic: "Plates", question: "The 'Ring of Fire' is located around which ocean?", choices: ["Atlantic", "Indian", "Arctic", "Pacific"], answer: 3 },

    // --- TOPIC 2: WEATHERING, EROSION, & ROCKS (25 Questions) ---
    { id: "G6-SCI-26", grade: 6, subject: "Science", topic: "Rocks", question: "Rocks formed from cooling lava are ___.", choices: ["Sedimentary", "Metamorphic", "Igneous", "Sand"], answer: 2 },
    { id: "G6-SCI-27", grade: 6, subject: "Science", topic: "Earth Processes", question: "Breaking rocks into smaller pieces is ___.", choices: ["Erosion", "Weathering", "Deposition", "Melting"], answer: 1 },
    { id: "G6-SCI-28", grade: 6, subject: "Science", topic: "Rocks", question: "Which rock type often contains fossils?", choices: ["Igneous", "Sedimentary", "Metamorphic", "Magma"], answer: 1 },
    { id: "G6-SCI-29", grade: 6, subject: "Science", topic: "Earth Processes", question: "Carrying away rock fragments by wind/water is ___.", choices: ["Weathering", "Erosion", "Magma", "Pressure"], answer: 1 },
    { id: "G6-SCI-30", grade: 6, subject: "Science", topic: "Rocks", question: "Metamorphic rocks are formed by heat and ___.", choices: ["Water", "Pressure", "Ice", "Wind"], answer: 1 },
    { id: "G6-SCI-31", grade: 6, subject: "Science", topic: "Earth Processes", question: "Dropping of sediment in a new location is ___.", choices: ["Erosion", "Deposition", "Weathering", "Melting"], answer: 1 },
    { id: "G6-SCI-32", grade: 6, subject: "Science", topic: "Rocks", question: "Molten rock inside the Earth is ___.", choices: ["Lava", "Magma", "Sediment", "Crystals"], answer: 1 },
    { id: "G6-SCI-33", grade: 6, subject: "Science", topic: "Earth Processes", question: "Acid rain breaking down limestone is ___ weathering.", choices: ["Physical", "Chemical", "Mechanical", "Biological"], answer: 1 },
    { id: "G6-SCI-34", grade: 6, subject: "Science", topic: "Rocks", question: "Example of a sedimentary rock?", choices: ["Obsidian", "Limestone", "Marble", "Pumice"], answer: 1 },
    { id: "G6-SCI-35", grade: 6, subject: "Science", topic: "Rocks", question: "Example of a metamorphic rock?", choices: ["Shale", "Sandstone", "Slate", "Granite"], answer: 2 },
    { id: "G6-SCI-36", grade: 6, subject: "Science", topic: "Earth Processes", question: "Ice wedging is a form of ___ weathering.", choices: ["Chemical", "Mechanical", "Subduction", "Atmospheric"], answer: 1 },
    { id: "G6-SCI-37", grade: 6, subject: "Science", topic: "Rocks", question: "Small pieces of rock, sand, and silt are ___.", choices: ["Sediment", "Lava", "Granite", "Metals"], answer: 0 },
    { id: "G6-SCI-38", grade: 6, subject: "Science", topic: "Earth Processes", question: "A delta at the mouth of a river is formed by ___.", choices: ["Erosion", "Deposition", "Weathering", "Heat"], answer: 1 },
    { id: "G6-SCI-39", grade: 6, subject: "Science", topic: "Rocks", question: "Intrusive igneous rocks cool ___.", choices: ["On the surface", "Inside the Earth", "In water", "Instantly"], answer: 1 },
    { id: "G6-SCI-40", grade: 6, subject: "Science", topic: "Rocks", question: "Extrusive igneous rocks have ___ crystals.", choices: ["Large", "Small/None", "Jagged", "Square"], answer: 1 },
    { id: "G6-SCI-41", grade: 6, subject: "Science", topic: "Earth Processes", question: "Which is a cause of erosion?", choices: ["Wind", "Gravity", "Glaciers", "All of these"], answer: 3 },
    { id: "G6-SCI-42", grade: 6, subject: "Science", topic: "Rocks", question: "The process of rocks changing types is the ___.", choices: ["Rock Cycle", "Water Cycle", "Life Cycle", "Plate Cycle"], answer: 0 },
    { id: "G6-SCI-43", grade: 6, subject: "Science", topic: "Rocks", question: "Rock made from cooled magma is ___.", choices: ["Intrusive", "Extrusive", "Sedimentary", "Organic"], answer: 0 },
    { id: "G6-SCI-44", grade: 6, subject: "Science", topic: "Earth Processes", question: "Rusting is an example of ___ weathering.", choices: ["Mechanical", "Chemical", "Physical", "Cold"], answer: 1 },
    { id: "G6-SCI-45", grade: 6, subject: "Science", topic: "Rocks", question: "Hardening of sediment into rock is ___.", choices: ["Erosion", "Lithification", "Weathering", "Melting"], answer: 1 },
    { id: "G6-SCI-46", grade: 6, subject: "Science", topic: "Rocks", question: "Rock that forms from organic remains is ___.", choices: ["Coal", "Basalt", "Slate", "Quartz"], answer: 0 },
    { id: "G6-SCI-47", grade: 6, subject: "Science", topic: "Earth Processes", question: "U-shaped valleys are created by ___.", choices: ["Rivers", "Wind", "Glaciers", "Earthquakes"], answer: 2 },
    { id: "G6-SCI-48", grade: 6, subject: "Science", topic: "Rocks", question: "Gneiss is a ___ rock.", choices: ["Igneous", "Metamorphic", "Sedimentary", "Liquid"], answer: 1 },
    { id: "G6-SCI-49", grade: 6, subject: "Science", topic: "Earth Processes", question: "The primary force behind mass wasting (landslides) is ___.", choices: ["Magnetism", "Gravity", "Sunlight", "Wind"], answer: 1 },
    { id: "G6-SCI-50", grade: 6, subject: "Science", topic: "Rocks", question: "Pumice is unique because it can ___.", choices: ["Burn", "Float", "Melt", "Conduct electricity"], answer: 1 },

    // --- TOPIC 3: CELL BIOLOGY (25 Questions) ---
    { id: "G6-SCI-51", grade: 6, subject: "Science", topic: "Cells", question: "The 'brain' or control center of the cell is the ___.", choices: ["Mitochondria", "Nucleus", "Vacuole", "Wall"], answer: 1 },
    { id: "G6-SCI-52", grade: 6, subject: "Science", topic: "Cells", question: "Powerhouse of the cell that creates energy?", choices: ["Ribosome", "Chloroplast", "Mitochondria", "Nucleus"], answer: 2 },
    { id: "G6-SCI-53", grade: 6, subject: "Science", topic: "Cells", question: "What do plant cells have that animal cells do NOT?", choices: ["Nucleus", "Cell Wall", "Cytoplasm", "Ribosome"], answer: 1 },
    { id: "G6-SCI-54", grade: 6, subject: "Science", topic: "Cells", question: "Jelly-like substance inside the cell is ___.", choices: ["DNA", "Cytoplasm", "Sap", "Lava"], answer: 1 },
    { id: "G6-SCI-55", grade: 6, subject: "Science", topic: "Cells", question: "Which organelle makes proteins?", choices: ["Vacuole", "Ribosome", "Lysosome", "Golgi"], answer: 1 },
    { id: "G6-SCI-56", grade: 6, subject: "Science", topic: "Cells", question: "Chloroplasts are used for ___.", choices: ["Digestion", "Photosynthesis", "Breathing", "Movement"], answer: 1 },
    { id: "G6-SCI-57", grade: 6, subject: "Science", topic: "Cells", question: "The thin outer layer of an animal cell is the ___.", choices: ["Cell Wall", "Cell Membrane", "Nuclear Envelope", "Shell"], answer: 1 },
    { id: "G6-SCI-58", grade: 6, subject: "Science", topic: "Cells", question: "Large storage area for water in plant cells?", choices: ["Nucleus", "Central Vacuole", "Mitochondria", "Ribosome"], answer: 1 },
    { id: "G6-SCI-59", grade: 6, subject: "Science", topic: "Cells", question: "Which organelle removes waste?", choices: ["Lysosome", "Chloroplast", "Nucleolus", "Wall"], answer: 0 },
    { id: "G6-SCI-60", grade: 6, subject: "Science", topic: "Cells", question: "Who first discovered cells under a microscope?", choices: ["Newton", "Hooke", "Darwin", "Pasteur"], answer: 1 },
    { id: "G6-SCI-61", grade: 6, subject: "Science", topic: "Cells", question: "Smallest unit of life is the ___.", choices: ["Atom", "Cell", "Tissue", "Organ"], answer: 1 },
    { id: "G6-SCI-62", grade: 6, subject: "Science", topic: "Cells", question: "DNA is found inside the ___.", choices: ["Mitochondria", "Nucleus", "Ribosome", "Membrane"], answer: 1 },
    { id: "G6-SCI-63", grade: 6, subject: "Science", topic: "Cells", question: "Groups of similar cells working together form ___.", choices: ["Organs", "Tissues", "Systems", "Organisms"], answer: 1 },
    { id: "G6-SCI-64", grade: 6, subject: "Science", topic: "Cells", question: "Which organelle packages and ships proteins?", choices: ["Ribosome", "Golgi Apparatus", "Vacuole", "Cell Wall"], answer: 1 },
    { id: "G6-SCI-65", grade: 6, subject: "Science", topic: "Cells", question: "Green pigment in chloroplasts is ___.", choices: ["Hemoglobin", "Chlorophyll", "Melanin", "Cytoplasm"], answer: 1 },
    { id: "G6-SCI-66", grade: 6, subject: "Science", topic: "Cells", question: "Cells without a nucleus are called ___.", choices: ["Eukaryotic", "Prokaryotic", "Multicellular", "Complex"], answer: 1 },
    { id: "G6-SCI-67", grade: 6, subject: "Science", topic: "Cells", question: "Human cells are ___ cells.", choices: ["Prokaryotic", "Eukaryotic", "Bacterial", "Plant"], answer: 1 },
    { id: "G6-SCI-68", grade: 6, subject: "Science", topic: "Cells", question: "Rough ER has ___ attached to it.", choices: ["Vacuoles", "Ribosomes", "Nuclei", "Lysosomes"], answer: 1 },
    { id: "G6-SCI-69", grade: 6, subject: "Science", topic: "Cells", question: "The 'gatekeeper' of the cell is the ___.", choices: ["Nucleus", "Cell Membrane", "Mitochondria", "Wall"], answer: 1 },
    { id: "G6-SCI-70", grade: 6, subject: "Science", topic: "Cells", question: "Multicellular means an organism has ___.", choices: ["One cell", "No cells", "Many cells", "Square cells"], answer: 2 },
    { id: "G6-SCI-71", grade: 6, subject: "Science", topic: "Cells", question: "Photosynthesis happens in the ___.", choices: ["Mitochondria", "Nucleus", "Chloroplast", "Ribosome"], answer: 2 },
    { id: "G6-SCI-72", grade: 6, subject: "Science", topic: "Cells", question: "What gives plant cells their rigid shape?", choices: ["Membrane", "Cell Wall", "Nucleus", "Cytoplasm"], answer: 1 },
    { id: "G6-SCI-73", grade: 6, subject: "Science", topic: "Cells", question: "A microscope is needed to see cells because they are ___.", choices: ["Invisible", "Microscopic", "Macroscopic", "Dark"], answer: 1 },
    { id: "G6-SCI-74", grade: 6, subject: "Science", topic: "Cells", question: "Cell theory states all cells come from ___.", choices: ["Water", "Existing cells", "Rocks", "Air"], answer: 1 },
    { id: "G6-SCI-75", grade: 6, subject: "Science", topic: "Cells", question: "The liquid part of the cytoplasm is the ___.", choices: ["Organelle", "Cytosol", "Nucleoplasm", "Plasma"], answer: 1 },

    // --- TOPIC 4: HUMAN BODY SYSTEMS (25 Questions) ---
    { id: "G6-SCI-76", grade: 6, subject: "Science", topic: "Body", question: "System that pumps blood through the body?", choices: ["Respiratory", "Circulatory", "Digestive", "Nervous"], answer: 1 },
    { id: "G6-SCI-77", grade: 6, subject: "Science", topic: "Body", question: "System used for breathing/oxygen exchange?", choices: ["Circulatory", "Respiratory", "Endocrine", "Skeletal"], answer: 1 },
    { id: "G6-SCI-78", grade: 6, subject: "Science", topic: "Body", question: "Which system breaks down food for energy?", choices: ["Excretory", "Digestive", "Muscular", "Nervous"], answer: 1 },
    { id: "G6-SCI-79", grade: 6, subject: "Science", topic: "Body", question: "System that controls the body using electrical signals?", choices: ["Nervous", "Immune", "Skeletal", "Digestive"], answer: 0 },
    { id: "G6-SCI-80", grade: 6, subject: "Science", topic: "Body", question: "The main organ of the circulatory system is the ___.", choices: ["Lungs", "Brain", "Heart", "Stomach"], answer: 2 },
    { id: "G6-SCI-81", grade: 6, subject: "Science", topic: "Body", question: "Which system provides the body's framework?", choices: ["Muscular", "Skeletal", "Nervous", "Integumentary"], answer: 1 },
    { id: "G6-SCI-82", grade: 6, subject: "Science", topic: "Body", question: "The lungs are part of the ___ system.", choices: ["Circulatory", "Respiratory", "Digestive", "Excretory"], answer: 1 },
    { id: "G6-SCI-83", grade: 6, subject: "Science", topic: "Body", question: "The brain and spinal cord are part of the ___.", choices: ["Peripheral NS", "Central Nervous System", "Skeletal System", "Muscular System"], answer: 1 },
    { id: "G6-SCI-84", grade: 6, subject: "Science", topic: "Body", question: "Where does most nutrient absorption happen?", choices: ["Stomach", "Small Intestine", "Large Intestine", "Esophagus"], answer: 1 },
    { id: "G6-SCI-85", grade: 6, subject: "Science", topic: "Body", question: "Which system removes liquid waste from the body?", choices: ["Digestive", "Excretory/Urinary", "Respiratory", "Integumentary"], answer: 1 },
    { id: "G6-SCI-86", grade: 6, subject: "Science", topic: "Body", question: "Blood vessels that carry blood AWAY from the heart?", choices: ["Veins", "Arteries", "Capillaries", "Vents"], answer: 1 },
    { id: "G6-SCI-87", grade: 6, subject: "Science", topic: "Body", question: "The 'skin' is the main organ of which system?", choices: ["Muscular", "Integumentary", "Endocrine", "Immune"], answer: 1 },
    { id: "G6-SCI-88", grade: 6, subject: "Science", topic: "Body", question: "System that allows for movement?", choices: ["Skeletal", "Muscular", "Nervous", "Respiratory"], answer: 1 },
    { id: "G6-SCI-89", grade: 6, subject: "Science", topic: "Body", question: "Tiny air sacs in the lungs are called ___.", choices: ["Villi", "Alveoli", "Bronchi", "Arteries"], answer: 1 },
    { id: "G6-SCI-90", grade: 6, subject: "Science", topic: "Body", question: "What carries oxygen in the blood?", choices: ["White blood cells", "Red blood cells", "Platelets", "Plasma"], answer: 1 },
    { id: "G6-SCI-91", grade: 6, subject: "Science", topic: "Body", question: "System that fights off germs and disease?", choices: ["Nervous", "Immune", "Digestive", "Skeletal"], answer: 1 },
    { id: "G6-SCI-92", grade: 6, subject: "Science", topic: "Body", question: "Which organ produces insulin?", choices: ["Liver", "Pancreas", "Kidney", "Heart"], answer: 1 },
    { id: "G6-SCI-93", grade: 6, subject: "Science", topic: "Body", question: "The windpipe is scientifically known as the ___.", choices: ["Esophagus", "Trachea", "Larynx", "Bronchi"], answer: 1 },
    { id: "G6-SCI-94", grade: 6, subject: "Science", topic: "Body", question: "Which system uses hormones to regulate the body?", choices: ["Nervous", "Endocrine", "Circulatory", "Excretory"], answer: 1 },
    { id: "G6-SCI-95", grade: 6, subject: "Science", topic: "Body", question: "Major organ that filters blood to create urine?", choices: ["Bladder", "Kidney", "Stomach", "Lung"], answer: 1 },
    { id: "G6-SCI-96", grade: 6, subject: "Science", topic: "Body", question: "The tube connecting the mouth to the stomach?", choices: ["Trachea", "Esophagus", "Intestine", "Vein"], answer: 1 },
    { id: "G6-SCI-97", grade: 6, subject: "Science", topic: "Body", question: "Where are blood cells made?", choices: ["Heart", "Bone Marrow", "Brain", "Muscles"], answer: 1 },
    { id: "G6-SCI-98", grade: 6, subject: "Science", topic: "Body", question: "What part of the brain controls balance?", choices: ["Cerebrum", "Cerebellum", "Brainstem", "Skull"], answer: 1 },
    { id: "G6-SCI-99", grade: 6, subject: "Science", topic: "Body", question: "Muscles you can control are called ___.", choices: ["Involuntary", "Voluntary", "Cardiac", "Smooth"], answer: 1 },
    { id: "G6-SCI-100", grade: 6, subject: "Science", topic: "Body", question: "The largest organ of the human body is the ___.", choices: ["Liver", "Heart", "Skin", "Brain"], answer: 2 }
];

module.exports = G6_SCIENCE_COMPLETE;
