const G6_SOCIAL_STUDIES_COMPLETE = [
    // --- TOPIC 1: MESOPOTAMIA (25 Questions) ---
    { id: "G6-SS-01", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "Mesopotamia means the land 'between the ___'.", choices: ["Mountains", "Rivers", "Deserts", "Oceans"], answer: 1 },
    { id: "G6-SS-02", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "The two main rivers of Mesopotamia are the Tigris and ___.", choices: ["Nile", "Euphrates", "Indus", "Yellow"], answer: 1 },
    { id: "G6-SS-03", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "The world's first writing system, created by Sumerians, was ___.", choices: ["Hieroglyphics", "Cuneiform", "Alphabet", "Sanskrit"], answer: 1 },
    { id: "G6-SS-04", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "A tiered, pyramid-shaped temple in Mesopotamia was a ___.", choices: ["Pyramid", "Ziggurat", "Cathedral", "Obelisk"], answer: 1 },
    { id: "G6-SS-05", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "Who wrote the first set of 282 laws?", choices: ["Sargon", "Hammurabi", "Nebuchadnezzar", "Gilgamesh"], answer: 1 },
    { id: "G6-SS-06", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "The 'Fertile Crescent' is named for its ___.", choices: ["Shape and soil", "Moon worship", "Gold mines", "Rivers"], answer: 0 },
    { id: "G6-SS-07", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "Supplying land with water through ditches/pipes is ___.", choices: ["Flooding", "Irrigation", "Silt", "Farming"], answer: 1 },
    { id: "G6-SS-08", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "Fine particles of fertile soil left by floods is ___.", choices: ["Sand", "Silt", "Clay", "Gravel"], answer: 1 },
    { id: "G6-SS-09", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "A city that governs itself and its surrounding territory is a ___.", choices: ["Empire", "City-state", "Village", "Kingdom"], answer: 1 },
    { id: "G6-SS-10", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "Sumerians practiced polytheism, which is the worship of ___.", choices: ["One god", "Many gods", "Nature only", "No gods"], answer: 1 },
    { id: "G6-SS-11", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "Professional writers in ancient times were called ___.", choices: ["Scribes", "Priests", "Kings", "Artisans"], answer: 0 },
    { id: "G6-SS-12", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "The wheel and the plow were invented by the ___.", choices: ["Egyptians", "Sumerians", "Persians", "Romans"], answer: 1 },
    { id: "G6-SS-13", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "The first empire-builder in Mesopotamia was ___.", choices: ["Hammurabi", "Sargon", "Cyrus", "Alexander"], answer: 1 },
    { id: "G6-SS-14", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "Hanging Gardens of Babylon were built by ___.", choices: ["Hammurabi", "Nebuchadnezzar II", "Sargon II", "Tut"], answer: 1 },
    { id: "G6-SS-15", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "Mesopotamian writing was done on ___.", choices: ["Paper", "Clay tablets", "Stone walls", "Wood"], answer: 1 },
    { id: "G6-SS-16", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "Which civilization was known for being fierce warriors?", choices: ["Sumerians", "Assyrians", "Phoenicians", "Hittites"], answer: 1 },
    { id: "G6-SS-17", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "An epic poem about a legendary Sumerian king is ___.", choices: ["The Odyssey", "Gilgamesh", "The Iliad", "Beowulf"], answer: 1 },
    { id: "G6-SS-18", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "The Phoenicians were famous for their ___.", choices: ["Pyramids", "Alphabet and purple dye", "Iron weapons", "Great Wall"], answer: 1 },
    { id: "G6-SS-19", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "Mesopotamian society was organized by ___.", choices: ["Equality", "Social Hierarchy", "Random choice", "Wealth only"], answer: 1 },
    { id: "G6-SS-20", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "Surplus means having ___.", choices: ["Not enough", "An extra supply", "No food", "Trade items"], answer: 1 },
    { id: "G6-SS-21", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "The system of trading goods without money is ___.", choices: ["Taxes", "Barter", "Currency", "Slavery"], answer: 1 },
    { id: "G6-SS-22", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "Which metal did the Hittites introduce for stronger weapons?", choices: ["Bronze", "Iron", "Gold", "Copper"], answer: 1 },
    { id: "G6-SS-23", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "Assyrians built the first world-class ___.", choices: ["Roads", "Library", "Temple", "Ship"], answer: 1 },
    { id: "G6-SS-24", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "Mesopotamian religion was primarily ___.", choices: ["Monotheistic", "Polytheistic", "Atheistic", "Christian"], answer: 1 },
    { id: "G6-SS-25", grade: 6, subject: "Social Studies", topic: "Mesopotamia", question: "Babylon was located near modern-day ___.", choices: ["Egypt", "Iraq", "Greece", "Turkey"], answer: 1 },

    // --- TOPIC 2: ANCIENT EGYPT (25 Questions) ---
    { id: "G6-SS-26", grade: 6, subject: "Social Studies", topic: "Egypt", question: "The Nile River flows in which direction?", choices: ["South", "North", "East", "West"], answer: 1 },
    { id: "G6-SS-27", grade: 6, subject: "Social Studies", topic: "Egypt", question: "The Egyptian writing system is called ___.", choices: ["Cuneiform", "Hieroglyphics", "Latin", "Sanskrit"], answer: 1 },
    { id: "G6-SS-28", grade: 6, subject: "Social Studies", topic: "Egypt", question: "The ruler of Ancient Egypt was called a ___.", choices: ["King", "Pharaoh", "Emperor", "Czar"], answer: 1 },
    { id: "G6-SS-29", grade: 6, subject: "Social Studies", topic: "Egypt", question: "The process used to preserve bodies for the afterlife is ___.", choices: ["Embalming", "Mummification", "Siltation", "Burial"], answer: 1 },
    { id: "G6-SS-30", grade: 6, subject: "Social Studies", topic: "Egypt", question: "What plant was used to make paper-like material?", choices: ["Cotton", "Papyrus", "Wheat", "Silk"], answer: 1 },
    { id: "G6-SS-31", grade: 6, subject: "Social Studies", topic: "Egypt", question: "The Great Pyramid was built for which Pharaoh?", choices: ["Khufu", "Tut", "Ramses", "Akhenaten"], answer: 0 },
    { id: "G6-SS-32", grade: 6, subject: "Social Studies", topic: "Egypt", question: "Who was the female pharaoh who wore a false beard?", choices: ["Cleopatra", "Hatshepsut", "Nefertiti", "Isis"], answer: 1 },
    { id: "G6-SS-33", grade: 6, subject: "Social Studies", topic: "Egypt", question: "The stone that helped decode hieroglyphics was the ___.", choices: ["Sun Stone", "Rosetta Stone", "Nile Stone", "Moon Stone"], answer: 1 },
    { id: "G6-SS-34", grade: 6, subject: "Social Studies", topic: "Egypt", question: "A fan-shaped area of fertile marshland at a river's mouth is a ___.", choices: ["Valley", "Delta", "Cataract", "Basin"], answer: 1 },
    { id: "G6-SS-35", grade: 6, subject: "Social Studies", topic: "Egypt", question: "The boy king whose tomb was found intact was ___.", choices: ["Ramses II", "Tutankhamun", "Seti I", "Thutmose III"], answer: 1 },
    { id: "G6-SS-36", grade: 6, subject: "Social Studies", topic: "Egypt", question: "What guarded the Great Pyramids at Giza?", choices: ["The Sphinx", "The Phoenix", "Anubis", "The Kraken"], answer: 0 },
    { id: "G6-SS-37", grade: 6, subject: "Social Studies", topic: "Egypt", question: "Egyptian sun god was named ___.", choices: ["Osiris", "Ra", "Anubis", "Horus"], answer: 1 },
    { id: "G6-SS-38", grade: 6, subject: "Social Studies", topic: "Egypt", question: "Upper Egypt was located in the ___.", choices: ["North", "South", "East", "West"], answer: 1 },
    { id: "G6-SS-39", grade: 6, subject: "Social Studies", topic: "Egypt", question: "Pharaohs were considered both kings and ___.", choices: ["Scribes", "Gods", "Farmers", "Merchants"], answer: 1 },
    { id: "G6-SS-40", grade: 6, subject: "Social Studies", topic: "Egypt", question: "Ancient Egypt was protected by natural barriers like ___.", choices: ["Oceans", "Deserts and Cataracts", "Forests", "Ice"], answer: 1 },
    { id: "G6-SS-41", grade: 6, subject: "Social Studies", topic: "Egypt", question: "Which sea does the Nile empty into?", choices: ["Red Sea", "Mediterranean Sea", "Dead Sea", "Caspian Sea"], answer: 1 },
    { id: "G6-SS-42", grade: 6, subject: "Social Studies", topic: "Egypt", question: "What was the purpose of the pyramids?", choices: ["Palaces", "Tombs", "Granaries", "Schools"], answer: 1 },
    { id: "G6-SS-43", grade: 6, subject: "Social Studies", topic: "Egypt", question: "The god of the underworld was ___.", choices: ["Ra", "Osiris", "Set", "Sobek"], answer: 1 },
    { id: "G6-SS-44", grade: 6, subject: "Social Studies", topic: "Egypt", question: "Ramses II was famous for his ___.", choices: ["Small size", "Military conquests and temples", "Poetry", "Defeat"], answer: 1 },
    { id: "G6-SS-45", grade: 6, subject: "Social Studies", topic: "Egypt", question: "During the New Kingdom, Egypt reached its ___.", choices: ["Smallest size", "Height of power/glory", "End", "Dark age"], answer: 1 },
    { id: "G6-SS-46", grade: 6, subject: "Social Studies", topic: "Egypt", question: "Canopic jars were used to store ___.", choices: ["Food", "Organs", "Jewelry", "Water"], answer: 1 },
    { id: "G6-SS-47", grade: 6, subject: "Social Studies", topic: "Egypt", question: "The Egyptian 365-day calendar was based on ___.", choices: ["Moon", "Sun/Stars", "Floods", "Harvest"], answer: 1 },
    { id: "G6-SS-48", grade: 6, subject: "Social Studies", topic: "Egypt", question: "The 'Valley of the Kings' replaced ___ as burial sites.", choices: ["Temples", "Pyramids", "Rivers", "Caves"], answer: 1 },
    { id: "G6-SS-49", grade: 6, subject: "Social Studies", topic: "Egypt", question: "Ancient Egypt's economy was based on ___.", choices: ["Fishing", "Agriculture and Trade", "Mining", "War"], answer: 1 },
    { id: "G6-SS-50", grade: 6, subject: "Social Studies", topic: "Egypt", question: "Akhenaten tried to change Egypt to ___ worship.", choices: ["Polytheistic", "Monotheistic", "Animal", "No"], answer: 1 },

    // --- TOPIC 3: ANCIENT GREECE (25 Questions) ---
    { id: "G6-SS-51", grade: 6, subject: "Social Studies", topic: "Greece", question: "Greece is a ___ (land surrounded by water on 3 sides).", choices: ["Island", "Peninsula", "Continent", "Delta"], answer: 1 },
    { id: "G6-SS-52", grade: 6, subject: "Social Studies", topic: "Greece", question: "A Greek city-state was called a ___.", choices: ["Acropolis", "Polis", "Agora", "Helot"], answer: 1 },
    { id: "G6-SS-53", grade: 6, subject: "Social Studies", topic: "Greece", question: "Which city-state is known as the birthplace of democracy?", choices: ["Sparta", "Athens", "Corinth", "Thebes"], answer: 1 },
    { id: "G6-SS-54", grade: 6, subject: "Social Studies", topic: "Greece", question: "Which city-state focused on military strength?", choices: ["Athens", "Sparta", "Olympia", "Delphi"], answer: 1 },
    { id: "G6-SS-55", grade: 6, subject: "Social Studies", topic: "Greece", question: "Government by the people is ___.", choices: ["Oligarchy", "Democracy", "Monarchy", "Tyranny"], answer: 1 },
    { id: "G6-SS-56", grade: 6, subject: "Social Studies", topic: "Greece", question: "A marketplace/meeting area in a Greek city was an ___.", choices: ["Acropolis", "Agora", "Parthenon", "Theater"], answer: 1 },
    { id: "G6-SS-57", grade: 6, subject: "Social Studies", topic: "Greece", question: "Greek storyteller famous for fables like 'The Tortoise and the Hare'?", choices: ["Homer", "Aesop", "Socrates", "Plato"], answer: 1 },
    { id: "G6-SS-58", grade: 6, subject: "Social Studies", topic: "Greece", question: "The author of the Iliad and the Odyssey was ___.", choices: ["Aristotle", "Homer", "Sophocles", "Pericles"], answer: 1 },
    { id: "G6-SS-59", grade: 6, subject: "Social Studies", topic: "Greece", question: "Who was the king of the Greek gods?", choices: ["Poseidon", "Zeus", "Hades", "Apollo"], answer: 1 },
    { id: "G6-SS-60", grade: 6, subject: "Social Studies", topic: "Greece", question: "The sporting event held every four years for Zeus?", choices: ["World Cup", "Olympics", "Marathon", "Super Bowl"], answer: 1 },
    { id: "G6-SS-61", grade: 6, subject: "Social Studies", topic: "Greece", question: "The high, fortified part of a city-state was the ___.", choices: ["Polis", "Acropolis", "Basin", "Mountain"], answer: 1 },
    { id: "G6-SS-62", grade: 6, subject: "Social Studies", topic: "Greece", question: "The war between Athens and Sparta was the ___ War.", choices: ["Persian", "Peloponnesian", "Trojan", "Punic"], answer: 1 },
    { id: "G6-SS-63", grade: 6, subject: "Social Studies", topic: "Greece", question: "A great leader during Athens' Golden Age was ___.", choices: ["Alexander", "Pericles", "Leonidas", "Solon"], answer: 1 },
    { id: "G6-SS-64", grade: 6, subject: "Social Studies", topic: "Greece", question: "Socrates, Plato, and Aristotle were Greek ___.", choices: ["Kings", "Philosophers", "Soldiers", "Traders"], answer: 1 },
    { id: "G6-SS-65", grade: 6, subject: "Social Studies", topic: "Greece", question: "Alexander the Great's empire spread ___ culture.", choices: ["Roman", "Hellenistic", "Persian", "Chinese"], answer: 1 },
    { id: "G6-SS-66", grade: 6, subject: "Social Studies", topic: "Greece", question: "300 Spartans famously fought at the Battle of ___.", choices: ["Marathon", "Thermopylae", "Salamis", "Plataea"], answer: 1 },
    { id: "G6-SS-67", grade: 6, subject: "Social Studies", topic: "Greece", question: "Greek theater featured two main types of plays: ___.", choices: ["Action/Sci-fi", "Comedy/Tragedy", "Opera/Musical", "History/Myth"], answer: 1 },
    { id: "G6-SS-68", grade: 6, subject: "Social Studies", topic: "Greece", question: "A person who can predict the future is an ___.", choices: ["Oracle", "Epic", "Scribe", "Artisan"], answer: 0 },
    { id: "G6-SS-69", grade: 6, subject: "Social Studies", topic: "Greece", question: "Government ruled by a small group of wealthy people?", choices: ["Democracy", "Oligarchy", "Monarchy", "Republic"], answer: 1 },
    { id: "G6-SS-70", grade: 6, subject: "Social Studies", topic: "Greece", question: "Where did the Greek gods live?", choices: ["Athens", "Mount Olympus", "The Underworld", "Delphi"], answer: 1 },
    { id: "G6-SS-71", grade: 6, subject: "Social Studies", topic: "Greece", question: "The first Greek civilization on the mainland was the ___.", choices: ["Minoans", "Mycenaeans", "Dorians", "Persians"], answer: 1 },
    { id: "G6-SS-72", grade: 6, subject: "Social Studies", topic: "Greece", question: "Direct democracy meant ___.", choices: ["Representatives voted", "All citizens voted directly", "Only kings voted", "Women voted"], answer: 1 },
    { id: "G6-SS-73", grade: 6, subject: "Social Studies", topic: "Greece", question: "The temple dedicated to Athena in Athens is the ___.", choices: ["Colosseum", "Parthenon", "Ziggurat", "Pyramid"], answer: 1 },
    { id: "G6-SS-74", grade: 6, subject: "Social Studies", topic: "Greece", question: "Greek columns included Doric, Ionic, and ___.", choices: ["Corinthian", "Spartan", "Athenian", "Roman"], answer: 0 },
    { id: "G6-SS-75", grade: 6, subject: "Social Studies", topic: "Greece", question: "Alexander the Great was from ___.", choices: ["Athens", "Macedonia", "Egypt", "Persia"], answer: 1 },

    // --- TOPIC 4: ANCIENT ROME (25 Questions) ---
    { id: "G6-SS-76", grade: 6, subject: "Social Studies", topic: "Rome", question: "The legend of Rome's founding involves Romulus and ___.", choices: ["Caesar", "Remus", "Augustus", "Nero"], answer: 1 },
    { id: "G6-SS-77", grade: 6, subject: "Social Studies", topic: "Rome", question: "A government where citizens elect leaders is a ___.", choices: ["Monarchy", "Republic", "Oligarchy", "Direct Democracy"], answer: 1 },
    { id: "G6-SS-78", grade: 6, subject: "Social Studies", topic: "Rome", question: "Wealthy landowners in Rome were called ___.", choices: ["Plebeians", "Patricians", "Consuls", "Tribunes"], answer: 1 },
    { id: "G6-SS-79", grade: 6, subject: "Social Studies", topic: "Rome", question: "Common people/farmers in Rome were called ___.", choices: ["Patricians", "Plebeians", "Gladiators", "Slaves"], answer: 1 },
    { id: "G6-SS-80", grade: 6, subject: "Social Studies", topic: "Rome", question: "Rome's first written code of laws was the ___.", choices: ["Hammurabi Code", "Twelve Tables", "Constitution", "Bill of Rights"], answer: 1 },
    { id: "G6-SS-81", grade: 6, subject: "Social Studies", topic: "Rome", question: "The wars between Rome and Carthage were the ___.", choices: ["Persian Wars", "Punic Wars", "Civil Wars", "Crusades"], answer: 1 },
    { id: "G6-SS-82", grade: 6, subject: "Social Studies", topic: "Rome", question: "The Carthaginian general who used elephants was ___.", choices: ["Scipio", "Hannibal", "Caesar", "Pompey"], answer: 1 },
    { id: "G6-SS-83", grade: 6, subject: "Social Studies", topic: "Rome", question: "Who became 'Dictator for Life' and was assassinated?", choices: ["Augustus", "Julius Caesar", "Mark Antony", "Brutus"], answer: 1 },
    { id: "G6-SS-84", grade: 6, subject: "Social Studies", topic: "Rome", question: "The first Emperor of Rome was ___.", choices: ["Julius Caesar", "Augustus", "Constantine", "Nero"], answer: 1 },
    { id: "G6-SS-85", grade: 6, subject: "Social Studies", topic: "Rome", question: "The 200-year period of Roman peace was the ___.", choices: ["Golden Age", "Pax Romana", "Renaissance", "Republic"], answer: 1 },
    { id: "G6-SS-86", grade: 6, subject: "Social Studies", topic: "Rome", question: "The large stadium used for gladiator fights was the ___.", choices: ["Parthenon", "Colosseum", "Circus Maximus", "Pantheon"], answer: 1 },
    { id: "G6-SS-87", grade: 6, subject: "Social Studies", topic: "Rome", question: "Roman engineering used to carry water into cities?", choices: ["Roads", "Aqueducts", "Bridges", "Sewers"], answer: 1 },
    { id: "G6-SS-88", grade: 6, subject: "Social Studies", topic: "Rome", question: "The language spoken in Ancient Rome was ___.", choices: ["Greek", "Latin", "English", "Italian"], answer: 1 },
    { id: "G6-SS-89", grade: 6, subject: "Social Studies", topic: "Rome", question: "Which structure was used for chariot races?", choices: ["Colosseum", "Circus Maximus", "Forum", "Appian Way"], answer: 1 },
    { id: "G6-SS-90", grade: 6, subject: "Social Studies", topic: "Rome", question: "What architectural feature did Romans perfect for strength?", choices: ["Columns", "Arches", "Towers", "Pyramids"], answer: 1 },
    { id: "G6-SS-91", grade: 6, subject: "Social Studies", topic: "Rome", question: "The group of 300 men who advised leaders in the Republic?", choices: ["The Assembly", "The Senate", "The Consuls", "The Tribunes"], answer: 1 },
    { id: "G6-SS-92", grade: 6, subject: "Social Studies", topic: "Rome", question: "The Roman 'Forum' was a central ___.", choices: ["Temple", "Marketplace/Public square", "Military camp", "Garden"], answer: 1 },
    { id: "G6-SS-93", grade: 6, subject: "Social Studies", topic: "Rome", question: "Who divided the Roman Empire into East and West?", choices: ["Augustus", "Diocletian", "Constantine", "Trajan"], answer: 1 },
    { id: "G6-SS-94", grade: 6, subject: "Social Studies", topic: "Rome", question: "The first Christian emperor was ___.", choices: ["Nero", "Constantine", "Hadrian", "Marcus Aurelius"], answer: 1 },
    { id: "G6-SS-95", grade: 6, subject: "Social Studies", topic: "Rome", question: "The Western Roman Empire fell in the year ___.", choices: ["44 BC", "476 AD", "1066 AD", "1492 AD"], answer: 1 },
    { id: "G6-SS-96", grade: 6, subject: "Social Studies", topic: "Rome", question: "The 'veto' power means 'I ___'.", choices: ["Agree", "Forbid", "Vote", "Lead"], answer: 1 },
    { id: "G6-SS-97", grade: 6, subject: "Social Studies", topic: "Rome", question: "Which group of 'barbarians' sacked Rome?", choices: ["Greeks", "Visigoths", "Persians", "Egyptians"], answer: 1 },
    { id: "G6-SS-98", grade: 6, subject: "Social Studies", topic: "Rome", question: "The Eastern Roman Empire became known as the ___.", choices: ["Byzantine Empire", "Holy Roman Empire", "Ottoman Empire", "Greek Empire"], answer: 0 },
    { id: "G6-SS-99", grade: 6, subject: "Social Studies", topic: "Rome", question: "Rome is located on which river?", choices: ["Nile", "Tiber", "Rhine", "Po"], answer: 1 },
    { id: "G6-SS-100", grade: 6, subject: "Social Studies", topic: "Rome", question: "Roman soldiers were organized into groups called ___.", choices: ["Phalanxes", "Legions", "Battalions", "Sectors"], answer: 1 }
];

module.exports = G6_SOCIAL_STUDIES_COMPLETE;
