const G7_MATH_COMPLETE = [
    // --- TOPIC 1: PROPORTIONAL RELATIONSHIPS (25 Questions) ---
    { id: "G7-MA-01", grade: 7, subject: "Math", topic: "Proportions", question: "A proportional relationship always passes through ___.", choices: ["(1,1)", "(0,0)", "(10,10)", "Any point"], answer: 1 },
    { id: "G7-MA-02", grade: 7, subject: "Math", topic: "Proportions", question: "The constant of proportionality is usually represented by ___.", choices: ["x", "y", "k", "p"], answer: 2 },
    { id: "G7-MA-03", grade: 7, subject: "Math", topic: "Proportions", question: "If y=5x, the constant of proportionality is ___.", choices: ["x", "y", "5", "0"], answer: 2 },
    { id: "G7-MA-04", grade: 7, subject: "Math", topic: "Proportions", question: "A scale drawing uses a ___ to relate lengths.", choices: ["Ruler", "Scale factor", "Protractor", "Compass"], answer: 1 },
    { id: "G7-MA-05", grade: 7, subject: "Math", topic: "Proportions", question: "10% of 200 is ___.", choices: ["10", "20", "2", "200"], answer: 1 },
    { id: "G7-MA-06", grade: 7, subject: "Math", topic: "Proportions", question: "Is the graph of a straight line through (0,0) proportional?", choices: ["Yes", "No"], answer: 0 },
    { id: "G7-MA-07", grade: 7, subject: "Math", topic: "Proportions", question: "If 2 shirts cost $20, how much for 5 shirts?", choices: ["$40", "$50", "$60", "$100"], answer: 1 },
    { id: "G7-MA-08", grade: 7, subject: "Math", topic: "Proportions", question: "Unit rate is the same as ___ in a proportional relationship.", choices: ["Slope", "Constant of Proportionality", "Intercept", "Variable"], answer: 1 },
    { id: "G7-MA-09", grade: 7, subject: "Math", topic: "Proportions", question: "A map scale is 1 in : 10 miles. 5 inches is ___ miles.", choices: ["5", "10", "50", "100"], answer: 2 },
    { id: "G7-MA-10", grade: 7, subject: "Math", topic: "Proportions", question: "Tax is ___ to the total price.", choices: ["Subtracted", "Added", "Divided", "Ignored"], answer: 1 },
    { id: "G7-MA-11", grade: 7, subject: "Math", topic: "Proportions", question: "A discount is ___ from the total price.", choices: ["Added", "Subtracted", "Multiplied", "Squared"], answer: 1 },
    { id: "G7-MA-12", grade: 7, subject: "Math", topic: "Proportions", question: "Formula for simple interest: I = ___.", choices: ["P+R+T", "PRT", "P/RT", "P-RT"], answer: 1 },
    { id: "G7-MA-13", grade: 7, subject: "Math", topic: "Proportions", question: "A $50 item with 20% off costs ___.", choices: ["$10", "$30", "$40", "$45"], answer: 2 },
    { id: "G7-MA-14", grade: 7, subject: "Math", topic: "Proportions", question: "Percent change formula: (Change / ___) x 100.", choices: ["New Amount", "Original Amount", "Total", "100"], answer: 1 },
    { id: "G7-MA-15", grade: 7, subject: "Math", topic: "Proportions", question: "If you tip 15% on a $20 bill, the tip is ___.", choices: ["$2", "$3", "$4", "$5"], answer: 1 },
    { id: "G7-MA-16", grade: 7, subject: "Math", topic: "Proportions", question: "Scale factor of 1/2 will make a drawing ___.", choices: ["Larger", "Smaller", "Same size", "Invisible"], answer: 1 },
    { id: "G7-MA-17", grade: 7, subject: "Math", topic: "Proportions", question: "Ratio of y to x (y/x) in a table is ___.", choices: ["k", "x", "y", "Sum"], answer: 0 },
    { id: "G7-MA-18", grade: 7, subject: "Math", topic: "Proportions", question: "A markup is an ___ in price.", choices: ["Increase", "Decrease", "Equality", "Evaluation"], answer: 0 },
    { id: "G7-MA-19", grade: 7, subject: "Math", topic: "Proportions", question: "Find 150% of 60.", choices: ["60", "90", "120", "150"], answer: 1 },
    { id: "G7-MA-20", grade: 7, subject: "Math", topic: "Proportions", question: "Commission is usually a ___ of sales.", choices: ["Fixed amount", "Percentage", "Subtraction", "Division"], answer: 1 },
    { id: "G7-MA-21", grade: 7, subject: "Math", topic: "Proportions", question: "Cross-multiply: a/b = c/d means ad = ___.", choices: ["ac", "bc", "bd", "cd"], answer: 1 },
    { id: "G7-MA-22", grade: 7, subject: "Math", topic: "Proportions", question: "If k=3, the equation is ___.", choices: ["x=3y", "y=3x", "y=x+3", "y=3"], answer: 1 },
    { id: "G7-MA-23", grade: 7, subject: "Math", topic: "Proportions", question: "Two ratios that are equal form a ___.", choices: ["Variable", "Proportion", "Constant", "Coordinate"], answer: 1 },
    { id: "G7-MA-24", grade: 7, subject: "Math", topic: "Proportions", question: "What is 1/4 into a percentage?", choices: ["14%", "25%", "40%", "4%"], answer: 1 },
    { id: "G7-MA-25", grade: 7, subject: "Math", topic: "Proportions", question: "Percent error is always a ___ value.", choices: ["Negative", "Positive (Absolute)", "Zero", "Changing"], answer: 1 },

    // --- TOPIC 2: RATIONAL NUMBER OPERATIONS (25 Questions) ---
    { id: "G7-MA-26", grade: 7, subject: "Math", topic: "Rational Numbers", question: "-5 + 3 = ___.", choices: ["8", "2", "-2", "-8"], answer: 2 },
    { id: "G7-MA-27", grade: 7, subject: "Math", topic: "Rational Numbers", question: "-4 - (-2) = ___.", choices: ["-6", "-2", "2", "6"], answer: 1 },
    { id: "G7-MA-28", grade: 7, subject: "Math", topic: "Rational Numbers", question: "A negative times a negative is a ___.", choices: ["Negative", "Positive", "Zero", "Fraction"], answer: 1 },
    { id: "G7-MA-29", grade: 7, subject: "Math", topic: "Rational Numbers", question: "(-2) x (-5) = ___.", choices: ["-10", "10", "7", "-7"], answer: 1 },
    { id: "G7-MA-30", grade: 7, subject: "Math", topic: "Rational Numbers", question: "A negative divided by a positive is a ___.", choices: ["Positive", "Negative", "Zero", "Whole number"], answer: 1 },
    { id: "G7-MA-31", grade: 7, subject: "Math", topic: "Rational Numbers", question: "Additive inverse of 7 is ___.", choices: ["1/7", "-7", "0", "7"], answer: 1 },
    { id: "G7-MA-32", grade: 7, subject: "Math", topic: "Rational Numbers", question: "-10 / 2 = ___.", choices: ["5", "-5", "20", "-20"], answer: 1 },
    { id: "G7-MA-33", grade: 7, subject: "Math", topic: "Rational Numbers", question: "Sum of a number and its opposite is ___.", choices: ["1", "0", "The number", "Double"], answer: 1 },
    { id: "G7-MA-34", grade: 7, subject: "Math", topic: "Rational Numbers", question: "Convert 1/2 to decimal.", choices: ["0.2", "0.5", "0.25", "5.0"], answer: 1 },
    { id: "G7-MA-35", grade: 7, subject: "Math", topic: "Rational Numbers", question: "Convert 3/4 to decimal.", choices: ["0.34", "0.75", "0.3", "7.5"], answer: 1 },
    { id: "G7-MA-36", grade: 7, subject: "Math", topic: "Rational Numbers", question: "A repeating decimal has a ___ over the repeating digits.", choices: ["Dot", "Bar", "Circle", "Star"], answer: 1 },
    { id: "G7-MA-37", grade: 7, subject: "Math", topic: "Rational Numbers", question: "Is 0 a rational number?", choices: ["Yes", "No"], answer: 0 },
    { id: "G7-MA-38", grade: 7, subject: "Math", topic: "Rational Numbers", question: "Solve: -1.5 + (-2.5)", choices: ["1", "-4", "-1", "4"], answer: 1 },
    { id: "G7-MA-39", grade: 7, subject: "Math", topic: "Rational Numbers", question: "Absolute value of -8.5 is ___.", choices: ["-8.5", "8.5", "0", "1"], answer: 1 },
    { id: "G7-MA-40", grade: 7, subject: "Math", topic: "Rational Numbers", question: "Which is greater: -10 or -5?", choices: ["-10", "-5", "Equal"], answer: 1 },
    { id: "G7-MA-41", grade: 7, subject: "Math", topic: "Rational Numbers", question: "Multiply: (-0.5) x 10", choices: ["5", "-5", "50", "-50"], answer: 1 },
    { id: "G7-MA-42", grade: 7, subject: "Math", topic: "Rational Numbers", question: "Multiplicative inverse of -2/3?", choices: ["2/3", "3/2", "-3/2", "1"], answer: 2 },
    { id: "G7-MA-43", grade: 7, subject: "Math", topic: "Rational Numbers", question: "0 / 5 = ___.", choices: ["0", "5", "Undefined", "1"], answer: 0 },
    { id: "G7-MA-44", grade: 7, subject: "Math", topic: "Rational Numbers", question: "5 / 0 = ___.", choices: ["0", "5", "Undefined", "1"], answer: 2 },
    { id: "G7-MA-45", grade: 7, subject: "Math", topic: "Rational Numbers", question: "Subtracting is the same as adding the ___.", choices: ["Reciprocal", "Opposite", "Square", "Same number"], answer: 1 },
    { id: "G7-MA-46", grade: 7, subject: "Math", topic: "Rational Numbers", question: "Are decimals that stop termed 'terminating'?", choices: ["Yes", "No"], answer: 0 },
    { id: "G7-MA-47", grade: 7, subject: "Math", topic: "Rational Numbers", question: "Evaluate: -2 + 4 - 6", choices: ["0", "4", "-4", "2"], answer: 2 },
    { id: "G7-MA-48", grade: 7, subject: "Math", topic: "Rational Numbers", question: "What is 1/3 as a repeating decimal?", choices: ["0.3", "0.33...", "0.34", "0.31"], answer: 1 },
    { id: "G7-MA-49", grade: 7, subject: "Math", topic: "Rational Numbers", question: "(-1) to the power of 100 is ___.", choices: ["-1", "1", "100", "0"], answer: 1 },
    { id: "G7-MA-50", grade: 7, subject: "Math", topic: "Rational Numbers", question: "Solve: 1/2 - 1", choices: ["1/2", "-1/2", "0", "1"], answer: 1 },

    // --- TOPIC 3: EXPRESSIONS, EQUATIONS & INEQUALITIES (25 Questions) ---
    { id: "G7-MA-51", grade: 7, subject: "Math", topic: "Algebra", question: "Simplify: 2x + 3x", choices: ["5", "5x", "6x", "x^5"], answer: 1 },
    { id: "G7-MA-52", grade: 7, subject: "Math", topic: "Algebra", question: "Solve for x: 2x = 10", choices: ["5", "8", "12", "20"], answer: 0 },
    { id: "G7-MA-53", grade: 7, subject: "Math", topic: "Algebra", question: "Solve for y: y + 5 = -2", choices: ["7", "-7", "3", "-3"], answer: 1 },
    { id: "G7-MA-54", grade: 7, subject: "Math", topic: "Algebra", question: "Expand: 3(x + 2)", choices: ["3x + 2", "3x + 6", "x + 6", "5x"], answer: 1 },
    { id: "G7-MA-55", grade: 7, subject: "Math", topic: "Algebra", question: "Solve: x / 3 = 4", choices: ["7", "1", "12", "1.3"], answer: 2 },
    { id: "G7-MA-56", grade: 7, subject: "Math", topic: "Algebra", question: "Coefficient of -y is ___.", choices: ["0", "1", "-1", "y"], answer: 2 },
    { id: "G7-MA-57", grade: 7, subject: "Math", topic: "Algebra", question: "Solve: 2x + 1 = 9", choices: ["4", "5", "8", "10"], answer: 0 },
    { id: "G7-MA-58", grade: 7, subject: "Math", topic: "Algebra", question: "Is x=2 a solution for 3x=6?", choices: ["Yes", "No"], answer: 0 },
    { id: "G7-MA-59", grade: 7, subject: "Math", topic: "Inequalities", question: "When multiplying/dividing an inequality by a negative, ___ the sign.", choices: ["Keep", "Flip", "Remove", "Square"], answer: 1 },
    { id: "G7-MA-60", grade: 7, subject: "Math", topic: "Inequalities", question: "Graph of x > 5 uses an ___ circle.", choices: ["Open", "Closed", "Solid", "None"], answer: 0 },
    { id: "G7-MA-61", grade: 7, subject: "Math", topic: "Inequalities", question: "Graph of x <= 2 uses a ___ circle.", choices: ["Open", "Closed", "Empty", "Square"], answer: 1 },
    { id: "G7-MA-62", grade: 7, subject: "Math", topic: "Algebra", question: "Factor: 4x + 8", choices: ["4(x+2)", "8(x+1)", "4(x+8)", "x(4+8)"], answer: 0 },
    { id: "G7-MA-63", grade: 7, subject: "Math", topic: "Algebra", question: "Solve: 10 - x = 12", choices: ["2", "-2", "22", "-22"], answer: 1 },
    { id: "G7-MA-64", grade: 7, subject: "Math", topic: "Algebra", question: "Expression for '5 less than x'?", choices: ["5 - x", "x - 5", "5x", "x/5"], answer: 1 },
    { id: "G7-MA-65", grade: 7, subject: "Math", topic: "Algebra", question: "Evaluate 3n - 1 for n=2.", choices: ["5", "6", "4", "7"], answer: 0 },
    { id: "G7-MA-66", grade: 7, subject: "Math", topic: "Algebra", question: "Like terms have the same ___.", choices: ["Numbers", "Variables/Power", "Coefficients", "Signs"], answer: 1 },
    { id: "G7-MA-67", grade: 7, subject: "Math", topic: "Inequalities", question: "Solve: -2x < 10", choices: ["x < -5", "x > -5", "x < 5", "x > 5"], answer: 1 },
    { id: "G7-MA-68", grade: 7, subject: "Math", topic: "Algebra", question: "Constant in 4x + 7?", choices: ["4", "x", "7", "4x"], answer: 2 },
    { id: "G7-MA-69", grade: 7, subject: "Math", topic: "Algebra", question: "Property in a(b+c) = ab + ac?", choices: ["Commutative", "Associative", "Distributive", "Identity"], answer: 2 },
    { id: "G7-MA-70", grade: 7, subject: "Math", topic: "Algebra", question: "Solve: 1/2 x = 10", choices: ["5", "10", "20", "12"], answer: 2 },
    { id: "G7-MA-71", grade: 7, subject: "Math", topic: "Algebra", question: "Term for the number in front of variable?", choices: ["Constant", "Coefficient", "Operator", "Exponent"], answer: 1 },
    { id: "G7-MA-72", grade: 7, subject: "Math", topic: "Algebra", question: "Simplify: x + x + y + y", choices: ["2x + 2y", "xy", "4xy", "x^2 + y^2"], answer: 0 },
    { id: "G7-MA-73", grade: 7, subject: "Math", topic: "Algebra", question: "If 3x = 0, then x = ___.", choices: ["3", "0", "1", "Undefined"], answer: 1 },
    { id: "G7-MA-74", grade: 7, subject: "Math", topic: "Algebra", question: "A statement that two expressions are equal is an ___.", choices: ["Expression", "Equation", "Inequality", "Variable"], answer: 1 },
    { id: "G7-MA-75", grade: 7, subject: "Math", topic: "Inequalities", question: "Symbol for 'no more than'?", choices: [">", ">=", "<", "<="], answer: 3 },

    // --- TOPIC 4: GEOMETRY, PROBABILITY & STATISTICS (25 Questions) ---
    { id: "G7-MA-76", grade: 7, subject: "Math", topic: "Geometry", question: "Area of a circle: A = PI * r^2.", choices: ["PI*d", "PI*r^2", "2*PI*r", "lw"], answer: 1 },
    { id: "G7-MA-77", grade: 7, subject: "Math", topic: "Geometry", question: "Circumference: C = 2 * PI * r.", choices: ["PI*r^2", "2*PI*r", "bh", "s^2"], answer: 1 },
    { id: "G7-MA-78", grade: 7, subject: "Math", topic: "Geometry", question: "Sum of angles in a triangle?", choices: ["90", "180", "360", "45"], answer: 1 },
    { id: "G7-MA-79", grade: 7, subject: "Math", topic: "Probability", question: "Probability of an impossible event is ___.", choices: ["0", "1", "0.5", "-1"], answer: 0 },
    { id: "G7-MA-80", grade: 7, subject: "Math", topic: "Probability", question: "Probability of a certain event is ___.", choices: ["0", "1", "100", "0.5"], answer: 1 },
    { id: "G7-MA-81", grade: 7, subject: "Math", topic: "Geometry", question: "Vertical angles are ___.", choices: ["Supplementary", "Equal", "90", "Adjacent"], answer: 1 },
    { id: "G7-MA-82", grade: 7, subject: "Math", topic: "Geometry", question: "Supplementary angles sum to ___.", choices: ["90", "180", "360", "270"], answer: 1 },
    { id: "G7-MA-83", grade: 7, subject: "Math", topic: "Geometry", question: "Complementary angles sum to ___.", choices: ["90", "180", "360", "45"], answer: 0 },
    { id: "G7-MA-84", grade: 7, subject: "Math", topic: "Statistics", question: "A sample that represents the whole population is ___.", choices: ["Biased", "Unbiased", "Small", "Large"], answer: 1 },
    { id: "G7-MA-85", grade: 7, subject: "Math", topic: "Statistics", question: "The middle value in a data set is the ___.", choices: ["Mean", "Median", "Mode", "Range"], answer: 1 },
    { id: "G7-MA-86", grade: 7, subject: "Math", topic: "Geometry", question: "Scale factor for area is (k) ___.", choices: ["k", "k^2", "k^3", "sqrt(k)"], answer: 1 },
    { id: "G7-MA-87", grade: 7, subject: "Math", topic: "Geometry", question: "Cross-section of a cube cut horizontally is a ___.", choices: ["Triangle", "Square", "Circle", "Rectangle"], answer: 1 },
    { id: "G7-MA-88", grade: 7, subject: "Math", topic: "Probability", question: "Flipping a coin has ___ outcomes.", choices: ["1", "2", "3", "4"], answer: 1 },
    { id: "G7-MA-89", grade: 7, subject: "Math", topic: "Probability", question: "Rolling a standard die has ___ outcomes.", choices: ["1", "4", "6", "12"], answer: 2 },
    { id: "G7-MA-90", grade: 7, subject: "Math", topic: "Geometry", question: "PI is approximately ___.", choices: ["2.14", "3.14", "3.41", "4.13"], answer: 1 },
    { id: "G7-MA-91", grade: 7, subject: "Math", topic: "Geometry", question: "Volume of a rectangular prism: V = lwh.", choices: ["l+w+h", "lwh", "2lw+2lh+2wh", "bh"], answer: 1 },
    { id: "G7-MA-92", grade: 7, subject: "Math", topic: "Statistics", question: "Mean is calculated by (Sum / ___).", choices: ["Median", "Number of items", "Maximum", "Minimum"], answer: 1 },
    { id: "G7-MA-93", grade: 7, subject: "Math", topic: "Statistics", question: "Difference between Q3 and Q1 is the ___.", choices: ["Range", "IQR", "Mean", "Mode"], answer: 1 },
    { id: "G7-MA-94", grade: 7, subject: "Math", topic: "Geometry", question: "Radius is ___ the diameter.", choices: ["Double", "Half", "Equal to", "Square of"], answer: 1 },
    { id: "G7-MA-95", grade: 7, subject: "Math", topic: "Probability", question: "Sample space is the set of ___ outcomes.", choices: ["Favorite", "All possible", "Least likely", "Impossible"], answer: 1 },
    { id: "G7-MA-96", grade: 7, subject: "Math", topic: "Geometry", question: "Surface area is the area of ___.", choices: ["The base", "The top", "All outer surfaces", "The inside"], answer: 2 },
    { id: "G7-MA-97", grade: 7, subject: "Math", topic: "Statistics", question: "A survey asking friends only is likely ___.", choices: ["Biased", "Unbiased", "Perfect", "Random"], answer: 0 },
    { id: "G7-MA-98", grade: 7, subject: "Math", topic: "Geometry", question: "Angles that share a vertex and a side are ___.", choices: ["Vertical", "Adjacent", "Opposite", "Reflex"], answer: 1 },
    { id: "G7-MA-99", grade: 7, subject: "Math", topic: "Probability", question: "Probability is always between 0 and ___.", choices: ["-1", "0.5", "1", "100"], answer: 2 },
    { id: "G7-MA-100", grade: 7, subject: "Math", topic: "Geometry", question: "If the radius is 10, the diameter is ___.", choices: ["5", "10", "20", "100"], answer: 2 }
];

module.exports = G7_MATH_COMPLETE;
