const G7_SOCIAL_STUDIES_COMPLETE = [
    // --- TOPIC 1: ANCIENT CIVILIZATIONS & WORLD RELIGIONS (25 Questions) ---
    { id: "G7-SS-01", grade: 7, subject: "Social Studies", topic: "Civilization", question: "The region often called the 'Cradle of Civilization' is:", choices: ["The Nile Valley", "Mesopotamia", "The Indus Valley", "The Yellow River Valley"], answer: 1 },
    { id: "G7-SS-02", grade: 7, subject: "Social Studies", topic: "Civilization", question: "The Code of Hammurabi is one of the earliest examples of:", choices: ["Religious poetry", "Written law", "Scientific formulas", "Maps"], answer: 1 },
    { id: "G7-SS-03", grade: 7, subject: "Social Studies", topic: "Religion", question: "Which religion originated in India and follows the Four Noble Truths?", choices: ["Hinduism", "Buddhism", "Judaism", "Islam"], answer: 1 },
    { id: "G7-SS-04", grade: 7, subject: "Social Studies", topic: "Religion", question: "The 'Torah' is the sacred text of which religion?", choices: ["Islam", "Christianity", "Judaism", "Hinduism"], answer: 2 },
    { id: "G7-SS-05", grade: 7, subject: "Social Studies", topic: "Religion", question: "Which religion believes in many gods (Polytheistic) and the concept of Karma?", choices: ["Christianity", "Islam", "Hinduism", "Sikhism"], answer: 2 },
    { id: "G7-SS-06", grade: 7, subject: "Social Studies", topic: "Civilization", question: "Ancient Egypt's economy was primarily based on the flooding of the:", choices: ["Tigris", "Nile", "Amazon", "Congo"], answer: 1 },
    { id: "G7-SS-07", grade: 7, subject: "Social Studies", topic: "Religion", question: "The 'Quran' is the holy book of which religion?", choices: ["Buddhism", "Islam", "Sikhism", "Shinto"], answer: 1 },
    { id: "G7-SS-08", grade: 7, subject: "Social Studies", topic: "Civilization", question: "The Great Wall was built to protect which civilization?", choices: ["Rome", "Greece", "China", "Aztec"], answer: 2 },
    { id: "G7-SS-09", grade: 7, subject: "Social Studies", topic: "Civilization", question: "Democracy first emerged in which ancient city-state?", choices: ["Sparta", "Athens", "Rome", "Babylon"], answer: 1 },
    { id: "G7-SS-10", grade: 7, subject: "Social Studies", topic: "Religion", question: "Monotheism is the belief in:", choices: ["Many gods", "One god", "No gods", "Animals as gods"], answer: 1 },
    { id: "G7-SS-11", grade: 7, subject: "Social Studies", topic: "Civilization", question: "Hieroglyphics was the writing system of Ancient:", choices: ["China", "Egypt", "Rome", "Greece"], answer: 1 },
    { id: "G7-SS-12", grade: 7, subject: "Social Studies", topic: "Civilization", question: "Which ancient civilization constructed the Colosseum?", choices: ["Greek", "Roman", "Mayan", "Egyptian"], answer: 1 },
    { id: "G7-SS-13", grade: 7, subject: "Social Studies", topic: "Religion", question: "To whom does the religion of Islam trace its origins through the prophet?", choices: ["Moses", "Abraham", "Muhammad", "Jesus"], answer: 2 },
    { id: "G7-SS-14", grade: 7, subject: "Social Studies", topic: "Civilization", question: "Cuneiform was the writing system developed in:", choices: ["Egypt", "Mesopotamia", "India", "China"], answer: 1 },
    { id: "G7-SS-15", grade: 7, subject: "Social Studies", topic: "Civilization", question: "The 'Silk Road' connected China to which other major power?", choices: ["Aztecs", "The Roman Empire", "The Vikings", "Great Britain"], answer: 1 },
    { id: "G7-SS-16", grade: 7, subject: "Social Studies", topic: "Civilization", question: "The 'Pax Romana' was a long period of:", choices: ["Warfare", "Roman Peace and Stability", "Flooding", "Religious change"], answer: 1 },
    { id: "G7-SS-17", grade: 7, subject: "Social Studies", topic: "Religion", question: "The Five Pillars are the base of which religion?", choices: ["Buddhism", "Islam", "Judaism", "Hinduism"], answer: 1 },
    { id: "G7-SS-18", grade: 7, subject: "Social Studies", topic: "Civilization", question: "The Caste System is a social structure traditionally associated with:", choices: ["Egypt", "India", "Greece", "Russia"], answer: 1 },
    { id: "G7-SS-19", grade: 7, subject: "Social Studies", topic: "Civilization", question: "The Parthenon is located in which city?", choices: ["Rome", "Athens", "Cairo", "Istanbul"], answer: 1 },
    { id: "G7-SS-20", grade: 7, subject: "Social Studies", topic: "Civilization", question: "The Phoenicians were best known for their:", choices: ["Pyramids", "Alphabet and maritime trade", "Cavalry", "Ice farming"], answer: 1 },
    { id: "G7-SS-21", grade: 7, subject: "Social Studies", topic: "Religion", question: "Jesus of Nazareth is the central figure of:", choices: ["Judaism", "Christianity", "Islam", "Sikhism"], answer: 1 },
    { id: "G7-SS-22", grade: 7, subject: "Social Studies", topic: "Civilization", question: "Which civilization developed in the Andes Mountains?", choices: ["Aztec", "Inca", "Maya", "Olmec"], answer: 1 },
    { id: "G7-SS-23", grade: 7, subject: "Social Studies", topic: "Civilization", question: "Aqueducts were an engineering feat of the:", choices: ["Greeks", "Romans", "Sumerians", "Persians"], answer: 1 },
    { id: "G7-SS-24", grade: 7, subject: "Social Studies", topic: "Religion", question: "The cycle of rebirth in Hinduism and Buddhism is called:", choices: ["Karma", "Reincarnation", "Nirvana", "Dharma"], answer: 1 },
    { id: "G7-SS-25", grade: 7, subject: "Social Studies", topic: "Civilization", question: "The Ziggurat was a temple structure in:", choices: ["Egypt", "Mesopotamia", "China", "Mexico"], answer: 1 },

    // --- TOPIC 2: THE MIDDLE AGES & RENAISSANCE (25 Questions) ---
    { id: "G7-SS-26", grade: 7, subject: "Social Studies", topic: "Middle Ages", question: "Feudalism was a social system based on:", choices: ["Money", "Land for Service/Loyalty", "Voting", "Equality"], answer: 1 },
    { id: "G7-SS-27", grade: 7, subject: "Social Studies", topic: "Middle Ages", question: "Who was at the bottom of the Feudal pyramid?", choices: ["Knights", "Kings", "Serfs/Peasants", "Lords"], answer: 2 },
    { id: "G7-SS-28", grade: 7, subject: "Social Studies", topic: "Middle Ages", question: "The 'Magna Carta' (1215) limited the power of the:", choices: ["Church", "King", "Peasants", "Army"], answer: 1 },
    { id: "G7-SS-29", grade: 7, subject: "Social Studies", topic: "Middle Ages", question: "The Crusades were a series of wars between:", choices: ["Romans and Greeks", "Christians and Muslims", "Vikings and English", "Maya and Aztec"], answer: 1 },
    { id: "G7-SS-30", grade: 7, subject: "Social Studies", topic: "Middle Ages", question: "The 'Black Death' was a deadly:", choices: ["War", "Plague or Pandemic", "Flood", "Storm"], answer: 1 },
    { id: "G7-SS-31", grade: 7, subject: "Social Studies", topic: "Middle Ages", question: "The Hundred Years' War was fought between France and:", choices: ["Germany", "England", "Spain", "Italy"], answer: 1 },
    { id: "G7-SS-32", grade: 7, subject: "Social Studies", topic: "Middle Ages", question: "Joan of Arc was a hero for which country?", choices: ["England", "France", "Spain", "Portugal"], answer: 1 },
    { id: "G7-SS-33", grade: 7, subject: "Social Studies", topic: "Renaissance", question: "Renaissance means:", choices: ["The End", "Rebirth", "War", "Science"], answer: 1 },
    { id: "G7-SS-34", grade: 7, subject: "Social Studies", topic: "Renaissance", question: "In which country did the Renaissance begin?", choices: ["France", "Italy", "Germany", "England"], answer: 1 },
    { id: "G7-SS-35", grade: 7, subject: "Social Studies", topic: "Renaissance", question: "Who painted the Mona Lisa?", choices: ["Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"], answer: 1 },
    { id: "G7-SS-36", grade: 7, subject: "Social Studies", topic: "Renaissance", question: "Who painted the Sistine Chapel ceiling?", choices: ["Leonardo", "Michelangelo", "Giotto", "Botticelli"], answer: 1 },
    { id: "G7-SS-37", grade: 7, subject: "Social Studies", topic: "Renaissance", question: "Johannes Gutenberg is famous for inventing the:", choices: ["Telescope", "Printing Press", "Compass", "Clock"], answer: 1 },
    { id: "G7-SS-38", grade: 7, subject: "Social Studies", topic: "Renaissance", question: "Humanism focused on:", choices: ["Only the Church", "Individual potential and human achievements", "Animal rights", "Space exploration"], answer: 1 },
    { id: "G7-SS-39", grade: 7, subject: "Social Studies", topic: "Renaissance", question: "Who wrote 'Romeo and Juliet' and 'Hamlet'?", choices: ["Chaucer", "William Shakespeare", "Dante", "Petrarch"], answer: 1 },
    { id: "G7-SS-40", grade: 7, subject: "Social Studies", topic: "Reformation", question: "Martin Luther started the:", choices: ["Industrial Revolution", "Protestant Reformation", "Crusades", "Renaissance"], answer: 1 },
    { id: "G7-SS-41", grade: 7, subject: "Social Studies", topic: "Reformation", question: "What did Martin Luther post on the church door?", choices: ["A poem", "The 95 Theses", "A map", "A recipe"], answer: 1 },
    { id: "G7-SS-42", grade: 7, subject: "Social Studies", topic: "Exploration", question: "Christopher Columbus sailed for which country?", choices: ["Italy", "Spain", "Portugal", "France"], answer: 1 },
    { id: "id: G7-SS-43", grade: 7, subject: "Social Studies", topic: "Exploration", question: "Who was the first person to circumnavigate the globe?", choices: ["Columbus", "Magellan", "Vasco da Gama", "Cortes"], answer: 1 },
    { id: "G7-SS-44", grade: 7, subject: "Social Studies", topic: "Middle Ages", question: "The knight's code of conduct was called:", choices: ["Law", "Chivalry", "Honor", "Fealty"], answer: 1 },
    { id: "G7-SS-45", grade: 7, subject: "Social Studies", topic: "Exploration", question: "The Exchange of plants/animals between Old and New worlds is:", choices: ["Trade Route", "Columbian Exchange", "Renaissance", "Reformation"], answer: 1 },
    { id: "G7-SS-46", grade: 7, subject: "Social Studies", topic: "Middle Ages", question: "The Byzantine capital was:", choices: ["Rome", "Constantinople", "Athens", "Paris"], answer: 1 },
    { id: "G7-SS-47", grade: 7, subject: "Social Studies", topic: "Renaissance", question: "Galileo was a famous:", choices: ["Painter", "Scientist/Astronomer", "King", "Priest"], answer: 1 },
    { id: "G7-SS-48", grade: 7, subject: "Social Studies", topic: "Middle Ages", question: "Charlemagne was crowned Emperor of the:", choices: ["French", "Romans", "English", "Vikings"], answer: 1 },
    { id: "G7-SS-49", grade: 7, subject: "Social Studies", topic: "Middle Ages", question: "Which group of invaders were known for their longships?", choices: ["Romans", "Vikings", "Mongols", "Huns"], answer: 1 },
    { id: "G7-SS-50", grade: 7, subject: "Social Studies", topic: "Middle Ages", question: "A 'Guild' was an association of:", choices: ["Soldiers", "Craftspeople or Merchants", "Farmers", "Kings"], answer: 1 },

    // --- TOPIC 3: GOVERNMENTS, ECONOMICS & CIVICS (25 Questions) ---
    { id: "G7-SS-51", grade: 7, subject: "Social Studies", topic: "Government", question: "A government ruled by a single person with total power is a:", choices: ["Democracy", "Dictatorship", "Republic", "Oligarchy"], answer: 1 },
    { id: "G7-SS-52", grade: 7, subject: "Social Studies", topic: "Government", question: "An Oligarchy is a government ruled by:", choices: ["The people", "A small group of powerful people", "A King", "Religious leaders"], answer: 1 },
    { id: "G7-SS-53", grade: 7, subject: "Social Studies", topic: "Civics", question: "The right to vote is also known as:", choices: ["Suffrage", "Veto", "Petition", "Draft"], answer: 0 },
    { id: "G7-SS-54", grade: 7, subject: "Social Studies", topic: "Government", question: "Which branch of government makes the laws?", choices: ["Executive", "Legislative", "Judicial", "Military"], answer: 1 },
    { id: "G7-SS-55", grade: 7, subject: "Social Studies", topic: "Government", question: "Which branch of government enforces the laws?", choices: ["Legislative", "Executive", "Judicial", "Administrative"], answer: 1 },
    { id: "G7-SS-56", grade: 7, subject: "Social Studies", topic: "Government", question: "Which branch of government interprets the laws?", choices: ["Executive", "Judicial", "Legislative", "Police"], answer: 1 },
    { id: "G7-SS-57", grade: 7, subject: "Social Studies", topic: "Economics", question: "The amount of goods available for sale is:", choices: ["Demand", "Supply", "Inventory", "Surplus"], answer: 1 },
    { id: "G7-SS-58", grade: 7, subject: "Social Studies", topic: "Economics", question: "How much consumers want to buy a good is:", choices: ["Supply", "Demand", "Price", "Cost"], answer: 1 },
    { id: "G7-SS-59", grade: 7, subject: "Social Studies", topic: "Economics", question: "When there is not enough of something to meet demand, it is:", choices: ["Scarcity", "Abundance", "Surplus", "Wealth"], answer: 0 },
    { id: "G7-SS-60", grade: 7, subject: "Social Studies", topic: "Government", question: "A 'Republic' is a government where:", choices: ["Kings rule", "Citizens elect representatives to lead", "One person has all power", "No rules exist"], answer: 1 },
    { id: "G7-SS-61", grade: 7, subject: "Social Studies", topic: "Government", question: "The U.S. Constitution begins with the words:", choices: ["Go USA", "We the People", "Four score and seven", "I have a dream"], answer: 1 },
    { id: "G7-SS-62", grade: 7, subject: "Social Studies", topic: "Civics", question: "How many amendments are in the Bill of Rights?", choices: ["5", "10", "27", "100"], answer: 1 },
    { id: "G7-SS-63", grade: 7, subject: "Social Studies", topic: "Economics", question: "Money paid by citizens to the government is:", choices: ["A gift", "Taxes", "Rent", "A loan"], answer: 1 },
    { id: "G7-SS-64", grade: 7, subject: "Social Studies", topic: "Economics", question: "The total value of all goods/services produced in a year is:", choices: ["GDP", "CPI", "USA", "Tax"], answer: 0 },
    { id: "G7-SS-65", grade: 7, subject: "Social Studies", topic: "Civics", question: "A change or addition to a constitution is an:", choices: ["Appendix", "Amendment", "Article", "Action"], answer: 1 },
    { id: "G7-SS-66", grade: 7, subject: "Social Studies", topic: "Economics", question: "To 'Import' means to:", choices: ["Sell goods to another country", "Bring goods in from another country", "Burn goods", "Hide goods"], answer: 1 },
    { id: "G7-SS-67", grade: 7, subject: "Social Studies", topic: "Economics", question: "To 'Export' means to:", choices: ["Buy goods from away", "Send goods to another country for sale", "Use goods at home", "Fix goods"], answer: 1 },
    { id: "G7-SS-68", grade: 7, subject: "Social Studies", topic: "Government", question: "Which system shares power between national and state governments?", choices: ["Federalism", "Monarchy", "Communism", "Anarchy"], answer: 0 },
    { id: "G7-SS-69", grade: 7, subject: "Social Studies", topic: "Civics", question: "The President's power to reject a law is a:", choices: ["Bill", "Veto", "Vote", "Vanish"], answer: 1 },
    { id: "G7-SS-70", grade: 7, subject: "Social Studies", topic: "Government", question: "A 'Monarchy' is ruled by a:", choices: ["President", "King or Queen", "Chief", "Prime Minister"], answer: 1 },
    { id: "G7-SS-71", grade: 7, subject: "Social Studies", topic: "Economics", question: "Inflation means that prices are:", choices: ["Falling", "Staying the same", "Rising", "Invisible"], answer: 2 },
    { id: "G7-SS-72", grade: 7, subject: "Social Studies", topic: "Economics", question: "An 'Entrepreneur' is someone who:", choices: ["Works for a boss", "Starts and operates a business", "Is retired", "Is a king"], answer: 1 },
    { id: "G7-SS-73", grade: 7, subject: "Social Studies", topic: "Economics", question: "Quotas and Tariffs are types of:", choices: ["Free trade", "Trade barriers", "Recipes", "Gifts"], answer: 1 },
    { id: "G7-SS-74", grade: 7, subject: "Social Studies", topic: "Government", question: "What is written in the US First Amendment?", choices: ["Right to bear arms", "Freedom of speech and religion", "Right to a fair trial", "No taxes"], answer: 1 },
    { id: "G7-SS-75", grade: 7, subject: "Social Studies", topic: "Economics", question: "What is 'Currency'?", choices: ["A type of food", "The system of money in use in a country", "A historic event", "A government building"], answer: 1 },

    // --- TOPIC 4: MODERN WORLD CONFLICTS & GEOGRAPHY (25 Questions) ---
    { id: "G7-SS-76", grade: 7, subject: "Social Studies", topic: "Geography", question: "Which continent is the largest in land area?", choices: ["Africa", "Asia", "North America", "Europe"], answer: 1 },
    { id: "G7-SS-77", grade: 7, subject: "Social Studies", topic: "Geography", question: "Which ocean is the largest?", choices: ["Atlantic", "Pacific", "Indian", "Arctic"], answer: 1 },
    { id: "G7-SS-78", grade: 7, subject: "Social Studies", topic: "History", question: "World War I began in which year?", choices: ["1914", "1939", "1861", "1776"], answer: 0 },
    { id: "G7-SS-79", grade: 7, subject: "Social Studies", topic: "History", question: "World War II ended in which year?", choices: ["1918", "1945", "1960", "2000"], answer: 1 },
    { id: "G7-SS-80", grade: 7, subject: "Social Studies", topic: "History", question: "The 'Cold War' was a period of tension between the USA and:", choices: ["China", "The Soviet Union (USSR)", "Germany", "Japan"], answer: 1 },
    { id: "G7-SS-81", grade: 7, subject: "Social Studies", topic: "Geography", question: "The 0 degree line of Latitude is the:", choices: ["Prime Meridian", "Equator", "North Pole", "Tropic of Cancer"], answer: 1 },
    { id: "G7-SS-82", grade: 7, subject: "Social Studies", topic: "Geography", question: "The 0 degree line of Longitude is the:", choices: ["Equator", "Prime Meridian", "Date Line", "South Pole"], answer: 1 },
    { id: "G7-SS-83", grade: 7, subject: "Social Studies", topic: "Geography", question: "Map showing countries and borders is a:", choices: ["Physical map", "Political map", "Climate map", "Road map"], answer: 1 },
    { id: "G7-SS-84", grade: 7, subject: "Social Studies", topic: "Geography", question: "A 'Sahara' is a massive desert in:", choices: ["Asia", "Africa", "South America", "Australia"], answer: 1 },
    { id: "G7-SS-85", grade: 7, subject: "Social Studies", topic: "History", question: "The Holocaust occurred during:", choices: ["The Civil War", "World War II", "The Vietnam War", "World War I"], answer: 1 },
    { id: "G7-SS-86", grade: 7, subject: "Social Studies", topic: "History", question: "Who was the leader of the Civil Rights movement known for the 'I Have a Dream' speech?", choices: ["Malcolm X", "Martin Luther King Jr.", "Rosa Parks", "John Lewis"], answer: 1 },
    { id: "G7-SS-87", grade: 7, subject: "Social Studies", topic: "Geography", question: "The Amazon Rainforest is located in:", choices: ["Africa", "South America", "Asia", "Europe"], answer: 1 },
    { id: "G7-SS-88", grade: 7, subject: "Social Studies", topic: "Economics", question: "NAFTA/USMCA is a trade agreement between USA, Canada, and:", choices: ["Brazil", "Mexico", "China", "Russia"], answer: 1 },
    { id: "G7-SS-89", grade: 7, subject: "Social Studies", topic: "Geography", question: "What is the capital of France?", choices: ["London", "Paris", "Berlin", "Madrid"], answer: 1 },
    { id: "G7-SS-90", grade: 7, subject: "Social Studies", topic: "History", question: "The Berlin Wall fell in 1989, symbolising the end of:", choices: ["WWI", "The Cold War", "WWII", "The Roman Empire"], answer: 1 },
    { id: "G7-SS-91", grade: 7, subject: "Social Studies", topic: "History", question: "Apartheid was a system of racial segregation in:", choices: ["USA", "South Africa", "India", "Kenya"], answer: 1 },
    { id: "G7-SS-92", grade: 7, subject: "Social Studies", topic: "Geography", question: "The largest country in the world by land area is:", choices: ["Canada", "China", "Russia", "USA"], answer: 2 },
    { id: "G7-SS-93", grade: 7, subject: "Social Studies", topic: "Geography", question: "Mount Everest, the highest peak, is in which mountain range?", choices: ["Rockies", "Andes", "Himalayas", "Alps"], answer: 2 },
    { id: "G7-SS-94", grade: 7, subject: "Social Studies", topic: "History", question: "Who was the first man to walk on the moon in 1969?", choices: ["John Glenn", "Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin"], answer: 1 },
    { id: "G7-SS-95", grade: 7, subject: "Social Studies", topic: "Civics", question: "The United Nations (UN) was created to promote:", choices: ["War", "International Peace and Cooperation", "Space travel", "Mining"], answer: 1 },
    { id: "G7-SS-96", grade: 7, subject: "Social Studies", topic: "Economics", question: "A 'Global Economy' refers to:", choices: ["Trading only locally", "Interconnected trade between countries worldwide", "No trade at all", "Money from space"], answer: 1 },
    { id: "G7-SS-97", grade: 7, subject: "Social Studies", topic: "Geography", question: "The island of Japan is located in which ocean?", choices: ["Atlantic", "Pacific", "Indian", "Arctic"], answer: 1 },
    { id: "G7-SS-98", grade: 7, subject: "Social Studies", topic: "Geography", question: "What is the primary language spoken in Brazil?", choices: ["Spanish", "Portuguese", "French", "English"], answer: 1 },
    { id: "G7-SS-99", grade: 7, subject: "Social Studies", topic: "History", question: "The Industrial Revolution began in which country?", choices: ["USA", "Great Britain", "China", "Germany"], answer: 1 },
    { id: "G7-SS-100", grade: 7, subject: "Social Studies", topic: "Civics", question: "To 'vibe' with global culture often means following global ___.", choices: ["Rules", "Trends and connections", "Maps", "Wars"], answer: 1 }
];

module.exports = G7_SOCIAL_STUDIES_COMPLETE;
