const G7_SCIENCE_COMPLETE = [
    // --- TOPIC 1: GENETICS & REPRODUCTION (25 Questions) ---
    { id: "G7-SCI-01", grade: 7, subject: "Science", topic: "Genetics", question: "A trait that always shows up when present is ___.", choices: ["Recessive", "Dominant", "Hidden", "Weak"], answer: 1 },
    { id: "G7-SCI-02", grade: 7, subject: "Science", topic: "Genetics", question: "Physical appearance of a trait is the ___.", choices: ["Genotype", "Phenotype", "Nucleus", "DNA"], answer: 1 },
    { id: "G7-SCI-03", grade: 7, subject: "Science", topic: "Genetics", question: "Genetic makeup of an organism (e.g., Tt) is the ___.", choices: ["Phenotype", "Genotype", "Trait", "Cell"], answer: 1 },
    { id: "G7-SCI-04", grade: 7, subject: "Science", topic: "Genetics", question: "Tool used to predict genetic outcomes?", choices: ["Punnett Square", "Bar Graph", "Microscope", "Scale"], answer: 0 },
    { id: "G7-SCI-05", grade: 7, subject: "Science", topic: "Genetics", question: "Different forms of a gene are called ___.", choices: ["DNA", "Alleles", "Chromosomes", "Cells"], answer: 1 },
    { id: "G7-SCI-06", grade: 7, subject: "Science", topic: "Reproduction", question: "Asexual reproduction results in offspring that are ___.", choices: ["Different", "Identical to parent", "Larger", "Stronger"], answer: 1 },
    { id: "G7-SCI-07", grade: 7, subject: "Science", topic: "Reproduction", question: "Sexual reproduction requires ___ parents.", choices: ["1", "2", "3", "0"], answer: 1 },
    { id: "G7-SCI-08", grade: 7, subject: "Science", topic: "Genetics", question: "Who is the 'Father of Genetics'?", choices: ["Darwin", "Mendel", "Hooke", "Einstein"], answer: 1 },
    { id: "G7-SCI-09", grade: 7, subject: "Science", topic: "Genetics", question: "DNA stands for ___ Acid.", choices: ["Deoxyribonucleic", "Diatomic", "Sulfuric", "Amino"], answer: 0 },
    { id: "G7-SCI-10", grade: 7, subject: "Science", topic: "Genetics", question: "A change in DNA sequence is a ___.", choices: ["Hybrid", "Mutation", "Clone", "Trait"], answer: 1 },
    { id: "G7-SCI-11", grade: 7, subject: "Science", topic: "Genetics", question: "Human body cells have ___ chromosomes.", choices: ["23", "46", "92", "12"], answer: 1 },
    { id: "G7-SCI-12", grade: 7, subject: "Science", topic: "Reproduction", question: "Binary fission is common in ___.", choices: ["Humans", "Bacteria", "Plants", "Dogs"], answer: 1 },
    { id: "G7-SCI-13", grade: 7, subject: "Science", topic: "Genetics", question: "The shape of DNA is a ___.", choices: ["Circle", "Double Helix", "Square", "Straight line"], answer: 1 },
    { id: "G7-SCI-14", grade: 7, subject: "Science", topic: "Genetics", question: "Genes are located on ___.", choices: ["Vacuoles", "Chromosomes", "Mitochondria", "Wall"], answer: 1 },
    { id: "G7-SCI-15", grade: 7, subject: "Science", topic: "Genetics", question: "Homozygous means having ___ alleles.", choices: ["Different", "Two of the same", "One", "None"], answer: 1 },
    { id: "G7-SCI-16", grade: 7, subject: "Science", topic: "Genetics", question: "Heterozygous means having ___ alleles.", choices: ["Same", "Different", "Two", "Zero"], answer: 1 },
    { id: "G7-SCI-17", grade: 7, subject: "Science", topic: "Genetics", question: "Which trait is hidden by a dominant allele?", choices: ["Strong", "Recessive", "Physical", "Parental"], answer: 1 },
    { id: "G7-SCI-18", grade: 7, subject: "Science", topic: "Reproduction", question: "Budding is a type of ___ reproduction.", choices: ["Sexual", "Asexual", "Complex", "Internal"], answer: 1 },
    { id: "G7-SCI-19", grade: 7, subject: "Science", topic: "Genetics", question: "A Punnett square for Tt x Tt has ___ probability of TT.", choices: ["25%", "50%", "75%", "100%"], answer: 0 },
    { id: "G7-SCI-20", grade: 7, subject: "Science", topic: "Genetics", question: "A Punnett square for Tt x Tt has ___ probability of Tt.", choices: ["25%", "50%", "75%", "100%"], answer: 1 },
    { id: "G7-SCI-21", grade: 7, subject: "Science", topic: "Reproduction", question: "Zygote is formed after ___.", choices: ["Mitosis", "Fertilization", "Osmosis", "Evaporation"], answer: 1 },
    { id: "G7-SCI-22", grade: 7, subject: "Science", topic: "Genetics", question: "Male sex chromosomes in humans are ___.", choices: ["XX", "XY", "YY", "XO"], answer: 1 },
    { id: "G7-SCI-23", grade: 7, subject: "Science", topic: "Genetics", question: "Female sex chromosomes in humans are ___.", choices: ["XY", "XX", "YY", "XO"], answer: 1 },
    { id: "G7-SCI-24", grade: 7, subject: "Science", topic: "Genetics", question: "Pedigree chart tracks ___ through generations.", choices: ["Wealth", "Traits/Diseases", "Weight", "Speed"], answer: 1 },
    { id: "G7-SCI-25", grade: 7, subject: "Science", topic: "Genetics", question: "Selective breeding is done by ___.", choices: ["Nature", "Humans", "Chance", "Wind"], answer: 1 },

    // --- TOPIC 2: EVOLUTION & ADAPTATIONS (25 Questions) ---
    { id: "G7-SCI-26", grade: 7, subject: "Science", topic: "Evolution", question: "Change in a species over time is ___.", choices: ["Mutation", "Evolution", "Extinction", "Stasis"], answer: 1 },
    { id: "G7-SCI-27", grade: 7, subject: "Science", topic: "Evolution", question: "Who proposed natural selection?", choices: ["Newton", "Darwin", "Mendel", "Hooke"], answer: 1 },
    { id: "G7-SCI-28", grade: 7, subject: "Science", topic: "Evolution", question: "Process where best-suited organisms survive?", choices: ["Artificial Selection", "Natural Selection", "Mutation", "Hybridization"], answer: 1 },
    { id: "G7-SCI-29", grade: 7, subject: "Science", topic: "Evolution", question: "A trait that helps an organism survive is an ___.", choices: ["Accident", "Adaptation", "Error", "Handicap"], answer: 1 },
    { id: "G7-SCI-30", grade: 7, subject: "Science", topic: "Evolution", question: "Remains of once-living things are ___.", choices: ["Rocks", "Fossils", "Crystals", "Dust"], answer: 1 },
    { id: "G7-SCI-31", grade: 7, subject: "Science", topic: "Evolution", question: "Similar structures in different species (like bone structure) are ___.", choices: ["Analogous", "Homologous", "Vestigial", "Fake"], answer: 1 },
    { id: "G7-SCI-32", grade: 7, subject: "Science", topic: "Evolution", question: "A structure no longer used (like a whale's leg bones)?", choices: ["Active", "Vestigial", "New", "Complex"], answer: 1 },
    { id: "G7-SCI-33", grade: 7, subject: "Science", topic: "Evolution", question: "When all members of a species die, it is ___.", choices: ["Migration", "Extinction", "Evolution", "Mutation"], answer: 1 },
    { id: "G7-SCI-34", grade: 7, subject: "Science", topic: "Evolution", question: "Darwin studied finches on the ___ Islands.", choices: ["Hawaii", "Galapagos", "Caribbean", "Canary"], answer: 1 },
    { id: "G7-SCI-35", grade: 7, subject: "Science", topic: "Evolution", question: "Natural selection acts on an organism's ___.", choices: ["Genotype", "Phenotype", "Cell size", "Name"], answer: 1 },
    { id: "G7-SCI-36", grade: 7, subject: "Science", topic: "Evolution", question: "Species with similar DNA are logically ___.", choices: ["Unrelated", "Closely related", "Competitors", "Opposites"], answer: 1 },
    { id: "G7-SCI-37", grade: 7, subject: "Science", topic: "Evolution", question: "Camouflage is an example of a ___ adaptation.", choices: ["Physical", "Behavioral", "Chemical", "Social"], answer: 0 },
    { id: "G7-SCI-38", grade: 7, subject: "Science", topic: "Evolution", question: "Migration is an example of a ___ adaptation.", choices: ["Physical", "Behavioral", "Genetic", "Internal"], answer: 1 },
    { id: "G7-SCI-39", grade: 7, subject: "Science", topic: "Evolution", question: "Most fossils are found in ___ rock.", choices: ["Igneous", "Sedimentary", "Metamorphic", "Granite"], answer: 1 },
    { id: "G7-SCI-40", grade: 7, subject: "Science", topic: "Evolution", question: "Determining age by comparing rock layers is ___ dating.", choices: ["Absolute", "Relative", "Carbon", "Speed"], answer: 1 },
    { id: "G7-SCI-41", grade: 7, subject: "Science", topic: "Evolution", question: "Using radioactive elements to find age is ___ dating.", choices: ["Relative", "Absolute", "Layer", "Visual"], answer: 1 },
    { id: "G7-SCI-42", grade: 7, subject: "Science", topic: "Evolution", question: "A branching diagram showing relationships?", choices: ["Cladogram", "Pie Chart", "Line Graph", "Histogram"], answer: 0 },
    { id: "G7-SCI-43", grade: 7, subject: "Science", topic: "Evolution", question: "The 'struggle for existence' means organisms ___.", choices: ["Help each other", "Compete for resources", "Sleep", "Die"], answer: 1 },
    { id: "G7-SCI-44", grade: 7, subject: "Science", topic: "Evolution", question: "Modern humans are classified as ___.", choices: ["Homo habilis", "Homo sapiens", "Homo erectus", "Neanderthals"], answer: 1 },
    { id: "G7-SCI-45", grade: 7, subject: "Science", topic: "Evolution", question: "Variation in a species is caused by ___.", choices: ["Environment only", "Mutations and sexual reproduction", "Cloning", "Copying"], answer: 1 },
    { id: "G7-SCI-46", grade: 7, subject: "Science", topic: "Evolution", question: "Darwin's book was 'On the ___'.", choices: ["Nature", "Origin of Species", "Cells", "Fossils"], answer: 1 },
    { id: "G7-SCI-47", grade: 7, subject: "Science", topic: "Evolution", question: "An index fossil is used to help ___.", choices: ["Clean rocks", "Identify rock ages", "Burn fuel", "Feed animals"], answer: 1 },
    { id: "G7-SCI-48", grade: 7, subject: "Science", topic: "Evolution", question: "How long ago did the Earth form (approx)?", choices: ["10,000 yrs", "1 million yrs", "4.6 billion yrs", "10 billion yrs"], answer: 2 },
    { id: "G7-SCI-49", grade: 7, subject: "Science", topic: "Evolution", question: "Fossil record shows life started simple and became ___.", choices: ["Simpler", "Complex", "Smaller", "Circular"], answer: 1 },
    { id: "G7-SCI-50", grade: 7, subject: "Science", topic: "Evolution", question: "Overproduction means species produce ___ offspring than survive.", choices: ["Fewer", "More", "Equal", "No"], answer: 1 },

    // --- TOPIC 3: MATTER & CHEMISTRY (25 Questions) ---
    { id: "G7-SCI-51", grade: 7, subject: "Science", topic: "Chemistry", question: "Smallest part of an element is an ___.", choices: ["Molecule", "Atom", "Cell", "Compound"], answer: 1 },
    { id: "G7-SCI-52", grade: 7, subject: "Science", topic: "Chemistry", question: "Three subatomic particles are protons, neutrons, and ___.", choices: ["Positrons", "Electrons", "Ions", "Photons"], answer: 1 },
    { id: "G7-SCI-53", grade: 7, subject: "Science", topic: "Chemistry", question: "A substance made of only one type of atom?", choices: ["Mixture", "Element", "Compound", "Solution"], answer: 1 },
    { id: "G7-SCI-54", grade: 7, subject: "Science", topic: "Chemistry", question: "The center of an atom is the ___.", choices: ["Shell", "Nucleus", "Orbit", "Core"], answer: 1 },
    { id: "G7-SCI-55", grade: 7, subject: "Science", topic: "Chemistry", question: "Particles with a positive charge?", choices: ["Electrons", "Protons", "Neutrons", "Atoms"], answer: 1 },
    { id: "G7-SCI-56", grade: 7, subject: "Science", topic: "Chemistry", question: "Particles with no charge (neutral)?", choices: ["Protons", "Neutrons", "Electrons", "Molecules"], answer: 1 },
    { id: "G7-SCI-57", grade: 7, subject: "Science", topic: "Chemistry", question: "Particles with a negative charge?", choices: ["Protons", "Electrons", "Neutrons", "Ions"], answer: 1 },
    { id: "G7-SCI-58", grade: 7, subject: "Science", topic: "Chemistry", question: "Two or more elements chemically combined?", choices: ["Mixture", "Compound", "Element", "Isotope"], answer: 1 },
    { id: "G7-SCI-59", grade: 7, subject: "Science", topic: "Chemistry", question: "A table that organizes all elements?", choices: ["Periodic Table", "Math Table", "Rock Table", "Star Chart"], answer: 0 },
    { id: "G7-SCI-60", grade: 7, subject: "Science", topic: "Chemistry", question: "Symbol for Oxygen?", choices: ["Ox", "O", "Oy", "Og"], answer: 1 },
    { id: "G7-SCI-61", grade: 7, subject: "Science", topic: "Chemistry", question: "Symbol for Gold?", choices: ["Go", "Gd", "Au", "Ag"], answer: 2 },
    { id: "G7-SCI-62", grade: 7, subject: "Science", topic: "Chemistry", question: "The atomic number is the number of ___.", choices: ["Neutrons", "Electrons", "Protons", "Shells"], answer: 2 },
    { id: "G7-SCI-63", grade: 7, subject: "Science", topic: "Chemistry", question: "Horizontal rows on the periodic table are ___.", choices: ["Groups", "Periods", "Families", "Sectors"], answer: 1 },
    { id: "G7-SCI-64", grade: 7, subject: "Science", topic: "Chemistry", question: "Vertical columns on the periodic table are ___.", choices: ["Groups/Families", "Periods", "Lines", "Orbits"], answer: 0 },
    { id: "G7-SCI-65", grade: 7, subject: "Science", topic: "Chemistry", question: "Which elements are shiny and good conductors?", choices: ["Nonmetals", "Metals", "Metalloids", "Gases"], answer: 1 },
    { id: "G7-SCI-66", grade: 7, subject: "Science", topic: "Chemistry", question: "Noble gases are found in which group?", choices: ["Group 1", "Group 18", "Group 2", "The middle"], answer: 1 },
    { id: "G7-SCI-67", grade: 7, subject: "Science", topic: "Chemistry", question: "Solids that can be hammered into sheets are ___.", choices: ["Brittle", "Malleable", "Ductile", "Liquid"], answer: 1 },
    { id: "G7-SCI-68", grade: 7, subject: "Science", topic: "Chemistry", question: "A mixture where parts are visible (like salad)?", choices: ["Homogeneous", "Heterogeneous", "Solution", "Element"], answer: 1 },
    { id: "G7-SCI-69", grade: 7, subject: "Science", topic: "Chemistry", question: "A mixture that is uniform throughout (like air)?", choices: ["Heterogeneous", "Homogeneous", "Solid", "Compound"], answer: 1 },
    { id: "G7-SCI-70", grade: 7, subject: "Science", topic: "Chemistry", question: "Density = Mass divided by ___.", choices: ["Weight", "Volume", "Height", "Length"], answer: 1 },
    { id: "G7-SCI-71", grade: 7, subject: "Science", topic: "Chemistry", question: "A chemical change results in a ___.", choices: ["Same substance", "New substance", "Change in size only", "Movement"], answer: 1 },
    { id: "G7-SCI-72", grade: 7, subject: "Science", topic: "Chemistry", question: "Which is a chemical change?", choices: ["Melting ice", "Burning wood", "Cutting paper", "Boiling water"], answer: 1 },
    { id: "G7-SCI-73", grade: 7, subject: "Science", topic: "Chemistry", question: "Conservation of Mass: mass cannot be created or ___.", choices: ["Moved", "Measured", "Destroyed", "Changed"], answer: 2 },
    { id: "G7-SCI-74", grade: 7, subject: "Science", topic: "Chemistry", question: "pH of 7 is ___.", choices: ["Acidic", "Basic", "Neutral", "Hot"], answer: 2 },
    { id: "G7-SCI-75", grade: 7, subject: "Science", topic: "Chemistry", question: "pH less than 7 is ___.", choices: ["Acidic", "Basic", "Neutral", "Sweet"], answer: 0 },

    // --- TOPIC 4: FORCE, MOTION & ENERGY (25 Questions) ---
    { id: "G7-SCI-76", grade: 7, subject: "Science", topic: "Physics", question: "A push or pull is a ___.", choices: ["Motion", "Force", "Speed", "Energy"], answer: 1 },
    { id: "G7-SCI-77", grade: 7, subject: "Science", topic: "Physics", question: "Force is measured in ___.", choices: ["Grams", "Newtons", "Liters", "Meters"], answer: 1 },
    { id: "G7-SCI-78", grade: 7, subject: "Science", topic: "Physics", question: "Speed = Distance divided by ___.", choices: ["Weight", "Time", "Height", "Force"], answer: 1 },
    { id: "G7-SCI-79", grade: 7, subject: "Science", topic: "Physics", question: "Velocity is speed and ___.", choices: ["Mass", "Direction", "Weight", "Volume"], answer: 1 },
    { id: "G7-SCI-80", grade: 7, subject: "Science", topic: "Physics", question: "Change in velocity over time is ___.", choices: ["Inertia", "Acceleration", "Friction", "Gravity"], answer: 1 },
    { id: "G7-SCI-81", grade: 7, subject: "Science", topic: "Physics", question: "The force that opposes motion between surfaces?", choices: ["Gravity", "Friction", "Magnetism", "Normal force"], answer: 1 },
    { id: "G7-SCI-82", grade: 7, subject: "Science", topic: "Physics", question: "Newton's 1st Law is the Law of ___.", choices: ["Friction", "Inertia", "Action-Reaction", "Gravity"], answer: 1 },
    { id: "G7-SCI-83", grade: 7, subject: "Science", topic: "Physics", question: "Newton's 2nd Law: Force = Mass x ___.", choices: ["Speed", "Acceleration", "Weight", "Gravity"], answer: 1 },
    { id: "G7-SCI-84", grade: 7, subject: "Science", topic: "Physics", question: "Newton's 3rd Law: For every action, there is an equal/opposite ___.", choices: ["Force", "Reaction", "Motion", "Speed"], answer: 1 },
    { id: "G7-SCI-85", grade: 7, subject: "Science", topic: "Physics", question: "Force pulling objects toward Earth?", choices: ["Friction", "Gravity", "Inertia", "Magnetism"], answer: 1 },
    { id: "G7-SCI-86", grade: 7, subject: "Science", topic: "Physics", question: "Stored energy is ___ energy.", choices: ["Kinetic", "Potential", "Thermal", "Light"], answer: 1 },
    { id: "G7-SCI-87", grade: 7, subject: "Science", topic: "Physics", question: "Energy of motion is ___ energy.", choices: ["Potential", "Kinetic", "Chemical", "Nuclear"], answer: 1 },
    { id: "G7-SCI-88", grade: 7, subject: "Science", topic: "Physics", question: "Energy can never be created or ___.", choices: ["Destroyed", "Transformed", "Moved", "Stored"], answer: 0 },
    { id: "G7-SCI-89", grade: 7, subject: "Science", topic: "Physics", question: "Heat transfer through direct touch is ___.", choices: ["Convection", "Conduction", "Radiation", "Insulation"], answer: 1 },
    { id: "G7-SCI-90", grade: 7, subject: "Science", topic: "Physics", question: "Heat transfer through fluids (air/water) is ___.", choices: ["Conduction", "Convection", "Radiation", "Subduction"], answer: 1 },
    { id: "G7-SCI-91", grade: 7, subject: "Science", topic: "Physics", question: "Heat transfer through space (waves) is ___.", choices: ["Conduction", "Convection", "Radiation", "Gravity"], answer: 2 },
    { id: "G7-SCI-92", grade: 7, subject: "Science", topic: "Physics", question: "Balanced forces result in ___ motion change.", choices: ["Zero", "Maximum", "Fast", "Downward"], answer: 0 },
    { id: "G7-SCI-93", grade: 7, subject: "Science", topic: "Physics", question: "The more mass an object has, the more ___ it has.", choices: ["Speed", "Inertia", "Volume", "Color"], answer: 1 },
    { id: "G7-SCI-94", grade: 7, subject: "Science", topic: "Physics", question: "Work = Force x ___.", choices: ["Time", "Distance", "Mass", "Height"], answer: 1 },
    { id: "G7-SCI-95", grade: 7, subject: "Science", topic: "Physics", question: "Simple machine with a fulcrum?", choices: ["Pulley", "Lever", "Wedge", "Screw"], answer: 1 },
    { id: "G7-SCI-96", grade: 7, subject: "Science", topic: "Physics", question: "Inclined plane wrapped around a cylinder?", choices: ["Wedge", "Screw", "Level", "Pulley"], answer: 1 },
    { id: "G7-SCI-97", grade: 7, subject: "Science", topic: "Physics", question: "Ability to do work or cause change?", choices: ["Power", "Energy", "Speed", "Force"], answer: 1 },
    { id: "G7-SCI-98", grade: 7, subject: "Science", topic: "Physics", question: "Rate at which work is done?", choices: ["Energy", "Power", "Force", "Inertia"], answer: 1 },
    { id: "G7-SCI-99", grade: 7, subject: "Science", topic: "Physics", question: "Potential energy of an object based on height?", choices: ["Elastic", "Gravitational", "Chemical", "Thermal"], answer: 1 },
    { id: "G7-SCI-100", grade: 7, subject: "Science", topic: "Physics", question: "Energy stored in food or fuel?", choices: ["Thermal", "Chemical", "Light", "Sound"], answer: 1 }
];

module.exports = G7_SCIENCE_COMPLETE;
