const G9_BIOLOGY_COMPLETE = [
    // --- TOPIC 1: CELL STRUCTURE & FUNCTION (25 Questions) ---
    { id: "G9-BIO-01", grade: 9, subject: "Biology", topic: "Cells", question: "The 'powerhouse' of the cell that produces ATP is the ___.", choices: ["Nucleus", "Mitochondria", "Ribosome", "Vacuole"], answer: 1 },
    { id: "G9-BIO-02", grade: 9, subject: "Biology", topic: "Cells", question: "Which organelle is responsible for photosynthesis in plants?", choices: ["Mitochondria", "Chloroplast", "Cell Wall", "Golgi Body"], answer: 1 },
    { id: "G9-BIO-03", grade: 9, subject: "Biology", topic: "Cells", question: "The control center of the cell containing genetic material is the ___.", choices: ["Nucleus", "Cytoplasm", "Cell Membrane", "Lysosome"], answer: 0 },
    { id: "G9-BIO-04", grade: 9, subject: "Biology", topic: "Cells", question: "Which structure is found in plant cells but NOT animal cells?", choices: ["Mitochondria", "Cell Wall", "Ribosome", "Nucleus"], answer: 1 },
    { id: "G9-BIO-05", grade: 9, subject: "Biology", topic: "Cells", question: "The semi-permeable boundary of the cell is the ___.", choices: ["Nuclear Envelope", "Cell Membrane", "Cytoskeleton", "Endoplasmic Reticulum"], answer: 1 },
    { id: "G9-BIO-06", grade: 9, subject: "Biology", topic: "Cells", question: "Protein synthesis occurs at the ___.", choices: ["Mitochondria", "Ribosomes", "Vacuoles", "Centrioles"], answer: 1 },
    { id: "G9-BIO-07", grade: 9, subject: "Biology", topic: "Cells", question: "A cell that lacks a nucleus is called ___.", choices: ["Eukaryotic", "Prokaryotic", "Multicellular", "Plant cell"], answer: 1 },
    { id: "G9-BIO-08", grade: 9, subject: "Biology", topic: "Cells", question: "The movement of water across a membrane is called ___.", choices: ["Diffusion", "Osmosis", "Active Transport", "Phagocytosis"], answer: 1 },
    { id: "G9-BIO-09", grade: 9, subject: "Biology", topic: "Cells", question: "Which organelle packages and ships proteins?", choices: ["Golgi Apparatus", "Ribosome", "Nucleus", "Lysosome"], answer: 0 },
    { id: "G9-BIO-10", grade: 9, subject: "Biology", topic: "Cells", question: "The jelly-like substance that fills the cell is ___.", choices: ["Cytoplasm", "Plasma", "Water", "Chlorophyll"], answer: 0 },
    { id: "G9-BIO-11", grade: 9, subject: "Biology", topic: "Cells", question: "Lysosomes are responsible for ___.", choices: ["Energy production", "Breaking down waste", "Making DNA", "Storage"], answer: 1 },
    { id: "G9-BIO-12", grade: 9, subject: "Biology", topic: "Cells", question: "Large storage sacs, especially big in plants, are ___.", choices: ["Nuclei", "Vacuoles", "Ribosomes", "Plasmids"], answer: 1 },
    { id: "G9-BIO-13", grade: 9, subject: "Biology", topic: "Cells", question: "Which transport requires energy (ATP)?", choices: ["Passive", "Active", "Diffusion", "Facilitated"], answer: 1 },
    { id: "G9-BIO-14", grade: 9, subject: "Biology", topic: "Cells", question: "The Rough ER is 'rough' because it has ___ attached to it.", choices: ["Fats", "Ribosomes", "Sugar", "DNA"], answer: 1 },
    { id: "G9-BIO-15", grade: 9, subject: "Biology", topic: "Cells", question: "A cell with a nucleus and membrane-bound organelles is ___.", choices: ["Prokaryotic", "Eukaryotic", "Bacterial", "Viral"], answer: 1 },
    { id: "G9-BIO-16", grade: 9, subject: "Biology", topic: "Cells", question: "Chromosomes are made of ___.", choices: ["Proteins and DNA", "Sugar and Salt", "Lipids", "Water"], answer: 0 },
    { id: "G9-BIO-17", grade: 9, subject: "Biology", topic: "Cells", question: "The 'fluid mosaic model' describes the ___.", choices: ["Nucleus", "Cell Membrane", "Mitochondria", "Ribosome"], answer: 1 },
    { id: "G9-BIO-18", grade: 9, subject: "Biology", topic: "Cells", question: "Cilia and Flagella are used for ___.", choices: ["Storage", "Movement", "Digestion", "Thinking"], answer: 1 },
    { id: "G9-BIO-19", grade: 9, subject: "Biology", topic: "Cells", question: "Homeostasis is the maintenance of a stable ___.", choices: ["External environment", "Internal environment", "Population", "DNA sequence"], answer: 1 },
    { id: "G9-BIO-20", grade: 9, subject: "Biology", topic: "Cells", question: "What is the primary component of the cell membrane?", choices: ["Proteins", "Phospholipids", "Carbohydrates", "Nucleic Acids"], answer: 1 },
    { id: "G9-BIO-21", grade: 9, subject: "Biology", topic: "Cells", question: "Endocytosis is a form of ___ transport.", choices: ["Passive", "Bulk/Active", "Facilitated", "Osmotic"], answer: 1 },
    { id: "G9-BIO-22", grade: 9, subject: "Biology", topic: "Cells", question: "Cells make up tissues, and tissues make up ___.", choices: ["Atoms", "Organs", "Organisms", "Molecules"], answer: 1 },
    { id: "G9-BIO-23", grade: 9, subject: "Biology", topic: "Cells", question: "The 'suicide sacs' of the cell are ___.", choices: ["Mitochondria", "Lysosomes", "Ribosomes", "Nuclei"], answer: 1 },
    { id: "G9-BIO-24", grade: 9, subject: "Biology", topic: "Cells", question: "What provides structural support in plant cells?", choices: ["Cytoplasm", "Cell Wall", "Mitochondria", "Lysosome"], answer: 1 },
    { id: "G9-BIO-25", grade: 9, subject: "Biology", topic: "Cells", question: "Diffusion moves molecules from ___ concentration.", choices: ["Low to High", "High to Low", "Inner to Outer", "Cold to Hot"], answer: 1 },

    // --- TOPIC 2: GENETICS & DNA (25 Questions) ---
    { id: "G9-BIO-26", grade: 9, subject: "Biology", topic: "Genetics", question: "DNA's shape is described as a ___.", choices: ["Single line", "Double Helix", "Sphere", "Ladder"], answer: 1 },
    { id: "G9-BIO-27", grade: 9, subject: "Biology", topic: "Genetics", question: "The base Adenine (A) always pairs with ___ in DNA.", choices: ["Cytosine", "Thymine", "Guanine", "Uracil"], answer: 1 },
    { id: "G9-BIO-28", grade: 9, subject: "Biology", topic: "Genetics", question: "The 'Father of Genetics' who studied pea plants was ___.", choices: ["Charles Darwin", "Gregor Mendel", "Watson and Crick", "Louis Pasteur"], answer: 1 },
    { id: "G9-BIO-29", grade: 9, subject: "Biology", topic: "Genetics", question: "An organism's physical appearance is its ___.", choices: ["Genotype", "Phenotype", "Allele", "Mutation"], answer: 1 },
    { id: "G9-BIO-30", grade: 9, subject: "Biology", topic: "Genetics", question: "An organism's genetic makeup (letters) is its ___.", choices: ["Phenotype", "Genotype", "Trait", "Heredity"], answer: 1 },
    { id: "G9-BIO-31", grade: 9, subject: "Biology", topic: "Genetics", question: "A 'heterozygous' genotype looks like ___.", choices: ["TT", "Tt", "tt", "XX"], answer: 1 },
    { id: "G9-BIO-32", grade: 9, subject: "Biology", topic: "Genetics", question: "A 'homozygous recessive' genotype looks like ___.", choices: ["TT", "Tt", "tt", "tT"], answer: 2 },
    { id: "G9-BIO-33", grade: 9, subject: "Biology", topic: "Genetics", question: "Mitosis produces two ___ daughter cells.", choices: ["Identical", "Different", "Haploid", "Small"], answer: 0 },
    { id: "G9-BIO-34", grade: 9, subject: "Biology", topic: "Genetics", question: "Meiosis produces ___ daughter cells.", choices: ["2", "4", "8", "1"], answer: 1 },
    { id: "G9-BIO-35", grade: 9, subject: "Biology", topic: "Genetics", question: "Gametes (sperm and egg) have ___ the number of chromosomes.", choices: ["Double", "Half", "The same", "Zero"], answer: 1 },
    { id: "G9-BIO-36", grade: 9, subject: "Biology", topic: "Genetics", question: "Human body cells have ___ chromosomes.", choices: ["23", "46", "92", "12"], answer: 1 },
    { id: "G9-BIO-37", grade: 9, subject: "Biology", topic: "Genetics", question: "A segment of DNA that codes for a trait is a ___.", choices: ["Cell", "Gene", "Organ", "Mutation"], answer: 1 },
    { id: "G9-BIO-38", grade: 9, subject: "Biology", topic: "Genetics", question: "DNA replication happens during the ___ phase of the cell cycle.", choices: ["G1", "S", "G2", "M"], answer: 1 },
    { id: "G9-BIO-39", grade: 9, subject: "Biology", topic: "Genetics", question: "In RNA, Thymine is replaced by ___.", choices: ["Adenine", "Uracil", "Guanine", "Cytosine"], answer: 1 },
    { id: "G9-BIO-40", grade: 9, subject: "Biology", topic: "Genetics", question: "The sugar in DNA is ___.", choices: ["Ribose", "Deoxyribose", "Glucose", "Sucrose"], answer: 1 },
    { id: "G9-BIO-41", grade: 9, subject: "Biology", topic: "Genetics", question: "A mutation is a change in the ___ sequence.", choices: ["Protein", "DNA", "Carbohydrate", "Lipid"], answer: 1 },
    { id: "G9-BIO-42", grade: 9, subject: "Biology", topic: "Genetics", question: "A tool used to predict genetic crosses is a ___ Square.", choices: ["Mendel", "Punnett", "Darwin", "Biology"], answer: 1 },
    { id: "G9-BIO-43", grade: 9, subject: "Biology", topic: "Genetics", question: "Incomplete dominance results in a ___ of traits (e.g., pink flowers).", choices: ["Masking", "Blending", "Disappearance", "Doubling"], answer: 1 },
    { id: "G9-BIO-44", grade: 9, subject: "Biology", topic: "Genetics", question: "Codominance results in ___ traits showing up (e.g., spotted cows).", choices: ["Zero", "Both", "Mixed", "Hidden"], answer: 1 },
    { id: "G9-BIO-45", grade: 9, subject: "Biology", topic: "Genetics", question: "The process of making mRNA from DNA is ___.", choices: ["Translation", "Transcription", "Replication", "Mutation"], answer: 1 },
    { id: "G9-BIO-46", grade: 9, subject: "Biology", topic: "Genetics", question: "The process of making protein from mRNA is ___.", choices: ["Transcription", "Translation", "Replication", "Mitosis"], answer: 1 },
    { id: "G9-BIO-47", grade: 9, subject: "Biology", topic: "Genetics", question: "XX chromosomes usually indicate a ___.", choices: ["Male", "Female", "Mutation", "Plant"], answer: 1 },
    { id: "G9-BIO-48", grade: 9, subject: "Biology", topic: "Genetics", question: "XY chromosomes usually indicate a ___.", choices: ["Female", "Male", "Bacteria", "Virus"], answer: 1 },
    { id: "G9-BIO-49", grade: 9, subject: "Biology", topic: "Genetics", question: "Natural Selection was proposed by ___.", choices: ["Mendel", "Charles Darwin", "Newton", "Einstein"], answer: 1 },
    { id: "G9-BIO-50", grade: 9, subject: "Biology", topic: "Genetics", question: "The 'Sides' of the DNA ladder are made of Sugar and ___.", choices: ["Base", "Phosphate", "Acid", "Protein"], answer: 1 },

    // --- TOPIC 3: ECOLOGY & ECOSYSTEMS (25 Questions) ---
    { id: "G9-BIO-51", grade: 9, subject: "Biology", topic: "Ecology", question: "An organism that makes its own food is an ___.", choices: ["Heterotroph", "Autotroph", "Decomposer", "Parasite"], answer: 1 },
    { id: "G9-BIO-52", grade: 9, subject: "Biology", topic: "Ecology", question: "An organism that must eat other organisms is a ___.", choices: ["Autotroph", "Heterotroph", "Producer", "Plant"], answer: 1 },
    { id: "G9-BIO-53", grade: 9, subject: "Biology", topic: "Ecology", question: "Non-living parts of an ecosystem (like rocks, sun) are ___ factors.", choices: ["Biotic", "Abiotic", "Organic", "Dead"], answer: 1 },
    { id: "G9-BIO-54", grade: 9, subject: "Biology", topic: "Ecology", question: "Living parts of an ecosystem are ___ factors.", choices: ["Abiotic", "Biotic", "Chemical", "Physical"], answer: 1 },
    { id: "G9-BIO-55", grade: 9, subject: "Biology", topic: "Ecology", question: "The base of an energy pyramid is always made of ___.", choices: ["Consumers", "Producers", "Decomposers", "Apex predators"], answer: 1 },
    { id: "G9-BIO-56", grade: 9, subject: "Biology", topic: "Ecology", question: "Only ___% of energy is transferred to the next level in a food chain.", choices: ["50", "10", "90", "100"], answer: 1 },
    { id: "G9-BIO-57", grade: 9, subject: "Biology", topic: "Ecology", question: "A symbiosis where both organisms benefit is ___.", choices: ["Commensalism", "Mutualism", "Parasitism", "Competition"], answer: 1 },
    { id: "G9-BIO-58", grade: 9, subject: "Biology", topic: "Ecology", question: "A symbiosis where one benefits and the other is harmed is ___.", choices: ["Mutualism", "Parasitism", "Commensalism", "Predation"], answer: 1 },
    { id: "G9-BIO-59", grade: 9, subject: "Biology", topic: "Ecology", question: "The maximum population an environment can support is ___ capacity.", choices: ["Holding", "Carrying", "Support", "Growth"], answer: 1 },
    { id: "G9-BIO-60", grade: 9, subject: "Biology", topic: "Ecology", question: "Organisms that break down dead matter are ___.", choices: ["Producers", "Decomposers", "Herbivores", "Carnivores"], answer: 1 },
    { id: "G9-BIO-61", grade: 9, subject: "Biology", topic: "Ecology", question: "A linear sequence of 'who eats whom' is a food ___.", choices: ["Web", "Chain", "Pyramid", "Circle"], answer: 1 },
    { id: "G9-BIO-62", grade: 9, subject: "Biology", topic: "Ecology", question: "Overlapping food chains in an ecosystem make a food ___.", choices: ["Chain", "Web", "Map", "Net"], answer: 1 },
    { id: "G9-BIO-63", grade: 9, subject: "Biology", topic: "Ecology", question: "Biodiversity refers to the ___ of species in an area.", choices: ["Number", "Variety", "Size", "Age"], answer: 1 },
    { id: "G9-BIO-64", grade: 9, subject: "Biology", topic: "Ecology", question: "Primary succession begins in an area with no ___.", choices: ["Water", "Soil", "Air", "Light"], answer: 1 },
    { id: "G9-BIO-65", grade: 9, subject: "Biology", topic: "Ecology", question: "An animal that eats only plants is a ___.", choices: ["Carnivore", "Herbivore", "Omnivore", "Decomposer"], answer: 1 },
    { id: "G9-BIO-66", grade: 9, subject: "Biology", topic: "Ecology", question: "An animal that eats both plants and animals is an ___.", choices: ["Herbivore", "Omnivore", "Carnivore", "Autotroph"], answer: 1 },
    { id: "G9-BIO-67", grade: 9, subject: "Biology", topic: "Ecology", question: "Global warming is linked to an increase in ___ gas.", choices: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"], answer: 1 },
    { id: "G9-BIO-68", grade: 9, subject: "Biology", topic: "Ecology", question: "The place where an organism lives is its ___.", choices: ["Niche", "Habitat", "Biome", "Community"], answer: 1 },
    { id: "G9-BIO-69", grade: 9, subject: "Biology", topic: "Ecology", question: "The role an organism plays in its environment is its ___.", choices: ["Habitat", "Niche", "Job", "Status"], answer: 1 },
    { id: "G9-BIO-70", grade: 9, subject: "Biology", topic: "Ecology", question: "Plants release water into the atmosphere through ___.", choices: ["Respiration", "Transpiration", "Condensation", "Precipitation"], answer: 1 },
    { id: "G9-BIO-71", grade: 9, subject: "Biology", topic: "Ecology", question: "Which cycle involves nitrogen-fixing bacteria?", choices: ["Water", "Nitrogen", "Carbon", "Rock"], answer: 1 },
    { id: "G9-BIO-72", grade: 9, subject: "Biology", topic: "Ecology", question: "A large geographic area with similar climate and animals is a ___.", choices: ["Habitat", "Biome", "Community", "Population"], answer: 1 },
    { id: "G9-BIO-73", grade: 9, subject: "Biology", topic: "Ecology", question: "The Tundra is characterized by ___ soil.", choices: ["Dry", "Permafrost", "Fertile", "Sandy"], answer: 1 },
    { id: "G9-BIO-74", grade: 9, subject: "Biology", topic: "Ecology", question: "Competition occurs when organisms try to use the same ___.", choices: ["Genes", "Resources", "Cells", "Offspring"], answer: 1 },
    { id: "G9-BIO-75", grade: 9, subject: "Biology", topic: "Ecology", question: "Limiting factors ___ the growth of a population.", choices: ["Speed up", "Stop or Decrease", "Help", "Change"], answer: 1 },

    // --- TOPIC 4: EVOLUTION & HUMAN SYSTEMS (25 Questions) ---
    { id: "G9-BIO-76", grade: 9, subject: "Biology", topic: "Evolution", question: "Survival of the fittest means the best ___ survive.", choices: ["Strongest", "Adapted", "Fastest", "Biggest"], answer: 1 },
    { id: "G9-BIO-77", grade: 9, subject: "Biology", topic: "Evolution", question: "Traces of long-dead organisms are ___.", choices: ["Genes", "Fossils", "Cells", "Atoms"], answer: 1 },
    { id: "G9-BIO-78", grade: 9, subject: "Biology", topic: "Evolution", question: "Similar structures in different species (like bone structure) are ___ structures.", choices: ["Analogous", "Homologous", "Vestigial", "Fake"], answer: 1 },
    { id: "G9-BIO-79", grade: 9, subject: "Biology", topic: "Evolution", question: "A structure that is no longer used (like the human appendix) is ___.", choices: ["Homologous", "Vestigial", "Analogous", "Primary"], answer: 1 },
    { id: "G9-BIO-80", grade: 9, subject: "Biology", topic: "Evolution", question: "The process of species changing over time is ___.", choices: ["Genetics", "Evolution", "Ecology", "Mitosis"], answer: 1 },
    { id: "G9-BIO-81", grade: 9, subject: "Biology", topic: "Evolution", question: "Speciation is the formation of a new ___.", choices: ["Cell", "Species", "Organ", "Planet"], answer: 1 },
    { id: "G9-BIO-82", grade: 9, subject: "Biology", topic: "Evolution", question: "An adaptation is a trait that helps an organism ___.", choices: ["Die", "Survive and Reproduce", "Grow bigger", "Move faster"], answer: 1 },
    { id: "G9-BIO-83", grade: 9, subject: "Biology", topic: "Systems", question: "The system that filters blood and removes liquid waste is ___.", choices: ["Digestive", "Excretory/Urinary", "Respiratory", "Nervous"], answer: 1 },
    { id: "G9-BIO-84", grade: 9, subject: "Biology", topic: "Systems", question: "The system responsible for gas exchange (O2 and CO2) is ___.", choices: ["Circulatory", "Respiratory", "Digestive", "Skeletal"], answer: 1 },
    { id: "G9-BIO-85", grade: 9, subject: "Biology", topic: "Systems", question: "The 'Master Control' system of the body is the ___.", choices: ["Endocrine", "Nervous", "Immune", "Muscular"], answer: 1 },
    { id: "G9-BIO-86", grade: 9, subject: "Biology", topic: "Systems", question: "Which system transports nutrients and oxygen to cells?", choices: ["Respiratory", "Circulatory", "Nervous", "Integumentary"], answer: 1 },
    { id: "G9-BIO-87", grade: 9, subject: "Biology", topic: "Evolution", question: "Artificial Selection is done by ___.", choices: ["Nature", "Humans", "Animals", "Luck"], answer: 1 },
    { id: "G9-BIO-88", grade: 9, subject: "Biology", topic: "Systems", question: "The body's first line of defense against infection is the ___.", choices: ["Heart", "Skin (Integumentary)", "Brain", "Lungs"], answer: 1 },
    { id: "G9-BIO-89", grade: 9, subject: "Biology", topic: "Evolution", question: "Convergent evolution creates ___ structures (similar function, different origin).", choices: ["Homologous", "Analogous", "Vestigial", "Ancient"], answer: 1 },
    { id: "G9-BIO-90", grade: 9, subject: "Biology", topic: "Systems", question: "Hormones are produced by the ___ system.", choices: ["Nervous", "Endocrine", "Excretory", "Digestive"], answer: 1 },
    { id: "G9-BIO-91", grade: 9, subject: "Biology", topic: "Systems", question: "The basic unit of the nervous system is the ___.", choices: ["Neuron", "Nephron", "Cell", "Muscle"], answer: 0 },
    { id: "G9-BIO-92", grade: 9, subject: "Biology", topic: "Systems", question: "White blood cells are part of the ___ system.", choices: ["Nervous", "Immune", "Endocrine", "Skeletal"], answer: 1 },
    { id: "G9-BIO-93", grade: 9, subject: "Biology", topic: "Systems", question: "The point where two bones meet is a ___.", choices: ["Muscle", "Joint", "Tendon", "Ligament"], answer: 1 },
    { id: "G9-BIO-94", grade: 9, subject: "Biology", topic: "Evolution", question: "Gradualism is the idea that evolution happens ___.", choices: ["Quickly", "Slowly and steadily", "In bursts", "Not at all"], answer: 1 },
    { id: "G9-BIO-95", grade: 9, subject: "Biology", topic: "Systems", question: "The small air sacs in the lungs are called ___.", choices: ["Bronchi", "Alveoli", "Villi", "Capillaries"], answer: 1 },
    { id: "G9-BIO-96", grade: 9, subject: "Biology", topic: "Systems", question: "Digestion starts in the ___.", choices: ["Stomach", "Mouth", "Esophagus", "Small Intestine"], answer: 1 },
    { id: "G9-BIO-97", grade: 9, subject: "Biology", topic: "Systems", question: "Most nutrient absorption happens in the ___.", choices: ["Stomach", "Small Intestine", "Large Intestine", "Liver"], answer: 1 },
    { id: "G9-BIO-98", grade: 9, subject: "Biology", topic: "Evolution", question: "A phylogenetic tree shows ___.", choices: ["How tall a tree grows", "Evolutionary relationships", "Cell parts", "Punnett squares"], answer: 1 },
    { id: "G9-BIO-99", grade: 9, subject: "Biology", topic: "Evolution", question: "Gene flow is the movement of genes ___ populations.", choices: ["Within", "Between", "Against", "Out of"], answer: 1 },
    { id: "G9-BIO-100", grade: 9, subject: "Biology", topic: "Evolution", question: "Genetic drift is a ___ change in allele frequency.", choices: ["Planned", "Random", "Certain", "Slow"], answer: 1 }
];

module.exports = G9_BIOLOGY_COMPLETE;
