const G9_ELA_COMPLETE = [
    // --- TOPIC 1: LITERARY ELEMENTS & DEVICES (25 Questions) ---
    { id: "G9-ELA-01", grade: 9, subject: "ELA", topic: "Plot", question: "The beginning of a story that provides background information is the ___.", choices: ["Climax", "Exposition", "Resolution", "Rising Action"], answer: 1 },
    { id: "G9-ELA-02", grade: 9, subject: "ELA", topic: "Literary Devices", question: "A 'flashback' is a scene that ___.", choices: ["Predicts the future", "Interrupts the sequence to show a past event", "Describes the setting", "Ends the story"], answer: 1 },
    { id: "G9-ELA-03", grade: 9, subject: "ELA", topic: "Literary Devices", question: "The use of hints or clues to suggest what will happen later is ___.", choices: ["Flashback", "Foreshadowing", "Irony", "Imagery"], answer: 1 },
    { id: "G9-ELA-04", grade: 9, subject: "ELA", topic: "Irony", question: "When a character says one thing but means the opposite, it is ___ irony.", choices: ["Situational", "Verbal", "Dramatic", "Structural"], answer: 1 },
    { id: "G9-ELA-05", grade: 9, subject: "ELA", topic: "Irony", question: "When the audience knows something the characters do not, it is ___ irony.", choices: ["Verbal", "Situational", "Dramatic", "Cosmic"], answer: 2 },
    { id: "G9-ELA-06", grade: 9, subject: "ELA", topic: "Point of View", question: "A narrator who is a character in the story and uses 'I' is ___ person.", choices: ["First", "Second", "Third Limited", "Third Omniscient"], answer: 0 },
    { id: "G9-ELA-07", grade: 9, subject: "ELA", topic: "Literary Devices", question: "An 'Oxymoron' is a figure of speech that ___.", choices: ["Exaggerates", "Combines contradictory terms", "Repeats sounds", "Compares using 'like'"], answer: 1 },
    { id: "G9-ELA-08", grade: 9, subject: "ELA", topic: "Theme", question: "A 'Theme' is best described as ___.", choices: ["The plot summary", "The subject of the book", "The universal truth or message of the work", "The main character"], answer: 2 },
    { id: "G9-ELA-09", grade: 9, subject: "ELA", topic: "Conflict", question: "A struggle within a character's own mind is ___ conflict.", choices: ["Man vs. Man", "Man vs. Nature", "Internal", "External"], answer: 2 },
    { id: "G9-ELA-10", grade: 9, subject: "ELA", topic: "Literary Devices", question: "A 'Symbol' is an object that ___.", choices: ["Is only literal", "Stands for an abstract idea", "Rhymes with the title", "Is the main character"], answer: 1 },
    { id: "G9-ELA-11", grade: 9, subject: "ELA", topic: "Structure", question: "Starting a story in the middle of the action is called ___.", choices: ["In media res", "Deus ex machina", "Frame narrative", "Epilogue"], answer: 0 },
    { id: "G9-ELA-12", grade: 9, subject: "ELA", topic: "Character", question: "A 'Protagonist' is the ___.", choices: ["Villain", "Narrator", "Main character/Hero", "Sidekick"], answer: 2 },
    { id: "G9-ELA-13", grade: 9, subject: "ELA", topic: "Character", question: "A character who changes significantly throughout the story is ___.", choices: ["Static", "Flat", "Dynamic", "Stock"], answer: 2 },
    { id: "G9-ELA-14", grade: 9, subject: "ELA", topic: "Character", question: "A character who stays the same throughout the story is ___.", choices: ["Dynamic", "Static", "Round", "Protagonist"], answer: 1 },
    { id: "G9-ELA-15", grade: 9, subject: "ELA", topic: "Literary Devices", question: "Hyperbole is an extreme ___.", choices: ["Understatement", "Exaggeration", "Comparison", "Definition"], answer: 1 },
    { id: "G9-ELA-16", grade: 9, subject: "ELA", topic: "Imagery", question: "Imagery appeals primarily to the reader's ___.", choices: ["Logic", "Five senses", "Emotions", "Vocabulary"], answer: 1 },
    { id: "G9-ELA-17", grade: 9, subject: "ELA", topic: "Literary Devices", question: "A 'Metaphor' compares two things by ___.", choices: ["Using 'like' or 'as'", "Stating one thing IS another", "Exaggerating", "Personifying"], answer: 1 },
    { id: "G9-ELA-18", grade: 9, subject: "ELA", topic: "Literary Devices", question: "Giving human qualities to non-human things is ___.", choices: ["Metaphor", "Simile", "Personification", "Alliteration"], answer: 2 },
    { id: "G9-ELA-19", grade: 9, subject: "ELA", topic: "Tone", question: "Tone is the ___.", choices: ["Atmosphere of the story", "Writer's attitude toward the subject", "Reader's feelings", "Volume of the narrator"], answer: 1 },
    { id: "G9-ELA-20", grade: 9, subject: "ELA", topic: "Mood", question: "Mood is the ___.", choices: ["Author's attitude", "Emotional atmosphere created for the reader", "Dictionary definition", "Plot structure"], answer: 1 },
    { id: "G9-ELA-21", grade: 9, subject: "ELA", topic: "Literary Devices", question: "A 'Paradox' is a statement that ___.", choices: ["Is always false", "Seems contradictory but may be true", "Is a funny joke", "Is a short story"], answer: 1 },
    { id: "G9-ELA-22", grade: 9, subject: "ELA", topic: "Structure", question: "A 'Sonnet' is a poem consisting of ___ lines.", choices: ["10", "12", "14", "16"], answer: 2 },
    { id: "G9-ELA-23", grade: 9, subject: "ELA", topic: "Literary Devices", question: "An 'Allusion' is a reference to ___.", choices: ["A made-up word", "Another work of literature, person, or event", "The future", "A hallucination"], answer: 1 },
    { id: "G9-ELA-24", grade: 9, subject: "ELA", topic: "Conflict", question: "Man vs. Society is an example of ___ conflict.", choices: ["Internal", "External", "Psychological", "Non-existent"], answer: 1 },
    { id: "G9-ELA-25", grade: 9, subject: "ELA", topic: "Structure", question: "The 'Climax' of a story is often referred to as the ___.", choices: ["Start", "Turning point", "Ending", "Boring part"], answer: 1 },

    // --- TOPIC 2: RHETORIC & PERSUASION (25 Questions) ---
    { id: "G9-ELA-26", grade: 9, subject: "ELA", topic: "Rhetoric", question: "Appealing to an audience's emotions is ___.", choices: ["Ethos", "Logos", "Pathos", "Kairos"], answer: 2 },
    { id: "G9-ELA-27", grade: 9, subject: "ELA", topic: "Rhetoric", question: "Appealing to logic and reason is ___.", choices: ["Pathos", "Ethos", "Logos", "Diction"], answer: 2 },
    { id: "G9-ELA-28", grade: 9, subject: "ELA", topic: "Rhetoric", question: "Establishing credibility or character is ___.", choices: ["Logos", "Ethos", "Pathos", "Syntax"], answer: 1 },
    { id: "G9-ELA-29", grade: 9, subject: "ELA", topic: "Rhetoric", question: "A 'Rhetorical Question' is asked to ___.", choices: ["Get an answer", "Make a point", "Confuse the reader", "Start a fight"], answer: 1 },
    { id: "G9-ELA-30", grade: 9, subject: "ELA", topic: "Writing", question: "A 'Thesis Statement' should be found in the ___.", choices: ["Conclusion", "Introduction", "Body Paragraph 2", "Works Cited"], answer: 1 },
    { id: "G9-ELA-31", grade: 9, subject: "ELA", topic: "Argument", question: "A 'Counterclaim' is used to ___.", choices: ["Support the main point", "Acknowledge the opposing view", "End the essay", "Define a word"], answer: 1 },
    { id: "G9-ELA-32", grade: 9, subject: "ELA", topic: "Rhetoric", question: "Diction refers to a writer's ___.", choices: ["Punctuation", "Word choice", "Sentence length", "Spelling"], answer: 1 },
    { id: "G9-ELA-33", grade: 9, subject: "ELA", topic: "Rhetoric", question: "Syntax refers to ___.", choices: ["Vocabulary", "Sentence structure/arrangement", "Moral behavior", "Rhyme scheme"], answer: 1 },
    { id: "G9-ELA-34", grade: 9, subject: "ELA", topic: "Writing", question: "Parallelism is the repetition of ___.", choices: ["Similar grammatical structures", "The same word 100 times", "Vowel sounds", "The ending of a story"], answer: 0 },
    { id: "G9-ELA-35", grade: 9, subject: "ELA", topic: "Argument", question: "A 'Rebuttal' follows a counterclaim to ___.", choices: ["Agree with it", "Prove it wrong or weak", "Introduce the author", "Ask a question"], answer: 1 },
    { id: "G9-ELA-36", grade: 9, subject: "ELA", topic: "Logic", question: "A 'Logical Fallacy' is an error in ___.", choices: ["Spelling", "Reasoning", "Formatting", "Pronunciation"], answer: 1 },
    { id: "G9-ELA-37", grade: 9, subject: "ELA", topic: "Rhetoric", question: "An 'Anecdote' is a ___.", choices: ["Medicine", "Short, personal story used as evidence", "Long poem", "Type of irony"], answer: 1 },
    { id: "G9-ELA-38", grade: 9, subject: "ELA", topic: "Rhetoric", question: "Using 'statistics' in an essay is an appeal to ___.", choices: ["Pathos", "Ethos", "Logos", "Imagery"], answer: 2 },
    { id: "G9-ELA-39", grade: 9, subject: "ELA", topic: "Writing", question: "The 'Audience' of a text is ___.", choices: ["The author", "The people intended to read it", "The characters", "The publisher"], answer: 1 },
    { id: "G9-ELA-40", grade: 9, subject: "ELA", topic: "Rhetoric", question: "Denotation is the ___ meaning of a word.", choices: ["Emotional", "Literal/Dictionary", "Slang", "Hidden"], answer: 1 },
    { id: "G9-ELA-41", grade: 9, subject: "ELA", topic: "Rhetoric", question: "Connotation is the ___ associated with a word.", choices: ["Spelling", "Emotional feeling", "Definition", "History"], answer: 1 },
    { id: "G9-ELA-42", grade: 9, subject: "ELA", topic: "Logic", question: "Ad Hominem is a fallacy that attacks ___.", choices: ["The argument", "The person making the argument", "A straw man", "The logic"], answer: 1 },
    { id: "G9-ELA-43", grade: 9, subject: "ELA", topic: "Logic", question: "A 'Slippery Slope' fallacy suggests ___.", choices: ["One small step leads to a chain of events", "Everyone is doing it", "The conclusion is the premise", "Two things are the same"], answer: 0 },
    { id: "G9-ELA-44", grade: 9, subject: "ELA", topic: "Writing", question: "The 'Purpose' of an expository text is to ___.", choices: ["Persuade", "Inform or explain", "Entertain", "Tell a story"], answer: 1 },
    { id: "G9-ELA-45", grade: 9, subject: "ELA", topic: "Writing", question: "The 'Purpose' of a narrative is to ___.", choices: ["Explain a process", "Tell a story", "Argue a point", "Analyze data"], answer: 1 },
    { id: "G9-ELA-46", grade: 9, subject: "ELA", topic: "Writing", question: "A 'Transition' word helps with ___.", choices: ["Vocabulary", "Flow and cohesion", "Spelling", "Word count"], answer: 1 },
    { id: "G9-ELA-47", grade: 9, subject: "ELA", topic: "Rhetoric", question: "Juxtaposition is placing two things side-by-side to ___.", choices: ["Make them match", "Highlight their differences", "Hide them", "Combine them"], answer: 1 },
    { id: "G9-ELA-48", grade: 9, subject: "ELA", topic: "Writing", question: "A 'Formal' tone avoids ___.", choices: ["Complex words", "Slang and contractions", "Facts", "Long sentences"], answer: 1 },
    { id: "G9-ELA-49", grade: 9, subject: "ELA", topic: "Logic", question: "The 'Bandwagon' fallacy appeals to ___.", choices: ["Logic", "The desire to follow the crowd", "Expertise", "Fear"], answer: 1 },
    { id: "G9-ELA-50", grade: 9, subject: "ELA", topic: "Rhetoric", question: "The 'Exigence' is the ___.", choices: ["Conclusion", "Spark or event that prompts the writing", "Author's name", "Main character"], answer: 1 },

    // --- TOPIC 3: GRAMMAR & CONVENTIONS (25 Questions) ---
    { id: "G9-ELA-51", grade: 9, subject: "ELA", topic: "Grammar", question: "A semicolon is used to ___.", choices: ["End a sentence", "Join two independent clauses", "Start a list", "Replace a comma"], answer: 1 },
    { id: "G9-ELA-52", grade: 9, subject: "ELA", topic: "Grammar", question: "A colon is used to ___.", choices: ["Join sentences", "Introduce a list or explanation", "Show emotion", "Separate adjectives"], answer: 1 },
    { id: "G9-ELA-53", grade: 9, subject: "ELA", topic: "Grammar", question: "Active voice: 'The chef prepared the meal.' Who is the subject?", choices: ["The meal", "The chef", "The kitchen", "The preparation"], answer: 1 },
    { id: "G9-ELA-54", grade: 9, subject: "ELA", topic: "Grammar", question: "Passive voice: 'The meal was prepared by the chef.' The subject is ___.", choices: ["The chef", "The meal", "Prepared", "By"], answer: 1 },
    { id: "G9-ELA-55", grade: 9, subject: "ELA", topic: "Grammar", question: "A 'clause' that cannot stand alone as a sentence is ___.", choices: ["Independent", "Dependent", "Relative", "Transitive"], answer: 1 },
    { id: "G9-ELA-56", grade: 9, subject: "ELA", topic: "Grammar", question: "A 'run-on' sentence occurs when ___.", choices: ["A sentence is very long", "Two independent clauses are joined improperly", "A sentence lacks a verb", "A sentence is too fast"], answer: 1 },
    { id: "G9-ELA-57", grade: 9, subject: "ELA", topic: "Grammar", question: "Which is a 'Complex' sentence?", choices: ["I like pie.", "I like pie and I like cake.", "Because I was hungry, I ate pie.", "Pie is good."], answer: 2 },
    { id: "G9-ELA-58", grade: 9, subject: "ELA", topic: "Grammar", question: "Identify the 'Gerund': 'Running is my favorite hobby.'", choices: ["Running", "is", "favorite", "hobby"], answer: 0 },
    { id: "G9-ELA-59", grade: 9, subject: "ELA", topic: "Grammar", question: "An 'Appositive' phrase ___.", choices: ["Renames a noun next to it", "Starts a sentence", "Is always a verb", "Shows action"], answer: 0 },
    { id: "G9-ELA-60", grade: 9, subject: "ELA", topic: "Grammar", question: "Subject-Verb Agreement: 'The group of students ___ arriving.'", choices: ["is", "are", "were", "be"], answer: 0 },
    { id: "G9-ELA-61", grade: 9, subject: "ELA", topic: "Grammar", question: "The 'Subject' of a sentence ___.", choices: ["Receives the action", "Performs the action", "Is always a noun", "Ends the sentence"], answer: 1 },
    { id: "G9-ELA-62", grade: 9, subject: "ELA", topic: "Grammar", question: "A 'Participle' is a verb form used as a(n) ___.", choices: ["Noun", "Adjective", "Adverb", "Conjunction"], answer: 1 },
    { id: "G9-ELA-63", grade: 9, subject: "ELA", topic: "Grammar", question: "Which pronoun is 'Objective'?", choices: ["I", "Me", "He", "They"], answer: 1 },
    { id: "G9-ELA-64", grade: 9, subject: "ELA", topic: "Grammar", question: "The 'Antecedent' is the word that a ___ replaces.", choices: ["Verb", "Pronoun", "Adjective", "Preposition"], answer: 1 },
    { id: "G9-ELA-65", grade: 9, subject: "ELA", topic: "Grammar", question: "Parallel structure: 'I like hiking, swimming, and ___.'", choices: ["to run", "running", "ran", "a runner"], answer: 1 },
    { id: "G9-ELA-66", grade: 9, subject: "ELA", topic: "Grammar", question: "Identify the preposition: 'The book is on the table.'", choices: ["book", "is", "on", "table"], answer: 2 },
    { id: "G9-ELA-67", grade: 9, subject: "ELA", topic: "Grammar", question: "A 'Dangling Modifier' occurs when a modifier ___.", choices: ["Is at the end", "Doesn't clearly describe any word in the sentence", "Is too long", "Is a verb"], answer: 1 },
    { id: "G9-ELA-68", grade: 9, subject: "ELA", topic: "Grammar", question: "Which punctuation shows an omission of words?", choices: ["Dash", "Ellipsis (...)", "Hyphen", "Parentheses"], answer: 1 },
    { id: "G9-ELA-69", grade: 9, subject: "ELA", topic: "Grammar", question: "The 'Mood' of a verb that states a fact is ___.", choices: ["Imperative", "Indicative", "Subjunctive", "Conditional"], answer: 1 },
    { id: "G9-ELA-70", grade: 9, subject: "ELA", topic: "Grammar", question: "The 'Mood' of a verb that expresses a wish/contrary to fact is ___.", choices: ["Indicative", "Subjunctive", "Interrogative", "Imperative"], answer: 1 },
    { id: "G9-ELA-71", grade: 9, subject: "ELA", topic: "Grammar", question: "Which is a 'Compound-Complex' sentence?", choices: ["I ran.", "I ran and he walked.", "Since it rained, I stayed in, but he went out.", "He went out."], answer: 2 },
    { id: "G9-ELA-72", grade: 9, subject: "ELA", topic: "Grammar", question: "Oxford Comma is used ___.", choices: ["Before 'and' in a list", "At the end of a quote", "In the date", "Between two names"], answer: 0 },
    { id: "G9-ELA-73", grade: 9, subject: "ELA", topic: "Grammar", question: "What is the 'Object of the Preposition' in 'after the game'?", choices: ["after", "the", "game"], answer: 2 },
    { id: "G9-ELA-74", grade: 9, subject: "ELA", topic: "Grammar", question: "A 'Transitive' verb requires a ___.", choices: ["Direct Object", "Comma", "Subject", "Adverb"], answer: 0 },
    { id: "G9-ELA-75", grade: 9, subject: "ELA", topic: "Grammar", question: "Possessive form of 'students' (plural)?", choices: ["student's", "students's", "students'", "studentes"], answer: 2 },

    // --- TOPIC 4: VOCABULARY & ANALYSIS (25 Questions) ---
    { id: "G9-ELA-76", grade: 9, subject: "ELA", topic: "Vocabulary", question: "Root 'Bene' means ___.", choices: ["Bad", "Good", "Small", "Earth"], answer: 1 },
    { id: "G9-ELA-77", grade: 9, subject: "ELA", topic: "Vocabulary", question: "Root 'Mal' means ___.", choices: ["Good", "Bad", "Sea", "Hand"], answer: 1 },
    { id: "G9-ELA-78", grade: 9, subject: "ELA", topic: "Analysis", question: "To 'Infer' means to ___.", choices: ["Directly state", "Draw a conclusion based on evidence", "Ignore the text", "Summarize"], answer: 1 },
    { id: "G9-ELA-79", grade: 9, subject: "ELA", topic: "Vocabulary", question: "Suffix '-logy' means ___.", choices: ["Fear of", "Study of", "Full of", "Person who"], answer: 1 },
    { id: "G9-ELA-80", grade: 9, subject: "ELA", topic: "Analysis", question: "An 'Objective Summary' should exclude ___.", choices: ["Main points", "Personal opinions", "Key characters", "The setting"], answer: 1 },
    { id: "G9-ELA-81", grade: 9, subject: "ELA", topic: "Vocabulary", question: "Prefix 'Omni-' means ___.", choices: ["One", "Many", "All", "Small"], answer: 2 },
    { id: "G9-ELA-82", grade: 9, subject: "ELA", topic: "Analysis", question: "A 'Primary Source' is ___.", choices: ["A textbook", "A first-hand account or original document", "A Wikipedia page", "A movie review"], answer: 1 },
    { id: "G9-ELA-83", grade: 9, subject: "ELA", topic: "Vocabulary", question: "Root 'Bio' means ___.", choices: ["Life", "Earth", "Book", "Time"], answer: 0 },
    { id: "G9-ELA-84", grade: 9, subject: "ELA", topic: "Vocabulary", question: "Root 'Chron' means ___.", choices: ["Color", "Time", "Sound", "Power"], answer: 1 },
    { id: "G9-ELA-85", grade: 9, subject: "ELA", topic: "Analysis", question: "Implicit information is ___.", choices: ["Directly stated", "Suggested or hinted at", "Irrelevant", "False"], answer: 1 },
    { id: "G9-ELA-86", grade: 9, subject: "ELA", topic: "Vocabulary", question: "Root 'Path' means ___.", choices: ["Road", "Feeling/Disease", "Light", "Voice"], answer: 1 },
    { id: "G9-ELA-87", grade: 9, subject: "ELA", topic: "Analysis", question: "A 'Claim' is ___.", choices: ["The final word of a book", "The writer's position on an issue", "A list of sources", "A character's name"], answer: 1 },
    { id: "G9-ELA-88", grade: 9, subject: "ELA", topic: "Vocabulary", question: "Prefix 'Poly-' means ___.", choices: ["One", "Two", "Many", "Small"], answer: 2 },
    { id: "G9-ELA-89", grade: 9, subject: "ELA", topic: "Analysis", question: "Relevant evidence is evidence that ___.", choices: ["Is funny", "Directly supports the claim", "Is long", "Was written recently"], answer: 1 },
    { id: "G9-ELA-90", grade: 9, subject: "ELA", topic: "Vocabulary", question: "Root 'Dict' means ___.", choices: ["To see", "To say/speak", "To lead", "To write"], answer: 1 },
    { id: "G9-ELA-91", grade: 9, subject: "ELA", topic: "Vocabulary", question: "Root 'Spec' means ___.", choices: ["To hear", "To look/see", "To build", "To carry"], answer: 1 },
    { id: "G9-ELA-92", grade: 9, subject: "ELA", topic: "Analysis", question: "Analyzing 'Style' involves looking at ___.", choices: ["Only the plot", "Word choice, tone, and syntax", "The font", "The cover art"], answer: 1 },
    { id: "G9-ELA-93", grade: 9, subject: "ELA", topic: "Vocabulary", question: "Root 'Graph' means ___.", choices: ["To see", "To write", "To hear", "To speak"], answer: 1 },
    { id: "G9-ELA-94", grade: 9, subject: "ELA", topic: "Vocabulary", question: "Prefix 'Sub-' means ___.", choices: ["Above", "Below", "Against", "With"], answer: 1 },
    { id: "G9-ELA-95", grade: 9, subject: "ELA", topic: "Vocabulary", question: "Suffix '-ism' often denotes a ___.", choices: ["Verb", "Belief, practice, or system", "Small object", "Place"], answer: 1 },
    { id: "G9-ELA-96", grade: 9, subject: "ELA", topic: "Analysis", question: "A 'Warrant' in an argument ___.", choices: ["Arrests the reader", "Explains how the evidence supports the claim", "Is a type of evidence", "Ends the paper"], answer: 1 },
    { id: "G9-ELA-97", grade: 9, subject: "ELA", topic: "Vocabulary", question: "Root 'Mort' means ___.", choices: ["Life", "Death", "Mountain", "Large"], answer: 1 },
    { id: "G9-ELA-98", grade: 9, subject: "ELA", topic: "Analysis", question: "Irony is often used to create ___.", choices: ["Humor or suspense", "Boredom", "Lists", "Spelling errors"], answer: 0 },
    { id: "G9-ELA-99", grade: 9, subject: "ELA", topic: "Vocabulary", question: "Root 'Phil' means ___.", choices: ["Fear", "Love", "Hate", "Wisdom"], answer: 1 },
    { id: "G9-ELA-100", grade: 9, subject: "ELA", topic: "Analysis", question: "Synthesis means ___.", choices: ["Breaking apart", "Combining different parts into a whole", "Summarizing", "Copying"], answer: 1 }
];

module.exports = G9_ELA_COMPLETE;
