const G9_GEOGRAPHY_COMPLETE = [
    // --- TOPIC 1: THE TOOLS OF GEOGRAPHY (25 Questions) ---
    { id: "G9-GEO-01", grade: 9, subject: "Geography", topic: "Basics", question: "Lines that run North to South but measure East to West are lines of ___.", choices: ["Latitude", "Longitude", "Equator", "Altitude"], answer: 1 },
    { id: "G9-GEO-02", grade: 9, subject: "Geography", topic: "Basics", question: "Lines that run East to West but measure North to South are lines of ___.", choices: ["Longitude", "Latitude", "Prime Meridian", "Isotherms"], answer: 1 },
    { id: "G9-GEO-03", grade: 9, subject: "Geography", topic: "Basics", question: "The 0° line of Latitude is the ___.", choices: ["Prime Meridian", "International Date Line", "Equator", "Tropic of Cancer"], answer: 2 },
    { id: "G9-GEO-04", grade: 9, subject: "Geography", topic: "Basics", question: "The 0° line of Longitude is the ___.", choices: ["Equator", "Prime Meridian", "North Pole", "Tropic of Capricorn"], answer: 1 },
    { id: "G9-GEO-05", grade: 9, subject: "Geography", topic: "Themes", question: "Which theme of geography describes the characteristics that make a location unique?", choices: ["Location", "Place", "Movement", "Region"], answer: 1 },
    { id: "G9-GEO-06", grade: 9, subject: "Geography", topic: "Themes", question: "Which theme of geography looks at how people, goods, and ideas get around?", choices: ["Region", "Movement", "Place", "HEI"], answer: 1 },
    { id: "G9-GEO-07", grade: 9, subject: "Geography", topic: "Themes", question: "A GPS coordinate (34°N, 118°W) is an example of ___ location.", choices: ["Relative", "Absolute", "Approximate", "Regional"], answer: 1 },
    { id: "G9-GEO-08", grade: 9, subject: "Geography", topic: "Maps", question: "What map feature explains the symbols used on the map?", choices: ["Scale", "Compass Rose", "Legend/Key", "Title"], answer: 2 },
    { id: "G9-GEO-09", grade: 9, subject: "Geography", topic: "Maps", question: "A map that shows mountains, rivers, and elevation is a ___ map.", choices: ["Political", "Physical", "Thematic", "Road"], answer: 1 },
    { id: "G9-GEO-10", grade: 9, subject: "Geography", topic: "Maps", question: "A map that shows boundaries, countries, and cities is a ___ map.", choices: ["Physical", "Political", "Topographic", "Climate"], answer: 1 },
    { id: "G9-GEO-11", grade: 9, subject: "Geography", topic: "Basics", question: "Which hemisphere is located north of the Equator?", choices: ["Eastern", "Western", "Northern", "Southern"], answer: 2 },
    { id: "G9-GEO-12", grade: 9, subject: "Geography", topic: "Maps", question: "What is the primary problem with all flat maps of the Earth?", choices: ["They are too small", "Distortion of size/shape", "Lack of color", "Inaccurate names"], answer: 1 },
    { id: "G9-GEO-13", grade: 9, subject: "Geography", topic: "Themes", question: "A group of places with at least one common characteristic is a ___.", choices: ["Place", "Region", "Site", "Landscape"], answer: 1 },
    { id: "G9-GEO-14", grade: 9, subject: "Geography", topic: "Basics", question: "The exact spot where something is found on Earth is ___.", choices: ["Relative Location", "Absolute Location", "Situation", "Site"], answer: 1 },
    { id: "G9-GEO-15", grade: 9, subject: "Geography", topic: "Basics", question: "The relationship between a distance on a map and the actual distance is ___.", choices: ["Legend", "Scale", "Orientation", "Grid"], answer: 1 },
    { id: "G9-GEO-16", grade: 9, subject: "Geography", topic: "Basics", question: "GIS stands for Geographic ___ System.", choices: ["Internal", "Information", "International", "Internet"], answer: 1 },
    { id: "G9-GEO-17", grade: 9, subject: "Geography", topic: "Basics", question: "The study of the Earth's physical features and human activity is ___.", choices: ["Geology", "Geography", "History", "Anthropology"], answer: 1 },
    { id: "G9-GEO-18", grade: 9, subject: "Geography", topic: "Basics", question: "Which continent is in all four hemispheres?", choices: ["Asia", "Africa", "South America", "Europe"], answer: 1 },
    { id: "G9-GEO-19", grade: 9, subject: "Geography", topic: "Basics", question: "How many continents are there?", choices: ["5", "6", "7", "8"], answer: 2 },
    { id: "G9-GEO-20", grade: 9, subject: "Geography", topic: "Basics", question: "Which ocean is the largest?", choices: ["Atlantic", "Indian", "Pacific", "Arctic"], answer: 2 },
    { id: "G9-GEO-21", grade: 9, subject: "Geography", topic: "Maps", question: "A map showing the distribution of population is a ___ map.", choices: ["Physical", "Political", "Thematic", "Flow"], answer: 2 },
    { id: "G9-GEO-22", grade: 9, subject: "Geography", topic: "Basics", question: "The 'Midwest' of the USA is an example of what type of region?", choices: ["Formal", "Functional", "Perceptual/Vernacular", "Physical"], answer: 2 },
    { id: "G9-GEO-23", grade: 9, subject: "Geography", topic: "Basics", question: "What line is at 180° longitude?", choices: ["Prime Meridian", "International Date Line", "Equator", "Arctic Circle"], answer: 1 },
    { id: "G9-GEO-24", grade: 9, subject: "Geography", topic: "Basics", question: "The Tropic of Cancer is in which hemisphere?", choices: ["Northern", "Southern", "Eastern", "Western"], answer: 0 },
    { id: "G9-GEO-25", grade: 9, subject: "Geography", topic: "Themes", question: "Building a dam to control river flooding is an example of ___.", choices: ["Movement", "Place", "Human-Environment Interaction", "Region"], answer: 2 },

    // --- TOPIC 2: PHYSICAL GEOGRAPHY & CLIMATE (25 Questions) ---
    { id: "G9-GEO-26", grade: 9, subject: "Geography", topic: "Earth", question: "The theory that Earth's outer shell is divided into several plates is ___.", choices: ["Evolution", "Plate Tectonics", "Big Bang", "Climate Change"], answer: 1 },
    { id: "G9-GEO-27", grade: 9, subject: "Geography", topic: "Earth", question: "What is the process of breaking down rocks into smaller pieces?", choices: ["Erosion", "Weathering", "Deposition", "Subduction"], answer: 1 },
    { id: "G9-GEO-28", grade: 9, subject: "Geography", topic: "Earth", question: "What is the movement of weathered material by wind, water, or ice?", choices: ["Weathering", "Erosion", "Faulting", "Plate Tectonics"], answer: 1 },
    { id: "G9-GEO-29", grade: 9, subject: "Geography", topic: "Climate", question: "The condition of the atmosphere at a specific time and place is ___.", choices: ["Climate", "Weather", "Current", "Biome"], answer: 1 },
    { id: "G9-GEO-30", grade: 9, subject: "Geography", topic: "Climate", question: "The average weather conditions over a long period is ___.", choices: ["Weather", "Climate", "Forecast", "Ecosystem"], answer: 1 },
    { id: "G9-GEO-31", grade: 9, subject: "Geography", topic: "Climate", question: "As elevation increases, temperature usually ___.", choices: ["Increases", "Decreases", "Stays the same", "Doubles"], answer: 1 },
    { id: "G9-GEO-32", grade: 9, subject: "Geography", topic: "Earth", question: "The 'Ring of Fire' is an area of intense volcanic activity in the ___ Ocean.", choices: ["Atlantic", "Indian", "Pacific", "Arctic"], answer: 2 },
    { id: "G9-GEO-33", grade: 9, subject: "Geography", topic: "Climate", question: "The side of a mountain that faces the wind and receives rain is the ___ side.", choices: ["Leeward", "Windward", "Sunny", "Shadow"], answer: 1 },
    { id: "G9-GEO-34", grade: 9, subject: "Geography", topic: "Climate", question: "The dry side of a mountain is called the ___ side.", choices: ["Windward", "Leeward", "Rainy", "Tropical"], answer: 1 },
    { id: "G9-GEO-35", grade: 9, subject: "Geography", topic: "Earth", question: "Pangaea was the name of a ___.", choices: ["Mountain", "Ancient Supercontinent", "Ocean", "Volcano"], answer: 1 },
    { id: "G9-GEO-36", grade: 9, subject: "Geography", topic: "Hydrosphere", question: "About ___% of the Earth's surface is covered by water.", choices: ["50", "70", "90", "25"], answer: 1 },
    { id: "G9-GEO-37", grade: 9, subject: "Geography", topic: "Earth", question: "Which layer of the Earth is the thin, outer layer?", choices: ["Core", "Mantle", "Crust", "Atmosphere"], answer: 2 },
    { id: "G9-GEO-38", grade: 9, subject: "Geography", topic: "Climate", question: "Low latitudes (near the equator) are generally ___.", choices: ["Cold", "Hot", "Temperate", "Dry"], answer: 1 },
    { id: "G9-GEO-39", grade: 9, subject: "Geography", topic: "Climate", question: "High latitudes (near the poles) are generally ___.", choices: ["Hot", "Cold", "Rainy", "Humid"], answer: 1 },
    { id: "G9-GEO-40", grade: 9, subject: "Geography", topic: "Biomes", question: "A tropical grassland with scattered trees is a ___.", choices: ["Steppe", "Savanna", "Desert", "Tundra"], answer: 1 },
    { id: "G9-GEO-41", grade: 9, subject: "Geography", topic: "Earth", question: "What occurs when two tectonic plates slide past each other?", choices: ["Volcanoes", "Earthquakes", "Deep-sea trenches", "Mountains"], answer: 1 },
    { id: "G9-GEO-42", grade: 9, subject: "Geography", topic: "Climate", question: "The Greenhouse Effect traps ___ in the atmosphere.", choices: ["Water", "Heat", "Ice", "Oxygen"], answer: 1 },
    { id: "G9-GEO-43", grade: 9, subject: "Geography", topic: "Hydrosphere", question: "97% of Earth's water is ___.", choices: ["Fresh", "Saltwater", "Frozen", "Underground"], answer: 1 },
    { id: "G9-GEO-44", grade: 9, subject: "Geography", topic: "Earth", question: "Magma that reaches the Earth's surface is called ___.", choices: ["Rock", "Lava", "Ash", "Sediment"], answer: 1 },
    { id: "G9-GEO-45", grade: 9, subject: "Geography", topic: "Climate", question: "The tilt of the Earth causes ___.", choices: ["Day and Night", "Tides", "Seasons", "Earthquakes"], answer: 2 },
    { id: "G9-GEO-46", grade: 9, subject: "Geography", topic: "Hydrosphere", question: "The process of turning salt water into fresh water is ___.", choices: ["Osmosis", "Desalination", "Irrigation", "Hydroponics"], answer: 1 },
    { id: "G9-GEO-47", grade: 9, subject: "Geography", topic: "Climate", question: "The 'Rain Shadow Effect' creates ___ on the leeward side of mountains.", choices: ["Swamps", "Deserts", "Lakes", "Forests"], answer: 1 },
    { id: "G9-GEO-48", grade: 9, subject: "Geography", topic: "Earth", question: "A narrow strip of land connecting two larger land masses is an ___.", choices: ["Island", "Isthmus", "Archipelago", "Peninsula"], answer: 1 },
    { id: "G9-GEO-49", grade: 9, subject: "Geography", topic: "Earth", question: "A group or chain of islands is an ___.", choices: ["Isthmus", "Archipelago", "Atoll", "Delta"], answer: 1 },
    { id: "G9-GEO-50", grade: 9, subject: "Geography", topic: "Earth", question: "Flat land at a high elevation is a ___.", choices: ["Valley", "Plateau", "Plain", "Basin"], answer: 1 },

    // --- TOPIC 3: HUMAN GEOGRAPHY & CULTURE (25 Questions) ---
    { id: "G9-GEO-51", grade: 9, subject: "Geography", topic: "Population", question: "The number of people living in a square mile is population ___.", choices: ["Growth", "Density", "Migration", "Distribution"], answer: 1 },
    { id: "G9-GEO-52", grade: 9, subject: "Geography", topic: "Migration", question: "Reasons that make people WANT to move to a new country are ___ factors.", choices: ["Push", "Pull", "Natural", "Economic"], answer: 1 },
    { id: "G9-GEO-53", grade: 9, subject: "Geography", topic: "Migration", question: "Reasons that make people NEED to leave their home country are ___ factors.", choices: ["Pull", "Push", "Positive", "Social"], answer: 1 },
    { id: "G9-GEO-54", grade: 9, subject: "Geography", topic: "Urbanization", question: "The growth of cities is called ___.", choices: ["Ruralization", "Urbanization", "Industrialization", "Immigration"], answer: 1 },
    { id: "G9-GEO-55", grade: 9, subject: "Geography", topic: "Economics", question: "Farming just enough to feed your family is ___ farming.", choices: ["Commercial", "Subsistence", "Industrial", "Organic"], answer: 1 },
    { id: "G9-GEO-56", grade: 9, subject: "Geography", topic: "Culture", question: "The spread of ideas and customs from one culture to another is culture ___.", choices: ["Invasion", "Diffusion", "Isolation", "Correction"], answer: 1 },
    { id: "G9-GEO-57", grade: 9, subject: "Geography", topic: "Economics", question: "Resources that can be replaced naturally (like wind, sun) are ___.", choices: ["Non-renewable", "Renewable", "Fossil fuels", "Limited"], answer: 1 },
    { id: "G9-GEO-58", grade: 9, subject: "Geography", topic: "Economics", question: "Resources that cannot be replaced (like oil, coal) are ___.", choices: ["Renewable", "Non-renewable", "Infinite", "Green"], answer: 1 },
    { id: "G9-GEO-59", grade: 9, subject: "Geography", topic: "Culture", question: "Belief in many gods is ___.", choices: ["Monotheism", "Polytheism", "Atheism", "Animism"], answer: 1 },
    { id: "G9-GEO-60", grade: 9, subject: "Geography", topic: "Culture", question: "Belief in one god is ___.", choices: ["Polytheism", "Monotheism", "Democracy", "Socialism"], answer: 1 },
    { id: "G9-GEO-61", grade: 9, subject: "Geography", topic: "Government", question: "A government ruled by a king or queen is a ___.", choices: ["Democracy", "Monarchy", "Dictatorship", "Republic"], answer: 1 },
    { id: "G9-GEO-62", grade: 9, subject: "Geography", topic: "Government", question: "A government where citizens hold the power is a ___.", choices: ["Monarchy", "Democracy", "Theocracy", "Oligarchy"], answer: 1 },
    { id: "G9-GEO-63", grade: 9, subject: "Geography", topic: "Economics", question: "The total value of goods and services produced in a country in a year is ___.", choices: ["GNP", "GDP", "CPI", "USA"], answer: 1 },
    { id: "G9-GEO-64", grade: 9, subject: "Geography", topic: "Culture", question: "A place where a culture first began is a culture ___.", choices: ["Region", "Hearth", "Capital", "Node"], answer: 1 },
    { id: "G9-GEO-65", grade: 9, subject: "Geography", topic: "Population", question: "Birth rate minus death rate equals ___.", choices: ["Total Population", "Natural Increase", "Migration Rate", "Fertility"], answer: 1 },
    { id: "G9-GEO-66", grade: 9, subject: "Geography", topic: "Urbanization", question: "An area with a city and its surrounding suburbs is a ___ area.", choices: ["Rural", "Metropolitan", "Agricultural", "Isolated"], answer: 1 },
    { id: "G9-GEO-67", grade: 9, subject: "Geography", topic: "Economics", question: "Primary economic activities involve ___.", choices: ["Manufacturing", "Extracting raw materials", "Service jobs", "Research"], answer: 1 },
    { id: "G9-GEO-68", grade: 9, subject: "Geography", topic: "Economics", question: "Secondary economic activities involve ___.", choices: ["Farming", "Manufacturing/Industry", "Banking", "Teaching"], answer: 1 },
    { id: "G9-GEO-69", grade: 9, subject: "Geography", topic: "Economics", question: "Tertiary economic activities involve ___.", choices: ["Mining", "Services (doctors, stores)", "Factories", "Logging"], answer: 1 },
    { id: "G9-GEO-70", grade: 9, subject: "Geography", topic: "Migration", question: "Someone who flees their country to escape war or persecution is a ___.", choices: ["Tourist", "Refugee", "Expatriate", "Immigrant"], answer: 1 },
    { id: "G9-GEO-71", grade: 9, subject: "Geography", topic: "Economics", question: "NAFTA (now USMCA) is a trade agreement between Canada, the USA, and ___.", choices: ["Brazil", "Mexico", "China", "England"], answer: 1 },
    { id: "G9-GEO-72", grade: 9, subject: "Geography", topic: "Culture", question: "The most common religion in Latin America is ___.", choices: ["Islam", "Catholicism", "Buddhism", "Hinduism"], answer: 1 },
    { id: "G9-GEO-73", grade: 9, subject: "Geography", topic: "Population", question: "The 'Baby Boom' occurred in the USA after which war?", choices: ["WWI", "WWII", "Vietnam", "Civil War"], answer: 1 },
    { id: "G9-GEO-74", grade: 9, subject: "Geography", topic: "Government", question: "A government ruled by religious leaders is a ___.", choices: ["Democracy", "Theocracy", "Dictatorship", "Monarchy"], answer: 1 },
    { id: "G9-GEO-75", grade: 9, subject: "Geography", topic: "Economics", question: "Infrastructure refers to a country's ___.", choices: ["Military", "Basic physical systems (roads, power, water)", "History", "Language"], answer: 1 },

    // --- TOPIC 4: REGIONAL GEOGRAPHY (25 Questions) ---
    { id: "G9-GEO-76", grade: 9, subject: "Geography", topic: "Americas", question: "The longest mountain range in South America is the ___.", choices: ["Rockies", "Andes", "Alps", "Appalachians"], answer: 1 },
    { id: "G9-GEO-77", grade: 9, subject: "Geography", topic: "Americas", question: "The largest tropical rainforest in the world is the ___.", choices: ["Congo", "Amazon", "Daintree", "Taiga"], answer: 1 },
    { id: "G9-GEO-78", grade: 9, subject: "Geography", topic: "Europe", question: "The European Union was created to increase ___ cooperation.", choices: ["Military", "Economic", "Religious", "Space"], answer: 1 },
    { id: "G9-GEO-79", grade: 9, subject: "Geography", topic: "Asia", question: "The highest mountain peak in the world is ___.", choices: ["Mt. Fuji", "Mt. Everest", "K2", "Kilimanjaro"], answer: 1 },
    { id: "G9-GEO-80", grade: 9, subject: "Geography", topic: "Africa", question: "The world's longest river is the ___.", choices: ["Amazon", "Nile", "Mississippi", "Yangtze"], answer: 1 },
    { id: "G9-GEO-81", grade: 9, subject: "Geography", topic: "Africa", question: "The largest hot desert in the world is the ___.", choices: ["Gobi", "Sahara", "Atacama", "Mojave"], answer: 1 },
    { id: "G9-GEO-82", grade: 9, subject: "Geography", topic: "Asia", question: "The caste system is traditionally associated with which country?", choices: ["China", "India", "Japan", "Thailand"], answer: 1 },
    { id: "G9-GEO-83", grade: 9, subject: "Geography", topic: "Middle East", question: "The primary natural resource found in the Middle East is ___.", choices: ["Gold", "Oil", "Diamonds", "Wood"], answer: 1 },
    { id: "G9-GEO-84", grade: 9, subject: "Geography", topic: "Middle East", question: "The holy city for Jews, Christians, and Muslims is ___.", choices: ["Mecca", "Jerusalem", "Rome", "Cairo"], answer: 1 },
    { id: "G9-GEO-85", grade: 9, subject: "Geography", topic: "Oceania", question: "The Great Barrier Reef is located off the coast of ___.", choices: ["New Zealand", "Australia", "Hawaii", "Fiji"], answer: 1 },
    { id: "G9-GEO-86", grade: 9, subject: "Geography", topic: "Asia", question: "Seasonal winds that bring heavy rains to South Asia are ___.", choices: ["Hurricanes", "Monsoons", "Tornadoes", "Cyclones"], answer: 1 },
    { id: "G9-GEO-87", grade: 9, subject: "Geography", topic: "Europe", question: "A narrow, deep inlet of the sea between high cliffs (common in Norway) is a ___.", choices: ["Fjord", "Delta", "Lagoon", "Strait"], answer: 0 },
    { id: "G9-GEO-88", grade: 9, subject: "Geography", topic: "Africa", question: "The 'Great Rift Valley' is located in ___ Africa.", choices: ["West", "East", "North", "South"], answer: 1 },
    { id: "G9-GEO-89", grade: 9, subject: "Geography", topic: "Asia", question: "The 'Gobi Desert' is located in ___.", choices: ["India", "Mongolia and China", "Saudi Arabia", "Vietnam"], answer: 1 },
    { id: "G9-GEO-90", grade: 9, subject: "Geography", topic: "Americas", question: "The 'Panama Canal' connects the Atlantic Ocean to the ___ Ocean.", choices: ["Indian", "Pacific", "Arctic", "Southern"], answer: 1 },
    { id: "G9-GEO-91", grade: 9, subject: "Geography", topic: "Russia", question: "The mountain range that separates Europe from Asia is the ___.", choices: ["Alps", "Urals", "Pyrenees", "Caucasus"], answer: 1 },
    { id: "G9-GEO-92", grade: 9, subject: "Geography", topic: "Asia", question: "The most populous country in the world is ___.", choices: ["USA", "India", "China", "Russia"], answer: 1 },
    { id: "G9-GEO-93", grade: 9, subject: "Geography", topic: "Americas", question: "Which river flows through Brazil and into the Atlantic?", choices: ["Rio Grande", "Amazon", "Orinoco", "Parana"], answer: 1 },
    { id: "G9-GEO-94", grade: 9, subject: "Geography", topic: "Africa", question: "Apartheid was a system of segregation in ___.", choices: ["Egypt", "South Africa", "Nigeria", "Kenya"], answer: 1 },
    { id: "G9-GEO-95", grade: 9, subject: "Geography", topic: "Antarctica", question: "Which continent has no permanent human inhabitants?", choices: ["Australia", "Antarctica", "South America", "Africa"], answer: 1 },
    { id: "G9-GEO-96", grade: 9, subject: "Geography", topic: "Europe", question: "The United Kingdom consists of England, Scotland, Wales, and ___.", choices: ["Ireland", "Northern Ireland", "Iceland", "France"], answer: 1 },
    { id: "G9-GEO-97", grade: 9, subject: "Geography", topic: "Oceania", question: "Native inhabitants of Australia are the ___.", choices: ["Maori", "Aborigines", "Inuit", "Aztecs"], answer: 1 },
    { id: "G9-GEO-98", grade: 9, subject: "Geography", topic: "Americas", question: "Which country is the largest in North America by land area?", choices: ["USA", "Canada", "Mexico", "Greenland"], answer: 1 },
    { id: "G9-GEO-99", grade: 9, subject: "Geography", topic: "Asia", question: "The 'Dead Sea' is the ___ point on Earth's land surface.", choices: ["Highest", "Lowest", "Coldest", "Hottest"], answer: 1 },
    { id: "G9-GEO-100", grade: 9, subject: "Geography", topic: "Middle East", question: "The process of a desert expanding is ___.", choices: ["Deforestation", "Desertification", "Urbanization", "Irrigation"], answer: 1 }
];

module.exports = G9_GEOGRAPHY_COMPLETE;
