const G9_MATH_COMPLETE = [
    // --- TOPIC 1: EQUATIONS & INEQUALITIES (25 Questions) ---
    { id: "G9-MA-01", grade: 9, subject: "Math", topic: "Equations", question: "Solve: 4(x - 2) = 3x + 10", choices: ["x = 18", "x = 2", "x = 12", "x = 8"], answer: 0 },
    { id: "G9-MA-02", grade: 9, subject: "Math", topic: "Inequalities", question: "When multiplying or dividing an inequality by a negative number, you must ___.", choices: ["Keep the sign the same", "Flip the inequality sign", "Change the variable", "Make the answer zero"], answer: 1 },
    { id: "G9-MA-03", grade: 9, subject: "Math", topic: "Equations", question: "Solve for y: 2x + y = 10", choices: ["y = 10 - 2x", "y = 2x + 10", "y = 5x", "y = 10/2x"], answer: 0 },
    { id: "G9-MA-04", grade: 9, subject: "Math", topic: "Inequalities", question: "Solve: -3x < 9", choices: ["x < -3", "x > -3", "x < 3", "x > 3"], answer: 1 },
    { id: "G9-MA-05", grade: 9, subject: "Math", topic: "Absolute Value", question: "Solve: |x - 5| = 10", choices: ["x = 15", "x = -5", "x = 15 or x = -5", "x = 5"], answer: 2 },
    { id: "G9-MA-06", grade: 9, subject: "Math", topic: "Literal Equations", question: "Solve for r in C = 2πr", choices: ["r = C/2π", "r = 2πC", "r = C - 2π", "r = 2C/π"], answer: 0 },
    { id: "G9-MA-07", grade: 9, subject: "Math", topic: "Equations", question: "A 'solution' to an equation makes the statement ___.", choices: ["False", "True", "Zero", "Negative"], answer: 1 },
    { id: "G9-MA-08", grade: 9, subject: "Math", topic: "Inequalities", question: "A closed circle on a number line represents ___.", choices: ["Greater than", "Less than", "Greater than or equal to (≥)", "Not equal to"], answer: 2 },
    { id: "G9-MA-09", grade: 9, subject: "Math", topic: "Equations", question: "Solve: 5x + 3 = 5x + 3", choices: ["x = 1", "No solution", "Infinitely many solutions", "x = 0"], answer: 2 },
    { id: "G9-MA-10", grade: 9, subject: "Math", topic: "Equations", question: "Solve: x/4 + 7 = 10", choices: ["x = 12", "x = 68", "x = 3", "x = 1.25"], answer: 0 },
    { id: "G9-MA-11", grade: 9, subject: "Math", topic: "Inequalities", question: "Graphing y > 2x + 1 involves a ___ line.", choices: ["Solid", "Dashed", "Vertical", "Horizontal"], answer: 1 },
    { id: "G9-MA-12", grade: 9, subject: "Math", topic: "Inequalities", question: "In y < 3x - 4, which side of the line is shaded?", choices: ["Above", "Below", "Left", "Right"], answer: 1 },
    { id: "G9-MA-13", grade: 9, subject: "Math", topic: "Equations", question: "Solve: 0.5x = 20", choices: ["x = 10", "x = 40", "x = 20.5", "x = 4"], answer: 1 },
    { id: "G9-MA-14", grade: 9, subject: "Math", topic: "Absolute Value", question: "Can an absolute value equation equal a negative number (e.g., |x| = -5)?", choices: ["Yes", "No"], answer: 1 },
    { id: "G9-MA-15", grade: 9, subject: "Math", topic: "Equations", question: "The first step to solve 3x - 4 = 11 is ___.", choices: ["Subtract 4", "Add 4", "Divide by 3", "Multiply by 3"], answer: 1 },
    { id: "G9-MA-16", grade: 9, subject: "Math", topic: "Inequalities", question: "Solve: 2x + 1 ≥ 5", choices: ["x ≥ 2", "x ≤ 2", "x > 3", "x < 1"], answer: 0 },
    { id: "G9-MA-17", grade: 9, subject: "Math", topic: "Logic", question: "A 'Compound Inequality' uses the words ___.", choices: ["Maybe or If", "And or Or", "But or So", "Then or Because"], answer: 1 },
    { id: "G9-MA-18", grade: 9, subject: "Math", topic: "Equations", question: "Solve for h: V = lwh", choices: ["h = V/lw", "h = Vlw", "h = lw/V", "h = V-l-w"], answer: 0 },
    { id: "G9-MA-19", grade: 9, subject: "Math", topic: "Inequalities", question: "The symbol '≤' means ___.", choices: ["Less than", "At most", "At least", "Equal to"], answer: 1 },
    { id: "G9-MA-20", grade: 9, subject: "Math", topic: "Inequalities", question: "The symbol '≥' means ___.", choices: ["At most", "At least", "Less than", "Only"], answer: 1 },
    { id: "G9-MA-21", grade: 9, subject: "Math", topic: "Equations", question: "Solve: 10 - x = 14", choices: ["x = 4", "x = -4", "x = 24", "x = -24"], answer: 1 },
    { id: "G9-MA-22", grade: 9, subject: "Math", topic: "Inequalities", question: "Which value is a solution to x + 5 > 10?", choices: ["5", "4", "6", "0"], answer: 2 },
    { id: "G9-MA-23", grade: 9, subject: "Math", topic: "Equations", question: "The property used in a(b + c) = ab + ac is ___.", choices: ["Commutative", "Associative", "Distributive", "Identity"], answer: 2 },
    { id: "G9-MA-24", grade: 9, subject: "Math", topic: "Equations", question: "Solve: 3x/2 = 9", choices: ["x = 6", "x = 27", "x = 13.5", "x = 18"], answer: 0 },
    { id: "G9-MA-25", grade: 9, subject: "Math", topic: "Equations", question: "A 'proportion' is two ___ that are equal.", choices: ["Equations", "Fractions/Ratios", "Variables", "Integers"], answer: 1 },

    // --- TOPIC 2: FUNCTIONS & LINEAR REPRESENTATIONS (25 Questions) ---
    { id: "G9-MA-26", grade: 9, subject: "Math", topic: "Functions", question: "f(x) is another way to write ___.", choices: ["Slope", "y", "x-intercept", "Variable"], answer: 1 },
    { id: "G9-MA-27", grade: 9, subject: "Math", topic: "Functions", question: "If f(x) = 3x - 1, find f(4).", choices: ["11", "12", "13", "7"], answer: 0 },
    { id: "G9-MA-28", grade: 9, subject: "Math", topic: "Functions", question: "The 'Zeros' of a function are where it crosses the ___.", choices: ["Y-axis", "X-axis", "Origin", "Vertical line"], answer: 1 },
    { id: "G9-MA-29", grade: 9, subject: "Math", topic: "Slope", question: "Standard Form of a linear equation is ___.", choices: ["y = mx + b", "Ax + By = C", "y - y1 = m(x - x1)", "x = a"], answer: 1 },
    { id: "G9-MA-30", grade: 9, subject: "Math", topic: "Slope", question: "Point-Slope Form is ___.", choices: ["y = mx + b", "y - y1 = m(x - x1)", "Ax + By = C", "m = rise/run"], answer: 1 },
    { id: "G9-MA-31", grade: 9, subject: "Math", topic: "Lines", question: "Perpendicular lines have slopes that are ___.", choices: ["Equal", "Opposite Reciprocals", "Zero", "Positive"], answer: 1 },
    { id: "G9-MA-32", grade: 9, subject: "Math", topic: "Lines", question: "Parallel lines have slopes that are ___.", choices: ["Equal", "Negative", "Opposite", "Undefined"], answer: 0 },
    { id: "G9-MA-33", grade: 9, subject: "Math", topic: "Functions", question: "A relation is a function if every input has ___ output(s).", choices: ["Multiple", "Exactly one", "No", "Zero"], answer: 1 },
    { id: "G9-MA-34", grade: 9, subject: "Math", topic: "Functions", question: "Domain refers to all possible ___ values.", choices: ["y", "x", "Slope", "Intercept"], answer: 1 },
    { id: "G9-MA-35", grade: 9, subject: "Math", topic: "Functions", question: "Range refers to all possible ___ values.", choices: ["x", "y", "Zero", "Positive"], answer: 1 },
    { id: "G9-MA-36", grade: 9, subject: "Math", topic: "Slope", question: "Slope of the line y = 5?", choices: ["5", "1", "0", "Undefined"], answer: 2 },
    { id: "G9-MA-37", grade: 9, subject: "Math", topic: "Slope", question: "Slope of the line x = 2?", choices: ["2", "0", "1", "Undefined"], answer: 3 },
    { id: "G9-MA-38", grade: 9, subject: "Math", topic: "Lines", question: "Two lines are perpendicular if their slopes multiply to ___.", choices: ["1", "-1", "0", "10"], answer: 1 },
    { id: "G9-MA-39", grade: 9, subject: "Math", topic: "Functions", question: "An 'arithmetic sequence' has a common ___.", choices: ["Ratio", "Difference", "Factor", "Multiple"], answer: 1 },
    { id: "G9-MA-40", grade: 9, subject: "Math", topic: "Functions", question: "The graph of a linear function is always a ___.", choices: ["Curve", "Circle", "Straight line", "Square"], answer: 2 },
    { id: "G9-MA-41", grade: 9, subject: "Math", topic: "Slope", question: "Find the slope between (1, 2) and (3, 6).", choices: ["2", "4", "1/2", "3"], answer: 0 },
    { id: "G9-MA-42", grade: 9, subject: "Math", topic: "Functions", question: "Which is a function: {(1,2), (2,2)} or {(1,2), (1,3)}?", choices: ["{(1,2), (2,2)}", "{(1,2), (1,3)}"], answer: 0 },
    { id: "G9-MA-43", grade: 9, subject: "Math", topic: "Slope", question: "In y = -2x + 7, what is the slope?", choices: ["7", "-2", "2", "x"], answer: 1 },
    { id: "G9-MA-44", grade: 9, subject: "Math", topic: "Slope", question: "In y = 4x - 3, what is the y-intercept?", choices: ["4", "3", "-3", "0"], answer: 2 },
    { id: "G9-MA-45", grade: 9, subject: "Math", topic: "Lines", question: "To find the x-intercept, set ___ to zero.", choices: ["x", "y", "m", "b"], answer: 1 },
    { id: "G9-MA-46", grade: 9, subject: "Math", topic: "Lines", question: "To find the y-intercept, set ___ to zero.", choices: ["y", "x", "slope", "intercept"], answer: 1 },
    { id: "G9-MA-47", grade: 9, subject: "Math", topic: "Functions", question: "Which represents a linear function?", choices: ["y = x^2", "y = 2x + 1", "y = |x|", "y = 1/x"], answer: 1 },
    { id: "G9-MA-48", grade: 9, subject: "Math", topic: "Functions", question: "A sequence 2, 5, 8, 11... has a common difference of ___.", choices: ["2", "3", "5", "1"], answer: 1 },
    { id: "G9-MA-49", grade: 9, subject: "Math", topic: "Functions", question: "If the rate of change is constant, the function is ___.", choices: ["Non-linear", "Linear", "Exponential", "Quadratic"], answer: 1 },
    { id: "G9-MA-50", grade: 9, subject: "Math", topic: "Functions", question: "Vertical translation of y = x up 3 units is ___.", choices: ["y = x - 3", "y = x + 3", "y = 3x", "y = x/3"], answer: 1 },

    // --- TOPIC 3: EXPONENTS & POLYNOMIALS (25 Questions) ---
    { id: "G9-MA-51", grade: 9, subject: "Math", topic: "Exponents", question: "(x^2)(x^5) =", choices: ["x^7", "x^10", "2x^7", "x^3"], answer: 0 },
    { id: "G9-MA-52", grade: 9, subject: "Math", topic: "Exponents", question: "(x^6) / (x^2) =", choices: ["x^3", "x^8", "x^4", "x^12"], answer: 2 },
    { id: "G9-MA-53", grade: 9, subject: "Math", topic: "Exponents", question: "(2x^3)^2 =", choices: ["2x^6", "4x^6", "4x^5", "2x^5"], answer: 1 },
    { id: "G9-MA-54", grade: 9, subject: "Math", topic: "Exponents", question: "x^-2 is equal to ___.", choices: ["-x^2", "1/x^2", "-2x", "0"], answer: 1 },
    { id: "G9-MA-55", grade: 9, subject: "Math", topic: "Polynomials", question: "A polynomial with two terms is a ___.", choices: ["Monomial", "Binomial", "Trinomial", "Constant"], answer: 1 },
    { id: "G9-MA-56", grade: 9, subject: "Math", topic: "Polynomials", question: "The 'degree' of 4x^3 + 2x is ___.", choices: ["4", "3", "1", "2"], answer: 1 },
    { id: "G9-MA-57", grade: 9, subject: "Math", topic: "Polynomials", question: "Combine like terms: 3x^2 + 5x - x^2 + 2.", choices: ["2x^2 + 5x + 2", "4x^2 + 5x + 2", "7x^2 + 2", "3x^4 + 2"], answer: 0 },
    { id: "G9-MA-58", grade: 9, subject: "Math", topic: "Polynomials", question: "Multiply (x + 2)(x + 3) using FOIL.", choices: ["x^2 + 5x + 6", "x^2 + 6", "2x + 5", "x^2 + 6x + 5"], answer: 0 },
    { id: "G9-MA-59", grade: 9, subject: "Math", topic: "Factoring", question: "The Greatest Common Factor (GCF) of 6x^2 and 12x is ___.", choices: ["6", "x", "6x", "12x"], answer: 2 },
    { id: "G9-MA-60", grade: 9, subject: "Math", topic: "Factoring", question: "Factor x^2 - 9 (Difference of Squares).", choices: ["(x-3)(x-3)", "(x-9)(x+1)", "(x-3)(x+3)", "(x+3)(x+3)"], answer: 2 },
    { id: "G9-MA-61", grade: 9, subject: "Math", topic: "Polynomials", question: "What is the leading coefficient of -5x^2 + 3x + 1?", choices: ["3", "-5", "2", "1"], answer: 1 },
    { id: "G9-MA-62", grade: 9, subject: "Math", topic: "Polynomials", question: "A polynomial with three terms is a ___.", choices: ["Monomial", "Trinomial", "Binomial", "Quadnomial"], answer: 1 },
    { id: "G9-MA-63", grade: 9, subject: "Math", topic: "Exponents", question: "Simplify (x^0)y^3.", choices: ["0", "xy^3", "y^3", "x^3"], answer: 2 },
    { id: "G9-MA-64", grade: 9, subject: "Math", topic: "Polynomials", question: "Multiply (2x)(3x^2).", choices: ["5x^3", "6x^3", "6x^2", "5x^2"], answer: 1 },
    { id: "G9-MA-65", grade: 9, subject: "Math", topic: "Factoring", question: "Factor x^2 + 5x + 6.", choices: ["(x+1)(x+6)", "(x+2)(x+3)", "(x-2)(x-3)", "(x+5)(x+1)"], answer: 1 },
    { id: "G9-MA-66", grade: 9, subject: "Math", topic: "Exponents", question: "The value of 5^-1 is ___.", choices: ["-5", "1/5", "0.5", "-1/5"], answer: 1 },
    { id: "G9-MA-67", grade: 9, subject: "Math", topic: "Polynomials", question: "Standard form of a polynomial is written with exponents in ___ order.", choices: ["Increasing", "Decreasing", "Random", "Alphabetical"], answer: 1 },
    { id: "G9-MA-68", grade: 9, subject: "Math", topic: "Polynomials", question: "(x + 4)^2 =", choices: ["x^2 + 16", "x^2 + 8x + 16", "x^2 + 4x + 8", "2x + 8"], answer: 1 },
    { id: "G9-MA-69", grade: 9, subject: "Math", topic: "Factoring", question: "Factor out the GCF: 5x + 10.", choices: ["5(x + 2)", "x(5 + 10)", "5(x + 10)", "15x"], answer: 0 },
    { id: "G9-MA-70", grade: 9, subject: "Math", topic: "Factoring", question: "Factor x^2 - 10x + 25.", choices: ["(x-5)(x+5)", "(x-5)^2", "(x-10)(x-10)", "(x+5)^2"], answer: 1 },
    { id: "G9-MA-71", grade: 9, subject: "Math", topic: "Exponents", question: "Scientific Notation for 0.00001?", choices: ["1 x 10^5", "1 x 10^-5", "1 x 10^-4", "10 x 10^-6"], answer: 1 },
    { id: "G9-MA-72", grade: 9, subject: "Math", topic: "Polynomials", question: "A 'monomial' has how many terms?", choices: ["0", "1", "2", "3"], answer: 1 },
    { id: "G9-MA-73", grade: 9, subject: "Math", topic: "Factoring", question: "Can x^2 + 16 be factored using Difference of Squares?", choices: ["Yes", "No (it is a sum)"], answer: 1 },
    { id: "G9-MA-74", grade: 9, subject: "Math", topic: "Polynomials", question: "Subtract (2x + 5) - (x + 2).", choices: ["x + 3", "3x + 7", "x + 7", "3x + 3"], answer: 0 },
    { id: "G9-MA-75", grade: 9, subject: "Math", topic: "Polynomials", question: "What is the degree of a constant (like 7)?", choices: ["1", "0", "Undefined", "7"], answer: 1 },

    // --- TOPIC 4: QUADRATICS & RADICALS (25 Questions) ---
    { id: "G9-MA-76", grade: 9, subject: "Math", topic: "Quadratics", question: "The graph of a quadratic function is called a ___.", choices: ["Line", "Parabola", "Hyperbola", "Circle"], answer: 1 },
    { id: "G9-MA-77", grade: 9, subject: "Math", topic: "Quadratics", question: "Standard form of a quadratic is f(x) = ___.", choices: ["mx + b", "ax^2 + bx + c", "a(x-h)^2 + k", "x/y"], answer: 1 },
    { id: "G9-MA-78", grade: 9, subject: "Math", topic: "Quadratics", question: "The highest or lowest point of a parabola is the ___.", choices: ["Root", "Vertex", "Axis", "Intercept"], answer: 1 },
    { id: "G9-MA-79", grade: 9, subject: "Math", topic: "Quadratics", question: "If 'a' is positive in ax^2 + bx + c, the parabola opens ___.", choices: ["Down", "Up", "Left", "Right"], answer: 1 },
    { id: "G9-MA-80", grade: 9, subject: "Math", topic: "Quadratics", question: "The vertical line that divides a parabola in half is the ___.", choices: ["X-axis", "Axis of Symmetry", "Directrix", "Slope"], answer: 1 },
    { id: "G9-MA-81", grade: 9, subject: "Math", topic: "Quadratics", question: "Formula for the Axis of Symmetry?", choices: ["x = -b/2a", "y = mx+b", "a^2+b^2=c^2", "x = c"], answer: 0 },
    { id: "G9-MA-82", grade: 9, subject: "Math", topic: "Quadratics", question: "What part of the quadratic formula is the 'discriminant'?", choices: ["2a", "-b", "b^2 - 4ac", "sqrt(b)"], answer: 2 },
    { id: "G9-MA-83", grade: 9, subject: "Math", topic: "Quadratics", question: "If the discriminant is zero, there is/are ___ real solution(s).", choices: ["One", "Two", "No", "Infinite"], answer: 0 },
    { id: "G9-MA-84", grade: 9, subject: "Math", topic: "Quadratics", question: "If the discriminant is negative, there are ___ real solutions.", choices: ["Two", "One", "Zero", "Infinite"], answer: 2 },
    { id: "G9-MA-85", grade: 9, subject: "Math", topic: "Radicals", question: "Simplify √48.", choices: ["4√3", "6√2", "16√3", "4√6"], answer: 0 },
    { id: "G9-MA-86", grade: 9, subject: "Math", topic: "Radicals", question: "Simplify √x^2.", choices: ["x", "x^2", "2x", "sqrt(x)"], answer: 0 },
    { id: "G9-MA-87", grade: 9, subject: "Math", topic: "Quadratics", question: "The solutions to a quadratic are also called roots or ___.", choices: ["Peaks", "Zeros", "Vertices", "Slopes"], answer: 1 },
    { id: "G9-MA-88", grade: 9, subject: "Math", topic: "Quadratics", question: "To solve x^2 = 25, take the ___ of both sides.", choices: ["Square", "Square Root", "Cube", "Factor"], answer: 1 },
    { id: "G9-MA-89", grade: 9, subject: "Math", topic: "Quadratics", question: "Solve x^2 - 9 = 0.", choices: ["x = 9", "x = 3", "x = 3 and -3", "No solution"], answer: 2 },
    { id: "G9-MA-90", grade: 9, subject: "Math", topic: "Radicals", question: "√9 + √16 =", choices: ["√25", "7", "5", "12"], answer: 1 },
    { id: "G9-MA-91", grade: 9, subject: "Math", topic: "Radicals", question: "Simplify 3√5 + 2√5.", choices: ["5√5", "6√5", "5√10", "32√5"], answer: 0 },
    { id: "G9-MA-92", grade: 9, subject: "Math", topic: "Quadratics", question: "What is the vertex of y = x^2?", choices: ["(1,1)", "(0,0)", "(0,1)", "(1,0)"], answer: 1 },
    { id: "G9-MA-93", grade: 9, subject: "Math", topic: "Quadratics", question: "Method of completing the ___ is used to solve quadratics.", choices: ["Circle", "Square", "Triangle", "Graph"], answer: 1 },
    { id: "G9-MA-94", grade: 9, subject: "Math", topic: "Quadratics", question: "The 'c' in ax^2 + bx + c represents the ___.", choices: ["Slope", "Y-intercept", "Vertex", "Root"], answer: 1 },
    { id: "G9-MA-95", grade: 9, subject: "Math", topic: "Radicals", question: "Is √2 a rational number?", choices: ["Yes", "No"], answer: 1 },
    { id: "G9-MA-96", grade: 9, subject: "Math", topic: "Quadratics", question: "A quadratic equation always has a degree of ___.", choices: ["1", "2", "3", "0"], answer: 1 },
    { id: "G9-MA-97", grade: 9, subject: "Math", topic: "Quadratics", question: "Vertex form of a quadratic is y = ___.", choices: ["a(x-h)^2 + k", "mx + b", "ax + b", "ax^2"], answer: 0 },
    { id: "G9-MA-98", grade: 9, subject: "Math", topic: "Radicals", question: "Rationalize the denominator of 1/√2.", choices: ["√2", "Power", "2", "1/2"], answer: 1 },
    { id: "G9-MA-99", grade: 9, subject: "Math", topic: "Quadratics", question: "If 'a' is large (e.g., 10), the parabola is ___.", choices: ["Wide", "Narrow", "Flat", "Upside down"], answer: 1 },
    { id: "G9-MA-100", grade: 9, subject: "Math", topic: "Quadratics", question: "If 'a' is a small fraction (e.g., 1/10), the parabola is ___.", choices: ["Narrow", "Wide", "Pointy", "Vertical"], answer: 1 }
];

module.exports = G9_MATH_COMPLETE;
