import { Question } from "./fallback-questions"

export const CURATED_TOPIC_QUESTIONS: { [key: string]: Question[] } = {
    // GRADE 1 MATH
    "numbers & counting": [
        { id: "g1_m1_1", question: "What number comes after 5?", options: ["4", "6", "3", "7"], correctIndex: 1 },
        { id: "g1_m1_2", question: "How many apples are there? 🍎🍎🍎", options: ["2", "4", "3", "5"], correctIndex: 2 },
        { id: "g1_m1_3", question: "Which number is bigger?", options: ["2", "1", "0", "3"], correctIndex: 3 },
        { id: "g1_m1_4", question: "Count the stars: ⭐⭐⭐⭐", options: ["3", "5", "4", "6"], correctIndex: 2 },
        { id: "g1_m1_5", question: "What number comes before 10?", options: ["11", "8", "9", "7"], correctIndex: 2 },
        { id: "g1_m1_6", question: "Which number is smallest?", options: ["5", "2", "1", "3"], correctIndex: 2 },
        { id: "g1_m1_7", question: "How many fingers are on one hand?", options: ["6", "4", "5", "3"], correctIndex: 2 },
        { id: "g1_m1_8", question: "What number matches this word: 'seven'?", options: ["6", "8", "9", "7"], correctIndex: 3 },
        { id: "g1_m1_9", question: "Which shows five objects?", options: ["●●●", "●●●●", "●●●●●", "●●"], correctIndex: 2 },
        { id: "g1_m1_10", question: "What comes next: 1, 2, 3, ___", options: ["5", "6", "4", "2"], correctIndex: 2 },
        { id: "g1_m1_11", question: "How many dots? ●●●●●●", options: ["5", "6", "7", "4"], correctIndex: 1 },
        { id: "g1_m1_12", question: "Which number is ten?", options: ["1", "0", "10", "100"], correctIndex: 2 },
        { id: "g1_m1_13", question: "What number comes after 8?", options: ["7", "9", "10", "6"], correctIndex: 1 },
        { id: "g1_m1_14", question: "Which is the smallest number?", options: ["4", "7", "2", "9"], correctIndex: 2 },
        { id: "g1_m1_15", question: "How many sides does a triangle have?", options: ["2", "4", "3", "5"], correctIndex: 2 },
        { id: "g1_m1_16", question: "Count the moons: 🌙🌙", options: ["1", "2", "3", "0"], correctIndex: 1 },
        { id: "g1_m1_17", question: "What number comes before 2?", options: ["0", "1", "3", "2"], correctIndex: 1 },
        { id: "g1_m1_18", question: "Which number is eight?", options: ["6", "7", "8", "9"], correctIndex: 2 },
        { id: "g1_m1_19", question: "How many legs does a dog have?", options: ["2", "4", "6", "0"], correctIndex: 1 },
        { id: "g1_m1_20", question: "What is zero plus one?", options: ["0", "2", "1", "10"], correctIndex: 2 },
        { id: "g1_m1_21", question: "Which number is between 3 and 5?", options: ["2", "4", "6", "1"], correctIndex: 1 },
        { id: "g1_m1_22", question: "Count the bees: 🐝🐝🐝🐝🐝", options: ["4", "6", "5", "3"], correctIndex: 2 },
        { id: "g1_m1_23", question: "What number comes after 19?", options: ["18", "21", "20", "22"], correctIndex: 2 },
        { id: "g1_m1_24", question: "Which number is less than 5?", options: ["6", "8", "3", "10"], correctIndex: 2 },
        { id: "g1_m1_25", question: "Count to three: 1, 2, ___", options: ["4", "5", "3", "2"], correctIndex: 2 },
    ],
    "addition & subtraction": [
        { id: "g1_m2_1", question: "What is 2 + 3?", options: ["4", "5", "6", "3"], correctIndex: 1 },
        { id: "g1_m2_2", question: "What is 7 – 4?", options: ["3", "2", "4", "5"], correctIndex: 0 },
        { id: "g1_m2_3", question: "Add: 5 + 1 = ?", options: ["6", "5", "7", "4"], correctIndex: 0 },
        { id: "g1_m2_4", question: "Subtract: 9 – 5 = ?", options: ["3", "4", "5", "6"], correctIndex: 1 },
        { id: "g1_m2_5", question: "What is 1 + 6?", options: ["7", "6", "8", "5"], correctIndex: 0 },
        { id: "g1_m2_6", question: "8 – 2 = ?", options: ["5", "6", "7", "4"], correctIndex: 1 },
        { id: "g1_m2_7", question: "Add: 3 + 3 = ?", options: ["5", "6", "4", "7"], correctIndex: 1 },
        { id: "g1_m2_8", question: "Subtract: 10 – 7 = ?", options: ["2", "3", "4", "5"], correctIndex: 1 },
        { id: "g1_m2_9", question: "What is 4 + 4?", options: ["7", "8", "9", "6"], correctIndex: 1 },
        { id: "g1_m2_10", question: "6 – 1 = ?", options: ["4", "5", "6", "3"], correctIndex: 1 },
        { id: "g1_m2_11", question: "What is 1 + 1?", options: ["1", "2", "3", "0"], correctIndex: 1 },
        { id: "g1_m2_12", question: "What is 10 – 1?", options: ["8", "9", "7", "11"], correctIndex: 1 },
        { id: "g1_m2_13", question: "Add: 2 + 2 = ?", options: ["3", "4", "5", "2"], correctIndex: 1 },
        { id: "g1_m2_14", question: "Subtract: 5 – 5 = ?", options: ["1", "5", "0", "10"], correctIndex: 2 },
        { id: "g1_m2_15", question: "What is 4 + 1?", options: ["3", "5", "6", "4"], correctIndex: 1 },
        { id: "g1_m2_16", question: "8 + 0 = ?", options: ["0", "8", "80", "7"], correctIndex: 1 },
        { id: "g1_m2_17", question: "Subtract: 3 – 1 = ?", options: ["2", "1", "4", "0"], correctIndex: 0 },
        { id: "g1_m2_18", question: "What is 7 + 2?", options: ["8", "10", "9", "72"], correctIndex: 2 },
        { id: "g1_m2_19", question: "10 – 5 = ?", options: ["5", "4", "6", "15"], correctIndex: 0 },
        { id: "g1_m2_20", question: "Add: 6 + 3 = ?", options: ["8", "9", "10", "7"], correctIndex: 1 },
        { id: "g1_m2_21", question: "What is 4 – 2?", options: ["1", "3", "2", "0"], correctIndex: 2 },
        { id: "g1_m2_22", question: "5 + 5 = ?", options: ["15", "11", "10", "20"], correctIndex: 2 },
        { id: "g1_m2_23", question: "Subtract: 6 – 4 = ?", options: ["1", "3", "2", "4"], correctIndex: 2 },
        { id: "g1_m2_24", question: "What is 3 + 2?", options: ["4", "5", "6", "32"], correctIndex: 1 },
        { id: "g1_m2_25", question: "9 – 1 = ?", options: ["7", "8", "9", "10"], correctIndex: 1 },
    ],
    "place value": [
        { id: "g1_m3_1", question: "What is the value of the 3 in 34?", options: ["30", "3", "300", "4"], correctIndex: 0 },
        { id: "g1_m3_2", question: "What is the value of the 7 in 72?", options: ["7", "70", "17", "2"], correctIndex: 1 },
        { id: "g1_m3_3", question: "In 56, which number is in the tens place?", options: ["5", "6", "50", "60"], correctIndex: 0 },
        { id: "g1_m3_4", question: "In 48, which number is in the ones place?", options: ["4", "8", "48", "40"], correctIndex: 1 },
        { id: "g1_m3_5", question: "What number has 2 tens and 3 ones?", options: ["23", "32", "25", "20"], correctIndex: 0 },
        { id: "g1_m3_6", question: "What number has 4 tens and 5 ones?", options: ["45", "54", "40", "50"], correctIndex: 0 },
        { id: "g1_m3_7", question: "Which number is bigger, 41 or 14?", options: ["14", "41", "40", "24"], correctIndex: 1 },
        { id: "g1_m3_8", question: "Which number is smaller, 36 or 63?", options: ["63", "36", "33", "63"], correctIndex: 1 },
        { id: "g1_m3_9", question: "What is the tens digit in 29?", options: ["2", "9", "20", "19"], correctIndex: 0 },
        { id: "g1_m3_10", question: "What is the ones digit in 57?", options: ["5", "7", "50", "57"], correctIndex: 1 },
        { id: "g1_m3_11", question: "How many tens are in 20?", options: ["0", "2", "1", "10"], correctIndex: 1 },
        { id: "g1_m3_12", question: "What number has 6 tens and 0 ones?", options: ["6", "60", "66", "16"], correctIndex: 1 },
        { id: "g1_m3_13", question: "Which is the ones place in 19?", options: ["1", "9", "10", "19"], correctIndex: 1 },
        { id: "g1_m3_14", question: "What is 10 + 4?", options: ["10", "14", "41", "4"], correctIndex: 1 },
        { id: "g1_m3_15", question: "Which is the tens place in 82?", options: ["8", "2", "80", "20"], correctIndex: 0 },
        { id: "g1_m3_16", question: "How many ones are in 15?", options: ["1", "5", "10", "0"], correctIndex: 1 },
        { id: "g1_m3_17", question: "What is 3 tens?", options: ["3", "13", "30", "33"], correctIndex: 2 },
        { id: "g1_m3_18", question: "What number is one more than 29?", options: ["28", "30", "31", "20"], correctIndex: 1 },
        { id: "g1_m3_19", question: "What is 7 tens and 2 ones?", options: ["7", "27", "72", "70"], correctIndex: 2 },
        { id: "g1_m3_20", question: "Which is smaller: 25 or 52?", options: ["25", "52", "20", "50"], correctIndex: 0 },
        { id: "g1_m3_21", question: "What number comes after 99?", options: ["90", "100", "101", "89"], correctIndex: 1 },
        { id: "g1_m3_22", question: "How many tens in 50?", options: ["5", "10", "50", "1"], correctIndex: 0 },
        { id: "g1_m3_23", question: "In 43, what does the 4 represent?", options: ["4", "40", "43", "34"], correctIndex: 1 },
        { id: "g1_m3_24", question: "What is 1 ten and 1 one?", options: ["1", "2", "11", "10"], correctIndex: 2 },
        { id: "g1_m3_25", question: "Which has 8 tens?", options: ["8", "18", "80", "88"], correctIndex: 2 },
    ],
    "measurement": [
        { id: "g1_m4_1", question: "Which is longer?", options: ["Pencil", "Crayon", "Eraser", "Paper"], correctIndex: 0 },
        { id: "g1_m4_2", question: "Which is heavier?", options: ["Feather", "Rock", "Leaf", "Paper"], correctIndex: 1 },
        { id: "g1_m4_3", question: "Which cup can hold more water?", options: ["Small cup", "Big cup", "Tiny cup", "Plate"], correctIndex: 1 },
        { id: "g1_m4_4", question: "Which is shorter?", options: ["Table", "Chair", "Bed", "Door"], correctIndex: 1 },
        { id: "g1_m4_5", question: "Which is lighter?", options: ["Book", "Balloon", "Rock", "Box"], correctIndex: 1 },
        { id: "g1_m4_6", question: "Which ruler is longer?", options: ["10 cm", "30 cm", "5 cm", "15 cm"], correctIndex: 1 },
        { id: "g1_m4_7", question: "Which is taller?", options: ["Dog", "Tree", "Cat", "Chair"], correctIndex: 1 },
        { id: "g1_m4_8", question: "Which container holds less?", options: ["Small cup", "Big cup", "Bottle", "Jar"], correctIndex: 0 },
        { id: "g1_m4_9", question: "Which is shorter?", options: ["Pencil", "Marker", "Eraser", "Pen"], correctIndex: 2 },
        { id: "g1_m4_10", question: "Which is heavier?", options: ["Paper", "Stone", "Leaf", "Feather"], correctIndex: 1 },
        { id: "g1_m4_11", question: "Which is taller than a cat?", options: ["Ant", "Mouse", "Giraffe", "Bug"], correctIndex: 2 },
        { id: "g1_m4_12", question: "Which can hold the most juice?", options: ["Spoon", "Cup", "Bucket", "Thimble"], correctIndex: 2 },
        { id: "g1_m4_13", question: "Which is lighter than a house?", options: ["Mountain", "Cloud", "Ant", "Elephant"], correctIndex: 2 },
        { id: "g1_m4_14", question: "Which is longer than a finger?", options: ["Hair", "Toe", "Arm", "Nail"], correctIndex: 2 },
        { id: "g1_m4_15", question: "Which is shorter than a tree?", options: ["Skyscraper", "Flower", "Mountain", "Cloud"], correctIndex: 1 },
        { id: "g1_m4_16", question: "Which container is the smallest?", options: ["Teacup", "Jug", "Bathtub", "Pool"], correctIndex: 0 },
        { id: "g1_m4_17", question: "Which is heavier than a book?", options: ["Paper", "Pen", "Car", "Feather"], correctIndex: 2 },
        { id: "g1_m4_18", question: "Which animal is the tallest?", options: ["Dog", "Rabbit", "Giraffe", "Cat"], correctIndex: 2 },
        { id: "g1_m4_19", question: "Which is colder?", options: ["Ice", "Sun", "Fire", "Soup"], correctIndex: 0 },
        { id: "g1_m4_20", question: "Which is hotter?", options: ["Snow", "Fire", "Moon", "Rain"], correctIndex: 1 },
        { id: "g1_m4_21", question: "Which is faster?", options: ["Snail", "Turtle", "Rocket", "Bike"], correctIndex: 2 },
        { id: "g1_m4_22", question: "Which is slower?", options: ["Plane", "Car", "Snail", "Bird"], correctIndex: 2 },
        { id: "g1_m4_23", question: "Which is bigger?", options: ["Ant", "Elephant", "Bee", "Spider"], correctIndex: 1 },
        { id: "g1_m4_24", question: "Which is smaller?", options: ["House", "Dog", "Ant", "Car"], correctIndex: 2 },
        { id: "g1_m4_25", question: "Which is longer?", options: ["Snake", "Worm", "Ant", "Bug"], correctIndex: 0 },
    ],
    "shapes & geometry": [
        { id: "g1_m5_1", question: "Which shape has 3 sides?", options: ["Square", "Triangle", "Circle", "Rectangle"], correctIndex: 1 },
        { id: "g1_m5_2", question: "Which shape has 4 equal sides?", options: ["Triangle", "Square", "Circle", "Rectangle"], correctIndex: 1 },
        { id: "g1_m5_3", question: "Which shape is round?", options: ["Circle", "Square", "Triangle", "Rectangle"], correctIndex: 0 },
        { id: "g1_m5_4", question: "Which shape has 4 sides but not all equal?", options: ["Triangle", "Rectangle", "Circle", "Square"], correctIndex: 1 },
        { id: "g1_m5_5", question: "Which shape has no corners?", options: ["Circle", "Square", "Triangle", "Rectangle"], correctIndex: 0 },
        { id: "g1_m5_6", question: "Which shape has 3 corners?", options: ["Circle", "Triangle", "Square", "Rectangle"], correctIndex: 1 },
        { id: "g1_m5_7", question: "Which shape looks like a door?", options: ["Circle", "Triangle", "Rectangle", "Square"], correctIndex: 2 },
        { id: "g1_m5_8", question: "Which shape has all sides equal?", options: ["Rectangle", "Triangle", "Square", "Circle"], correctIndex: 2 },
        { id: "g1_m5_9", question: "Which shape has one curved side?", options: ["Circle", "Square", "Triangle", "Rectangle"], correctIndex: 0 },
        { id: "g1_m5_10", question: "Which shape has four corners?", options: ["Circle", "Triangle", "Square", "Oval"], correctIndex: 2 },
        { id: "g1_m5_11", question: "How many sides does a rectangle have?", options: ["3", "4", "5", "6"], correctIndex: 1 },
        { id: "g1_m5_12", question: "Which shape looks like a ball?", options: ["Square", "Circle/Sphere", "Triangle", "Cube"], correctIndex: 1 },
        { id: "g1_m5_13", question: "Which shape looks like a slice of pizza?", options: ["Square", "Triangle", "Circle", "Oval"], correctIndex: 1 },
        { id: "g1_m5_14", question: "Which shape looks like a window?", options: ["Circle", "Square", "Triangle", "Heart"], correctIndex: 1 },
        { id: "g1_m5_15", question: "How many corners does a circle have?", options: ["0", "1", "2", "3"], correctIndex: 0 },
        { id: "g1_m5_16", question: "Which shape is like a diamond?", options: ["Circle", "Square", "Rhombus", "Triangle"], correctIndex: 2 },
        { id: "g1_m5_17", question: "How many sides does a square have?", options: ["2", "3", "4", "5"], correctIndex: 2 },
        { id: "g1_m5_18", question: "Which shape is like a star?", options: ["Circle", "Star", "Square", "Oval"], correctIndex: 1 },
        { id: "g1_m5_19", question: "Which shape is like a moon?", options: ["Crescent", "Circle", "Triangle", "Square"], correctIndex: 0 },
        { id: "g1_m5_20", question: "Which shape has 5 sides?", options: ["Square", "Pentagon", "Hexagon", "Triangle"], correctIndex: 1 },
        { id: "g1_m5_21", question: "Which shape has 6 sides?", options: ["Square", "Pentagon", "Hexagon", "Triangle"], correctIndex: 2 },
        { id: "g1_m5_22", question: "Which is a 3D shape?", options: ["Square", "Circle", "Cube", "Triangle"], correctIndex: 2 },
        { id: "g1_m5_23", question: "What shape is a TV screen usually?", options: ["Triangle", "Rectangle", "Circle", "Oval"], correctIndex: 1 },
        { id: "g1_m5_24", question: "Which shape has 8 sides?", options: ["Octagon", "Hexagon", "Square", "Circle"], correctIndex: 0 },
        { id: "g1_m5_25", question: "Which shape is like an egg?", options: ["Circle", "Oval", "Square", "Triangle"], correctIndex: 1 },
    ],
    "time & money": [
        { id: "g1_m6_1", question: "How many hours are in a day?", options: ["12", "24", "10", "20"], correctIndex: 1 },
        { id: "g1_m6_2", question: "How many minutes are in one hour?", options: ["60", "50", "100", "10"], correctIndex: 0 },
        { id: "g1_m6_3", question: "What coin is worth 1 cent?", options: ["Penny", "Nickel", "Dime", "Quarter"], correctIndex: 0 },
        { id: "g1_m6_4", question: "What coin is worth 5 cents?", options: ["Penny", "Nickel", "Dime", "Quarter"], correctIndex: 1 },
        { id: "g1_m6_5", question: "What coin is worth 10 cents?", options: ["Penny", "Nickel", "Dime", "Quarter"], correctIndex: 2 },
        { id: "g1_m6_6", question: "What coin is worth 25 cents?", options: ["Nickel", "Dime", "Penny", "Quarter"], correctIndex: 3 },
        { id: "g1_m6_7", question: "What time shows 3:00?", options: ["Hour hand on 3, minute hand on 12", "Hour hand on 12, minute hand on 3", "Hour hand on 6, minute hand on 12", "Hour hand on 3, minute hand on 6"], correctIndex: 0 },
        { id: "g1_m6_8", question: "How many quarters make 1 dollar?", options: ["2", "4", "5", "10"], correctIndex: 1 },
        { id: "g1_m6_9", question: "If it is 7:00 in the morning, what part of the day is it?", options: ["Morning", "Afternoon", "Night", "Evening"], correctIndex: 0 },
        { id: "g1_m6_10", question: "If you have 2 dimes and 1 nickel, how much money do you have?", options: ["25 cents", "15 cents", "10 cents", "20 cents"], correctIndex: 0 },
        { id: "g1_m6_11", question: "What time is it if the big hand is on 12 and small hand on 6?", options: ["6:00", "12:00", "12:30", "6:30"], correctIndex: 0 },
        { id: "g1_m6_12", question: "How many cents in a dollar?", options: ["10", "50", "100", "1000"], correctIndex: 2 },
        { id: "g1_m6_13", question: "Which day comes after Monday?", options: ["Sunday", "Tuesday", "Friday", "Saturday"], correctIndex: 1 },
        { id: "g1_m6_14", question: "How many months are in a year?", options: ["10", "12", "7", "31"], correctIndex: 1 },
        { id: "g1_m6_15", question: "Which coin has Abraham Lincoln on it?", options: ["Penny", "Nickel", "Dime", "Quarter"], correctIndex: 0 },
        { id: "g1_m6_16", question: "Which month is usually the coldest?", options: ["July", "January", "June", "August"], correctIndex: 1 },
        { id: "g1_m6_17", question: "How many days are in a week?", options: ["5", "6", "7", "8"], correctIndex: 2 },
        { id: "g1_m6_18", question: "What do you use to buy toys?", options: ["Leaves", "Money", "Stones", "Sand"], correctIndex: 1 },
        { id: "g1_m6_19", question: "Which is more: 1 dime or 1 nickel?", options: ["Dime", "Nickel", "They are same", "Neither"], correctIndex: 0 },
        { id: "g1_m6_20", question: "What time do most people eat breakfast?", options: ["Morning", "Night", "Afternoon", "Midnight"], correctIndex: 0 },
        { id: "g1_m6_21", question: "Which season comes after Winter?", options: ["Fall", "Spring", "Summer", "Autumn"], correctIndex: 1 },
        { id: "g1_m6_22", question: "Which coin is silver and small?", options: ["Penny", "Dime", "Nickel", "Quarter"], correctIndex: 1 },
        { id: "g1_m6_23", question: "How many nickels make a dime?", options: ["1", "2", "5", "10"], correctIndex: 1 },
        { id: "g1_m6_24", question: "Which day is part of the weekend?", options: ["Monday", "Friday", "Saturday", "Wednesday"], correctIndex: 2 },
        { id: "g1_m6_25", question: "What time is 'half past one'?", options: ["1:00", "1:30", "2:00", "12:30"], correctIndex: 1 },
    ],
    // GRADE 2 ELA
    "sentence structure": [
        { id: "g2_e1_1", question: "Which is a complete sentence?", options: ["The big dog", "The dog barked.", "Barked loudly", "Dog big."], correctIndex: 1 },
        { id: "g2_e1_2", question: "Which word should be capitalized?", options: ["apple", "london", "table", "chair"], correctIndex: 1 },
        { id: "g2_e1_3", question: "Which marks the end of a question?", options: [".", "?", "!", ","], correctIndex: 1 },
        { id: "g2_e1_4", question: "Which is a noun?", options: ["Run", "Happy", "Book", "Quickly"], correctIndex: 2 },
        { id: "g2_e1_5", question: "Which is a verb?", options: ["Blue", "Jump", "Apple", "Soft"], correctIndex: 1 },
        { id: "g2_e1_6", question: "Which is an adjective?", options: ["Dog", "Brave", "Run", "Fastly"], correctIndex: 1 },
        { id: "g2_e1_7", question: "Choose the correct verb: 'The cat ___ on the mat.'", options: ["sit", "sits", "sitting", "sitted"], correctIndex: 1 },
        { id: "g2_e1_8", question: "Which sentence has correct punctuation?", options: ["Where are you.", "Where are you?", "Where are you!", "where are you"], correctIndex: 1 },
        { id: "g2_e1_9", question: "Identify the subject: 'The bird sings.'", options: ["The", "Bird", "Sings", "The bird"], correctIndex: 1 },
        { id: "g2_e1_10", question: "Which word is a pronoun?", options: ["Tree", "He", "Fast", "Green"], correctIndex: 1 },
        { id: "g2_e1_11", question: "What should every sentence end with?", options: ["A capital letter", "Punctuation", "A comma", "A space"], correctIndex: 1 },
        { id: "g2_e1_12", question: "Which is a plural noun?", options: ["Cat", "Dogs", "Run", "Blue"], correctIndex: 1 },
        { id: "g2_e1_13", question: "Choose the correct pronoun: '___ is my friend.'", options: ["Them", "She", "Us", "Me"], correctIndex: 1 },
        { id: "g2_e1_14", question: "Which word is a verb?", options: ["Softly", "Drink", "Paper", "Red"], correctIndex: 1 },
        { id: "g2_e1_15", question: "Which word is an adjective?", options: ["Go", "Funny", "Table", "Quickly"], correctIndex: 1 },
        { id: "g2_e1_16", question: "What is the opposite of 'hot'?", options: ["Warm", "Sun", "Cold", "Ice"], correctIndex: 2 },
        { id: "g2_e1_17", question: "Which word is spelled correctly?", options: ["Happie", "Happy", "Hapy", "Happei"], correctIndex: 1 },
        { id: "g2_e1_18", question: "Identify the verb: 'They dance together.'", options: ["They", "Dance", "Together", "None"], correctIndex: 1 },
        { id: "g2_e1_19", question: "Which is a compound word?", options: ["House", "Dog", "Doghouse", "Garden"], correctIndex: 2 },
        { id: "g2_e1_20", question: "Which word is an antonym of 'fast'?", options: ["Quick", "Slow", "Run", "Speedy"], correctIndex: 1 },
        { id: "g2_e1_21", question: "Where do you put a comma in a list?", options: ["Between items", "At the end", "At the start", "Nowhere"], correctIndex: 0 },
        { id: "g2_e1_22", question: "Which is a synonym for 'happy'?", options: ["Sad", "Glad", "Angry", "Tired"], correctIndex: 1 },
        { id: "g2_e1_23", question: "What type of sentence is: 'Stop that!'", options: ["Question", "Exclamation", "Statement", "Greeting"], correctIndex: 1 },
        { id: "g2_e1_24", question: "Find the adjective: 'The little cat.'", options: ["The", "Little", "Cat", "None"], correctIndex: 1 },
        { id: "g2_e1_25", question: "Which word is a proper noun?", options: ["Boy", "Monday", "Month", "Day"], correctIndex: 1 },
    ],
    "reading comprehension (stories)": [
        { id: "g2_e2_1", question: "Where does the story usually start?", options: ["Middle", "Beginning", "End", "Nowhere"], correctIndex: 1 },
        { id: "g2_e2_2", question: "What is the people in the story called?", options: ["Settings", "Characters", "Plots", "Titles"], correctIndex: 1 },
        { id: "g2_e2_3", question: "What is where the story happens called?", options: ["Plot", "Setting", "Character", "Ending"], correctIndex: 1 },
        { id: "g2_e2_4", question: "What is the main idea?", options: ["The first word", "What the story is about", "The characters' names", "The ending"], correctIndex: 1 },
        { id: "g2_e2_5", question: "Who tells the story?", options: ["Character", "Narrator", "Reader", "Villain"], correctIndex: 1 },
        { id: "g2_e2_6", question: "What is the problem in a story called?", options: ["Conflict", "Solution", "Setting", "Theme"], correctIndex: 0 },
        { id: "g2_e2_7", question: "What happens at the end of the story?", options: ["Introduction", "Resolution", "Climax", "Rising action"], correctIndex: 1 },
        { id: "g2_e2_8", question: "Which part of the book tells you the name?", options: ["Title", "Author", "Page", "Cover"], correctIndex: 0 },
        { id: "g2_e2_9", question: "Who writes the book?", options: ["Author", "Illustrator", "Character", "Narrator"], correctIndex: 0 },
        { id: "g2_e2_10", question: "What are the pictures in a book called?", options: ["Words", "Illustrations", "Pages", "Chapters"], correctIndex: 1 },
        { id: "g2_e2_11", question: "What is the lesson of a story called?", options: ["Summary", "Moral/Theme", "Setting", "Title"], correctIndex: 1 },
        { id: "g2_e2_12", question: "Which part of a story tells how the problem was fixed?", options: ["Beginning", "Resolution", "Conflict", "Introduction"], correctIndex: 1 },
        { id: "g2_e2_13", question: "What is a group of lines in a poem called?", options: ["Sentence", "Stanza", "Chapter", "Paragraph"], correctIndex: 1 },
        { id: "g2_e2_14", question: "Which is a make-believe story?", options: ["History", "Fiction", "Non-fiction", "Fact"], correctIndex: 1 },
        { id: "g2_e2_15", question: "Which is a true story?", options: ["Fiction", "Non-fiction", "Fairy tale", "Myth"], correctIndex: 1 },
        { id: "g2_e2_16", question: "What is a table of contents used for?", options: ["Finding pages", "Reading the story", "Drawing", "Writing"], correctIndex: 0 },
        { id: "g2_e2_17", question: "What is the back of the book called?", options: ["Front cover", "Back cover", "Title page", "Spine"], correctIndex: 1 },
        { id: "g2_e2_18", question: "What is the person who draws pictures for a book?", options: ["Author", "Illustrator", "Publisher", "Printer"], correctIndex: 1 },
        { id: "g2_e2_19", question: "What is the order of events in a story?", options: ["Setting", "Plot/Sequence", "Conflict", "Resolution"], correctIndex: 1 },
        { id: "g2_e2_20", question: "What do we call the conversation between characters?", options: ["Narrative", "Dialogue", "Paragraph", "Chapter"], correctIndex: 1 },
        { id: "g2_e2_21", question: "What is an index found in?", options: ["Fiction", "Non-fiction", "Poetry", "Songs"], correctIndex: 1 },
        { id: "g2_e2_22", question: "Which word describes a person in a story?", options: ["Place", "Character", "Event", "Time"], correctIndex: 1 },
        { id: "g2_e2_23", question: "What is a short writing about the main points?", options: ["Detail", "Summary", "Sentence", "Letter"], correctIndex: 1 },
        { id: "g2_e2_24", question: "What is a story passed down over time?", options: ["News", "Folktale", "Recipe", "Email"], correctIndex: 1 },
        { id: "g2_e2_25", question: "What part of a book tells the name of each chapter?", options: ["Index", "Table of Contents", "Glossary", "Cover"], correctIndex: 1 },
    ],
    "science topics (mammals)": [
        { id: "g2_s1_1", question: "Which is a mammal?", options: ["Frog", "Snake", "Cat", "Fish"], correctIndex: 2 },
        { id: "g2_s1_2", question: "What do mammals have on their bodies?", options: ["Feathers", "Scales", "Hair or fur", "Shells"], correctIndex: 2 },
        { id: "g2_s1_3", question: "How do mammals breathe?", options: ["Gills", "Lungs", "Skin", "Wings"], correctIndex: 1 },
        { id: "g2_s1_4", question: "Which mammal lives in the ocean?", options: ["Shark", "Whale", "Fish", "Crab"], correctIndex: 1 },
        { id: "g2_s1_5", question: "Do mammals lay eggs usually?", options: ["Yes", "No", "Sometimes", "Only in water"], correctIndex: 1 },
        { id: "g2_s1_6", question: "Which is NOT a mammal?", options: ["Dog", "Human", "Bird", "Elephant"], correctIndex: 2 },
        { id: "g2_s1_7", question: "What do baby mammals drink?", options: ["Water", "Milk", "Juice", "Soda"], correctIndex: 1 },
        { id: "g2_s1_8", question: "Are humans mammals?", options: ["Yes", "No", "Maybe", "Only adults"], correctIndex: 0 },
        { id: "g2_s1_9", question: "Which mammal can fly?", options: ["Bird", "Bat", "Squirrel", "Eagle"], correctIndex: 1 },
        { id: "g2_s1_10", question: "Which is a very large mammal?", options: ["Mouse", "Blue Whale", "Ant", "Cat"], correctIndex: 1 },
        { id: "g2_s1_11", question: "Which mammal has a trunk?", options: ["Elephant", "Lion", "Giraffe", "Zebra"], correctIndex: 0 },
        { id: "g2_s1_12", question: "What do mammals use to feed their babies?", options: ["Leaves", "Milk", "Seeds", "Water"], correctIndex: 1 },
        { id: "g2_s1_13", question: "Which of these is a warm-blooded animal?", options: ["Snake", "Lizard", "Dog", "Turtle"], correctIndex: 2 },
        { id: "g2_s1_14", question: "Which mammal lives in a hole in the ground?", options: ["Bird", "Rabbit", "Fish", "Butterfly"], correctIndex: 1 },
        { id: "g2_s1_15", question: "Which mammal is known for having a long neck?", options: ["Elephant", "Giraffe", "Horse", "Bear"], correctIndex: 1 },
        { id: "g2_s1_16", question: "Do mammals have backbones?", options: ["Yes", "No", "Only some", "Only whales"], correctIndex: 0 },
        { id: "g2_s1_17", question: "Which is a small mammal that likes cheese?", options: ["Lion", "Mouse", "Wolf", "Horse"], correctIndex: 1 },
        { id: "g2_s1_18", question: "Which mammal can swim very well?", options: ["Squirrel", "Otter/Dolphin", "Chicken", "Spider"], correctIndex: 1 },
        { id: "g2_s1_19", question: "What is the fastest land mammal?", options: ["Turtle", "Cheetah", "Elephant", "Dog"], correctIndex: 1 },
        { id: "g2_s1_20", question: "Which mammal has stripes?", options: ["Zebra", "Lion", "Elephant", "Bear"], correctIndex: 0 },
        { id: "g2_s1_21", question: "Which mammal lives in the jungle?", options: ["Polar Bear", "Monkey", "Camel", "Penguin"], correctIndex: 1 },
        { id: "g2_s1_22", question: "Which mammal likes to eat bamboo?", options: ["Panda", "Tiger", "Fox", "Rabbit"], correctIndex: 0 },
        { id: "g2_s1_23", question: "Which mammal hibernates in winter?", options: ["Dog", "Bear", "Cat", "Bird"], correctIndex: 1 },
        { id: "g2_s1_24", question: "How many legs do most mammals have?", options: ["2", "4", "6", "8"], correctIndex: 1 },
        { id: "g2_s1_25", question: "Which mammal is the 'King of the Jungle'?", options: ["Tiger", "Lion", "Gorilla", "Elephant"], correctIndex: 1 },
    ],
    "government & laws": [
        { id: "g2_ss1_1", question: "Who is the leader of a country?", options: ["Mayor", "Governor", "President", "Teacher"], correctIndex: 2 },
        { id: "g2_ss1_2", question: "Where does the President live?", options: ["The Blue House", "The White House", "The Red House", "The Capitol"], correctIndex: 1 },
        { id: "g2_ss1_3", question: "Who makes the laws?", options: ["Police", "Congress", "Students", "Pets"], correctIndex: 1 },
        { id: "g2_ss1_4", question: "Why do we have laws?", options: ["To be mean", "To keep order and safety", "To play games", "To sleep"], correctIndex: 1 },
        { id: "g2_ss1_5", question: "Who is the leader of a city?", options: ["President", "Governor", "Mayor", "Principal"], correctIndex: 2 },
        { id: "g2_ss1_6", question: "What is the capital of the USA?", options: ["New York", "Washington D.C.", "Los Angeles", "Chicago"], correctIndex: 1 },
        { id: "g2_ss1_7", question: "What is the name of the law book of the USA?", options: ["Declaration", "Constitution", "Bible", "Dictionary"], correctIndex: 1 },
        { id: "g2_ss1_8", question: "How often do we elect a President?", options: ["Every year", "Every 4 years", "Every 10 years", "Never"], correctIndex: 1 },
        { id: "g2_ss1_9", question: "Which flag represents the USA?", options: ["Stars & Stripes", "Tricolor", "Union Jack", "Maple Leaf"], correctIndex: 0 },
        { id: "g2_ss1_10", question: "What color are the stars on the US flag?", options: ["Red", "White", "Blue", "Yellow"], correctIndex: 1 },
        { id: "g2_ss1_11", question: "Who is the leader of a school?", options: ["Teacher", "Principal", "Mayor", "Student"], correctIndex: 1 },
        { id: "g2_ss1_12", question: "Where do laws get followed?", options: ["Only at home", "Everywhere", "Only at school", "Nowhere"], correctIndex: 1 },
        { id: "g2_ss1_13", question: "Which of these is a right in the USA?", options: ["Stealing", "Freedom of Speech", "Fighting", "Breaking rules"], correctIndex: 1 },
        { id: "g2_ss1_14", question: "What is the name of the US national anthem?", options: ["The Star-Spangled Banner", "Happy Birthday", "Jingle Bells", "Twinkle Twinkle"], correctIndex: 0 },
        { id: "g2_ss1_15", question: "How many states are in the USA?", options: ["13", "50", "48", "52"], correctIndex: 1 },
        { id: "g2_ss1_16", question: "Who was the first President of the USA?", options: ["Lincoln", "Washington", "Jefferson", "Adams"], correctIndex: 1 },
        { id: "g2_ss1_17", question: "What animal is a symbol of the USA?", options: ["Lion", "Bald Eagle", "Panda", "Tiger"], correctIndex: 1 },
        { id: "g2_ss1_18", question: "Which month is Independence Day in?", options: ["June", "July", "August", "May"], correctIndex: 1 },
        { id: "g2_ss1_19", question: "What do we do during an election?", options: ["Sleep", "Vote", "Fight", "Run"], correctIndex: 1 },
        { id: "g2_ss1_20", question: "What is a community?", options: ["A group of people living together", "A single house", "A forest", "A planet"], correctIndex: 0 },
        { id: "g2_ss1_21", question: "Who helps keep us safe in the city?", options: ["Chef", "Police Officer", "Singer", "Clown"], correctIndex: 1 },
        { id: "g2_ss1_22", question: "What is the name of our planet?", options: ["Mars", "Venus", "Earth", "Saturn"], correctIndex: 2 },
        { id: "g2_ss1_23", question: "What do we call the rules of a country?", options: ["Games", "Laws", "Songs", "Stories"], correctIndex: 1 },
        { id: "g2_ss1_24", question: "Which city is the US capital?", options: ["New York", "Washington D.C.", "Miami", "Dallas"], correctIndex: 1 },
        { id: "g2_ss1_25", question: "How many stripes are on the US flag?", options: ["10", "13", "15", "50"], correctIndex: 1 },
    ],
    // GRADE 3 MATH
    "multiplication": [
        { id: "g3_m1_1", question: "What is 2 x 5?", options: ["7", "10", "12", "15"], correctIndex: 1 },
        { id: "g3_m1_2", question: "What is 3 x 4?", options: ["7", "12", "15", "10"], correctIndex: 1 },
        { id: "g3_m1_3", question: "What is 5 x 5?", options: ["20", "25", "30", "15"], correctIndex: 1 },
        { id: "g3_m1_4", question: "What is 10 x 3?", options: ["13", "30", "40", "103"], correctIndex: 1 },
        { id: "g3_m1_5", question: "What is 4 x 4?", options: ["8", "16", "20", "12"], correctIndex: 1 },
        { id: "g3_m1_6", question: "What is 6 x 2?", options: ["8", "12", "14", "10"], correctIndex: 1 },
        { id: "g3_m1_7", question: "What is 0 x 10?", options: ["10", "1", "0", "100"], correctIndex: 2 },
        { id: "g3_m1_8", question: "What is 1 x 9?", options: ["1", "9", "10", "0"], correctIndex: 1 },
        { id: "g3_m1_9", question: "What is 3 x 3?", options: ["6", "9", "12", "15"], correctIndex: 1 },
        { id: "g3_m1_10", question: "Which is the same as 2 + 2 + 2?", options: ["2 x 3", "2 x 2", "3 x 3", "2 + 3"], correctIndex: 0 },
        { id: "g3_m1_11", question: "What is 4 x 5?", options: ["15", "20", "25", "10"], correctIndex: 1 },
        { id: "g3_m1_12", question: "What is 6 x 3?", options: ["9", "18", "21", "12"], correctIndex: 1 },
        { id: "g3_m1_13", question: "What is 7 x 2?", options: ["12", "14", "16", "9"], correctIndex: 1 },
        { id: "g3_m1_14", question: "What is 8 x 5?", options: ["35", "40", "45", "30"], correctIndex: 1 },
        { id: "g3_m1_15", question: "What is 9 x 2?", options: ["11", "18", "20", "15"], correctIndex: 1 },
        { id: "g3_m1_16", question: "What is 10 x 5?", options: ["15", "50", "100", "55"], correctIndex: 1 },
        { id: "g3_m1_17", question: "What is 3 x 5?", options: ["8", "15", "10", "12"], correctIndex: 1 },
        { id: "g3_m1_18", question: "What is 2 x 9?", options: ["11", "18", "20", "7"], correctIndex: 1 },
        { id: "g3_m1_19", question: "What is 4 x 3?", options: ["7", "12", "15", "10"], correctIndex: 1 },
        { id: "g3_m1_20", question: "What is 5 x 2?", options: ["7", "10", "25", "5"], correctIndex: 1 },
        { id: "g3_m1_21", question: "What is 6 x 4?", options: ["10", "24", "28", "20"], correctIndex: 1 },
        { id: "g3_m1_22", question: "What is 7 x 3?", options: ["10", "21", "24", "14"], correctIndex: 1 },
        { id: "g3_m1_23", question: "What is 8 x 2?", options: ["10", "16", "18", "14"], correctIndex: 1 },
        { id: "g3_m1_24", question: "What is 9 x 3?", options: ["12", "27", "30", "21"], correctIndex: 1 },
        { id: "g3_m1_25", question: "What is 10 x 10?", options: ["20", "100", "1000", "10"], correctIndex: 1 },
    ],
    "division": [
        { id: "g3_m2_1", question: "What is 10 / 2?", options: ["2", "5", "10", "8"], correctIndex: 1 },
        { id: "g3_m2_2", question: "What is 12 / 3?", options: ["3", "4", "5", "6"], correctIndex: 1 },
        { id: "g3_m2_3", question: "What is 20 / 4?", options: ["4", "5", "10", "15"], correctIndex: 1 },
        { id: "g3_m2_4", question: "What is 15 / 5?", options: ["2", "3", "4", "5"], correctIndex: 1 },
        { id: "g3_m2_5", question: "What is 18 / 2?", options: ["7", "9", "10", "8"], correctIndex: 1 },
        { id: "g3_m2_6", question: "What is 8 / 4?", options: ["2", "4", "6", "8"], correctIndex: 0 },
        { id: "g3_m2_7", question: "What is 30 / 10?", options: ["2", "3", "4", "5"], correctIndex: 1 },
        { id: "g3_m2_8", question: "What is 9 / 3?", options: ["2", "3", "4", "5"], correctIndex: 1 },
        { id: "g3_m2_9", question: "What is 100 / 10?", options: ["1", "10", "100", "50"], correctIndex: 1 },
        { id: "g3_m2_10", question: "What is 14 / 2?", options: ["6", "7", "8", "9"], correctIndex: 1 },
        { id: "g3_m2_11", question: "What is 16 / 4?", options: ["2", "4", "6", "8"], correctIndex: 1 },
        { id: "g3_m2_12", question: "What is 25 / 5?", options: ["3", "5", "10", "15"], correctIndex: 1 },
        { id: "g3_m2_13", question: "What is 18 / 3?", options: ["4", "6", "8", "9"], correctIndex: 1 },
        { id: "g3_m2_14", question: "What is 21 / 3?", options: ["5", "7", "9", "6"], correctIndex: 1 },
        { id: "g3_m2_15", question: "What is 24 / 4?", options: ["4", "6", "8", "10"], correctIndex: 1 },
        { id: "g3_m2_16", question: "What is 27 / 3?", options: ["7", "9", "10", "8"], correctIndex: 1 },
        { id: "g3_m2_17", question: "What is 32 / 4?", options: ["6", "8", "9", "7"], correctIndex: 1 },
        { id: "g3_m2_18", question: "What is 36 / 4?", options: ["7", "9", "10", "8"], correctIndex: 1 },
        { id: "g3_m2_19", question: "What is 40 / 5?", options: ["6", "8", "10", "5"], correctIndex: 1 },
        { id: "g3_m2_20", question: "What is 45 / 5?", options: ["7", "9", "5", "10"], correctIndex: 1 },
        { id: "g3_m2_21", question: "What is 50 / 10?", options: ["2", "5", "10", "4"], correctIndex: 1 },
        { id: "g3_m2_22", question: "What is 8 / 2?", options: ["2", "4", "6", "8"], correctIndex: 1 },
        { id: "g3_m2_23", question: "What is 6 / 3?", options: ["1", "2", "3", "4"], correctIndex: 1 },
        { id: "g3_m2_24", question: "What is 4 / 2?", options: ["1", "2", "3", "4"], correctIndex: 1 },
        { id: "g3_m2_25", question: "What is 0 / 5?", options: ["5", "1", "0", "10"], correctIndex: 2 },
    ],
    "fractions": [
        { id: "g3_m3_1", question: "What is 1/2?", options: ["One whole", "Half", "Quarter", "One third"], correctIndex: 1 },
        { id: "g3_m3_2", question: "Which fraction is one quarter?", options: ["1/2", "1/3", "1/4", "1/5"], correctIndex: 2 },
        { id: "g3_m3_3", question: "If you cut a pizza into 4 equal pieces and eat 1, what fraction did you eat?", options: ["1/2", "1/3", "1/4", "3/4"], correctIndex: 2 },
        { id: "g3_m3_4", question: "Which is bigger?", options: ["1/2", "1/4", "1/8", "1/10"], correctIndex: 0 },
        { id: "g3_m3_5", question: "What is 3/3 equal to?", options: ["0", "1", "3", "1/3"], correctIndex: 1 },
        { id: "g3_m3_6", question: "How many halves make a whole?", options: ["1", "2", "3", "4"], correctIndex: 1 },
        { id: "g3_m3_7", question: "How many quarters make a whole?", options: ["2", "4", "6", "8"], correctIndex: 1 },
        { id: "g3_m3_8", question: "What fraction of a day is 12 hours?", options: ["1/2", "1/4", "1/3", "2/3"], correctIndex: 0 },
        { id: "g3_m3_9", question: "If you have 1/3 of a cake, how many pieces make the whole cake?", options: ["1", "2", "3", "4"], correctIndex: 2 },
        { id: "g3_m3_10", question: "Which is smaller?", options: ["1/2", "1/3", "1/4", "1/5"], correctIndex: 3 },
        { id: "g3_m3_11", question: "What is 2/2?", options: ["Half", "One whole", "Two wholes", "Zero"], correctIndex: 1 },
        { id: "g3_m3_12", question: "What is the top number of a fraction called?", options: ["Denominator", "Numerator", "Whole number", "Decimal"], correctIndex: 1 },
        { id: "g3_m3_13", question: "What is the bottom number of a fraction called?", options: ["Numerator", "Denominator", "Whole", "Part"], correctIndex: 1 },
        { id: "g3_m3_14", question: "Which fraction is the same as 1/2?", options: ["2/4", "1/3", "2/2", "1/4"], correctIndex: 0 },
        { id: "g3_m3_15", question: "How many thirds make a whole?", options: ["1", "2", "3", "4"], correctIndex: 2 },
        { id: "g3_m3_16", question: "Which is more: 3/4 or 1/4?", options: ["3/4", "1/4", "They are same", "Neither"], correctIndex: 0 },
        { id: "g3_m3_17", question: "What part of the circle is 1/4?", options: ["Half", "Quarter", "Whole", "None"], correctIndex: 1 },
        { id: "g3_m3_18", question: "What fraction is 'three out of five'?", options: ["5/3", "3/5", "1/3", "1/5"], correctIndex: 1 },
        { id: "g3_m3_19", question: "If a pizza has 8 slices and you eat 4, what fraction did you eat?", options: ["1/4", "1/2", "1/8", "3/8"], correctIndex: 1 },
        { id: "g3_m3_20", question: "Whic fraction means none?", options: ["1/1", "0/4", "4/4", "1/4"], correctIndex: 1 },
        { id: "g3_m3_21", question: "What is 2/4 simplified?", options: ["1/4", "1/2", "3/4", "2/2"], correctIndex: 1 },
        { id: "g3_m3_22", question: "How many eighths make a whole?", options: ["4", "6", "8", "10"], correctIndex: 2 },
        { id: "g3_m3_23", question: "Which is less: 1/10 or 1/2?", options: ["1/2", "1/10", "Same", "Neither"], correctIndex: 1 },
        { id: "g3_m3_24", question: "What is 1 minus 1/4?", options: ["1/4", "3/4", "2/4", "0"], correctIndex: 1 },
        { id: "g3_m3_25", question: "What do we call fractions that are the same value?", options: ["Equal", "Equivalent", "Different", "Opposite"], correctIndex: 1 },
    ],
    // GRADE 3 ELA
    "parts of speech (advanced)": [
        { id: "g3_e1_1", question: "Which is a common noun?", options: ["London", "City", "John", "Mars"], correctIndex: 1 },
        { id: "g3_e1_2", question: "Which is a proper noun?", options: ["street", "river", "Paris", "mountain"], correctIndex: 2 },
        { id: "g3_e1_3", question: "Which word is a conjunction?", options: ["Happy", "And", "Run", "Blue"], correctIndex: 1 },
        { id: "g3_e1_4", question: "Which word is a preposition?", options: ["Under", "Fast", "Jump", "Yellow"], correctIndex: 0 },
        { id: "g3_e1_5", question: "What is an adverb?", options: ["A person", "A word that describes a verb", "A color", "A shape"], correctIndex: 1 },
        { id: "g3_e1_6", question: "Which word is an adverb?", options: ["Quickly", "Fast", "Smart", "Big"], correctIndex: 0 },
        { id: "g3_e1_7", question: "Which is a pronoun?", options: ["Book", "They", "School", "Pencil"], correctIndex: 1 },
        { id: "g3_e1_8", question: "What is a plural noun for 'child'?", options: ["Childs", "Children", "Childes", "Cildren"], correctIndex: 1 },
        { id: "g3_e1_9", question: "Which is an adjective?", options: ["Delicious", "Eat", "Plate", "Fork"], correctIndex: 0 },
        { id: "g3_e1_10", question: "Which word is a verb in 'She runs'?", options: ["She", "Runs", "She runs", "None"], correctIndex: 1 },
        { id: "g3_e1_11", question: "Which is a plural of 'tooth'?", options: ["Tooths", "Teeth", "Toothes", "Teeths"], correctIndex: 1 },
        { id: "g3_e1_12", question: "Which is a plural of 'mouse'?", options: ["Mouses", "Mice", "Miceys", "Mousees"], correctIndex: 1 },
        { id: "g3_e1_13", question: "Which word is an interjection?", options: ["Wow!", "Run", "Green", "Slowly"], correctIndex: 0 },
        { id: "g3_e1_14", question: "Which word is a preposition in 'The cat is on the table'?", options: ["Cat", "On", "Table", "The"], correctIndex: 1 },
        { id: "g3_e1_15", question: "Which is a synonym for 'large'?", options: ["Small", "Tiny", "Huge", "Thin"], correctIndex: 2 },
        { id: "g3_e1_16", question: "Which is an antonym for 'brave'?", options: ["Strong", "Cowardly", "Smart", "Happy"], correctIndex: 1 },
        { id: "g3_e1_17", question: "What is the past tense of 'see'?", options: ["Seed", "Saw", "Seen", "Seeing"], correctIndex: 1 },
        { id: "g3_e1_18", question: "What is the past tense of 'go'?", options: ["Goed", "Went", "Gone", "Going"], correctIndex: 1 },
        { id: "g3_e1_19", question: "Which sentence is a question?", options: ["Run fast.", "How are you?", "Stop that!", "I am here."], correctIndex: 1 },
        { id: "g3_e1_20", question: "Which word should be capitalized in 'we live in america'?", options: ["we", "live", "america", "we & america"], correctIndex: 2 },
        { id: "g3_e1_21", question: "Which is a collective noun?", options: ["Dog", "Team", "Person", "Tree"], correctIndex: 1 },
        { id: "g3_e1_22", question: "Which word is an adjective in 'The blue sky'?", options: ["The", "Blue", "Sky", "None"], correctIndex: 1 },
        { id: "g3_e1_23", question: "Which is a compound word?", options: ["Rain", "Bow", "Rainbow", "Cloud"], correctIndex: 2 },
        { id: "g3_e1_24", question: "What is the root word of 'unhappy'?", options: ["Un", "Happy", "Appy", "Happily"], correctIndex: 1 },
        { id: "g3_e1_25", question: "Which word is an adverb in 'He sang loudly'?", options: ["He", "Sang", "Loudly", "None"], correctIndex: 2 },
    ],
    // GRADE 3 SCIENCE
    "solar system": [
        { id: "g3_s1_1", question: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Earth"], correctIndex: 1 },
        { id: "g3_s1_2", question: "Which is the largest planet?", options: ["Mars", "Saturn", "Jupiter", "Neptune"], correctIndex: 2 },
        { id: "g3_s1_3", question: "Which is the closest planet to the Sun?", options: ["Venus", "Earth", "Mercury", "Mars"], correctIndex: 2 },
        { id: "g3_s1_4", question: "Which planet has rings around it?", options: ["Saturn", "Jupiter", "Uranus", "All of these"], correctIndex: 3 },
        { id: "g3_s1_5", question: "What is the Sun?", options: ["A planet", "A moon", "A star", "A comet"], correctIndex: 2 },
        { id: "g3_s1_6", question: "How many planets are in our solar system?", options: ["7", "8", "9", "10"], correctIndex: 1 },
        { id: "g3_s1_7", question: "Which planet do we live on?", options: ["Mars", "Venus", "Earth", "Saturn"], correctIndex: 2 },
        { id: "g3_s1_8", question: "Does the Moon shine with its own light?", options: ["Yes", "No", "Only at night", "Sometimes"], correctIndex: 1 },
        { id: "g3_s1_9", question: "What planet is the hottest?", options: ["Mercury", "Venus", "Mars", "Earth"], correctIndex: 1 },
        { id: "g3_s1_10", question: "Which planet is famous for its Great Red Spot?", options: ["Mars", "Jupiter", "Saturn", "Neptune"], correctIndex: 1 },
        { id: "g3_s1_11", question: "Which planet is known as Earth's twin?", options: ["Mars", "Venus", "Jupiter", "Mercury"], correctIndex: 1 },
        { id: "g3_s1_12", question: "Which is the furthest planet from the Sun?", options: ["Saturn", "Uranus", "Neptune", "Jupiter"], correctIndex: 2 },
        { id: "g3_s1_13", question: "What is the center of our solar system?", options: ["The Earth", "The Moon", "The Sun", "The Milky Way"], correctIndex: 2 },
        { id: "g3_s1_14", question: "How long does it take Earth to go around the Sun?", options: ["One day", "One month", "One year", "Ten years"], correctIndex: 2 },
        { id: "g3_s1_15", question: "What causes day and night?", options: ["Earth's rotation", "The Sun moving", "The Moon moving", "Clouds"], correctIndex: 0 },
        { id: "g3_s1_16", question: "Which galaxy do we live in?", options: ["Andromeda", "Milky Way", "Sombrero", "Cigar"], correctIndex: 1 },
        { id: "g3_s1_17", question: "What is the name of the first man on the moon?", options: ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "Elon Musk"], correctIndex: 1 },
        { id: "g3_s1_18", question: "Which planet is the smallest?", options: ["Mars", "Mercury", "Venus", "Earth"], correctIndex: 1 },
        { id: "g3_s1_19", question: "What are Saturn's rings made of?", options: ["Gases", "Rock and Ice", "Dust", "Fire"], correctIndex: 1 },
        { id: "g3_s1_20", question: "Does Mars have water?", options: ["No", "Yes (Ice)", "Only in oceans", "Only in rain"], correctIndex: 1 },
        { id: "g3_s1_21", question: "Which planet tilted on its side?", options: ["Saturn", "Uranus", "Neptune", "Jupiter"], correctIndex: 1 },
        { id: "g3_s1_22", question: "How many moons does Earth have?", options: ["0", "1", "2", "3"], correctIndex: 1 },
        { id: "g3_s1_23", question: "What is a group of stars called?", options: ["Planet", "Galaxy/Constellation", "Moon", "Comet"], correctIndex: 1 },
        { id: "g3_s1_24", question: "What is a shooting star?", options: ["A star falling", "A meteor burning up", "A planet", "An alien"], correctIndex: 1 },
        { id: "g3_s1_25", question: "Which is the brightest object in our night sky?", options: ["Mars", "The Moon", "Venus", "North Star"], correctIndex: 1 },
    ],
    "ecosystems": [
        { id: "g3_s2_1", question: "What is an ecosystem?", options: ["A single animal", "A community of living and non-living things", "A type of plant", "The sky"], correctIndex: 1 },
        { id: "g3_s2_2", question: "Which is a producer?", options: ["Lion", "Rabbit", "Grass", "Mushroom"], correctIndex: 2 },
        { id: "g3_s2_3", question: "Which is a consumer?", options: ["Tree", "Flower", "Wolf", "Sun"], correctIndex: 2 },
        { id: "g3_s2_4", question: "Where do desert animals get water?", options: ["Rain", "Oasis/Plants", "Snow", "Caves"], correctIndex: 1 },
        { id: "g3_s2_5", question: "Which is a decomposer?", options: ["Grass", "Rabbit", "Worm/Fungi", "Fox"], correctIndex: 2 },
        { id: "g3_s2_6", question: "What is a food chain?", options: ["A list of food", "How energy passes from one living thing to another", "A type of farm", "A grocery store"], correctIndex: 1 },
        { id: "g3_s2_7", question: "What is at the start of most food chains?", options: ["Animals", "Plants/Sun", "Rocks", "Humans"], correctIndex: 1 },
        { id: "g3_s2_8", question: "Which ecosystem is very wet and has many trees?", options: ["Desert", "Rainforest", "Tundra", "Grassland"], correctIndex: 1 },
        { id: "g3_s2_9", question: "Which animal is a predator?", options: ["Rabbit", "Deer", "Hawk", "Snail"], correctIndex: 2 },
        { id: "g3_s2_10", question: "What happens if a part of the food chain is removed?", options: ["Nothing", "It affects the whole chain", "Only one animal dies", "Plants grow faster"], correctIndex: 1 },
        { id: "g3_s2_11", question: "Which ecosystem is extremely cold and dry?", options: ["Desert", "Tundra", "Rainforest", "Ocean"], correctIndex: 1 },
        { id: "g3_s2_12", question: "What animal lives in the Arctic?", options: ["Lion", "Polar Bear", "Elephant", "Camel"], correctIndex: 1 },
        { id: "g3_s2_13", question: "What do we call animals that eat only plants?", options: ["Carnivores", "Herbivores", "Omnivores", "Decomposers"], correctIndex: 1 },
        { id: "g3_s2_14", question: "What do we call animals that eat only meat?", options: ["Herbivores", "Carnivores", "Omnivores", "Producers"], correctIndex: 1 },
        { id: "g3_s2_15", question: "What do we call animals that eat both plants and meat?", options: ["Carnivores", "Herbivores", "Omnivores", "Scavengers"], correctIndex: 2 },
        { id: "g3_s2_16", question: "Which is a freshwater ecosystem?", options: ["Ocean", "Lake/River", "Sea", "Puddle"], correctIndex: 1 },
        { id: "g3_s2_17", question: "Which is a saltwater ecosystem?", options: ["Lake", "Ocean", "River", "Pond"], correctIndex: 1 },
        { id: "g3_s2_18", question: "What is camoflauge?", options: ["A type of food", "Blending into the environment", "Running fast", "Sleeping"], correctIndex: 1 },
        { id: "g3_s2_19", question: "What is migration?", options: ["Sleeping in winter", "Moving to another place for seasons", "Eating", "Growing"], correctIndex: 1 },
        { id: "g3_s2_20", question: "What is hibernation?", options: ["Moving", "Sleeping for a long time in winter", "Eating a lot", "Growing fur"], correctIndex: 1 },
        { id: "g3_s2_21", question: "Which is a pollinator?", options: ["Bee", "Lion", "Wolf", "Snake"], correctIndex: 0 },
        { id: "g3_s2_22", question: "What is the natural home of an animal called?", options: ["House", "Habitat", "Cage", "Forest"], correctIndex: 1 },
        { id: "g3_s2_23", question: "What do plants need for photosynthesis?", options: ["Milk", "Sunlight, Water, CO2", "Food", "Soil only"], correctIndex: 1 },
        { id: "g3_s2_24", question: "Which of these is non-living?", options: ["Tree", "Bird", "Rock", "Ant"], correctIndex: 2 },
        { id: "g3_s2_25", question: "What is an endangered animal?", options: ["A dangerous animal", "An animal at risk of disappearing", "A fast animal", "A common animal"], correctIndex: 1 },
    ],
};
