import { Question } from "./fallback-questions"

export const CURATED_TOPIC_QUESTIONS: { [key: string]: Question[] } = {
    // GRADE 1 MATH
    "numbers & counting": [
        { id: "g1_m1_1", question: "What number comes after 5?", options: ["4", "6", "3", "7"], correctIndex: 1 },
        { id: "g1_m1_2", question: "How many apples are there? 🍎🍎🍎", options: ["2", "4", "3", "5"], correctIndex: 2 },
        { id: "g1_m1_3", question: "Which number is bigger?", options: ["2", "1", "0", "3"], correctIndex: 3 },
        { id: "g1_m1_4", question: "Count the stars: ⭐⭐⭐⭐", options: ["3", "5", "4", "6"], correctIndex: 2 },
        { id: "g1_m1_5", question: "What number comes before 10?", options: ["11", "8", "9", "7"], correctIndex: 2 },
        { id: "g1_m1_6", question: "Which number is smallest?", options: ["5", "2", "1", "3"], correctIndex: 2 },
        { id: "g1_m1_7", question: "How many fingers are on one hand?", options: ["6", "4", "5", "3"], correctIndex: 2 },
        { id: "g1_m1_8", question: "What number matches this word: 'seven'?", options: ["6", "8", "9", "7"], correctIndex: 3 },
        { id: "g1_m1_9", question: "Which shows five objects?", options: ["●●●", "●●●●", "●●●●●", "●●"], correctIndex: 2 },
        { id: "g1_m1_10", question: "What comes next: 1, 2, 3, ___", options: ["5", "6", "4", "2"], correctIndex: 2 },
    ],
    "addition & subtraction": [
        { id: "g1_m2_1", question: "What is 2 + 3?", options: ["4", "5", "6", "3"], correctIndex: 1 },
        { id: "g1_m2_2", question: "What is 7 – 4?", options: ["3", "2", "4", "5"], correctIndex: 0 },
        { id: "g1_m2_3", question: "Add: 5 + 1 = ?", options: ["6", "5", "7", "4"], correctIndex: 0 },
        { id: "g1_m2_4", question: "Subtract: 9 – 5 = ?", options: ["3", "4", "5", "6"], correctIndex: 1 },
        { id: "g1_m2_5", question: "What is 1 + 6?", options: ["7", "6", "8", "5"], correctIndex: 0 },
        { id: "g1_m2_6", question: "8 – 2 = ?", options: ["5", "6", "7", "4"], correctIndex: 1 },
        { id: "g1_m2_7", question: "Add: 3 + 3 = ?", options: ["5", "6", "4", "7"], correctIndex: 1 },
        { id: "g1_m2_8", question: "Subtract: 10 – 7 = ?", options: ["2", "3", "4", "5"], correctIndex: 1 },
        { id: "g1_m2_9", question: "What is 4 + 4?", options: ["7", "8", "9", "6"], correctIndex: 1 },
        { id: "g1_m2_10", question: "6 – 1 = ?", options: ["4", "5", "6", "3"], correctIndex: 1 },
    ],
    "place value": [
        { id: "g1_m3_1", question: "What is the value of the 3 in 34?", options: ["30", "3", "300", "4"], correctIndex: 0 },
        { id: "g1_m3_2", question: "What is the value of the 7 in 72?", options: ["7", "70", "17", "2"], correctIndex: 1 },
        { id: "g1_m3_3", question: "In 56, which number is in the tens place?", options: ["5", "6", "50", "60"], correctIndex: 0 },
        { id: "g1_m3_4", question: "In 48, which number is in the ones place?", options: ["4", "8", "48", "40"], correctIndex: 1 },
        { id: "g1_m3_5", question: "What number has 2 tens and 3 ones?", options: ["23", "32", "25", "20"], correctIndex: 0 },
        { id: "g1_m3_6", question: "What number has 4 tens and 5 ones?", options: ["45", "54", "40", "50"], correctIndex: 0 },
        { id: "g1_m3_7", question: "Which number is bigger, 41 or 14?", options: ["14", "41", "40", "24"], correctIndex: 1 },
        { id: "g1_m3_8", question: "Which number is smaller, 36 or 63?", options: ["63", "36", "33", "63"], correctIndex: 1 },
        { id: "g1_m3_9", question: "What is the tens digit in 29?", options: ["2", "9", "20", "19"], correctIndex: 0 },
        { id: "g1_m3_10", question: "What is the ones digit in 57?", options: ["5", "7", "50", "57"], correctIndex: 1 },
    ],
    "measurement": [
        { id: "g1_m4_1", question: "Which is longer?", options: ["Pencil", "Crayon", "Eraser", "Paper"], correctIndex: 0 },
        { id: "g1_m4_2", question: "Which is heavier?", options: ["Feather", "Rock", "Leaf", "Paper"], correctIndex: 1 },
        { id: "g1_m4_3", question: "Which cup can hold more water?", options: ["Small cup", "Big cup", "Tiny cup", "Plate"], correctIndex: 1 },
        { id: "g1_m4_4", question: "Which is shorter?", options: ["Table", "Chair", "Bed", "Door"], correctIndex: 1 },
        { id: "g1_m4_5", question: "Which is lighter?", options: ["Book", "Balloon", "Rock", "Box"], correctIndex: 1 },
        { id: "g1_m4_6", question: "Which ruler is longer?", options: ["10 cm", "30 cm", "5 cm", "15 cm"], correctIndex: 1 },
        { id: "g1_m4_7", question: "Which is taller?", options: ["Dog", "Tree", "Cat", "Chair"], correctIndex: 1 },
        { id: "g1_m4_8", question: "Which container holds less?", options: ["Small cup", "Big cup", "Bottle", "Jar"], correctIndex: 0 },
        { id: "g1_m4_9", question: "Which is shorter?", options: ["Pencil", "Marker", "Eraser", "Pen"], correctIndex: 2 },
        { id: "g1_m4_10", question: "Which is heavier?", options: ["Paper", "Stone", "Leaf", "Feather"], correctIndex: 1 },
    ],
    "shapes & geometry": [
        { id: "g1_m5_1", question: "Which shape has 3 sides?", options: ["Square", "Triangle", "Circle", "Rectangle"], correctIndex: 1 },
        { id: "g1_m5_2", question: "Which shape has 4 equal sides?", options: ["Triangle", "Square", "Circle", "Rectangle"], correctIndex: 1 },
        { id: "g1_m5_3", question: "Which shape is round?", options: ["Circle", "Square", "Triangle", "Rectangle"], correctIndex: 0 },
        { id: "g1_m5_4", question: "Which shape has 4 sides but not all equal?", options: ["Triangle", "Rectangle", "Circle", "Square"], correctIndex: 1 },
        { id: "g1_m5_5", question: "Which shape has no corners?", options: ["Circle", "Square", "Triangle", "Rectangle"], correctIndex: 0 },
        { id: "g1_m5_6", question: "Which shape has 3 corners?", options: ["Circle", "Triangle", "Square", "Rectangle"], correctIndex: 1 },
        { id: "g1_m5_7", question: "Which shape looks like a door?", options: ["Circle", "Triangle", "Rectangle", "Square"], correctIndex: 2 },
        { id: "g1_m5_8", question: "Which shape has all sides equal?", options: ["Rectangle", "Triangle", "Square", "Circle"], correctIndex: 2 },
        { id: "g1_m5_9", question: "Which shape has one curved side?", options: ["Circle", "Square", "Triangle", "Rectangle"], correctIndex: 0 },
        { id: "g1_m5_10", question: "Which shape has four corners?", options: ["Circle", "Triangle", "Square", "Oval"], correctIndex: 2 },
    ],
    "time & money": [
        { id: "g1_m6_1", question: "How many hours are in a day?", options: ["12", "24", "10", "20"], correctIndex: 1 },
        { id: "g1_m6_2", question: "How many minutes are in one hour?", options: ["60", "50", "100", "10"], correctIndex: 0 },
        { id: "g1_m6_3", question: "What coin is worth 1 cent?", options: ["Penny", "Nickel", "Dime", "Quarter"], correctIndex: 0 },
        { id: "g1_m6_4", question: "What coin is worth 5 cents?", options: ["Penny", "Nickel", "Dime", "Quarter"], correctIndex: 1 },
        { id: "g1_m6_5", question: "What coin is worth 10 cents?", options: ["Penny", "Nickel", "Dime", "Quarter"], correctIndex: 2 },
        { id: "g1_m6_6", question: "What coin is worth 25 cents?", options: ["Nickel", "Dime", "Penny", "Quarter"], correctIndex: 3 },
        { id: "g1_m6_7", question: "What time shows 3:00?", options: ["Hour hand on 3, minute hand on 12", "Hour hand on 12, minute hand on 3", "Hour hand on 6, minute hand on 12", "Hour hand on 3, minute hand on 6"], correctIndex: 0 },
        { id: "g1_m6_8", question: "How many quarters make 1 dollar?", options: ["2", "4", "5", "10"], correctIndex: 1 },
        { id: "g1_m6_9", question: "If it is 7:00 in the morning, what part of the day is it?", options: ["Morning", "Afternoon", "Night", "Evening"], correctIndex: 0 },
        { id: "g1_m6_10", question: "If you have 2 dimes and 1 nickel, how much money do you have?", options: ["25 cents", "15 cents", "10 cents", "20 cents"], correctIndex: 0 },
    ],
    // GRADE 2 ELA
    "sentence structure": [
        { id: "g2_e1_1", question: "Which is a complete sentence?", options: ["The big dog", "The dog barked.", "Barked loudly", "Dog big."], correctIndex: 1 },
        { id: "g2_e1_2", question: "Which word should be capitalized?", options: ["apple", "london", "table", "chair"], correctIndex: 1 },
        { id: "g2_e1_3", question: "Which marks the end of a question?", options: [".", "?", "!", ","], correctIndex: 1 },
        { id: "g2_e1_4", question: "Which is a noun?", options: ["Run", "Happy", "Book", "Quickly"], correctIndex: 2 },
        { id: "g2_e1_5", question: "Which is a verb?", options: ["Blue", "Jump", "Apple", "Soft"], correctIndex: 1 },
        { id: "g2_e1_6", question: "Which is an adjective?", options: ["Dog", "Brave", "Run", "Fastly"], correctIndex: 1 },
        { id: "g2_e1_7", question: "Choose the correct verb: 'The cat ___ on the mat.'", options: ["sit", "sits", "sitting", "sitted"], correctIndex: 1 },
        { id: "g2_e1_8", question: "Which sentence has correct punctuation?", options: ["Where are you.", "Where are you?", "Where are you!", "where are you"], correctIndex: 1 },
        { id: "g2_e1_9", question: "Identify the subject: 'The bird sings.'", options: ["The", "Bird", "Sings", "The bird"], correctIndex: 1 },
        { id: "g2_e1_10", question: "Which word is a pronoun?", options: ["Tree", "He", "Fast", "Green"], correctIndex: 1 },
    ],
    "reading comprehension (stories)": [
        { id: "g2_e2_1", question: "Where does the story usually start?", options: ["Middle", "Beginning", "End", "Nowhere"], correctIndex: 1 },
        { id: "g2_e2_2", question: "What is the people in the story called?", options: ["Settings", "Characters", "Plots", "Titles"], correctIndex: 1 },
        { id: "g2_e2_3", question: "What is where the story happens called?", options: ["Plot", "Setting", "Character", "Ending"], correctIndex: 1 },
        { id: "g2_e2_4", question: "What is the main idea?", options: ["The first word", "What the story is about", "The characters' names", "The ending"], correctIndex: 1 },
        { id: "g2_e2_5", question: "Who tells the story?", options: ["Character", "Narrator", "Reader", "Villain"], correctIndex: 1 },
        { id: "g2_e2_6", question: "What is the problem in a story called?", options: ["Conflict", "Solution", "Setting", "Theme"], correctIndex: 0 },
        { id: "g2_e2_7", question: "What happens at the end of the story?", options: ["Introduction", "Resolution", "Climax", "Rising action"], correctIndex: 1 },
        { id: "g2_e2_8", question: "Which part of the book tells you the name?", options: ["Title", "Author", "Page", "Cover"], correctIndex: 0 },
        { id: "g2_e2_9", question: "Who writes the book?", options: ["Author", "Illustrator", "Character", "Narrator"], correctIndex: 0 },
        { id: "g2_e2_10", question: "What are the pictures in a book called?", options: ["Words", "Illustrations", "Pages", "Chapters"], correctIndex: 1 },
    ],
    "science topics (mammals)": [
        { id: "g2_s1_1", question: "Which is a mammal?", options: ["Frog", "Snake", "Cat", "Fish"], correctIndex: 2 },
        { id: "g2_s1_2", question: "What do mammals have on their bodies?", options: ["Feathers", "Scales", "Hair or fur", "Shells"], correctIndex: 2 },
        { id: "g2_s1_3", question: "How do mammals breathe?", options: ["Gills", "Lungs", "Skin", "Wings"], correctIndex: 1 },
        { id: "g2_s1_4", question: "Which mammal lives in the ocean?", options: ["Shark", "Whale", "Fish", "Crab"], correctIndex: 1 },
        { id: "g2_s1_5", question: "Do mammals lay eggs usually?", options: ["Yes", "No", "Sometimes", "Only in water"], correctIndex: 1 },
        { id: "g2_s1_6", question: "Which is NOT a mammal?", options: ["Dog", "Human", "Bird", "Elephant"], correctIndex: 2 },
        { id: "g2_s1_7", question: "What do baby mammals drink?", options: ["Water", "Milk", "Juice", "Soda"], correctIndex: 1 },
        { id: "g2_s1_8", question: "Are humans mammals?", options: ["Yes", "No", "Maybe", "Only adults"], correctIndex: 0 },
        { id: "g2_s1_9", question: "Which mammal can fly?", options: ["Bird", "Bat", "Squirrel", "Eagle"], correctIndex: 1 },
        { id: "g2_s1_10", question: "Which is a very large mammal?", options: ["Mouse", "Blue Whale", "Ant", "Cat"], correctIndex: 1 },
    ],
    "government & laws": [
        { id: "g2_ss1_1", question: "Who is the leader of a country?", options: ["Mayor", "Governor", "President", "Teacher"], correctIndex: 2 },
        { id: "g2_ss1_2", question: "Where does the President live?", options: ["The Blue House", "The White House", "The Red House", "The Capitol"], correctIndex: 1 },
        { id: "g2_ss1_3", question: "Who makes the laws?", options: ["Police", "Congress", "Students", "Pets"], correctIndex: 1 },
        { id: "g2_ss1_4", question: "Why do we have laws?", options: ["To be mean", "To keep order and safety", "To play games", "To sleep"], correctIndex: 1 },
        { id: "g2_ss1_5", question: "Who is the leader of a city?", options: ["President", "Governor", "Mayor", "Principal"], correctIndex: 2 },
        { id: "g2_ss1_6", question: "What is the capital of the USA?", options: ["New York", "Washington D.C.", "Los Angeles", "Chicago"], correctIndex: 1 },
        { id: "g2_ss1_7", question: "What is the name of the law book of the USA?", options: ["Declaration", "Constitution", "Bible", "Dictionary"], correctIndex: 1 },
        { id: "g2_ss1_8", question: "How often do we elect a President?", options: ["Every year", "Every 4 years", "Every 10 years", "Never"], correctIndex: 1 },
        { id: "g2_ss1_9", question: "Which flag represents the USA?", options: ["Stars & Stripes", "Tricolor", "Union Jack", "Maple Leaf"], correctIndex: 0 },
        { id: "g2_ss1_10", question: "What color are the stars on the US flag?", options: ["Red", "White", "Blue", "Yellow"], correctIndex: 1 },
    ],
    // GRADE 3 MATH
    "multiplication": [
        { id: "g3_m1_1", question: "What is 2 x 5?", options: ["7", "10", "12", "15"], correctIndex: 1 },
        { id: "g3_m1_2", question: "What is 3 x 4?", options: ["7", "12", "15", "10"], correctIndex: 1 },
        { id: "g3_m1_3", question: "What is 5 x 5?", options: ["20", "25", "30", "15"], correctIndex: 1 },
        { id: "g3_m1_4", question: "What is 10 x 3?", options: ["13", "30", "40", "103"], correctIndex: 1 },
        { id: "g3_m1_5", question: "What is 4 x 4?", options: ["8", "16", "20", "12"], correctIndex: 1 },
        { id: "g3_m1_6", question: "What is 6 x 2?", options: ["8", "12", "14", "10"], correctIndex: 1 },
        { id: "g3_m1_7", question: "What is 0 x 10?", options: ["10", "1", "0", "100"], correctIndex: 2 },
        { id: "g3_m1_8", question: "What is 1 x 9?", options: ["1", "9", "10", "0"], correctIndex: 1 },
        { id: "g3_m1_9", question: "What is 3 x 3?", options: ["6", "9", "12", "15"], correctIndex: 1 },
        { id: "g3_m1_10", question: "Which is the same as 2 + 2 + 2?", options: ["2 x 3", "2 x 2", "3 x 3", "2 + 3"], correctIndex: 0 },
    ],
    "division": [
        { id: "g3_m2_1", question: "What is 10 / 2?", options: ["2", "5", "10", "8"], correctIndex: 1 },
        { id: "g3_m2_2", question: "What is 12 / 3?", options: ["3", "4", "5", "6"], correctIndex: 1 },
        { id: "g3_m2_3", question: "What is 20 / 4?", options: ["4", "5", "10", "15"], correctIndex: 1 },
        { id: "g3_m2_4", question: "What is 15 / 5?", options: ["2", "3", "4", "5"], correctIndex: 1 },
        { id: "g3_m2_5", question: "What is 18 / 2?", options: ["7", "9", "10", "8"], correctIndex: 1 },
        { id: "g3_m2_6", question: "What is 8 / 4?", options: ["2", "4", "6", "8"], correctIndex: 0 },
        { id: "g3_m2_7", question: "What is 30 / 10?", options: ["2", "3", "4", "5"], correctIndex: 1 },
        { id: "g3_m2_8", question: "What is 9 / 3?", options: ["2", "3", "4", "5"], correctIndex: 1 },
        { id: "g3_m2_9", question: "What is 100 / 10?", options: ["1", "10", "100", "50"], correctIndex: 1 },
        { id: "g3_m2_10", question: "What is 14 / 2?", options: ["6", "7", "8", "9"], correctIndex: 1 },
    ],
    "fractions": [
        { id: "g3_m3_1", question: "What is 1/2?", options: ["One whole", "Half", "Quarter", "One third"], correctIndex: 1 },
        { id: "g3_m3_2", question: "Which fraction is one quarter?", options: ["1/2", "1/3", "1/4", "1/5"], correctIndex: 2 },
        { id: "g3_m3_3", question: "If you cut a pizza into 4 equal pieces and eat 1, what fraction did you eat?", options: ["1/2", "1/3", "1/4", "3/4"], correctIndex: 2 },
        { id: "g3_m3_4", question: "Which is bigger?", options: ["1/2", "1/4", "1/8", "1/10"], correctIndex: 0 },
        { id: "g3_m3_5", question: "What is 3/3 equal to?", options: ["0", "1", "3", "1/3"], correctIndex: 1 },
        { id: "g3_m3_6", question: "How many halves make a whole?", options: ["1", "2", "3", "4"], correctIndex: 1 },
        { id: "g3_m3_7", question: "How many quarters make a whole?", options: ["2", "4", "6", "8"], correctIndex: 1 },
        { id: "g3_m3_8", question: "What fraction of a day is 12 hours?", options: ["1/2", "1/4", "1/3", "2/3"], correctIndex: 0 },
        { id: "g3_m3_9", question: "If you have 1/3 of a cake, how many pieces make the whole cake?", options: ["1", "2", "3", "4"], correctIndex: 2 },
        { id: "g3_m3_10", question: "Which is smaller?", options: ["1/2", "1/3", "1/4", "1/5"], correctIndex: 3 },
    ],
    // GRADE 3 ELA
    "parts of speech (advanced)": [
        { id: "g3_e1_1", question: "Which is a common noun?", options: ["London", "City", "John", "Mars"], correctIndex: 1 },
        { id: "g3_e1_2", question: "Which is a proper noun?", options: ["street", "river", "Paris", "mountain"], correctIndex: 2 },
        { id: "g3_e1_3", question: "Which word is a conjunction?", options: ["Happy", "And", "Run", "Blue"], correctIndex: 1 },
        { id: "g3_e1_4", question: "Which word is a preposition?", options: ["Under", "Fast", "Jump", "Yellow"], correctIndex: 0 },
        { id: "g3_e1_5", question: "What is an adverb?", options: ["A person", "A word that describes a verb", "A color", "A shape"], correctIndex: 1 },
        { id: "g3_e1_6", question: "Which word is an adverb?", options: ["Quickly", "Fast", "Smart", "Big"], correctIndex: 0 },
        { id: "g3_e1_7", question: "Which is a pronoun?", options: ["Book", "They", "School", "Pencil"], correctIndex: 1 },
        { id: "g3_e1_8", question: "What is a plural noun for 'child'?", options: ["Childs", "Children", "Childes", "Cildren"], correctIndex: 1 },
        { id: "g3_e1_9", question: "Which is an adjective?", options: ["Delicious", "Eat", "Plate", "Fork"], correctIndex: 0 },
        { id: "g3_e1_10", question: "Which word is a verb in 'She runs'?", options: ["She", "Runs", "She runs", "None"], correctIndex: 1 },
    ],
    // GRADE 3 SCIENCE
    "solar system": [
        { id: "g3_s1_1", question: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Earth"], correctIndex: 1 },
        { id: "g3_s1_2", question: "Which is the largest planet?", options: ["Mars", "Saturn", "Jupiter", "Neptune"], correctIndex: 2 },
        { id: "g3_s1_3", question: "Which is the closest planet to the Sun?", options: ["Venus", "Earth", "Mercury", "Mars"], correctIndex: 2 },
        { id: "g3_s1_4", question: "Which planet has rings around it?", options: ["Saturn", "Jupiter", "Uranus", "All of these"], correctIndex: 3 },
        { id: "g3_s1_5", question: "What is the Sun?", options: ["A planet", "A moon", "A star", "A comet"], correctIndex: 2 },
        { id: "g3_s1_6", question: "How many planets are in our solar system?", options: ["7", "8", "9", "10"], correctIndex: 1 },
        { id: "g3_s1_7", question: "Which planet do we live on?", options: ["Mars", "Venus", "Earth", "Saturn"], correctIndex: 2 },
        { id: "g3_s1_8", question: "Does the Moon shine with its own light?", options: ["Yes", "No", "Only at night", "Sometimes"], correctIndex: 1 },
        { id: "g3_s1_9", question: "What planet is the hottest?", options: ["Mercury", "Venus", "Mars", "Earth"], correctIndex: 1 },
        { id: "g3_s1_10", question: "Which planet is famous for its Great Red Spot?", options: ["Mars", "Jupiter", "Saturn", "Neptune"], correctIndex: 1 },
    ],
    "ecosystems": [
        { id: "g3_s2_1", question: "What is an ecosystem?", options: ["A single animal", "A community of living and non-living things", "A type of plant", "The sky"], correctIndex: 1 },
        { id: "g3_s2_2", question: "Which is a producer?", options: ["Lion", "Rabbit", "Grass", "Mushroom"], correctIndex: 2 },
        { id: "g3_s2_3", question: "Which is a consumer?", options: ["Tree", "Flower", "Wolf", "Sun"], correctIndex: 2 },
        { id: "g3_s2_4", question: "Where do desert animals get water?", options: ["Rain", "Oasis/Plants", "Snow", "Caves"], correctIndex: 1 },
        { id: "g3_s2_5", question: "Which is a decomposer?", options: ["Grass", "Rabbit", "Worm/Fungi", "Fox"], correctIndex: 2 },
        { id: "g3_s2_6", question: "What is a food chain?", options: ["A list of food", "How energy passes from one living thing to another", "A type of farm", "A grocery store"], correctIndex: 1 },
        { id: "g3_s2_7", question: "What is at the start of most food chains?", options: ["Animals", "Plants/Sun", "Rocks", "Humans"], correctIndex: 1 },
        { id: "g3_s2_8", question: "Which ecosystem is very wet and has many trees?", options: ["Desert", "Rainforest", "Tundra", "Grassland"], correctIndex: 1 },
        { id: "g3_s2_9", question: "Which animal is a predator?", options: ["Rabbit", "Deer", "Hawk", "Snail"], correctIndex: 2 },
        { id: "g3_s2_10", question: "What happens if a part of the food chain is removed?", options: ["Nothing", "It affects the whole chain", "Only one animal dies", "Plants grow faster"], correctIndex: 1 },
    ],
};
