CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  age INTEGER NOT NULL,
  tokens INTEGER NOT NULL DEFAULT 0,
  daily_tokens INTEGER NOT NULL DEFAULT 0,
  packs TEXT[] NOT NULL DEFAULT '{}',
  booms JSONB NOT NULL DEFAULT '{}',
  is_owner BOOLEAN NOT NULL DEFAULT FALSE,
  is_banned BOOLEAN NOT NULL DEFAULT FALSE,
  is_muted BOOLEAN NOT NULL DEFAULT FALSE,
  status TEXT NOT NULL DEFAULT 'pending',
  reason TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT 'player',
  join_date TEXT NOT NULL,
  boom_score INTEGER NOT NULL DEFAULT 0,
  total_value INTEGER NOT NULL DEFAULT 0,
  profile_picture TEXT NOT NULL DEFAULT '🎯',
  is_plus_user BOOLEAN NOT NULL DEFAULT FALSE,
  name_color TEXT NOT NULL DEFAULT 'white',
  banner_color TEXT NOT NULL DEFAULT 'purple',
  last_daily_spin TEXT NOT NULL DEFAULT '',
  badges TEXT[] NOT NULL DEFAULT '{}',
  mute_expiry BIGINT,
  ban_expiry BIGINT,
  ban_reason TEXT,
  last_seen BIGINT NOT NULL DEFAULT 0
);
