-- Deprecated utility.
-- Password hashes are now generated by the Next.js server using scrypt with a random salt.
-- Do not create password_hash values directly in SQL; doing so can downgrade account security.

DO $$
BEGIN
  RAISE EXCEPTION 'Do not hash passwords in SQL. Use the owner/admin password reset flow in the application.';
END $$;
